= Deleting Movie nodes
:order: 3
:type: lesson

In previous lessons, you created a new `Movie` node and its relationships in the database from your Java application. Now you will learn how to delete a `Movie` node and its relationships from the database.

== DeleteById() method

Just as with previous derived methods for `findAll()` or `save()`, there is a derived method to delete data called `deleteById()`. You will use this method to delete a `Movie` node in Neo4j.

In the `MovieController.java` file in the `src/main/java/com/example/appspringdata` directory, add the following code:

[source,java]
----
@RestController
@RequestMapping("/movies")
public class MovieController {
    //previous code and methods

    @DeleteMapping("/delete")
    void delete(@RequestParam String movieId) {
        movieRepo.deleteById(movieId);
        System.out.println("Deleted movie with movieId: " + movieId);
    }
}
----

Full code for the `MovieController` class is available in the dropdown below.

[%collapsible]
.Click to reveal the completed `MovieController` class code
====
[source,java]
----
include::code/MovieController.java[tag=delete-method]
----
====

This method is annotated with `@DeleteMapping` and will handle requests to the `/movies/delete` endpoint. It passes in a `movieId` specified as a request parameter at the end of the URL. The `deleteById()` method is called on the repository with the `movieId` passed in as an argument. The method then prints a message to the console to confirm the deletion.

[TIP]
.Deleting relationships
====
By default, the delete operation will do a `DETACH DELETE`, which means it will first delete any relationships connected to the node before deleting the node itself.
====

== Testing the deleteById() method

For this example, you will delete the movie created in the last lesson.

Run your application. Once the application is running, go to the terminal tab and execute `curl -X DELETE localhost:8080/movies/delete?movieId=9876` to delete the `MyMovie` node created in the last lesson.

//TODO: Figure out how this works in Gitpod!

.Delete Results (example)
----
Deleted movie with movieId: 9876
----

Execute the populated query in the right-hand tab to verify that the node has been deleted. You should see no results returned.

//TODO: Screenshot of query results!

read::Success[]

[.summary]
== Summary

In this lesson, you learned how to delete a `Movie` node in Neo4j using the derived `deleteById()` method.

In the next module, you will define methods with custom Cypher statements for reading, writing, and updating data.