= Your Neo4j Sandbox
:disable-cache: true
:branch: main
:language: Go

include::{shared}/courses/apps/sandbox.adoc[tag="info"]


=== Setting Application Configuration

You should add these values to the `config.json` file in the project root.

.config.json
[source,json,subs="attributes+"]
----
{
  "APP_PORT": 3000,
  "NEO4J_URI": "bolt://{sandbox_ip}:{sandbox_boltPort}",
  "NEO4J_USERNAME": "{sandbox_username}",
  "NEO4J_PASSWORD": "{sandbox_password}",
  "JWT_SECRET": "secret",
  "SALT_ROUNDS": 10
}
----

* `APP_PORT` - defines which port the Go process should run on
* `NEO4J_URI` - defines the connection string, more about that in link:../1-driver/2-connection-strings/[Connection Strings & Authentication]
* `NEO4J_USERNAME` - the username for the Neo4j instance
* `NEO4J_PASSWORD` - the password for the Neo4j instance
* `JWT_SECRET` - the secret phrase used to sign any JWT tokens
* `SALT_ROUNDS` - the cost parameter used when hashing passwords

These values will be read by the `ReadConfig()` function in link:{repository-blob}/{branch}/pkg/config/config.go[`pkg/config/config.go`^].

.Reading Config Values
[source,go,role=nocopy]
----
include::{repository-raw}/{branch}/pkg/config/config.go[tag=readConfig]
----

[IMPORTANT]
.Updating Variables
Remember to restart the process after saving the `config.json` file to apply the new variables to the project.


include::{shared}/courses/apps/sandbox.adoc[tags="summary,complete"]