= Actorラベルによる再試験
:type: challenge
:order: 5
:sandbox: true
:updated-at: 2022-04-25 T 21:00:00 Z


適切なノードに _Actor_ ラベルを追加するようにグラフをリファクタリングしています。
ここで、リファクタリングしたグラフに対して、ユースケースを再テストする必要があります。

もし、完全にスケーリングされたグラフがあれば、_Person_ ラベルを使用するクエリと _Actor_ ラベルを使用するクエリの違いが分かるでしょう。
クエリのプロファイルを作成して、取得した行を前後で比較することができます。

== ユースケース#1: 誰が映画に出演したのか？

このCypherのコードを実行し、映画「Sleepless in Seattle」を使ってこのユースケースをテストしてください。

[source,cypher]
----
MATCH (p:Actor)-[:ACTED_IN]-(m:Movie)
WHERE m.title = 'Sleepless in Seattle'
RETURN p.name AS Actor
----

トム・ハンクス、メグ・ライアンという2人の俳優の名前が返ってくるはずです。

== ユースケース#3: この人は何の映画に出演したのか？

このCypherのコードを実行して、Tom Hanksという人物を使ってこのユースケースをテストしてください。

[source,cypher]
----
MATCH (p:Actor)-[:ACTED_IN]-(m:Movie)
WHERE p.name = 'Tom Hanks'
RETURN m.title AS Movie
----

映画『アポロ13』や『スリープレス・イン・シアトル』を返すはずです。

== ユースケース#5: 最年少で映画に出演したのは誰か？

このCypherのコードを実行し、映画「Hoffa」でこの使用例をテストしてください。

[source,cypher]
----
MATCH (p:Actor)-[:ACTED_IN]-(m:Movie)
WHERE m.title = 'Hoffa'
RETURN  p.name AS Actor, p.born as `Year Born` ORDER BY p.born DESC LIMIT 1
----

ダニー・デビートと誕生年が返されるはずです。

== ユースケース#6: 映画の中で、その人はどんな役割を担っていたのか。

このCypherのコードを実行して、映画「Sleepless in Seattle」と人物「Meg Ryan」でこのユースケースをテストしてください。

[source,cypher]
----
MATCH (p:Actor)-[r:ACTED_IN]-(m:Movie)
WHERE m.title = 'Sleepless in Seattle' AND
p.name = 'Meg Ryan'
RETURN  r.role AS Role
----

アニー・リードを返すはずです。

== ユースケース#8: この俳優が出演したドラマ映画とは？

このCypherのコードを実行して、Tom Hanksという人物でこのユースケースをテストしてください。

[source,cypher]
----
MATCH (p:Actor)-[:ACTED_IN]-(m:Movie)
WHERE p.name = 'Tom Hanks' AND
'Drama' IN m.genres
RETURN m.title AS Movie
----

このクエリで「Drama」を「Comedy」に変更した場合、異なる結果が返されます。

== ユースケース#10: 1950年以前に生まれた俳優とは？

このCypherのコードを実行して、このユースケースを1950年でテストしてください。

[source,cypher]
----
MATCH (p:Actor)
WHERE p.born < '1950'
RETURN p.name
----

俳優のダニー・デヴィートとジャック・ニコルソンが戻ってくるはずです。

このCypherのコードを実行すると、グラフ内のすべてのものが返され、次の質問に答えることができます。

[source,cypher]
----
MATCH (n)
RETURN n
----

include::./questions/verify.adoc[leveloffset=+1]

[.summary]
== まとめ

この課題では、_Actor_ ラベルを追加するリファクタリングによって影響を受けるユースケースをテストしました。

次のチャレンジでは、グラフに _Director_ のラベルを追加します。
