= Graph types
:type: lesson
:order: 1
:slides: true

[.slide.discrete.col-60-40]
== Introduction

[.col]
====
Let's take a look at the types of data returned by a Cypher query.

The majority of the types returned by a Cypher query are mapped directly to Go types, but some more complex types need special handling.

* Graph types - Nodes, Relationships and Paths
* Temporal types - Dates and times
* Spatial types - Points and distances

[TIP]
.Returning graph types
=====
When graph types are returned by a query executed in the Query window, they are visualized in a graph layout.
=====


====

[.col]
====

[cols="1,1"]
.Direct mapping
|===
| Go Type | Neo4j Cypher Type 

| `nil`
| `null`

| `bool`
| `Boolean`

| `int64`
| `Integer`

| `float64`
| `Float`

| `string`
| `String`

| `[]byte`
| `Bytes [1]`

| `[]any`
| `List`

| `map[string]any`
| `Map`
|===


====

[.slide]
== Graph types

The following code snippet finds all movies with the specified title and returns `person`, `acted_in` and `movie`.

.Return Nodes and Relationships
[source,go,role=ncopy,subs="attributes+",indent=0]
----
result, err := neo4j.ExecuteQuery(ctx, driver, `
MATCH path = (person:Person)-[actedIn:ACTED_IN]->(movie:Movie {title: $title})
RETURN path, person, actedIn, movie
`, map[string]any{"title": movie}, neo4j.EagerResultTransformer)
----


[.slide.col-2]
== Nodes

[.col]
====

Nodes are returned as a `neo4j.Node` object.


[source,go,role=ncopy,subs="attributes+",indent=0]
----
for _, record := range result.Records {
    node, _ := record.Get("movie")
    movieNode := node.(neo4j.Node)
}
----

.Working with Node Objects
[source,go,role=ncopy,subs="attributes+",indent=0]
----
    fmt.Println(movieNode.ElementId)             // (1)
    fmt.Println(movieNode.Labels)                // (2)
    fmt.Println(movieNode.Props)                 // (3)

    if name, ok := movieNode.Props["name"]; ok { // (4)
        fmt.Println("name:", name)
    }
----

====

[.col]
====
1. The `ElementId` property provides access to the node's element ID +
    eg. `4:97b72e9c-ae4d-427c-96ff-8858ecf16f88:0` 
2. The `Labels` property is a slice containing an array of labels attributed to the Node +
    eg. `["Person", "Actor"]`
3. The `Props` property provides access to the node's properties as a map. +
    eg. `{name: "Tom Hanks", tmdbId: "31"}`
4. A single property can be retrieved using the `Props` map.

====

[.slide.col-2]
== Relationships

[.col]
====

Relationships are returned as a `neo4j.Relationship` object.

[source,go,role=ncopy,subs="attributes+",indent=0]
----
    actedIn, _ := record.Get("actedIn")
    relationship := actedIn.(neo4j.Relationship)

    fmt.Println(relationship.ElementId)             // (1)
    fmt.Println(relationship.Type)                  // (2)
    fmt.Println(relationship.Props)                 // (3)

    if role, ok := relationship.Props["role"]; ok { // (4)
        fmt.Println("role:", role)
    }
----

====

[.col]
====
1. `ElementId` - Internal ID of the relationship (eg. `9876`)
2. `Type` - Type of relationship (eg. `ACTED_IN`) 
3. `Props` - Returns relationship properties as a map (eg. `{role: "Woody"}`)
4. Individual properties can be accessed using the `Props` map.

====

[.slide.col-2]
== Paths

[.col]
====

A path is a sequence of nodes and relationships and is returned as a `neo4j.Path` object.


[source,go,role=ncopy,subs="attributes+",indent=0]
----
    path, _ := record.Get("path")
    pathObj := path.(neo4j.Path)

    fmt.Println(pathObj.Start)  // (1)
    fmt.Println(pathObj.End)    // (2)
    fmt.Println(len(pathObj.Relationships))  // (3)
    fmt.Println(pathObj.Relationships)  // (4)
----

====

[.col]
====
1. `Start` - `neo4j.Node` object at the start of the path
2. `End` - `neo4j.Node` object at the end of the path
3. `len(pathObj.Relationships)` - The number of relationships within the path
4. `Relationships` - A slice of `neo4j.Relationship` objects within the path.

[TIP]
.Paths are iterable
======
Use `for _, rel := range pathObj.Relationships` to iterate over the relationships in a path.

======

====

[.next.discrete]
== Check your understanding

link:../2c-accessing-graph-types/[Advance to challenge,role=btn]

[.summary]
== Summary

In this lesson, you learned about the types of data returned by a Cypher query and how to work with them in your application.

Now it's time to test yourself on what you've learned.
