= Introduction to Neo4j Graph Data Science
:usecase: recommendations
:categories: data-scientist:1
:duration: 30 minutes
:caption: Gain a high-level technical understanding of the Neo4j Graph Data Science (GDS) library
:status: active

== Course Description

This course introduces you to the fundamentals of using the Neo4j Graph Data Science (GDS), including an introduction of how Neo4j GDS works, creating and maintaining graph projections.

The course automatically creates a new `movie recommendations` sandbox within link:https://sandbox.neo4j.com/?usecase=recommendations[Neo4j Sandbox] that you will use throughout the course.


=== Prerequisites

This course is intended for analysts and data scientists who have basic knowledge of:

* Data science fundamentals
* Graph database fundamentals

=== Duration

2 hours

=== What you will learn

* Basics for how Neo4j GDS works to enable analytics
* How to install GDS and the different licensing options
* Graph projection and algorithm execution patterns
* Different categories of graph algorithms and common use cases for each
* How to run graph native machine learning pipelines in GDS
