= Building Neo4j Applications with Node.js
:usecase: recommendations
:status: active
:categories: developer:3, nodejs
:caption: Learn how to interact with Neo4j from Node.js using the Neo4j JavaScript Driver
// tag::config[]
:repository: neo4j-graphacademy/app-nodejs
:node-version: v16.15.1
:cypher-repository: neo4j-graphacademy/neoflix-cypher
// end::config[]

== Course Description

In this course, we walk through the steps to integrate Neo4j into your Node.js projects.

We will follow the steps to create an instance of the Neo4j JavaScript Driver, learn how to use sessions and transactions, and use that knowledge to replace hardcoded API responses with data from a Neo4j Sandbox instance.

The project also serves a pre-built Single Page Application (SPA) that calls the API.
As you work through the course, you will replace the hardcoded API responses with data from Neo4j.

The course automatically creates a new `recommendations` sandbox within link:https://sandbox.neo4j.com/?usecase=recommendations[Neo4j Sandbox] that you will use throughout the course.

=== Prerequisites

By taking this course, we assume that you have a working knowledge of JavaScript, NPM and the Node.js ecosystem.
We also assume that you have at least a basic knowledge of Neo4j.

If you haven't already done so, we recommend that you also take the link:/courses/neo4j-fundamentals/[Neo4j Fundamentals] course in order to gain a basic understanding of Neo4j and the link:/courses/cypher-fundamentals/[Cypher Fundamentals] to understand how to query Neo4j using Cypher.

=== Duration

8 hours

=== What you will learn

* The lifecycle of the Neo4j Driver and how it relates to your application
* How to install and instantiate the Neo4j JavaScript Driver to your Node.js project
* How read and write transactions work with Neo4j
* Best practices on how to use Neo4j within your Node.js project.
