= Deleting Data
:type: quiz
:order: 9

[.video]
video::9UdAfdG5Gag[youtube,width=560,height=315]


////

2-Writing-DeletingData

https://docs.google.com/document/d/1IgJFtqQ0epVu3ywM7cNgbe6nuTxpz-TVTarGV74-pqs/edit?usp=sharing

////
[.transcript]
== Deleting data
In a Neo4j database you can delete:

* nodes
* relationships
* properties

To delete any data in the database, you must first retrieve it, then you can delete it.
You have already learned how to remove or delete properties from nodes or relationships.

=== Deleting a node

Suppose you have created a _Person_ node for _Jane Doe_.

Run this Cypher code to create the node:

[source,cypher]
----
MERGE (p:Person {name: 'Jane Doe'})
----

You delete this node as follows where you first retrieve the node. Then with a reference to the node you can delete it.

[source,cypher]
----
MATCH (p:Person)
WHERE p.name = 'Jane Doe'
DELETE p
----

=== Deleting a relationship

Suppose we had our _Jane Doe_ node again where she was added as an actor in the movie, _The Matrix_.
Run this code to create the node and the relationship.

[source,cypher]
----
MATCH (m:Movie {title: 'The Matrix'})
MERGE (p:Person {name: 'Jane Doe'})
MERGE (p)-[:ACTED_IN]->(m)
RETURN p, m
----

This code creates one node and the relationship from _Jane Doe_ to _The Matrix_.

To leave the _Jane Doe_ node in the graph, but remove the relationship we retrieve the relationship and delete it.

[source,cypher]
----
MATCH (p:Person {name: 'Jane Doe'})-[r:ACTED_IN]->(m:Movie {title: 'The Matrix'})
DELETE r
RETURN p, m
----

Run this Cypher code that recreates the relationship:

[source,cypher]
----
MATCH (p:Person {name: 'Jane Doe'})
MATCH (m:Movie {title: 'The Matrix'})
MERGE (p)-[:ACTED_IN]->(m)
RETURN p, m
----

If we attempt to delete the _Jane Doe_ node, we will receive an error because it has relationships in the graph.

Try running this Cypher code:

[source,cypher]
----
MATCH (p:Person {name: 'Jane Doe'})
DELETE p
----

You should receive an error. Neo4j prevents orphaned relationships in the graph.


=== Deleting a node and its relationships

Neo4j provides a feature where you cannot delete a node if it has incoming or outgoing relationships.
This prevents the graph from having orphaned relationships.

Run this Cypher code:

[source,cypher]
----
MATCH (p:Person {name: 'Jane Doe'})
DETACH DELETE p
----

This code deletes the relationship and the _Person_ node.

You can also delete all nodes and relationships in a database with this code.

[NOTE]
Do not delete all nodes and relationships in the graph as you need them for the next challenge!

[source,cypher,role=nocopy noplay]
----
MATCH (n)
DETACH DELETE n
----

[IMPORTANT]
You should only do this on relatively small databases as trying to do this on a large database will exhaust memory.

== Check your understanding

include::questions/1-complete-code.adoc[]

include::questions/2-delete-all.adoc[]

[.summary]
== Summary

In this lesson, you learned how to delete nodes and relationships from the graph.
In the next challenge, you will demonstrate that you can delete a node from the graph.