= Creating Existence Constraints for Node properties
:type: challenge
:order: 5
:sandbox: true

== Property must exist

In our Movie data model, we want to ensure every Movie in the graph has a value for its title property and every User has a value for the name property.
In your real application, you would create existence constraints for nodes prior to loading the data.
For this course, we already have the data loaded, but we still want to constrain the graph so that all movies have titles and all users have names.

In the previous lesson, you executed code to create an existence constraint for the Person nodes to ensure they always have a value for the name property.
In this Challenge, you will create two more uniqueness constraints in the graph.

In the sandbox on the right, modify the code to create these existence constraints in the graph:

1. For the Person nodes:

* *`constraint_name`*: [copy]#User_name_exists#
* *`node_label`*: [copy]#User#
* *`property_key`*: [copy]#name#

2. For the Movie nodes:

* *`constraint_name`*: [copy]#Movie_title_exists#
* *`node_label`*: [copy]#Movie#
* *`property_key`*: [copy]#title#

After you have created the constraints, list them:

[source,cypher]
----
SHOW CONSTRAINTS
----

[NOTE]
.Creating Multiple Constraints
--
If you create incorrect constraints with different names or property_key names, do not worry.
You can create new ones, provided the constraint_name or property_key is unique.
Later in this course you will learn how to remove constraints from the graph.

If you reload this page, the graph will be reset to what it should be at the beginning of the challenge.
--

include::./questions/verify.adoc[leveloffset=+2]


[.summary]
== Summary

In this challenge, you demonstrated that you can create existence constraints for node properties in the graph.
In the next lesson, you will learn how to create existence constraints for relationship properties.