= Neo4j Fundamentals
:categories: beginners:1, start:1, software-development:1, data-analysis:1, reporting:1, llms:1, foundation:1
:status: active
:next: cypher-fundamentals
:duration: 1 hour
:caption: Learn the basics of Neo4j and the property graph model
:video: https://www.youtube.com/embed/W6p0oNbzW3o
:translations: jp-neo4j-fundamentals,cn-neo4j-fundamentals
:key-points: The basics of graph theory, Graph structures, Elements of a graph database
:usecase: recommendations

// == Course Description

Welcome to GraphAcademy, and the Neo4j Fundamentals course.
This course has been designed to set you on your way to becoming a Neo4j expert.
In this course you will learn about the underlying principles that underpin Neo4j.

We will take you on a journey from 1736 Prussia for a brief history of graph theory,  discuss the types of graphs you may see in the wild, and walk through an example dataset that we will revisit throughout your journey with GraphAcademy.

== 2025 Course Update

This course will be updated on the *2nd January 2025* to include new content and exercises.

If you are currently working through this course, *please complete it before this date*. 

If you are part way through the course when it is updated, you will *loose any progress*.

== Duration

1 hour

== What you will learn

* Basic graph theory and the elements that make a graph
* Graph structures
* Common graph use cases
* Elements of a Neo4j graph database
* How Neo4j implements index-free-adjacency
* How to navigate a Neo4j dataset
* How to write basic Cypher queries


[.includes]
== This course includes

// * [lessons]#9 lessons#
// * [challenges]#4 short hands-on challenges#
* [videos]#7 video lessons#
* [lessons]#3 lessons#
* [quizes]#8 multiple choice quizzes#
