= Neo4j Fundamentals
:categories: beginners:1
:status: active
:next: cypher-fundamentals
:duration: 30 minutes
:caption: Learn the basics of Neo4j and the property graph model
// :video: https://www.youtube.com/embed/gQN67autVaQ

////
Script: C:Neo4j Fundamentals
https://docs.google.com/document/d/1XUxDVgzFGR3XT1FC6ubWviitQdhJhf5NTZNMYzdCVVY/edit?usp=sharing

////

== Course Description

Welcome to GraphAcademy, and the Neo4j Fundamentals course.  This course has been designed to set you on your way to becoming a Neo4j expert.  In this course you will learn about the underlying principles that underpin Neo4j.

We will take you on a journey from 1736 Prussia for a brief history of Graph Theory,  discuss the types of Graph you may see in the wild and walk through an example dataset that we will revisit throughout your journey with GraphAcademy.



// This course introduces you to graph databases and how Neo4j supports them.

// This course contains videos, content, and questions to check your understanding of the content.

=== Prerequisites

You need not have any programming experience to take this course.

=== Duration

30 minutes

=== What you will learn

* Graph theory basics
* Common graph use cases
* The difference between directed and undirected graphs
* The elements of a Graph database
* The native Graph advantage
* How Graph Databases compare to other types of database
* How the movies dataset is structured
