= Course Summary
:pdf-summary:

In this course, you have learned:

* Basic graph theory 
* The structure of a Neo4j graph database
* Common graph use cases
* How to navigate a Neo4j database
* How to write simple Cypher queries

Continue your learning on GraphAcademy with the following link:https://graphacademy.neo4j.com/categories/beginners/[foundational courses^]:

* link:https://graphacademy.neo4j.com/courses/cypher-fundamentals/[Cypher Fundamentals^] - Learn the essentials of the Cypher query language
* link:https://graphacademy.neo4j.com/courses/modeling-fundamentals/[Graph Data Modeling Fundamentals^] - Learn how to design a Neo4j graph
* link:https://graphacademy.neo4j.com/courses/importing-cypher/[Importing CSV data into Neo4j] - Learn how to import CSV data into Neo4j using Cypher

You can create a free link:https://console.neo4j.io[Neo4j AuraDB instance^] or download link:https://neo4j.com/download/[Neo4j Desktop^] to get a free Neo4j database to support your learning.

Here is a summary of the course.
// Feel free to link:./print/[Save this file for future reference].

[.columns]
== What are graph databases?

[.large.list-columns]
* Graphs are mathematical structures consisting of **Edges** and **Vertices**
* Neo4j stores and organizes data using **Nodes**, **Relationships**, **Labels**, and **Properties**


[.columns]
== What are graph databases?

[.column]
=== Graphs are useful when:

// * The connections between data are as important as the data themselves.
// ** For example, social networks are built around the existence and strength of relationships between people.

* When the problem requires understanding the relationship between entities.
// ** For example, to analyze the connections between customers and products to provide recommendations.

* When the problem involves a hierarchy.
// ** For example, to understand the organizational hierarchy at a company.

* When the problem requires exploring relationships of varying or unknown depth.
// ** For example, to understand the use of a part in the manufacturing process.

* When the problem requires evaluating routes or paths through a network.
// ** For example, finding the quickest route on from your home to the office public transport.

[.column]
=== Common Use Cases

* E-commerce platforms combine ratings, purchase history and browsing history to provide **real-time recommendations**.
* The ICIJ used Neo4j to explore and understand the network of global companies and identify persons with significant control.
* Many enterprises use Neo4j for planning, cost analysis, impact analysis and also to troubleshoot problems when a problem arises.

[.column]
=== What gives Neo4j its advantage?

* Neo4j is a native graph database designed specifically for graph traversal.
// * The distinguishing feature of native graph databases like Neo4j is index-free adjacency, where relationships are stored with starting and ending nodes.
* Where Joins between tables are computed at read-time, this information is saved in a way that allows for quick pointer-chasing in memory
* Queries in Graph Databases are proportional to the amount of data touched during a query, not the size of data overall.


[.columns]
== What are Graph Databases?

[.column]
=== Graph Elements


[cols="1,3"]
|===
// | Element | Description

| **Node**
| A node will commonly represent an individual record, for example, a _thing_ or a _fact_.

| **Label**
| Nodes can have one or more labels.
Labels provide a way to group nodes and also serve as a starting point for any database queries.


| **Relationship**
| A relationship connects two nodes.
Each relationship has exactly one **start** and **end** node.
A relationship will have a single a **type**.

| **Type**
| Relationships are identified by their **type**.

| **Property**
| Both nodes and relationships can contain properties.
A property is a key/value pair.

|===

[.column.discrete]
=== Example Graph

image::https://cdn.graphacademy.neo4j.com/courses/neo4j-fundamentals/modules/1-graph-thinking/lessons/1-what-is-neo4j/images/node-properties.svg[An example graph, width=320]



// [.columns.page-break-before]
// == Modeling Rules

[.column]
=== Modeling Rules

* **Nodes typically represent things**.
Examples of entities that could typically be represented as a node are: person, product, event, book or subway station.

* **Relationships are typically verbs**.
We could use a relationship to represent a personal or professional connection (Person _knows_ Person, Person _married to_ Person), to state a fact (Person _lives in_ Location, Person _owns_ Car, Person _rated_ Movie), or even to represent a hierarchy (Parent _parent of_ Child, Software _depends on_ Library).


* **Verbs can also be nodes**.
A verb may be modeled as a node when one or more facts need to be associated with it.  For example, you may want to group multiple product purchases through a single `(:Order)` node.



[.hide-print]
include::{shared}/resources.adoc[]
