= Aura Tiers
:table-caption!:

One size does **not** fit all and before you embark upon the Aura journey it pays (literally) to pause for a moment and pin down what your purpose is.

== Selection

You want to experiment with graph. Dip your toe in, get your feet wet, test the waters or take the plunge. Your one graph isn't big, less than 200 000 nodes and less than 400 000 relationships. You don't care about high availability. Should this cost you money? No. It shouldn't and **Aura Free** is exactly where you need to be.

You developed that killer application and now want to take it a step further. The graph is bursting at the seams, you need more space. You want the database to run on a cloud of your choice (AWS, GCP, Azure) close to where your application is running. You still don't care about high availability but that daily backup gives you peace of mind. You have to pull out the credit card now, **Aura Professional** is the tier to allow.

Things are going great, you can hardly cope with the demand. Tightened security needed, RBAC and SSO will do. High availability is a must. Hourly backups buy you trust. The value proven, but it's time to evolve. **Aura Business Critical** is your enterprise-grade solve.

The auditors have arrived. They brought the compliance people too. Your application is about to go places but you need dedicated infrastructure. You also need everything encrypted with **your** keys. There's no need to shout, you need **Aura Virtual Dedicated Cloud**.

== Feature comparison

.Side-by-side
[cols="1,1,1,1,1"]  
|===
| |Free |Professional |Business Critical |VDC

|**payment method** |none |PAYG or prepaid ACU |PAYG or prepaid ACU |prepaid ACU
|**support** |link:https://community.neo4j.com/[community] |best effort |link:https://neo4j.com/terms/support-terms/[regional] |link:https://neo4j.com/terms/support-terms/[regional/global/signature]
|**cloud** | |GCP/AWS/Azure |GCP/AWS/Azure |GCP/AWS/Azure
|**architecture** | single instance |single instance | multi AZ cluster | multi AZ cluster
|**backups** |on demand |daily |daily |hourly
|**backup retention** | |7 days |30 days |60 days
|**instance size** | |1GB - 128GB |2GB - 512GB |2GB - 512GB 
|**upgrades** |automatic |automatic |automatic |automatic
|**security** |single user |single user |RBAC / SSO |RBAC / SSO / CMEK
|**uptime SLA** | | |99.95% |99.95%

|===

[NOTE]
====
* **ACU** - Aura Consumption Unit
* **CMEK** - Customer Managed Encryption Keys
* **PAYG** - Pay As You Go
* **RBAC** - Role Based Access Control
* **SSO** - Single Sign-On
* Instance size refers to **RAM**
* The main difference between **Business Critical** and **Aura Virtual Dedicated Cloud** is that the latter comes with VPC isolation and dedicated infrastructure.
* **SLA** - Service Level Agreement. Note that the 99.95% corresponds to that of what the cloud platforms themselves guarantee. So higher is currently not possible.
====

[.quiz]
== Check your understanding
include::questions/1-choosing.adoc[leveloffset=+1]

include::questions/2-differences.adoc[leveloffset=+1]

[.summary]
== Summary
In this lesson, you learned learned about the different tiers available on Neo4j Aura and how to select the right tier for your use case.
