= About Aura
:table-caption!:

For over 15 years now Neo4j has provided the go-to graph database. And it has no intention to stop doing that. Know your customer. Product recommendations. Fraud detection.  Connected data = graph. And Neo4j is there to help you make sense of it and support **your** business.

Your business is unlikely to be setting up and maintaining complex IT infrastructure. And even if it is, setting up and maintaining graph databases is not.

Over that same 15 years the **cloud** has made it's entry in most organisations. It takes care of the datacenter but everything else is still the same. Enter **Aura** Neo4j's Database-As-A-Service. We manage the database. That is **our** business so you can take care of **yours**.

.Side-by-side
[cols="1,1"]  
|===
|self-managed |Aura

|your datacenter/cloud | our cloud (GCP, AWS, Azure)
|SLA is your problem | SLA is our problem
|High availability is your problem | High availability is our problem
|Encryption is your problem | Encryption is our problem
|Backups are your problem | Backups are our problem
|Patches and upgrades are your problem | Patches and upgrades are our problem
|===

[.quiz]
== Check your understanding
include::questions/1-versus.adoc[leveloffset=+1]

[.summary]
== Summary
In this lesson you found out why Aura is a thing.
