= About Aura


Welcome to the Aura Fundamentals course on GraphAcademy!
Throughout this course, you will learn all about Neo4j Aura, a fully managed cloud graph database service that allows you to run multiple Neo4j instances. 

== Understanding Neo4j Aura

Aura provides a fully managed Neo4j database service, which means you don't have to worry about the underlying infrastructure, maintenance, or operations. You can deploy Neo4j instances in the cloud and scale them as needed without the hassle of managing servers, backups, or updates. 

== Comparing self-managed Neo4j with Aura

The key difference lies in who handles the operational responsibilities. With Aura, Neo4j handles everything so you can concentrate on building your application:

* **Infrastructure**: Fully managed service, with zero maintenance required from your side. Instances are deployed in the same region as your cloud provider, ensuring low latency, data security and compliance.
* **Service Level Agreements**: 99.95% uptime SLA is provided, with fault tolerance and high availability built-in, ensuring your database is always accessible.
* **High Availability**: Depending on the tier, Aura provides single instance or multi-availability zone cluster architectures, ensuring your data is always available and resilient to failures.
* **Security**: Built-in security features such as encryption at rest and in transit, as well as network isolation and access controls.
* **Backups**: Automated backups are taken regularly, allowing you to restore your database to a previous state if needed: 
  * Daily backups for Professional, Business Critical and Virtual Dedicated Cloud tiers.
  * Free tier allows you to take on-demand backups.
  * Enterprise: Up to 90 days retention.
* **Updates**: Aura handles all software updates and patches, ensuring you are always running the latest and most secure version of Neo4j.

This separation allows you to concentrate on building applications and analyzing data while Neo4j handles the database operations, monitoring, and maintenance.


== Check your understanding
include::questions/1-versus.adoc[leveloffset=+1]

[.summary]
== Summary
In this lesson, you learned what Neo4j Aura is and how it differs from self-managed Neo4j databases, with Aura handling all the operational responsibilities in the cloud.

In the next lesson, you will learn about the shared responsibilities of Aura and its users.
