= About Aura
:type: lesson
:order: 1
:slides: true

[.slide.discrete]
== Understanding Neo4j Aura

Welcome to the Aura Fundamentals course on GraphAcademy!

Throughout this course, you will learn how to get started with Neo4j Aura.

Aura provides a fully managed Neo4j database service, that allows you to run multiple instances in the cloud, while handling the underlying infrastructure, maintenance, and operations.
You can deploy Neo4j instances in the cloud and scale them as needed without the hassle of managing servers, backups, or updates.


[.slide]
== Comparing self-managed Neo4j with Aura

The key difference lies in who handles the operational responsibilities. With Aura, Neo4j handles everything so you can concentrate on building your application:

  * **Infrastructure**: Fully managed service, with zero maintenance required from your side.
  * **Service Level Agreements**: 99.95% uptime SLA is provided, with fault tolerance and high availability.
  * **High Availability**: Depending on the tier, Aura provides single instance or multi-availability zone cluster architectures.
  * **Security**: Encryption at rest and in transit, as well as network isolation and access controls.
  * **Backups**: Automated backups are taken regularly, allowing you to restore your database to a previous state if needed:
  ** Daily backups for Professional, Business Critical and Virtual Dedicated Cloud tiers.
  ** Free tier allows you to take on-demand backups.
  ** Enterprise: Up to 90 days retention.
  * **Updates**: Aura handles all software updates and patches, ensuring you are always running the latest and most secure version of Neo4j.

[.quiz]
== Check your understanding
include::questions/1-versus.adoc[leveloffset=+1]

[.summary]
== Summary
In this lesson, you learned what Neo4j Aura is and how it differs from self-managed Neo4j databases.

In the next lesson, you will learn about the shared responsibilities of Aura and its users.
