graph TD
    Territory -->|IN_REGION| Region
    Supplier -->|SUPPLIES| Product
    Product -->|PART_OF| Category
    Shipper -->|SHIPS| Order
    Customer -->|PURCHASED| Order
    Employee -->|SOLD| Order
    Employee -->|IN_TERRITORY| Territory
    Employee -->|REPORTS_TO| Employee
    Order -->|ORDERS<br/>unitPrice<br/>quantity<br/>discount| Product
    
    Territory(("<b>Territory</b>"))
    
    Region(("<b>Region</b>"))
    
    Supplier(("<b>Supplier</b>"))
    
    Shipper(("<b>Shipper</b>"))
    
    Product(("<b>Product</b>"))
    
    Category(("<b>Category</b>"))
    
    Order(("<b>Order</b>"))
    
    Customer(("<b>Customer</b>"))
    
    Employee(("<b>Employee</b>"))
