graph TD
    Territory -->|IN_REGION| Region
    Supplier -->|SUPPLIES| Product
    Product -->|PART_OF| Category
    Shipper -->|SHIPS| Order
    Customer -->|PURCHASED| Order
    Employee -->|SOLD| Order
    Employee -->|IN_TERRITORY| Territory
    Employee -->|REPORTS_TO| Employee
    Order -->|ORDERS<br/>unitPrice<br/>quantity<br/>discount| Product
    
    Territory(("<b>Territory</b><br/>territoryID<br/>territoryDescription"))
    
    Region(("<b>Region</b><br/>regionID<br/>regionDescription"))
    
    Supplier(("<b>Supplier</b><br/>supplierID<br/>companyName<br/>contactName<br/>contactTitle<br/>address<br/>city<br/>region<br/>postalCode<br/>country<br/>phone<br/>fax<br/>homePage"))
    
    Shipper(("<b>Shipper</b><br/>shipperID<br/>companyName<br/>phone"))
    
    Product(("<b>Product</b><br/>productID<br/>productName<br/>quantityPerUnit<br/>unitPrice<br/>unitsInStock<br/>unitsOnOrder<br/>reorderLevel<br/>discontinued"))
    
    Category(("<b>Category</b><br/>categoryID<br/>categoryName<br/>description"))
    
    Order(("<b>Order</b><br/>orderID<br/>orderDate<br/>requiredDate<br/>shippedDate<br/>freight<br/>shipName<br/>shipAddress<br/>shipCity<br/>shipRegion<br/>shipPostalCode<br/>shipCountry"))
    
    Customer(("<b>Customer</b><br/>customerID<br/>companyName<br/>contactName<br/>contactTitle<br/>address<br/>city<br/>region<br/>postalCode<br/>country<br/>phone<br/>fax"))
    
    Employee(("<b>Employee</b><br/>employeeID<br/>lastName<br/>firstName<br/>title<br/>titleOfCourtesy<br/>birthDate<br/>hireDate<br/>address<br/>city<br/>region<br/>postalCode<br/>country<br/>homePhone<br/>extension<br/>notes<br/>photoPath"))
