graph TD
    Territory -->|IN_REGION| Region
    Supplier -->|SUPPLIES| Product
    Product -->|PART_OF| Category
    Shipper -->|SHIPS| Order
    Customer -->|PURCHASED| Order
    Employee -->|SOLD| Order
    Employee -->|IN_TERRITORY| Territory
    Employee -->|REPORTS_TO| Employee
    Order -->|ORDERS<br/>unitPrice: float<br/>quantity: integer<br/>discount: float| Product
    
    Territory(("<b>Territory</b><br/>territoryID: string<br/>territoryDescription: string"))
    
    Region(("<b>Region</b><br/>regionID: string<br/>regionDescription: string"))
    
    Supplier(("<b>Supplier</b><br/>supplierID: string<br/>companyName: string<br/>contactName: string<br/>contactTitle: string<br/>address: string<br/>city: string<br/>region: string<br/>postalCode: string<br/>country: string<br/>phone: string<br/>fax: string<br/>homePage: string"))
    
    Shipper(("<b>Shipper</b><br/>shipperID: string<br/>companyName: string<br/>phone: string"))
    
    Product(("<b>Product</b><br/>productID: string<br/>productName: string<br/>quantityPerUnit: integer<br/>unitPrice: float<br/>unitsInStock: integer<br/>unitsOnOrder: integer<br/>reorderLevel: integer<br/>discontinued: boolean"))
    
    Category(("<b>Category</b><br/>categoryID: string<br/>categoryName: string<br/>description: string"))
    
    Order(("<b>Order</b><br/>orderID: string<br/>orderDate: string<br/>requiredDate: string<br/>shippedDate: string<br/>freight: string<br/>shipName: string<br/>shipAddress: string<br/>shipCity: string<br/>shipRegion: string<br/>shipPostalCode: string<br/>shipCountry: string"))
    
    Customer(("<b>Customer</b><br/>customerID: string<br/>companyName: string<br/>contactName: string<br/>contactTitle: string<br/>address: string<br/>city: string<br/>region: string<br/>postalCode: string<br/>country: string<br/>phone: string<br/>fax: string"))
    
    Employee(("<b>Employee</b><br/>employeeID: string<br/>lastName: string<br/>firstName: string<br/>title: string<br/>titleOfCourtesy: string<br/>birthDate: string<br/>hireDate: string<br/>address: string<br/>city: string<br/>region: string<br/>postalCode: string<br/>country: string<br/>homePhone: string<br/>extension: string<br/>notes: string<br/>photoPath: string"))