= About the Driver
:type: quiz

In the link:/courses/cypher-fundamentals/[Cypher Fundamentals^] course, we cover how to query Neo4j using a language called Cypher.
To execute a Cypher query against a Neo4j database you will use an object called a *Driver*.


// tag::driver[]
> The **Driver** object is a thread-safe, application-wide fixture from which all Neo4j interaction derives.
>
> The Driver API is **topology independent**, so you can run the same code against a *Neo4j cluster* or a *single DBMS*.

// end::driver[]

To connect to and query Neo4j from within a Java application, you use the link:https://neo4j.com/developer/java[Neo4j Java Driver^].

The Neo4j Java Driver is one of five officially supported drivers, the others are Java, .NET, Python, and Go.
There are also a wide range of Community Drivers available for other languages including PHP and Ruby.

You should create a **single instance** of the Driver in your application per Neo4j cluster or DBMS, which can then be shared across your application.

== Installing the Driver

The Neo4j Java Driver is available from Maven Central, so you can use it with Maven, Gradle and other build tools.

In our project we use Maven, so you can add the driver with the following dependency section to your `pom.xml`.

[source,xml,indent=0]
----
include::{repository-raw}/main/pom.xml[tag=driver]
----

== Creating a Driver Instance

Each driver instance will connect to one DBMS, or Neo4j cluster, depending on the value provided in the connection string.

After importing the `org.neo4j.driver.*` package, you can instantiate a `Driver` instance from the `GraphDatabase.driver()` factory method call.
The `driver()` method requires two arguments:

1. **A connection string** for the Neo4j cluster or DBMS - for example `neo4j://localhost:7687` or `neo4j+s://_dbhash_.databases.neo4j.io:7687`
2. **An authentication token** - Neo4j supports basic username and password authentication, kerberos tokens or custom authentication.  You can create an authentication token by calling one of the static methods provided by `AuthTokens`.


Here is an example for how to create a driver instance:

.Creating a Driver Instance
[source,java,indent=0,role=nocopy,subs="attributes+"]
----
include::{repository-raw}/main/src/main/java/example/index.java[tag=import]

include::{repository-raw}/main/src/main/java/example/index.java[tag=driver,indent=0]
----

The above example creates an _unencrypted_ connection to the Neo4j server at `localhost` on the default port number of `7687`.
The driver then attemps to authenticate against the server using a basic authentication with the username `neo4j` and password `letmein!`.


=== Verifying Connectivity

You can verify that the connection details used during driver instantiation are correct by calling the `verifyConnectivity()` function.
This function returns the Driver instance if the connection details are correct, or fails with a `Neo.ClientError.Security.Unauthorized` Exception if a connection could not be made.

.Verify Connectivity
[source,java,indent=0,role=nocopy,subs="attributes+"]
----
include::{repository-raw}/main/src/main/java/example/index.java[tag=verifyConnectivity,indent=0]
----


== Check Your Understanding

// To do: need to add some hints for these

include::./questions/1-supported-languages.adoc[leveloffset=+1]

include::./questions/2-package-name.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this lesson, you learned about the Neo4j Java Driver and how it can be used to connect to Neo4j from within a Java application.

In the next lesson, we will take a closer look at the first argument in the `GraphDatabase.driver()` method, the connection string.
