[.question]
= 1. What type of constraint?

Suppose your graph data model includes _Customer_ nodes and _Order_ nodes where there is a _SUBMITTED_ relationship between a _Customer_ node and an _Order_ node.
Some properties of the _Order_ node include the _date_ and _vendorNum_ properties.
The customer can only submit one order per day for a given vendor (identified by vendorNum).

What type of constraint would be best for this use case in our application where we want to allow a single order per day for a vendor?

[source,cypher,rel="norun nocopy"]
----
// Find the customer, c
// Find the order, o
MERGE (c)-[r:SUBMITTED]->(o)
// set the order to today with the vendor vNum
SET o.date = date(), o.vendorNum = $vNum
----

* [ ] existence constraint on o.date
* [ ] uniqueness constraint on o.date
* [x] Node key on o.date and o.vendorNum
* [ ] Node key on c.name and o.orderNum

[TIP,role=hint]
.Hint
====
A node key constraint provides existence and uniqueness for multiple property values.
====

[TIP,role=solution]
.Solution
====
A node key on o.vendorNum  and o.date ensures that only one order per vendor is added to the graph.
====