= Setting up the Project
:type: text
:order: 1
:node-version: v16.15.1

We have put together a project with all of the boilerplate in place.
As you move through this course, you will learn some theory and then how to apply it to the example project.

In order to run the project, you must make sure that Node.js is installed.


== Setup Node.js

We are assuming that in taking this course, you already have at least a basic understanding of Node.js.

If you haven't already installed Node.js, you must link:https://nodejs.org/en/[install Node.js using the instructions on nodejs.org^].
The project has been written to work wth Node.js version **{node-version}**.

You can verify that the installation is successful by running the following command in the command line:

.Verify Node.js Version
[source,sh]
node -v

You will also need a package manager to install the dependencies.  NPM is included with Node.js, but if you prefer you can also link:https://classic.yarnpkg.com/lang/en/docs/install/[install Yarn using these instructions^].



// == Clone the Repository

include::{shared}/lesson/clone-repository.adoc[]


== Install Dependencies

Once you have cloned the repository, navigate to the folder in your terminal and run the following command to install the dependencies.

[.tab]
.NPM
====
.Install Dependencies using NPM
[source,sh]
npm install
====

[.tab]
.Yarn
====
.Install Dependencies using Yarn
[source,sh]
yarn install
====

You can view a full list of dependencies by opening link:{repository-raw}/main/package.json[`package.json`^].

[WARNING]
.Errors while installing dependencies?
====
This project has been written using Node.js version **{node-version}**.
If you are using the wrong version, you may experience errors when trying to install the dependencies.

The project includes an `.nvmrc` file which can be used in conjuction with Node Version Manager (`nvm`) to set the correct version of Node.js.
If you experience any problems, run the following commands to set your Node.js configuration to the correct version for your current terminal session.

[source,sh]
----
nvm install
nvm use
----
====


== Setting Environment Variables

This project uses the link:https://www.npmjs.com/package/dotenv[`dotenv`^] library to manage environment variables for this project.
When the `config()` function exported by the `dotenv` library is called, the `.env` file in the root of the project is parsed and all settings are appended to the `process.env` variable.

The project contains an example file at `.env.example`.  You can run the following command in your terminal window to copy the example file to `.env`.

[source,sh]
cp .env.example .env


== Start the Project

To start the project, run the following command:

[.tab]
.NPM
====
.Start the project using NPM
[source,sh]
npm start
====

[.tab]
.Yarn
====
.Start the project using Yarn
[source,sh]
yarn start
====

You should see an output similar to the following confirming that the server has successfully started:

.Console Output
[source,role=nocopy]
[nodemon] 2.0.13
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src`
Server listening on http://localhost:3000/

Unless you change the `APP_PORT` setting in `.env`, the server will listen on http://localhost:3000.
You can change which port the server listens on by editing the `APP_PORT` variable in `.env` and restarting the node pocess.


== A Brief Tour of the Project

If you open up the listening address in your browser, you will see a Single Page Application (SPA) that communicates with the API served at http://localhost:3000/api.
Currently, the responses are hardcoded, but as you progress through the course, you will learn how to query Neo4j to find this information.

Here are some of the important directories in the project:

// * `.env` - This file holds environment variables for the server and is parsed by the link:https://www.npmjs.com/package/dotenv[`dotenv`^] library.
* `example/` - Example code for driver instantiation.
* `src/` - The application code:
** `middleware/` - Some custom middleware functions that are used by Express including generic error handling.
** `passport/` - Logic required for user authentication.
** `routes/` - Route handlers that are registered on the server.  You shouldn't need to edit these files.
** `services/` - Services that you will need to update to interact with Neo4j.
* `test/` - Test files that will you will need to run in order to pass the test.  You will run these using the `npm run test` or `yarn run test` command.
* `public/` - Minified build files for the SPA.  *Do not edit these files*.


== Done!

Once you have the project up and running, click the button below to complete this lesson.

read::The project is running![]


[.summary]
== Next Steps

Now that we have the project up and running, let's take a look at the Neo4j Sandbox instance that has been created as part of your enrollment in this course.
