= Using Parameters
:type: challenge
:sandbox: true
:updated-at: 2022-05-03T14:00:00Z

In the previous challenge, you identified how to set the `name` parameter within a Neo4j Browser session.

In this challenge, you will need to execute the following query to find all movies acted in by an Actor with a name **starting with** Tom, and that also have the value **UK** within the `countries` array on the movie.

.Your Query
[source,cypher]
----
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
WHERE p.name STARTS WITH $name
AND $country IN m.countries
RETURN p.name AS actor,
m.title AS title
----

If you run this query without setting any parameters, you will receive an error:

----
Expected parameter(s): name, coutry
----

To complete this challenge, complete the following steps:




== 1. Set the `name` Parameter

Using the same format as the previous lesson, set the [copy]#name# parameter to [copy]#Tom#.

== 2. Set the `country` Parameter

Set the [copy]#country# parameter to [copy]#UK#.


== 3. Execute the Query

Hit the **Run in Sandbox** button to the top right of the query window below to execute the query.

.Run this Query
[source,cypher]
----
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
WHERE p.name STARTS WITH $name
AND $country IN m.countries
RETURN p.name AS actor,
m.title AS title
----

You should see a message at the bottom of the screen in the following format:

_Started streaming **XXX** records after Y ms and completed after Z ms._


include::./questions/q1.adoc[leveloffset=+1]


[.summary]
== Summary

In this challenge, you used multiple parameters to affect the results of a Cypher query.

In the next lesson, you will see some application code that uses parameters in Cypher.
