[.question.freetext]
= Encode the Punctuality value

Your challenge is to encode the `Punctuality` property from text to a numerical value using a Cypher query.

Follow these guidelines:

* Map 'I am often running late' to `1`
* Map 'I am often early' to `3`
* Map 'I am always on time' to `5`

Use the Cypher `CASE` clause to accomplish this task and store the results in a new property `PunctualityEncoding`.

Modify the Cypher statement in the Neo4j Browser window to encode the `Punctuality` variable and store the results as a `PunctualityEncoding` property on the node.

Hit the **Check Database** button below to verify that the test has been successfully run.

verify::[]


[TIP,role=hint]
.Hint
====
You should use the Cypher `CASE` clause to convert the text values into a numerical value and assign the value to the `PunctualityEncoding` property.

.Case Statement
[source,cypher]
----
include::../solution.cypher[tag=case]
----

====


[TIP,role=solution]
.Solution
====
The following Cypher statement uses the `CASE` clause to encode the values as an integer and stores the value in the `PunctualityEncoding` property.

[source,cypher]
----
include::../solution.cypher[]
----

Once you have run this statement, click **Try again...*** to complete the challenge.
====
