= The Neo4j Type System
:type: lesson
:order: 3

At this point, we should take a look at the Cypher type system.
As Neo4j is written in Java (the _j_ in Neo4**j** stands for _Java_ after all), there are some discrepancies between the types stored in the Neo4j database and native C# types.

Some values like strings, numbers, booleans, dates, and nulls map directly to C# types but more complex types like nodes, relationship, points, durations need special handling.

//Adam: are the Cypher types here supposed to be the types in the db (according to apoc.meta.nodeTypeProperty??
[%collapsible]
..NET Types to Neo4j/Cypher Types
====
[cols="1,1,1"]
|===
| Neo4j Cypher Type | .NET Type | Notes

| null | null |
| List | IList<object> |
| Map | IDictionary<string, object> |
| Boolean | `bool` |
| Integer | `int` or `long` |
| Float | `double` |
| String | `string` |
| ByteArray | `byte[]` |
| Date | `LocalDate` | See <<Temporal Types>>
| Time | `OffsetTime` | See <<Temporal Types>>
| LocalTime | `LocalTime` | See <<Temporal Types>>
| DateTime* | `ZonedDateTime` | See <<Temporal Types>>
| LocalDateTime | `LocalDateTime` | See <<Temporal Types>>
| Duration | `Duration` |
| Point | `Point` |
| Node | `INode` | See <<Nodes & Relationships>>
| Relationship | `IRelationship` | See <<Nodes & Relationships>>
| Path | `IPath` | See <<Nodes & Relationships>>

|===

* Time zone names adhere to the link:https://www.iana.org/time-zones[IANA system^], rather than the link:https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones[Windows system^]. Inbound conversion is carried out using link:http://cldr.unicode.org/development/development-process/design-proposals/extended-windows-olson-zid-mapping[Extended Windows-Olson zid mapping^] as defined by Unicode CLDR.

====


You can use the `.As<Type>` method on any `Values` type or nested structure to cast underlying values to expected types.
See the https://neo4j.com/docs/api/dotnet-driver/current/html/71232690-2adc-e9b2-275e-c5d6d0c13bb3.htm[API docs for `IRecord.Values`^] for more information.

For example, in the code block below, the `year` value is cast as a `Number`.

.Accessing Values
[source,c#,role=ncopy,subs="attributes+",indent=0]
----
int movieCount = row["movieCount"].As<int>();
----
// include::{repository-raw}/main/Examples/Neo4jExamples/Results.cs[tag=values]

Let's take a look at some of these types in more detail.

== Numbers

For numeric values the main confusion comes from the naming, while Neo4j itself can store all kinds of .NET primitive values for a unified surface, Cypher only exposes one floating point type called `Float` (equivalent to 64-bit double) and one integer type  called `Integer` (equivalent to 64-bit long).

Cypher itself has functions like `toFloat()` and `toInteger()` respectively and driver parameters of other types are automatically coerced.

The driver's `Value` type can return most .NET numeric types via `.As<Type>` methods.

== Temporal Types

The Temporal types used in the Cypher type system mirror the .NET temporal types, so there are few surprises.
// The only difference is `IsoDuration` for which the driver provides a custom type.

.Temporal Types
[cols="1,3,1,1"]
|===
| Type | Description | Example | Access Function

| `Date`
| Represents an instant capturing the date, but not the time, nor the timezone.
| `2020-01-02`
| `As<Date>`

| `DateTime`
| Represents an instant capturing the date, the time and the timezone identifier.
| `2020-01-02T01:02:03+04:00`
| `As<DateTime>`


| `LocalDateTime`
| Represents an instant capturing the date and the time, but not the timezone.
| `2020-01-02T01:02:03`
| `As<LocalDateTime>`

| `LocalTime`
| Represents an instant capturing the time of day, but not the date, nor the timezone.
| `12:34:56`
| `As<LocalTime>`

// | `DateTimeOffset`
// | Represents an instant capturing the time of day, and the timezone offset in seconds, but not the date.
// | `12:34:56+04:00`
// | `As<DateTimeOffset>`

| `Duration`
| Represents a duration between two dates or timestamps (different resolutions). Has individual accessors for the parts.
| `P1M12D`
| `As<DateTimeOffset>`

|===

.Working with Temporal types
[source,c#,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/Examples/Neo4jExamples/Results.cs[tag=temporal]
----


== Nodes & Relationships

Nodes and Relationships are both returned as similar types with a common interface `IEntity`.

As an example, let's take the following code snippet:

.Return Nodes and Relationships
[source,c#,role=ncopy,subs="attributes+",indent=0]
----
var cursor = await tx.RunAsync(@"
    MATCH path = (person:Person)-[actedIn:ACTED_IN]->(movie:Movie)
    RETURN path, person, actedIn, movie,
            size((person)-[:ACTED]->()) as movieCount,
            exists { (person)-[:DIRECTED]->() } as isDirector
    LIMIT 1
");
----

=== Nodes

We can retrieve the `person` value using the `.Values["person"]` method on the row and then turn it into a `INode` using `as<INode>`.

[source,c#,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/Examples/Neo4jExamples/Results.cs[tag=get]
----

The value assigned to the `person` variable will be the instance of an `INode` implementation.
`INode` is an implementation provided by the Neo4j .NET Driver to represent the information held in Neo4j for a node.

An instance of a `Node` has three parts:

.Working with Node Objects
[source,c#,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/Examples/Neo4jExamples/Results.cs[tag=node]
----

1. `Id` - a `long` representing the internal ID for the node.
2. `Labels` -  a list of string values, eg. `['Person', 'Actor']`
3. `Properties` - A dictionary containing all the properties for the node. +
    eg. `{"name": "Tom Hanks", "tmdbId": "31" }`

Properties can also be retrieved from `IEntity` instances using square brackets, for example `person.Properties["name"]`.

[TIP]
.Internal IDs
Internal IDs should be treated as opaque values and just sent back to the database as you get them.
These ids can be re-used, a best practice is to always look up a node by its business key and label rather than relying on an internal ID.

=== Relationships

`Relationship` objects are also `IEntity` instances, and therefore also include an `Id`, and `Properties`.


.Working with Relationships
[source,c#,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/Examples/Neo4jExamples/Results.cs[tag=rel]
----


1. `Id` - the internal ID for the relationship.
2. `Type` - a string representing the type of the relationship, eg - `ACTED_IN`
3. `Properties` - A .NET Map containing all the properties for the relationship. +
    eg. `{"role": "Woody" }`
4. `StartNodeId` - a `long` representing the internal ID for the node at the start of the relationship
5. `EndNodeId` - a `long` representing the internal ID for the node at the end of the relationship


=== Paths

If you return a path of nodes and relationships, they will be returned as an instance of the `IPath` implementation.

.Working with Path Objects
[source,c#,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/Examples/Neo4jExamples/Results.cs[tag=path]
----

1. `Start` - the node starting the path
2. `End` - the node ending the path
3. `Nodes` - An `IEnumerable` containing the nodes that form the path
4. `Relationships` - An `IEnumerable` containing `IRelationship` implementations for all segments within the path


==== Path Segments

A path is split into segments representing each relationship in the path.
For example, say we have a path of `+(p:Person)-[:ACTED_IN]->(m:Movie)-[:IN_GENRE]->(g:Genre)+`, there would be two segments.

1. `+(p:Person)-[:ACTED_IN]->(m:Movie)+`
2. `+(m:Movie)-[:IN_GENRE]->(g:Genre)+`

The `IPath` implementation can be iterated over to access each relationship within the path.

.Iterating over Segments
[source,c#,role=ncopy,subs="attributes+",indent=0]
----
foreach (var segment in path) {
    Console.WriteLine(segment.Id);
    Console.WriteLine(segment.Type);
    Console.WriteLine(segment.StartNodeId);
    Console.WriteLine(segment.EndNodeId);
    Console.WriteLine(segment.Properties);
}
----
// include::{repository-raw}/main/Examples/Neo4jExamples/Results.cs[tag=segments]

== Check Your Understanding

include::questions/1-node-property.adoc[leveloffset=+2]

include::questions/2-temporal.adoc[leveloffset=+2]

[.summary]
== Lesson Summary

In this lesson you have learned how to handle some of the more complex objects returned by a Cypher statement.
As we progress through this module, you will use the knowledge gained so far to read data from, and write data back to the database.

In the next Challenge, you will modify code to read from the database.