[.question]
= Querying a vector index

What does the `SEARCH` clause expect? (Select all that apply)

* [x] `binding_variable` - a node or relationship in the `MATCH` pattern to which the search will be applied
* [x] `index_name` - the name of the vector index to query
* [x] `query_vector` - a vector value to compare against the vectors in the index
* [x] `top_k` - the number of most similar results to return
* [ ] `token` - The OpenAI token to use for the query

[TIP,role=hint]
.Hint
====
A token is only required to create an embedding not to query one.
====

[TIP,role=solution]
.Solution
====
The `SEARCH` clause expects the following:

* [x] `binding_variable` - a node or relationship in the `MATCH` pattern to which the search will be applied
* [x] `index_name` - the name of the vector index to query
* [x] `query_vector` - a vector value to compare against the vectors in the index
* [x] `top_k` - the number of most similar results to return
    
A token is only required to create an embedding, not to query the index.
====
