= The Neo4j Type System
:type: quiz

At this point, we look at the Cypher type system.
As Neo4j is written in Java (the _j_ in Neo4**j** stands for Java after all), there are some discrepencies between the types stored in the Neo4j database and native Python types.

Some values like strings, floats, booleans, and nulls have a direct mapping to Python types but more complex types need special handling.

//Adam: are the Cypher types here supposed to be the types in the db (according to apoc.meta.nodeTypeProperty??
[%collapsible]
.Python Types to Neo4j Types
====
[cols="1,1,1"]
|===
| Python Type | Neo4j Cypher Type | Notes

| `None`
| `null`
|

| `bool`
| `Boolean`
|

| `int`
| `Integer`
|

| `float`
| `Float`
|

| `str`
| `String`
|

| `bytearray`
| `Bytes [1]`
|

| `list`
| `List`
|

| `dict`
| `Map`
|


// | `Date`
// | `Date`
// | See <<Temporal Types>>

// | `Time`
// | `Time`
// | See <<Temporal Types>>

// | `LocalTime`
// | `LocalTime`
// | See <<Temporal Types>>

// | `DateTime`
// | `DateTime`
// | See <<Temporal Types>>

// | `LocalDateTime`
// | `LocalDateTime`
// | See <<Temporal Types>>

// | `Duration`
// | `Duration`
// |

| `neo4j.spatial.Point`
| `Point`
| See <<Spatial Data Types>>

| `neo4j.spatial.CartesianPoint`
| `Point (Cartesian)`
| See <<Spatial Data Types>>

| `neo4j.spatial.WGS84Point`
| `Point (WGS-84)`
| See <<Spatial Data Types>>



| `neo4j.graph.Node`
| `Node`
| See <<Nodes & Relationships>>

| `neo4j.graph.Relationship`
| `Relationship`
| See <<Nodes & Relationships>>

| `neo4j.graph.Path`
| `Path`
| See <<Nodes & Relationships>>

|===

For more information about Temporal Data Types, see <<Temporal Data Types>>.

====

Let's take a look at some of these types in more detail.



== Temporal Data Types

Temporal data types are implemented by the neo4j.time module.

It provides a set of types compliant with ISO-8601 and Cypher, which are similar to those found in the built-in datetime module. Sub-second values are measured to nanosecond precision and the types are compatible with link:http://pytz.sourceforge.net/[pytz^].

The table below shows the general mappings between Cypher and the temporal types provided by the driver.

In addition, the built-in temporal types can be passed as parameters and will be mapped appropriately.


.Temporal Types
[cols="1,3,1,1"]
|===
| Neo4j Cypher Type | Python driver type | Python built-in type | `tzinfo`


| Date
| `neo4j.time.Date`
| `datetime.date`
|

| Time
| `neo4j.time.Time`
| `datetime.time`
| not `None`

| LocalTime
| `neo4j.time.Time`
| `datetime.time`
| `None`

| DateTime
| `neo4j.time.DateTime`
| `datetime.datetime`
| not `None`

| LocalDateTime
| `neo4j.time.DateTime`
| `datetime.datetime`
| `None`

| Duration
| `neo4j.time.Duration`
| `datetime.timedelta`
|

|===



.Working with Temporal types
[source,python,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/example/results.py[tag=temporal]
----

Each of the above types has a number of attributes for accessing the different, for example `year`, `month`, `day`, and in the case of the types that include a time, `hour`, `minute` and `second`.

For more information, see link:https://neo4j.com/docs/api/python-driver/4.4/temporal_types.html[Temporal Data Types^&^].


== Nodes & Relationships

Nodes and Relationships are both returned as similar classes.

As an example, let's take the following code snippet:

.Return Nodes and Relationships
[source,python,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/example/results.py[tag=run]
----

The query will return one record for each `:Person` and `:Movie` node with an `:ACTED_IN` relationship between them.

=== Nodes

We can retrieve the `movie` value from a record using the `[]` brackets method, providing a string that refers to the alias for the `:Movie` node in the Cypher query.

[source,python,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/example/results.py[tag=node]
----

The value assigned to the `node` variable will be the instance of a `Node`.
Node is a type provided by the Neo4j Python Driver to hold the information held in Neo4j for the node.

.Working with Node Objects
[source,python,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/example/results.py[tag=node_info]
----

1. The `id` property provides access to the node's Internal ID +
    eg. `1234`
2. The `labels` property is a frozenset containing an array of labels attributed to the Node +
    eg. `['Person', 'Actor']`
3. The `items()` method provides access to the node's properties as an iterable of all name-value pairs. +
    eg. `{name: 'Tom Hanks', tmdbId: '31' }`
4. A single property can be retrieved by either using `[]` brackets or using the `get()` method.  The `get()` method also allows you to define a default property if none exists.


[TIP]
.Internal IDs
Internal IDs refer to the position in the Neo4j store files where the record is held.
These numbers can be re-used, a best practice is to always look up a node by its key rather than relying on an internal ID.

=== Relationships

`Relationship` objects re similar to a `Node` in that they provide the same method for accessing the internal ID and properties.


.Working with Relationship Objects
[source,python,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/example/results.py[tag=rel]
----


1. The `id` property holds the internal ID of the relationship. +
    eg. `9876`
2. The `type` property holds the relationship type +
    eg - `ACTED_IN`
3. The `items()` method provides access to the relationships's properties as an iterable of all name-value pairs. +
    eg. `{role: 'Woody' }`
4. As with Nodes, you can access a single relationship property using brackets or the `get()` method.
5. `start_node` - an integer representing the internal ID for the node at the start of the relationship
6. `end_node` - an integer representing the internal ID for the node at the end of the relationship


=== Paths

If you return a path of nodes and relationships, they will be returned as an instance of a `Path`.

.Working with Path Objects
[source,python,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/example/results.py[tag=path]
----

1. `start_node` - a Neo4j `Integer` representing the internal ID for the node at the start of the path
2.  `end_node` - a Neo4j `Integer` representing the internal ID for the node at the end of the path
3. `len(path)` - A count of the number of relationships within the path
4. `relationships` - An array of `Relationship` objects within the path.

==== Path Segments

A path is split into segments representing each relationship in the path.
For example, say we have a path of `(p:Person)-[:ACTED_IN]->(m:Movie)-[:IN_GENRE]->(g:Genre)`, there would be two relationships.

1. `(p:Person)-[:ACTED_IN]->(m:Movie)`
2. `(m:Movie)-[:IN_GENRE]->(g:Genre)`

The relationships within a path can be iterated over using the `iter()` function.

.Iterating over Segments
[source,python,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/example/results.py[tag=segments]
----


== Check Your Understanding

include::questions/1-node-property.adoc[leveloffset=+1]

include::questions/2-integer-helper.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this lesson you have learned how to handle some of the more complex objects returned by a Cypher query.

As we progress through this module, you will use the knowledge gained so far to read data from, and write data back to the database.
In the next Challenge, you will modify code to read from the database.