:id: _challenge

[.verify]
= Verifying the Test

If the test has run successfully, a user with the email address `graphacademy.favorite@neo4j.com` will have added the movie Toy Story to their list of favorites.


verify::[]

//appears when user clicks the Hint button
[TIP,role=hint]
.Hint
====
You can run the following query to check for the user within the database.
If the `shouldVerify` value returns true, the verification should be successful.

[source,cypher]
----
include::{cypher-repository-raw}/main/cypher/2-interacting/9-user-favorites/verify-relationship-exists.cypher[]
----

====

[TIP,role=solution]
.Solution
====
The following statement will mimic the behaviour of the test, merging a new `:User` node with the email address `graphacademy.favorite@neo4j.com` and ensuring that a node exists for the movie Toy Story.
The test then merges a `:HAS_FAVORITE` relationship between the user and movie nodes.
[source,cypher]
----
include::../solution.cypher[]
----
Once you have run this statement, click **Try again...*** to complete the challenge.
====
