= Why we teach
:type: lesson
:order: 1

== Our mission

The mission of GraphAcademy is to **teach developers and data scientists** everything they need to know to be **successful with Neo4j**.

We do this with a **Hands-on** learning approach with interactive exercises.


== How we are judged

We use the following key metrics to judge the overall efficacy of the platform.

1. **Total enrollment** - an increasing number of enrollments means we are offering courses that users care about.  We look to increase the total enrollment numbers by 30% year-on-year.

2. **Completed enrollment percentage** - let's face it, total enrollments is a vanity metric that will only go up.  The more engaging our courses are, the more likely users are to complete them.  The aim should be to have a 40% completion rate per course, way above industry standards for free online courses.

3. **Enrollments per user** - we want users to continue learning with us.  The more courses the user takes, the more knowledge they hold, and the more likely they will be to keep Neo4j top of mind.   The aim is 2.5 enrollments per user.

4. **Positive feedback percentage** - The more positive feedback we receive, the better our course content is.  The goal is to keep positive feedback above 98%.


[TIP]
.Engaged Developer
====
Completing two or more courses qualifies the learner as an **engaged developer**, a metric used across Marketing to judge our efforts.
====


== Movie recommendations

Where possible, we use the link:https://sandbox.neo4j.com?uecase=recommendations[movie recommendations^] dataset.
This dataset is ubiquitous and easy to understand.

We try to avoid _verticals_ or the seven graphs where possible, as a left-field dataset covers what the learner needs to know without being overly specific to a certain industry.

The dataset is rich enough to provide **real-world examples** of data modeling, import and Cypher.

== Learning paths

If the learner feels that they are working towards something, they are more likely to complete and continue to the next course.

Just as we build on the knowledge of a previous lesson into the next, each course builds on the information in a previous course.

Courses are categorized as beginner, intermediate and advanced.

A _beginners_ course that acts as an entry-point to a subject should assume no prior knowledge of the subject.  This should be followed by intermediate courses that build on the subject, and into advanced courses.

At the end of the path, the user should be left with something that they can extend, either a working website, application, or a graph that they can demo to their colleagues.

read::Complete[]

[.summary]
== Summary

In this lesson, you learned about the mission of GraphAcademy, how we are judged, and the movie recommendations dataset.

In the next lesson, you will learn about the GraphAcademy pedagogy and learning approach.