= Creating a Node Key Constraint
:type: challenge
:order: 9
:sandbox: true

== Set of properties must exist and must be unique

In our Movie data model, we want to ensure every Person in the graph has both name and url properties defined and also that the two properties combined are unique across all nodes.

Recall from earlier in this course that there are two Person nodes with the same name:

[source,cypher]
----
MATCH (p:Person)
WHERE p.name = 'Austin Green'
RETURN p
----

In the sandbox on the right, modify the code to a Node key constraint for the name and url properties in the graph.

* *`constraint_name`*: [copy]#Person_name_url_nodekey#
* *`node_label`*: [copy]#Person#
* *`property_keys`*: [copy]#name#, [copy]#url#

After you have created the Node key constraint, list all constraints:

[source,cypher]
----
SHOW CONSTRAINTS
----

[NOTE]
.Creating Multiple Constraints
--
If you create incorrect constraints with different names or property_key names, do not worry.
You can create new ones, provided the constraint_name or property_key is unique.
Later in this course you will learn how to remove constraints from the graph.

If you reload this page, the graph will be reset to what it should be at the beginning of the challenge.
--


include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Summary

In this challenge, you demonstrated that you can create a Node key constraint for multiple node properties in the graph.
In the next challenge, you will drop constraints from the graph.
