= The @cypher Directive
:order: 1

Schema directives are GraphQL's built-in extension mechanism and indicate that some custom logic will occur on the server. Schema directives are not exposed through GraphQL introspection and are therefore invisible to the client. The `@cypher` GraphQL schema directive allows for defining custom logic using Cypher in the GraphQL schema. Using the `@cypher` schema directive overrides field resolution and will execute the attached Cypher statement to resolve the GraphQL field. Refer to the https://neo4j.com/docs/graphql-manual/current/type-definitions/cypher/[`@cypher` directive documentation for more information.]

== Computed Scalar Field

Let's look at an example of using the `@cypher` directive to define a computed scalar field in our GraphQL schema. Let's compute the average of the user reviews for any resolved movies. These review ratings are stored as relationship properties on the `RATED` relationship. A Cypher query to compute the average of the user ratings of the movie Jurassic Park would look like this:

[source,Cypher,role=nocopy]
----
MATCH (m:Movie {title: "Jurassic Park"})<-[r:RATED]-(:User)
RETURN avg(r.rating) AS avgRating
----

With the `@cypher` schema directive in the Neo4j GraphQL Library we can add a field called `avgRating` to our `Movie` type that includes the logic for traversing through any user ratings and computing the average.

Return to the Type definitions pane in GraphQL Toolbox and add the following to your GraphQL type definitions.

[source,GraphQL]
----
extend type Movie {
  avgRating: Float
    @cypher(
      statement: """
      MATCH (this)<-[r:RATED]-(:User)
      RETURN avg(r.rating)
      """
    )
}
----

The `@cypher` directive takes a single argument `statement` which is the Cypher statement to be executed to resolve the field. This Cypher statement can reference the `this` variable which is the currently resolved node, in this case the currently resolved `Movie` node.

We can now include this `avgRating` field in our GraphQL queries:

[source,GraphQL]
----
{
  movies(where: { title_CONTAINS: "Matrix" }) {
    title
    avgRating
  }
}
----

[source,JSON,role=nocopy]
----
{
  "data": {
    "movies": [
      {
        "title": "Matrix Reloaded, The",
        "avgRating": 3.268292682926829
      },
      {
        "title": "Matrix Revolutions, The",
        "avgRating": 3.037037037037037
      },
      {
        "title": "Matrix, The",
        "avgRating": 4.183397683397683
      }
    ]
  }
}
----

The `@cypher` directive gives us all the power of Cypher, with the ability to express complex traversals, pattern matching, even leveraging Cypher procedures like APOC. Let's see how we can use the `@cypher` directive to define a node object array field - in this case to add movie recommendations to our API!

== Node And Object Fields

The above example used a `@cypher` directive field to compute a scalar field by returning a scalar value from the Cypher query defined in the `@cypher` directive. If we return node objects in the Cypher query we can create object and object array fields backed by a Cypher query. 

Let's say that a user enjoyed the movie Jurassic Park. How could we find similar movies that the user might also enjoy? One approach would be to find all the users who rated Jurassic Park and then traverse to all the other movies those users rated, and then find the most common movies these users also rated. This is an example of a collaborative filtering recommendation query that uses information about user actions from the graph to create recommendations.

[source,Cypher,role=nocopy]
----
MATCH (m:Movie {title: "Jurassic Park"})<-[:RATED]->(u:User)-[:RATED]->(rec:Movie)
WITH rec, COUNT(u) AS score ORDER BY score DESC
RETURN rec LIMIT 3
----

Let's update our GraphQL type definitions to include this movie recommendation query as a `@cypher` directive field. We'll add this field to the `Movie` type, and return recommended movies for the currently resolved movie.

[source,GraphQL]
----
extend type Movie {
  recommended(limit: Int = 3): [Movie!]!
    @cypher(
      statement: """
      MATCH (this)<-[:RATED]-(u:User)-[:RATED]->(rec:Movie)
      WITH rec, COUNT(u) AS score ORDER BY score DESC
      RETURN rec LIMIT $limit
      """
    )
}
----

Select "Build schema" to update the GraphQL API to include our new `similar` field. Now we can include this field in our GraphQL selection set to find the most similar movies to Jurassic 

[source,GraphQL]
----
{
  movies(where: { title: "Jurassic Park" }) {
    title
    recommended {
      title
    }
  }
}
----

[source,JSON,role=nocopy]
----
{
  "data": {
    "movies": [
      {
        "title": "Jurassic Park",
        "recommended": [
          { "title": "G.I. Joe: Retaliation" },
          { "title": "Terminator Genisys" },
          { "title": "Mad Max: Fury Road" }
        ]
      }
    ]
  }
}
----

This is neat, but what if we wanted to return more than 3 recommended movies? Let's update our GraphQL type definitions to allow for specifying the number of recommended movies to return at query time. To do this we'll add an argument to the `recommended` field called `limit`. Any arguments defined on a `@cypher` directive field are passed to the Cypher query as a Cypher parameter with the same name as the argument and can be referenced using the `$` syntax.

So in order to return an arbitrary number of recommended movies we replace the hardcoded value 3 with `$limit` in our Cypher statement.

[source,GraphQL]
----
extend type Movie {
  recommended(limit: Int = 3): [Movie!]!
    @cypher(
      statement: """
      MATCH (this)<-[:RATED]-(u:User)-[:RATED]->(rec:Movie)
      WITH rec, COUNT(u) AS score ORDER BY score DESC
      RETURN rec LIMIT $limit
      """
    )
}
----
 
Note that we specify a default value for the `limit` argument (`limit: Int = 3`). This ensures that even if a value for the optional `limit` argument is not specified, our Cypher query will have a value and avoid an error. An alternative would be to make the `limit` argument required (`limit: Int!`).

Here we request 10 recommended movies instead of the default 3.

[source,GraphQL]
----
{
  movies(where: { title: "Jurassic Park" }) {
    title
    recommended(limit: 10) {
      title
    }
  }
}
----

And our query response now includes the number of recommended movies we've specified.

[source,GraphQL]
----
{
  "data": {
    "movies": [
      {
        "title": "Jurassic Park",
        "recommended": [
          { "title": "Forrest Gump" },
          { "title": "Silence of the Lambs, The" },
          { "title": "Pulp Fiction" },
          { "title": "Terminator 2: Judgment Day" },
          { "title": "Shawshank Redemption, The" },
          { "title": "Fugitive, The" },
          { "title": "Braveheart" },
          { "title": "Star Wars: Episode IV - A New Hope" },
          { "title": "Aladdin" },
          { "title": "True Lies" }
        ]
      }
    ]
  }
}
----

[.quiz]
== Check Your Understanding

include::questions/question-1.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson we learned how to use the `@cypher` GraphQL schema directive to add custom to our GraphQL API using the Cypher query language. We saw how this can be used for scalar fields as well as node object array fields.
