= Querying with Cypher
:usecase: recommendations
:caption: Continue your path with Cypher queries
:categories: cypher:1
:previous: cypher-fundamentals
:status: draft
:duration: ? hours
//:video:

== Course description

Build on from the knowledge gained in the link:/courses/cypher-fundamentals/[Cypher Fundamentals] course with more complex patterns and the more advanced features of Cypher.

In this course we will take a deeper look into more advanced uses of Cypher for querying.
This course uses the Recommendations dataset that contains Person, Movie, Genre, and User nodes.

=== Prerequisites

To take this course we recommend that you have taken these beginner courses in GraphAcademy:

. link:/courses/neo4j-fundamentals[Neo4j Fundamentals^]
. link:/courses/cypher-fundamentals[Cypher Fundamentals^]
. link:/courses/modeling-fundamentals[Graph Data Modeling Fundamentals^]

=== Duration

? hours

=== What you will learn

* Filtering queries
* Controlling results returned
* Working with Cypher data
* Graph traversal
* Pipelining queries
* Using projection
* Subqueries
* Using parameters
