= Additional Data
:order: 4
:type: challenge
:optional: true

In this optional challenge, you can explore how adding additional data to the GraphRAG retriever can improve the agent's responses to more complex questions.

The retrieval query you defined in the previous lesson returns data relating to actors and genres.

You can extend the retrieval query to include additional data, such as:

* Movie directors
* Revenue and budget information
* Spoken languages
* Release dates

You should:

. Explore the graph, and the data it contains
. Identify additional data that could be useful for the agent
. Update the `retrieval_query` to include this additional data
. Test the agent with specific questions that require this additional context

When you are ready to continue, you can move on to the next module.

read::Continue[]

In this optional challenge, you extended the retriever to include additional data, and tested the agent with more complex questions.

In the next module, you will learn how to use Text to Cypher to create retriever that can find context in the graph based on natural language queries.
