= Dates and times
:type: video 
:order: 3

[.slide.discrete.col-2]
== Temporal types

[.col]
====
The `neo4j.time` module provides temporal types for working with dates and times in Cypher. 
These types have nanosecond precision and are compatible with `pytz`.

Date and time types can either be serialized in Python or converted within a Cypher statement.

Python's built-in temporal types can be used as parameters.

The following table shows the mapping between Cypher and Python temporal types. 
====

[.col]
====
.Temporal Types
[cols="1,3,1,1"]
|===
| Neo4j Cypher Type | Python driver type | Python built-in type | `tzinfo`


| Date
| `neo4j.time.Date`
| `datetime.date`
|

| Time
| `neo4j.time.Time`
| `datetime.time`
| not `None`

| LocalTime
| `neo4j.time.Time`
| `datetime.time`
| `None`

| DateTime
| `neo4j.time.DateTime`
| `datetime.datetime`
| not `None`

| LocalDateTime
| `neo4j.time.DateTime`
| `datetime.datetime`
| `None`

| Duration
| `neo4j.time.Duration`
| `datetime.timedelta`
|

|===
====

// [.slide]
// .Working with Temporal types
// [source,python,role=ncopy,subs="attributes+",indent=0]
// ----
// include::{repository-raw}/main/example/results.py[tag=temporal]
// ----

// Each of the above types has a number of attributes for accessing the different, for example `year`, `month`, `day`, and in the case of the types that include a time, `hour`, `minute` and `second`.

// For more information, see link:https://neo4j.com/docs/api/python-driver/4.4/temporal_types.html[Temporal Data Types^&^].




[.slide.col-2]
== Date

[.col]
====

[source,python]
----
from neo4j.time import Date

driver.execute_query("""
CREATE (a:Person {
  born: $date,                   // <1>
  updatedOn: date($datestring),  // <2>
  createdOn: date(),             // <3>
})
""", date=Date(2018, 4, 30),     # <4>
    datestring="2025-01-01"
)
----
====

[.col]
====
You can create a date in Cypher using the `date()` function, or using the `Date` class in Python.

&nbsp;

<1> You can pass a `Date` object as a parameter.
<2> You can pass a date string in ISO format and cast the value as a date using Cypher's `date()` function.
<3> Calling the `date()` function in Cypher creates a date for the current date.
<4> The `Date` class accepts three arguments: year, month, and day.
====

[.slide.col-2]
== Time

[.col]
====

[source,python]
----
from neo4j.time import Time
from datetime import timezone, timedelta

# Create timezone UTC+2
tz = timezone(timedelta(hours=2))

driver.execute_query("""
CREATE (e:Event {
  startsAt: $time,                    // <1>
  createdAt: time($timestring),       // <2>
  updatedAt: time(),                  // <3>
})
""", time=Time(12, 30, 0, tzinfo=tz), # <4>
    timestring="12:30:00+02:00"
)
----
====


[.col]
====
The time type with timezone information stores a time value with nanosecond precision and timezone information.

&nbsp;

<1> You can pass a `Time` object with timezone information as a parameter
<2> You can pass a time string in ISO format with timezone offset
<3> Calling the `time()` function in Cypher creates a time for the current time in the local timezone
<4> The `Time` class accepts timezone information via the `tzinfo` parameter
====

[.slide.col-2]
== LocalTime

[.col]
====

[source,python]
----
from neo4j.time import Time

driver.execute_query("""
CREATE (s:Schedule {
  openTime: $time,        // <1>
  closeTime: localtime($timestring), // <2>
  breakTime: localtime()  // <3>
})
""", time=Time(9, 0, 0), # <4>
    timestring="17:00:00"
)
----
====

[.col]
====
A LocalTime represents a time _without timezone information_, useful for time-of-day values that don't need timezone context.

&nbsp;

<1> A `Time` object without timezone info represents a local time
<2> Use `localtime()` in Cypher to parse time strings as local time
<3> `localtime()` returns the current local time without timezone info
<4> Create a local time by omitting the `tzinfo` parameter
====

[.slide.col-2]
== DateTime

[.col]
====

[source,python]
----
from neo4j.time import DateTime
from datetime import timezone, timedelta

# Create timezone UTC+2
tz = timezone(timedelta(hours=2))

driver.execute_query("""
CREATE (e:Event {
  startsAt: $datetime,        // <1>
  createdAt: datetime($dtstring), // <2>
  updatedAt: datetime()  // <3>
})
""", datetime=DateTime(2024, 3, 15, 14, 30, 0, tzinfo=tz), # <4>
    dtstring="2024-03-15T14:30:00+02:00"
)
----
====

[.col]
====
DateTime combines date and time information with timezone support.

&nbsp;

<1> Pass a `DateTime` object with timezone as a parameter
<2> Parse an ISO format datetime string with timezone information
<3> Get current date and time in the local timezone
<4> Create a `DateTime` with year, month, day, hour, minute, second and timezone
====

[.slide.col-2]
== LocalDateTime

[.col]
====

[source,python]
----
from neo4j.time import DateTime

driver.execute_query("""
CREATE (e:Event {
  scheduledFor: $datetime,        // <1>
  createdAt: localdatetime($dtstring), // <2>
  updatedAt: localdatetime()  // <3>
})
""", datetime=DateTime(2024, 3, 15, 14, 30), # <4>
    dtstring="2024-03-15T14:30:00"
)
----
====

[.col]
====
LocalDateTime combines date and time _without timezone information_, useful for timestamps that don't need timezone context.

&nbsp;

<1> A `DateTime` without timezone represents a local datetime
<2> Use `localdatetime()` to parse datetime strings without timezone
<3> Get current local date and time without timezone information
<4> Create local datetime by omitting the `tzinfo` parameter
====


[.slide.col-2]
== Duration

[.col]
====

[source,python]
----
from neo4j.time import Duration

driver.execute_query("""
CREATE (t:Task {
    estimatedTime: $short_duration,     // <1>
    deadline: datetime() + duration('P2M5DT3H'),  // <2>
    timeSpent: duration($duration_string),  // <3>
    reminderInterval: duration({     // <4>
        days: 1,
        hours: 12
    })
})
""",
    short_duration=Duration(hours=2, minutes=30),  # <5>
    duration_string="P1Y2M"  # <6>
)
----
====

[.col]
====
Duration represents a period of time with components for months, days, seconds, and nanoseconds. It can be used to represent both fixed-length durations (like 5 hours) and variable-length durations (like 1 month).

&nbsp;

<1> Pass a Duration object as a parameter
<2> Add a duration to a datetime in Cypher using ISO 8601 format
<3> Parse a duration string in Cypher
<4> Create a duration using a Cypher map
<5> Create a Duration in Python specifying components
<6> ISO 8601 format: P[nY][nM][nD]T[nH][nM][nS]
====


[.slide.col-2]
== Working with Durations

[.col]
====

[source,python]
----
from neo4j.time import Duration, DateTime
from datetime import timedelta

# Add duration to datetime
now = DateTime.now()
future = now + Duration(months=1, days=5)  # <1>

# Add two durations
total_time = Duration(hours=2) + Duration(minutes=30)  # <2>

# Multiply duration
double_time = Duration(days=1) * 2  # <3>

# Convert to/from timedelta
duration = Duration(seconds=timedelta(hours=2).total_seconds())  # <4>
----
====

[.col]
====
Durations can be added to dates and times, and support arithmetic operations:

&nbsp;

<1> Add duration to datetime for date arithmetic
<2> Combine durations with addition
<3> Multiply duration by a number
<4> Convert between Duration and timedelta

