= Transaction functions
:type: challenge
:minutes: 10
:order: 2

You have built an application that streams the results of a long-running Cypher statement to the client.

You have written a transaction function called `get_cheapest_flights` to execute a **read** query within a transaction.

[%collapsible]
.View the `get_cheapest_flights` function
====
[source,python]
----
def get_cheapest_flights(tx, date, origin, destination):
    """
    Return the cheapest flights between the origin and 
    destination airports on a given date.
    """
    result = tx.run("""
        MATCH (origin:Airport)<-[:ORIGIN]-(f:Flight)-[:DESTINATION]->(destination:Airport),
            (f)-[:OPERATED_BY]->(operator:Airline)
        WHERE origin.name = $origin AND destination.name = $destination AND f.date = $date
        RETURN f.price AS price, operator.name AS operator
    """, date=date, origin=origin, destination=destination)
    return result.values()
----
====

The application then uses an external function called `send_to_ui` to send the results to the client.

include::./questions/1-run.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you demonstrated how to execute a read transaction using the `execute_read()` method.
The method handles transaction management automatically and allows for streaming results as they become available.

The `execute_read()` method is the recommended way to run read transactions as it:

* Automatically handles transaction management
* Enables streaming of results as they become available
* Ensures proper transaction lifecycle and resource cleanup

[TIP]
.Consuming results
====
Remember that the results must be consumed within the transaction function. 
Once the transaction is completed, the results are no longer available.
====

