= Spatial types 
:type: quiz
:order: 5


[.slide.discrete]
== Points and locations


[.col]
====
Cypher has built-in support for handling points in space.

Depending on the values used to create the point, it can either be a `CartesianPoint` or a `WGS84Point`.  If you specify three values, these are considered three dimensional points.  Otherwise, they are considered two dimensional points.

In Python, these values are represented by the `neo4j.spatial.CartesianPoint` and `neo4j.spatial.WGS84Point` classes, which are subclasses of the `neo4j.spatial.Point` class.

The underlying values are saved as `x`, `y`, `z`, and an `SRID` that corresponds to the coordinate system.

====

[.col]
====

|===
| Cypher Type | Python Type | SRID | 3D SRID

| Point (Cartesian) | `neo4j.spatial.CartesianPoint` | `7203` | `9157`

| Point (WGS-84) | `neo4j.spatial.WGS84Point` | `4326` | `4979`
|===
====

[.slide.col-2]
== CartesianPoint

[.col]
====
A Cartesian Point can be created in Cypher by supplying `x` and `y` values to the `point()` function.
The optional `z` value represents the height.

To create a Cartesian Point in Python, you can import the `neo4j.spatial.CartesianPoint` class.

====

[.col]
====
.Cartesian
[source,python]
----
# Using X and Y values
twoD=CartesianPoint((1.23, 4.56))
print(twoD.x, twoD.y, twoD.srid) # 1.23, 4.56, 7203

# Using X, Y and Z
threeD=CartesianPoint((1.23, 4.56, 7.89))
print(threeD.x, threeD.y, threeD.z, threeD.srid) # 1.23, 4.56, 7.89, 9157
----
====

[.slide.col-2]
== WGS84Point

[.col]
====
A WGS84 Point can be created in Cypher by supplying `latitude` and `longitude` values to the `point()` function.
To create a Cartesian Point in Python, you can import the `neo4j.spatial.WGS84Point` class.

====

[.col]
====
.WGS84
[source,python]
----
london=WGS84Point((-0.118092, 51.509865))
print(london.longitude, london.latitude, london.srid) # -0.118092, 51.509865, 4326

the_shard=WGS84Point((-0.086500, 51.504501, 310))
print(the_shard.longitude, the_shard.latitude, the_shard.height, the_shard.srid) # -0.0865, 51.504501, 310, 4979
----
====


[.slide.col-2]
== Distance

[.col]
====
The `point.distance` function can be used to calculate the distance between two points with the same SRID.
The result is a `float` representing the distance in a straight line between the two points.

If the SRID values are different, the function will return `None`.

====

[.col]
====
[source,python]
----
from neo4j.spatial import CartesianPoint

# Create two points
point1 = CartesianPoint((1, 1))
point2 = CartesianPoint((10, 10))

# Query the distance using Cypher
result = driver.execute_query("""
    RETURN point.distance($p1, $p2) AS distance
""", p1=point1, p2=point2)

# Print the distance from the result
distance = result.records[0]["distance"]
print(distance)  # 12.727922061357855
----


====

[.summary]
== Lesson Summary

In this lesson, you learned about the `CartesianPoint` and `WGS84Point` classes and how to use them in Python.

For more information on Spatial types, link:https://neo4j.com/docs/cypher-manual/current/values-and-types/spatial/[view the Spatial types page in Cypher Manual^].

[.transcript-only]
====
Now it's your turn to practice.
====

