== Resources

* *There are many resources available to you for learning more about Neo4j* +
https://neo4j.com/developer/resources/

* *Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users:* +
https://community.neo4j.com

* *Neo4j documentation:* +
https://neo4j.com/docs/


* *Neo4j Sandboxes for experimenting with graphs:* +
https://sandbox.neo4j.com/?ref=graph-academy

* *Videos on  the Neo4j YouTube channel:* +
https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

// * *Neo4j online and classroom training:* +
// https://graphacademy.neo4j.com/


* *Become a Neo4j certified developer:* +
https://graphacademy.neo4j.com/categories/certification/


* *GitHub repository:* +
https://github.com/neo4j-contrib

* *Neo4j events all over the world:* +
https://neo4j.com/events/world/all/

* *Graph Gists for learning more use cases for Neo4j:* +
https://neo4j.com/graphgists/

* *Attend a Neo4j meetup:* +
https://www.meetup.com/topics/neo4j/

* *View questions/answers raised about Neo4j:* +
https://stackoverflow.com/tags/neo4j/hot


== Course feedback

Any feedback that you could provide us on this course would be greatly appreciated.
If you have any feedback for us, please https://forms.gle/k6nhzMXiYFyUYUNs7[complete this form].
We actively monitor feedback and use it to improve our course catalogue.
