:type: freetext

[.question.freetext]
= How many people directed the movie _Cloud Atlas_?

Use the Neo4j Browser window to the right of the screen to modify the query to find the number of `(:Person)` nodes who have a `[:DIRECTED]` relationship to the Cloud Atlas `(:Movie)` node.

Enter the **number** of directors for _Cloud Atlas_ in the box below, then click the **Check Answer** button below to continue.

input::answer[]

* [x] 3

// Once you have entered the answer, click the **Check Answer** button below to continue.

[TIP,role=hint]
.Hint
====
You are looking for the number of `[:DIRECTED]` relationships between person nodes and the _Cloud Atlas_ movie node.
You can find the result by returning the number of nodes and counting the rows, or use the `count()` aggregate function to find the answer.
====

[TIP,role=solution]
.Solution
====
You can use the following query to find the number of people who directed _Cloud Atlas_:

[source,cypher]
----
include::../solution.cypher[]
----

Click the **Run in Sandbox** button to reveal the answer in the Sandbox window.
====