[.question]
= Who directed the movie _Cloud Atlas_?

Complete the Cypher query to find who directed the movie _Cloud Atlas_.

Replace the `?????` with the correct Cypher to: 

. `MATCH` using the [copy]#DIRECTED# relationship between `(:Person)` and `(:Movie)` nodes.
. `RETURN` the [copy]#name# property of the `(:Person)` nodes.

Select all the directors that apply:

* [x] Tom Tykwer
* [ ] Robert Zemeckis
* [x] Lana Wachowski
* [x] Lilly Wachowski

[TIP,role=hint]
.Hint
====
There is more than one director for the movie _Cloud Atlas_. Select all that apply.

You need to find the `Person` nodes that have a `[:DIRECTED]` relationship to the _Cloud Atlas_ `Movie` node.

You can find the director names using the `name` property of the `Person` node.
====

[TIP,role=solution]
.Solution
====
You can use the following query to find who directed _Cloud Atlas_:

[source,cypher]
----
include::../solution.cypher[]
----

The directors of _Cloud Atlas_ are:

* Tom Tykwer
* Lana Wachowski
* Lilly Wachowski
====