= Cypher Generation Chain
:type: challenge
:prompt-filename: cypher-generation-with-instructions.txt
:lab-filename: cypher-generation.chain.ts
:lab-file: modules/agent/tools/cypher/{lab-filename}
:lab: {repository-blob}/main/src/{lab-file}
:lab-solution: src/solutions/{lab-file}
:test-filename: cypher-generation.chain.test.ts
:test-file: src/modules/agent/tools/cypher/{test-filename}


The first step in retrieving data from a Neo4j database is to generate a Cypher statement.

To complete this challenge, you must modify the `initCypherGenerationChain()` function in link:{repository-blob}/main/{lab-file}[`{lab-file}`^] to return a chain that:

1. Accepts the rephrased question as a `string`
2. Format a prompt that instructs the LLM to use the schema provided to generate a Cypher statement to retrieve the data that answers the question
3. Pass the formatted prompt to an LLM
4. Parse the output as a string

lab::Open `{lab-filename}`[]


== Prompt Template

In the `initCypherGenerationChain()` function, use the `PromptTemplate.fromTemplate()` method to create a new prompt template with the following prompt.

.Prompt
[source]
----
include::{repository-raw}/{branch}/prompts/{prompt-filename}[]
----

Remember to use backslashes (`\`) to escape the back-ticks if you are using template strings.

[TIP]
.Specific Instructions
====
This prompt includes specific instructions that the LLM should follow when writing the Cypher statement.

This is a technique used as in-context learning, a quick method used by an LLM to adapt its responses to new tasks or questions without needing prior training on specific tasks.

You can learn more in the link:https://graphacademy.neo4j.com/courses/llm-fundamentals/4-cypher-generation/5-specific-instructions/[Providing Specific Instructions lesson in Neo4j & LLM Fundamentals^].

====

Your code should resemble the following:

.Prompt Template
[source,typescript,indent=0]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=prompt, indent=0]
----

[TIP]
.Returning Element IDs
====
You may have noticed the instruction to use the `elementId()` function to return the Element ID of any nodes returned.

As with link:../../4-vector-retrieval/2-retrieval-chain/[the metadata object in the Retrieval Chain^], this will be used to store the nodes used to generate the context.


====

== Return a Runnable Sequence

Use the `RunnableSequence.from()` method to create a new chain.
The chain should pass the prompt to the LLM passed as a parameter, then format the response as a string using a new instance of the `StringOutputParser`.

[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=startsequence, indent=0]
  // ...
include::{repository-raw}/{branch}/{lab-solution}[tag=endsequence, indent=0]
----

=== Initial Inputs

Inside the array, add an object that sets the `question` and `schema` for the chain.

To assign the original input string to the `question` key, create a new `RunnablePassthrough` instance.
Use the `graph.getSchema()` to assign a copy of the database schema to the `schema` key.

[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=assign, indent=0]
----

=== Format Prompt and Process

Now that the inputs required for the prompt have been prepared, these can be formatted in the prompt, passed to the LLM and the output parsed as a string.


[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tags="startsequence,assign,rest,endsequence", indent=0]
----

=== Finished Sequence

If you have followed the steps correctly, your code should resemble the following:

[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=function, indent=0]
----

include::../../../../includes/test.adoc[leveloffset=+1]


== It works!

If all the tests have passed, you will now have a chain capable of generating Cypher statements based on a question using the database schema.

Once you have finished, hit the button below to mark the challenge as complete.

read::It works![]


[.summary]
== Summary

In this lesson, you built a chain that generates a Cypher statement based on user input.

In the next lesson, you will learn how an LLM can be used to evaluate the statement.
