= Labels
:order: 4
:type: lesson

In this lesson, you will learn how to add additional labels to existing nodes. Adding labels to existing nodes can make your graph more useful and performant.

The `Person` nodes in the graph represent both actors and directors. To determine if a person is an actor or director, you need to query the `ACTED_IN` or `DIRECTED` relationships. Instead, you can add labels to the existing nodes to distinguish between actors and directors.

== Add Labels to Existing Nodes

You can add labels to a node using `SET`, the syntax is:

[source, cypher, role=nocopy noplay]
----
MATCH (n)
SET n:Label
----

To add the `Actor` label to all `Person` nodes that have acted in a movie, run the following query:

[source, cypher]
----
MATCH (p:Person)-[:ACTED_IN]->()
SET p:Actor
----

This query will match all `Person` nodes that have an `ACTED_IN` relationship to a movie, and add the `Actor` label to those nodes.

As there are people in the database who have acted in more than 1 movie, you can use `WITH DISTINCT` to ensure that each person is only labeled once. Although not essential, this will improve the performance of your import query.

[source, cypher]
----
MATCH (p:Person)-[:ACTED_IN]->()
WITH DISTINCT p SET p:Actor
----

You can now use the `Actor` label to find actors in the graph:

[source, cypher]
----
MATCH (a:Actor) RETURN a LIMIT 25
----

== Add Director label

Your task is to create a query that adds the `Director` label to all `Person` nodes with a `DIRECTED` relationship to a `Movie` node.

[.quiz]
== Check Your Understanding

include::questions/verify.adoc[leveloffset=+1]

verify::[]

[.summary]
== Summary

In this lesson, you learned how to add labels to existing nodes and updated the import process to do so.

Next, you will check your knowledge by taking a short quiz.