= Splitting text into chunks
:type: lesson
:order: 2
:optional: true
:branch: main

You can modify how the `SimpleKGBuilder` splits text into chunks.
Your strategy for splitting text will impact the construction and how you search the knowledge graph.

In this lesson you will learn how to create a custom text splitter or integrate with an existing link:https://python.langchain.com/docs/concepts/text_splitters/[LangChain text splitter^].

== Custom Text Splitter

A custom text splitter allows you to define how the text is divided into chunks.

The PDF documents you have been using in this course contain sections, for example `= Heading` and `== Subheading`, that can be used to logically split the text into meaningful chunks.

[source,text]
.Sectioned document
----
= What is Generative AI

== GenAI

Generative AI (or GenAI) refers to artificial intelligence systems ...

== Large Language Models (LLMs)

LLMs are a type of generative AI model designed to understand and generate human-like text ...
----

You can create a custom text splitter by extending the link:https://neo4j.com/docs/neo4j-graphrag-python/current/api.html#textsplitter[`TextSplitter`^] class:

[source,python]
----
include::{repository-raw}/{branch}/genai-graphrag-python/examples/text_splitter_section.py[tag=import_splitter]

include::{repository-raw}/{branch}/genai-graphrag-python/examples/text_splitter_section.py[tag=splitter]
----

The `SectionSplitter` class splits the text based on a section heading (`== `), then creates `TextChunk` objects for each section, and finally returns a `TextChunks` object containing all the chunks.

You can run the text splitter directly with test data to verify that it is working:

[source,python]
----
include::{repository-raw}/{branch}/genai-graphrag-python/examples/text_splitter_section.py[tag=run_splitter]
----

Your text splitter can then be used in the `SimpleKGPipeline` to split text into chunks by setting the `text_splitter` parameter:

[source,python]
----
include::{repository-raw}/{branch}/genai-graphrag-python/examples/text_splitter_section.py[tag=kg_builder]
----

[%collapsible]
.Reveal the complete code
====
This example code shows how to create and use the `SectionSplitter` in a `SimpleKGPipeline`:
[source, python]
----
include::{repository-raw}/{branch}/genai-graphrag-python/examples/data_loader_text_file.py[tag=**,!run_loader]
----
====

== Integrate with LangChain Text Splitters

LangChain provides a variety of link:https://python.langchain.com/docs/concepts/text_splitters/[text splitters^] that you can use to implement different chunking strategies.

The `neo4j_graphrag` package includes a `LangChainTextSplitterAdapter` class that allows you to integrate LangChain text splitters with the `SimpleKGBuilder`.

You can use the https://python.langchain.com/api_reference/text_splitters/character/langchain_text_splitters.character.CharacterTextSplitter.html[LangChain `CharacterTextSplitter`^] to split text into paragraphs.

[source,python]
----
include::{repository-raw}/{branch}/genai-graphrag-python/examples/text_splitter_langchain.py[tag=import_splitter]

include::{repository-raw}/{branch}/genai-graphrag-python/examples/text_splitter_langchain.py[tag=splitter]
----

The `LangChainTextSplitterAdapter` wraps the LangChain `CharacterTextSplitter` to create text chunks.

The LangChain text splitter can then be used in the `SimpleKGPipeline` to split text into chunks by setting the `text_splitter` parameter:

[source,python]
----
include::{repository-raw}/{branch}/genai-graphrag-python/examples/text_splitter_langchain.py[tag=kg_builder]
----

[%collapsible]
.Reveal the complete code
====
This example code shows how to create and use the `LangChainTextSplitterAdapter` in a `SimpleKGPipeline`:
[source, python]
----
include::{repository-raw}/{branch}/genai-graphrag-python/examples/text_splitter_langchain.py[tag=**]
----
====

When you're ready you can continue.

read::Continue[]

[.summary]
== Lesson Summary

In this lesson, you learned how to create custom text splitters and integrate with LangChain text splitters.

In the next lesson, you will learn how to configure the lexical (unstructured) graph data model.
