= What is Graph Data Modeling?
:type: quiz
:order: 1

[.video]
video::xxxx[youtube,width=560,height=315]


[.transcript]
== Why model?

If you will use a Neo4j graph to support part or all of your application, you must collaboratively work with your stakeholders to design a graph that will:

* Answer the key use cases for the application.
* Provide the best Cypher query performance for the key use cases.

=== Components of a graph data model

The Neo4j components that are used to define the graph data model are:

* Nodes
* Labels
* Relationships
* Properties

=== Data modeling process

Here are the steps to create a graph data model:

. Understand the domain and define specific use cases (questions) for the application.
. Develop the initial data model:
.. Model the nodes (entities).
.. Model the relationships between nodes.
. Test the use cases against the initial data model.
. Create the graph with test data (Cypher).
. Test scalability and performance against the graph with the use cases.
. Refactor (improve) the graph due to a change in the key use cases or for performance reasons.
. Implement the refactoring and retest (Cypher)

Graph data modeling is an iterative process.
Your initial graph data model is a starting point, but as you learn more about the use cases or if the use cases change, the initial graph data model will need to change.
In addition, you may find that especially when the graph scales, you will need to modify the graph (*refactor*) to achieve the best performance for your key use cases.

Refactoring is *very common* in the development process.
A Neo4j graph has an optional schema which is quite flexible, unlike the schema in an RDBMS.
A Cypher developer can easily modify the graph to represent an improved data model.

== Check your understanding


include::questions/1-graph-elements.adoc[]

include::questions/2-refactor.adoc[]


[.summary]
== Summary

In this lesson, you learned about the steps for graph data modeling.
In the next lesson, you will learn about understanding the domain for a graph data model.
