= What is Graph Data Modeling?
:type: quiz
:order: 1

[.video]
video::xxxx[youtube,width=560,height=315]


[.transcript]
== Why model?

If you will use a Neo4j graph to support part or all of your application, you must collaboratively work with your stakeholders to design a graph will:

* Answer the key use cases for the application.
* Provide the best query performance for the key use cases.

=== Data modeling process

To model a graph, you must understand the key elements of a Neo4j graph that you learned about in the _Neo4j Fundamentals_ course.
You will apply the node, label, relationship types and direction, and property elements of a graph to come up with a data model.

There are many steps to create a graph data model:

. Understand the domain and define specific questions for the application.
. Develop initial data model:
.. Identify nodes (entities).
.. Identify relationships between nodes.
. Test the questions against the model.
. Create the graph with test data (Cypher).
. Test scalability and performance.
. Refactor (improve) the graph due to a change in the key questions or for performance reasons.
. Implement the refactoring and retest. (Cypher)

Testing the questions and testing scalability is where you typically work with Cypher developers who will create the graph per the initial design and populate it with sample data.

Refactoring is *very common* in the development process. Since a Neo4j graph does not have a schema,  a Cypher developer easily modify the graph to represent an improved data model.

== Check your understanding


include::questions/1-graph-elements.adoc[]

include::questions/2-refactor.adoc[]


[.summary]
== Summary

In this lesson, you learned about the steps for graph data modeling.
In the next lesson, you will learn about understanding the domain for a graph data model.
