version: '3.7'

networks:
  graphacademy:
    driver: bridge

services:
  neo4j:
    image: neo4j:enterprise
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./.neo4j/data:/data"
      - "./.neo4j/logs:/logs"
    environment:
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_dbms_security_auth__minimum__password__length=1
    networks:
      - graphacademy
    healthcheck:
      test: [ "CMD", "neo4j", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
