#!/bin/sh


if test "$1" = 'course'; then
    echo "Creating course $2 with {title: $3}"

    if test -f "./asciidoc/courses/$2/course.adoc"; then
        echo "⛔️ Course $2 already exists"
    else
        mkdir -p ./asciidoc/courses/$2
        echo "= $3" > ./asciidoc/courses/$2/course.adoc
        echo ":categories: $4" >> ./asciidoc/courses/$2/course.adoc

        if command -v "code"; then
            code ./asciidoc/courses/$2/course.adoc
        fi
    fi

elif test "$1" = 'module'; then
    echo "Creating module in $2 with {slug: $3, title: $4,  order $5}"

    if test -f "./asciidoc/courses/$2/modules/$3/module.adoc"; then
        echo "⛔️ Module $3 in $2 already exists"
    else
        mkdir -p ./asciidoc/courses/$2/modules/$3
        echo "= $4" > ./asciidoc/courses/$2/modules/$3/module.adoc
        echo ":order: $5" >> ./asciidoc/courses/$2/modules/$3/module.adoc

        if command -v "code"; then
            code ./asciidoc/courses/$2/modules/$3/module.adoc
        fi
    fi

elif test "$1" = 'lesson'; then
    echo "Creating lesson in $2/$3 with {slug: $4, title: $5, order: $6}"

    if test -f "./asciidoc/courses/$2/modules/$3/lessons/$4/lesson.adoc"; then
        echo "⛔️ Lesson $4 in $2/$3 already exists"
    else
        mkdir -p ./asciidoc/courses/$2/modules/$3/lessons/$4
        echo "= $5" > ./asciidoc/courses/$2/modules/$3/lessons/$4/lesson.adoc
        echo ":order: $6" >> ./asciidoc/courses/$2/modules/$3/lessons/$4/lesson.adoc

        if command -v "code"; then
            code ./asciidoc/courses/$2/modules/$3/module.adoc
        fi

    fi

elif test "$1" = 'question'; then
    echo "Creating question in $2/$3/$4 with {slug: $5, title: $6}"

    if test -f "./asciidoc/courses/$2/modules/$3/lessons/$4/questions/$5.adoc"; then
        echo "⛔️ Question $5 in $2/$3/$4 already exists"
    else
        mkdir -p ./asciidoc/courses/$2/modules/$3/lessons/$4/questions

        echo "[.question]" > ./asciidoc/courses/$2/modules/$3/lessons/$4/questions/$5.adoc
        echo "== $6" >> ./asciidoc/courses/$2/modules/$3/lessons/$4/questions/$5.adoc
        echo "include::questions/$5.adoc[]" >> ./asciidoc/courses/$2/modules/$3/lessons/$4/lesson.adoc

        if command -v "code"; then
            code ./asciidoc/courses/$2/modules/$3/lessons/$4/lesson.adoc
            code ./asciidoc/courses/$2/modules/$3/lessons/$4/questions/$5.adoc
        fi
    fi

else
    echo "Usage:"
    echo "\tgraphacademy course [slug] [title] [categories]"
    echo "\tgraphacademy module [course-slug] [module-slug] [title] [order]"
    echo "\tgraphacademy lesson [course-slug] [module-slug] [lesson-slug] [title] [order]"
    echo "\tgraphacademy question [course-slug] [module-slug] [lesson-slug] [question-slug] [title] [order]"
fi