apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: graphacademy-next
build:
  artifacts:
  - image: 715633473519.dkr.ecr.us-east-1.amazonaws.com/graphacademy
    docker:
      dockerfile: Dockerfile
      buildArgs:
        GITHUB_OAUTH_TOKEN: '{{ .GITHUB_OAUTH_TOKEN }}'
deploy:
  kustomize:
    paths:
    - k8s/base
profiles:
- name: development
  deploy:
    kustomize:
      paths:
      - k8s/development
- name: production
  deploy:
    kustomize:
      paths:
      - k8s/production
portForward:
  - resourceType: service
    resourceName: graphacademy
    port: 3000 
    localPort: 3000 # *Optional*
