#! /bin/sh
AUTH="Authorization: token $GITHUB_OAUTH_TOKEN"
#RELEASE=$(curl -H "$AUTH" -q https://api.github.com/repos/neo4j-graphacademy/courses/tags | jq 'sort_by( .name | ltrimstr("v") | split(".") | map(tonumber) ) | reverse |.[0].zipball_url' | tr -d '"')

curl -H "$AUTH" https://api.github.com/repos/neo4j-graphacademy/courses/tags > tags.json
cat tags.json
jq 'sort_by( .name | ltrimstr("v") | split(".") | map(tonumber) ) | reverse | .[0].zipball_url' tags.json

echo "Downloading $RELEASE"

wget -O /tmp/content.zip --header "$AUTH" $RELEASE
unzip -d /tmp/content /tmp/content.zip

if [[ $? -gt 0 ]]; then 
   echo "Unzipping content failed, either because of bad file or failure to download zip"
   exit 1
fi

cp -r /tmp/content/*/asciidoc/ /app/
ls /app/asciidoc/courses

node --max-http-header-size=24000 /app/dist/main.jsyes
