#! /bin/sh

echo "Saving credentials..."
echo $GOOGLE_APPLICATION_CREDENTIALS_CONTENT >> $GOOGLE_APPLICATION_CREDENTIALS

COURSE_RELEASE=$(curl -q https://api.github.com/repos/neo4j-graphacademy/courses/tags | jq 'sort_by( .name | ltrimstr("v") | split(".") | map(tonumber) ) | reverse |.[0].zipball_url' | tr -d '"')

echo "Downloading $COURSE_RELEASE"
wget -q -O /tmp/courses.zip $COURSE_RELEASE
unzip -q -d /tmp/courses /tmp/courses.zip

if [[ $? -gt 0 ]]; then
   echo "Unzipping course content failed, either because of bad file or failure to download zip"
   exit 1
fi

cp -rf /tmp/courses/*/asciidoc/ /app/ 2>/dev/null


CERTIFICATION_RELEASE=$(curl -q https://api.github.com/repos/neo4j-graphacademy/certifications/tags | jq 'sort_by( .name | ltrimstr("v") | split(".") | map(tonumber) ) | reverse |.[0].zipball_url' | tr -d '"')

echo "Downloading $CERTIFICATION_RELEASE"
wget -q -O /tmp/certifications.zip $CERTIFICATION_RELEASE
unzip -q -d /tmp/certifications /tmp/certifications.zip

if [[ $? -gt 0 ]]; then
   echo "Unzipping certifications content failed, either because of bad file or failure to download zip"
   exit 1
fi

cp -rf /tmp/certifications/*/asciidoc/certifications/ /app/asciidoc/certifications/ 2>/dev/null

npm run $1