#! /bin/sh
cd /
RELEASE=$(curl -q https://api.github.com/repos/neo4j-graphacademy/courses/tags | jq '.[0].zipball_url' | tr -d '"')
wget -O /tmp/content.zip $RELEASE
unzip -d /tmp/content /tmp/content.zip 
cp -r /tmp/content/*/asciidoc/ /app/
