= Put the "D" in CRUD - Delete
:order: 2
:type: lesson

While we can use a DTO projections similarly to interface-based projections with a subset of existing domain class properties, DTO-based projections really shine when we want to add additional properties to our projection.

What if we want to calculate cast size and add it to our display data as a fun fact for users to know? Let's create a DTO projection that contains the `title`, `released`, `poster`, and `castSize` properties to find out!

== MovieDTO class

First, we need to create a DTO class that contains the properties we want to include in our projection. We will call this class `MovieDTOProjection`.

[source,java]
----
include::code/MovieDTOProjection.java[]
----

Now let's update our `MovieRepository` and `MovieController` by adding a new method to return a list of `MovieDTOProjection`.

[source,java]
----
include::code/MovieRepository.java[]
include::code/MovieController.java[]
----

In this repository method, we are using a custom query to calculate the `castSize` so that it maps to the property name in our DTO class.

Now, when we test the application and call the `/movies/dtocast` endpoint, we will get the four properties we specified in our projection, including the calculated `castSize` property.

[source,shell]
----
curl localhost:8080/movies/movielist
----

Note: nearly all of the cast sizes have a value of `4`. This is likely because the data was only imported with a maximum of four actors per movie. If we wanted to get a more accurate cast size, we would need to update our data import to include all actors for each movie.

== Further reading

More information on projections and additional capabilities can be found in the documentation for https://docs.spring.io/spring-data/neo4j/reference/projections/sdn-projections.html[Spring Data Neo4j Projections^].

[.summary]
== Summary

In this lesson, you learned about and created two different kinds of projections - interface-based and DTO-based.

Next, you will learn about some tips and tricks to working with Spring Data Neo4j.