= Using the driver
:type: lesson
:slides: true
:order: 3
:minutes: 10

[.slide.discrete]
== Introduction
In the link:/courses/cypher-fundamentals/[Cypher Fundamentals^] course, you learned how to query Neo4j using Cypher.

To run Cypher statements in a Java application, you'll need the link:https://neo4j.com/developer/Java[Neo4j Java Driver^].
The driver acts as a bridge between your Java code and Neo4j, handling connections to the database and the execution of Cypher queries.

[.slide]
== Creating a Driver Instance

Open the `src/main/java/neoflix/NeoflixApp.java` file.

Import the driver: 

[source,java]
----
import org.neo4j.driver.GraphDatabase;
import org.neo4j.driver.AuthTokens;
----

[.slide.discrete.col-2]
== Creating a Driver Instance

[.col]
====
Create a `driver` instance in `main()`:

[source,Java]
----
public class App {
    public static void main(String[] args) {
        AppUtils.loadProperties();

        // Create a new Neo4j driver instance
        var driver = GraphDatabase.driver(
                System.getProperty("NEO4J_URI"), // <1>
                AuthTokens.basic(
                    System.getProperty("NEO4J_USERNAME"), // <2>
                    System.getProperty("NEO4J_PASSWORD")) 
            );
        // Verify connectivity
        driver.verifyConnectivity(); // <3>
    }
}
----
====

[.col]
====
<1> The connection string for your Neo4j database
<2> Your Neo4j username and password
<3> Verify the connection (exception raised if connection fails)


[TIP]
.Best Practice
=====
Create **one** Driver instance and share it across your entire application.
=====
====

[.slide.col-2]
== Running Your First Query

[.col]
====
The `executableQuery()` method executes a Cypher query and returns the results.

[source,Java]
----
// <1>
var result = driver.executableQuery( 
    "RETURN COUNT {()} AS count"
    ).execute();

// Get the first record
var records = result.records(); // <2>
var first = records.get(0);

// Print the count entry
System.out.println(first.get("count"));   // <3>
----
====

[.col]
====
<1> `executableQuery()` runs a Cypher query to get the count of all nodes in the database
<2> `records()` returns a list of the records returned
<3> Keys from the `RETURN` clause are accessed using the `get` method
====

[.slide.discrete]
== Run the application

You can run the application to see the output:

[source, bash]
----
mvn compile exec:java
----

[TIP]
You can also run the application using the _play_ button in your IDE.


[.next.discrete]
== Check your understanding

link:../2c-create-driver-instance/[Take challenge,role=btn]

[.summary]
== Lesson Summary

In this lesson you learned how to install the Neo4j Java Driver, create a Driver instance, verify connectivity to your database, and execute your first Cypher statement.

In the next lesson, you will take a quiz to test your knowledge of installing and creating a driver instance.