= GraphQL Queries
:order: 1
// :sandbox: https://graphql-toolbox.neo4j.io/?connectURL=neo4j%2Bs://neo4j:felt-airport-manuals@d8086e75a731979f82f10f93e02eadd2.neo4jsandbox.com:7687
:disable-cache: true

The Neo4j GraphQL Library is a GraphQL to Cypher query execution layer for Neo4j and JavaScript GraphQL implementations.


In the previous section we said the four main goals of the Neo4j GraphQL Library are to:

1. Support GraphQL First Development
2. Auto Generate GraphQL API Operations
3. Generate Cypher From GraphQL Operations
4. Extend GraphQL With Cypher


== GraphQL First Development

// link:./1-setup/[Setup the Repository →, role=btn]

To start off be sure to use the default GraphQL type definitions that are defining a simple `Movie` type with only one property `title`. 

> Replace the contents of the type definition editor with the following snippet:

[source,GraphQL]
----
type Movie {
  title: String
}
----

Our database contains other data, but for now we'll start with just this simple type definition. The Neo4j GraphQL Library uses the convention of mapping GraphQL types to Neo4j node labels in the property graph model.

The single movie type defined above maps to a Neo4j property graph model with a single node label `Movie` and a single node property `title`.

// TODO: add arrows image of data model

If we click on the "Build Schema" button we can see the following operations are generated for us:


* `Query.movies`
* `Query.moviesAggregate`
* `Query.moviesConnection`

Similarly, the following mutation operations are generated as part of the GraphQL API:

* `Mutation.createMovies`
* `Mutation.deleteMovies`
* `Mutation.updateMovies`

That's quite a few operations available for just one single type! Let's ignore the other generated operations and focus on `Query.movies` for now.

[source,GraphQL]
----

----


== The Generated GraphQL API

== Queries

== Filtering




