Congratulations on completing this course!

In this course, you have modified an existing project to query the https://sandbox.neo4j.com/?usecase=recommendations[Recommendations dataset^].

In the first module, **Project Setup** you configured the project and stored the Neo4j Sandbox credentials within the project's environment variables for use at a later stage.

In the second module, **The {driver}**, you learned all about the  Neo4j Driver and how it should be used within an application.
This included installing the `{dependency}` dependency, building a connection string, creating a Driver instance using the `{method}` method and verifying that the credentials used to create the driver instance were correct.

In the third module, **Interacting with Neo4j**, you learned how to open new database sessions, execute read and write transactions and how to consume the results.
You also learned how to handle potential errors thrown by the driver, and gained hands on experience by implementing these skills within the project.

In the final module, **Project Backlog**, you honed your skills by modifying the remaining service classes to retrieve.

You should now have a fully working application that you can share with your friends or colleagues, and all of the knowledge required to build one of your own.


== Continue Learning

Now that you have completed the course, we have terminated your Sandbox instance.
If you would like to continue learning, you can either link:https://samdbox.neo4j.com/?usecase=recommendations[create a new Neo4j Sandbox instance^] or link:https://github.com/neo4j-graph-examples/recommendations/data[download the Recommendations dataset^] and follow the instructions in the link:../0-setup/2-sandbox/[Your Neo4j Sandbox^] to update the credentials used by the driver.

You can find instructions on how to
link:https://neo4j.com/docs/operations-manual/current/backup-restore/restore-dump/[import a Neo4j dump using the `neo4j-admin load` command^] in the link:https://neo4j.com/docs/operations-manual/current/[Neo4j Operations Manual^].


include::../../resources.adoc[]

We wish you good luck on your journey with Neo4j!
