= Creating Existence Constraints on Relationship Properties
:type: quiz
:sandbox: true

//[.video]
//video::Po4k7vXGBIE[youtube,width=560,height=315]

//https://youtu.be/Po4k7vXGBIE

[.transcript]

== Existence constraints for relationship properties

You may want to ensure that some relationship types **always** have a particular property.
For example, a REVIEWED relationship **must** have a property, rating.

[NOTE]
--
Existence constraints are only available in Enterprise Edition.
---

== Syntax for creating an existence constraint for a relationship

Here is the syntax for creating an existence constraint on a relationship property:

[source,cypher,rel="norun nocopy"]
----
CREATE CONSTRAINT <constraint_name>
IF NOT EXISTS FOR ()-[x:<RELATIONSHIP_TYPE>]-()
REQUIRE x.<property_key> IS NOT NULL
----

You specify the name of the constraint, the relationship type it will be associated with, and the name of the property that must exist for relationships of that type.

* If a constraint already exists in the graph with the same name, no constraint is created.
* If a constraint does not exist in the graph with the same name:
** No constraint is created if there already is an existence constraint for that relationship type and property key.
** Otherwise, the constraint is created.

=== Creating the existence constraint

Suppose we want to enforce that all _RATED_ relationships must have a value for the **rating** property.
Execute this code to create an existence constraint for this property:

[source,cypher]
----
CREATE CONSTRAINT RATED_rating_exists
IF NOT EXISTS FOR ()-[x:RATED]-()
REQUIRE x.rating IS NOT NULL
----

This code creates the existence constraint named RATED_rating_exists.

[NOTE]
You typically create constraints before the data is loaded into the graph, but in our case, we already have the data in the graph.

=== Constraint creation failure

Not all people in the graph have a ACTED_IN relationship with a role property set.
The creation of this constraint should fail:

[source,cypher]
----
CREATE CONSTRAINT ACTED_IN_role_exists
IF NOT EXISTS FOR ()-[x:ACTED_IN]-()
REQUIRE x.role IS NOT NULL
----

=== Property update failure

Suppose we have created the RATED_rating_exists constraint in the graph.

If we attempt to remove all rated properties from existing relationships, an error will occur:

[source,cypher]
----
MATCH ()-[x:RATED]->()
SET x.rating = null
----


include::questions/1-complete-query.adoc[leveloffset=+1]
include::questions/2-select-answer.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you learned how to create an existence constraint for a relationship type property.
In the next challenge, you will create another existence constraints.
