= Constraints and Indexes in Neo4j
:type: quiz
:sandbox: true

//[.video]
//video::Po4k7vXGBIE[youtube,width=560,height=315]

//https://youtu.be/Po4k7vXGBIE

[.transcript]
== Constraints in Neo4j

A constraint is implemented internally as an index.
It is used to constrain what is added to the graph.

For example, in the Movie graph, we must uniquely identify every Person node.
To do this, you identify a property whose value will be unique for all Person nodes.

Execute this query that returns all Person nodes for a person named _Austin Green_:

[source,cypher]
----
MATCH (p:Person)
WHERE p.name = 'Austin Green'
RETURN p
----

This query returns two Person nodes for two different people.
Their names are the same, but their tmdbId values are different.
In our Movie graph, we will assume that the tmdbId value for every Person node is unique.

[NOTE]
If you took the GraphAcademy course  link:/courses/importing-data/[Importing CSV Data into Neo4j^], you have already used uniqueness constraints to load the data.

=== Uniqueness constraint

If we define a uniqueness constraint on the node property, an error is raised if we attempt to create another node with the same property value or if we set the value of an existing node property that already exists in the graph.

[IMPORTANT]
A graph data modeling best practice is to always uniquely identify a node with a given label in the graph where a node will typically represent your business entities in your application.

=== Existence constraint

An existence constraint for a node or relationship property means that a property must exist.
Even though, by default, you need not create all nodes or relationships with the same property keys, you graph data model may benefit from requiring that a particular property key exists.

For example, in the Movie graph, we want all Person nodes to have a name property with a value.
Remember that a node with a property with a null value is the same as that node not having that property.

You can create an existence constraint for a node or relationship property, when the node or relationship is created or updated, it must have that property with a value, otherwise and error is raised.

== Indexes in Neo4j

An index in Neo4j is a data structure that allows the graph engine to retrieve data quickly.
All indexes in Neo4j require more storage in the graph, so you must ensure that you do not index everything.

Constraints are implemented as indexes, but there are more types of indexes that you can create.
A best practice is to create uniqueness constraints before you load your data, then after the data is loaded, you create additional indexes to make your queries perform faster.

=== b-tree indexes


=== composite indexes


=== LOOKUP indexes

=== TEXT indexes


== Check your understanding

include::questions/1-complete-query.adoc[leveloffset=+1]
include::questions/2-select-answer.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, reviewed and learned about basic query filtering using the `WHERE` clause.
In the next challenge, you will write queries to filter data.
