= Creating the Movie Application Domain
:type: challenge
:lab-file: src/challenges/create-driver/challenge.java
:lab-solution: src/challenges/create-driver/solution.java
:lab: {repository-blob}/main/{lab-file}

//LEFT OFF HERE!
////
Movie properties:
{
  "languages": String array,
  "year": integer,
  "imdbId": string,
  "runtime": integer,
  "imdbRating": float,
  "movieId": string,
  "countries": String array,
  "imdbVotes": integer,
  "title": string,
  "url": string,
  "revenue": integer,
  "tmdbId": string,
  "plot": string,
  "poster": string,
  "released": string,
  "budget": integer
}

Person properties:
{
  "bornIn": string,
  "tmdbId": string,
  "imdbId": string,
  "born": string,
  "name": string,
  "bio": string,
  "died": string,
  "poster": string,
  "url": string
}
////


Your challenge is to add a new Driver instance to an existing file with the connection details provided.
Once you have created the Driver, you will need to open a new session and run a Cypher statement to find the director of the movie **Toy Story**.


link:./lab[Open Challenge in an Online IDE →^, role=btn]

== Steps

1. Install the Neo4j JavaScript Driver in the integrated terminal window
+
include::{repository-raw}/main/README.adoc[tag=install]

2. Use the `neo4j` object to create a new instance of the Driver with the credentials provided:
  * `NEO4J_URI` is the connection string
  * `NEO4J_USERNAME` and `NEO4J_PASSWORD` should be used to create the authentication token.

3. Once you have created the Driver, open a new session and run the following query: +
+
.Find the Director
[source, cypher]
----
include::{repository-raw}/main/cypher/movie-director.cypher[]
----

4. To find the answer, click the Debug icon to the left of the window and run **Create Driver Challenge** task, or use the integrated terminal window to run the following command: +
+
.Run The Challenge
[source,sh,subs=attributes+]
----
ts-node {lab-file}
----

5. Once you have the result, copy and paste it into the text box below and click **Check Answer**.


== Your Answer

include::questions/1-director.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

In this challenge, you used your knowledge to create a driver instance and run a Cypher statement.

In the next lesson, you will learn about the different transaction functions and when to use them.
