= Course Summary and Next Steps
:order: 2
:type: lesson

Congratulations! You have completed the course. From start to finish, you learned how to build a Spring Boot application that used Spring Data Neo4j to interact with data in a Neo4j graph database.

== Spring Data Neo4j Course Summary

Let's review all you have accomplished:

* You learned the building blocks of the Spring Data Neo4j library.
* You learned how to configure the Spring Data Neo4j library to connect to a Neo4j database and test the connection.
* You learned about the graph model and application model and how to map one to the other.
* You created the application model by mapping nodes and relationships to Java domain classes.
* You learned how to create a Spring Data Neo4j repository interface and use it to perform read and write operations between the application and database.
* You learned how to use the `@Query` annotation to define custom Cypher queries for both reading and writing data.
* You learned how to use projections to create custom views of entities.

== Ideas for Further Development

There are a variety of things you can do following this course to further your knowledge of Spring Data Neo4j and graph databases.

*First*, you can expand this course's project by adding more methods and custom queries. Can you fill in repository and controller methods for `Person` entities? Can you add projections that update entities? Can you add a custom query to do a fuzzy search with a partial string? Or perhaps you want to find persons who worked together often? See how you can increment your current knowledge by stretching it in targeted ways.

*Second*, build a new project with another data set. Push your domain modeling skills (along with your graph modeling and application modeling skills) by applying what you have learned to other domains. A different data set can bring new challenges or improve learned concepts. You might need to make decisions on architecting multiple relationships, hierarchical/trees, hypernodes, or other data modeling structures.

*Third* (and finally), integrate other technologies and tools into a Spring Data Neo4j project. For example, you can stay within the Spring projects by adding Spring Security to secure your application or Spring Actuator for monitoring and application health. You can also integrate other technologies like the Kafka Connector to stream data into or out of your graph or cloud options to deploy and run your application in the cloud.

The possibilities are endless! The important thing is to find something that interests you and feels manageable. Then, go for it! And, as always, if you get stuck along the way, don't hesitate to reach out and post your question on our https://community.neo4j.com/[Neo4j Community Forum^].

read::Continue[]

[.summary]
== Summary

In this lesson, you reviewed all the skills you achieved through the completion of this Spring Data Neo4j course. You also received some ideas for further development that hopefully inspired you to continue your learning journey.

I hope you have enjoyed the time spent learning about Spring Data Neo4j and building your own application with the Neo4j graph database. Best wishes in your future projects and learning!