= Challenge: Create Person classes
:type: challenge
:lab-file: src/main/resources/challenges/create-person/challenge.java
:lab-solution: src/main/resources/challenges/create-person/solution.java
:lab: {repository-blob}/main/{lab-file}

Your challenge is to create the classes for the Person domain, repository, and controller.
Once you have created them, you will need to test the application and find the results for the person with the `imdbId` **0000245**.

== Person node properties

Create a new Java class called `Person` and utilize the following list of properties and data types for the Person node in Neo4j to map in your domain class, using the `imdbId` field as the class's identifier:

[source,text]
----
{
  born:"DATE", 
  bornIn:"STRING", 
  tmdbId:"STRING", 
  bio:"STRING", 
  died:"DATE", 
  name:"STRING", 
  poster:"STRING", 
  imdbId:"STRING", 
  url:"STRING"
}
----

Reference the Cypher-to-Java https://neo4j.com/docs/java-reference/current/extending-neo4j/values-and-types/[data type mappings^] from the documentation, if needed.

link:./lab[Open Challenge in an Online IDE →^, role=btn]

[%collapsible]
.Click to reveal the sample solution
====
[source,java]
----
@Node
public class Person {
    @Id
    private String imdbId;

    private String tmdbId;
    private String name;
    private String bio;
    private String poster;
    private String url;
    private String bornIn;

    private LocalDate born;
    private LocalDate died;

    //constructor, getters, and setters
}
----
====

== PersonRepository

Next, create an interface called `PersonRepository` that extends the `Neo4jRepository` interface with the appropriate domain and identifier types.

[%collapsible]
.Click to reveal the sample solution
====
[source,java]
----
public interface PersonRepository extends Neo4jRepository<Person, String> {
}
----
====

== PersonController

Finally, create a new class called `PersonController` with annotations and create methods to implement `findAll()` and `findById()`.

[%collapsible]
.Click to reveal the sample solution
====
[source,java]
----
@RestController
@RequestMapping("/people")
public class PersonController {
    private final PersonRepository personRepo;

    public PersonController(PersonRepository personRepo) {
        this.personRepo = personRepo;
    }

    @GetMapping()
    Iterable<Person> findAllPeople() {
        return personRepo.findAll();
    }

    @GetMapping("/{imdbId}")
    Optional<Person> findPersonById(@PathVariable String imdbId) {
        return personRepo.findById(imdbId);
    }
}
----
====

== Test the application

With those pieces in place, you can now test the application. Run the application and run the following commands in the terminal to see the results.

[source,shell]
----
curl http://localhost:8080/people
curl http://localhost:8080/people/0000245
----

== Find the answer

Once you have the result, copy and paste it into the text box below and click **Check Answer**.

== Your Answer

include::questions/1-person.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

In this challenge, you used your knowledge to create the domain class, repository interface, and controller class for Person entities.

In the next lesson, you will learn how to create classes to map relationships between Movie and Person entities.
