= Course Summary

Congratulations on completing _Constructing Knowledge Graphs with Neo4j GraphRAG for Python_.``


You have learned:

* The process of creating knowledge graphs from unstructured text.
* How to use the `SimpleKGPipeline` class to create a knowledge graph from unstructured data.
* How to modify the configuration to define a knowledge graph schema and data model.
* How to use retrieval techniques to find relevant information from a knowledge graph
* How you can use vector, vector + cypher, and text to cypher retrievers to get relevant data from a knowledge graph
* How to modify the knowledge graph pipeline to suit your own use case, including:
** Creating custom data loaders.
** Implementing a chunking and text splitting strategy.
** Enhanced entity resolution.
** Using different LLMs and embedding mode


You can continue your learning on GraphAcademy with the link:https://graphacademy.neo4j.com/knowledge-graph-rag/[GraphRAG learning pathway^].

You may also want to explore some of the topics covered in this course in more detail, with the following courses:

* link:https://graphacademy.neo4j.com/courses/llm-chatbot-python/[Build a Neo4j-backed Chatbot using Python^]
* link:https://graphacademy.neo4j.com/courses/genai-integration-langchain/[Using Neo4j with LangChain^]
* link:https://graphacademy.neo4j.com/courses/genai-mcp-neo4j-tools/[Developing with Neo4j MCP Tools^]
* link:https://graphacademy.neo4j.com/courses/genai-mcp-build-custom-tools-python/[Building GraphRAG Python MCP tools^]
