[.question]
= business email or not

Which one of these is (most) true?

* [ ] Neo4j wants my business email so they can target the company I work for with marketing and sales.
* [ ] Neo4j wants my business email to spy. They will then tell my boss that I'm using graph instead of a relational database during working hours!
* [x] Neo4j wants my business email in order to avoid future issues once I move to a paid tier.
* [ ] Neo4j wants my business email so abuse of the free tier and trials is limited and everybody can enjoy the power of graph.

[TIP,role=hint]
.Hint
====
You don't need a hint for this!
====

[TIP,role=solution]
.Solution
====
The second option would be against the privacy laws and is **false**. All the other options are true to some degree. 

Make sure to opt out of any targeting you do not want. 

Do not create a dozen email addresses to create a poor man's cluster of **Aura Free** instances.

The main reason however is administrative. If you intend to use the account in a business context, use a business email. It'll save you pain later.
====