= Neo4j データインポートの概要
:type: quiz

[.video]
video::ImKvXY72SA0[youtube,width=560,height=315]

[.transcript]
== データを取り込むとはどういうことか？

Neo4jにデータをインポートする場合、通常、次のようなソースファイルのセットがあります:

* RDBMS
* Web APIs
* Publicデータディレクトリ
* BIツール
* Excel

ファイルの種類は、通常、CSV、JSON、XMLなどです。
このコースでは、CSVデータをノード、リレーションシップ、およびそのプロパティとしてNeo4jにインポートする方法を学びます。
Cypherには、CSVファイルをインポートするための `LOAD CSV` という句が組み込まれています。
JSONやXMLファイルの場合は、APOCライブラリを使用してデータをインポートする必要がありますが、APOCでCSVをインポートすることも可能です。
また、Neo4j Data Importerは、Cypherのコードを書かずにCSVデータをインポートすることが可能です。

ソースファイルのデータには、グラフに必要なデータよりも多くのデータが含まれている場合があります。
CSVファイルのデータをグラフデータモデルのノードとして使用する場合、1-1マッピングがない場合があります。
また、ソースファイルのデータは、Neo4j でサポートされていないデータ型や、実装しているデータモデルで指定されていないデータ型を表している場合があります。
ソースファイルのデータの中には、適切な型に変換する必要があるものもあります。

Neo4jでプロパティとして保存できるデータの種類は以下の通りです。:

* String
* Long (integer values)
* Double (decimal values)
* Boolean
* Date/Datetime
* Point (spatial)
* StringArray (comma-separated list of strings)
* LongArray (comma-separated list of integer values)
* DoubleArray (comma-separated list of decimal values)

作業するソースデータと、実装するグラフデータモデルを理解したら、データをNeo4jにインポートします。
CSVデータをNeo4jにインポートする方法は、このコースで学ぶ2つの方法があります。:

. Neo4j Data Importerを使用する。
. インポートを実行するためのCypherのコードを書く。

どちらの場合も、インポートではソースデータを読み込み、それらを使ってグラフ内にノード、リレーションシップ、プロパティを作成します。

=== CSVデータのインポートに必要な条件

グラフに作成されるノードとリレーションシップを表すCSVファイルを1つ以上用意する必要があります。
また、既存のNeo4j DBMSが起動されている必要があります。
通常、何も入っていないグラフからスタートします。

このコースでは、インポート用のソースデータファイルを作成するのではなく、すでに作成されているファイルを使用します。

=== データ取り込みのための準備手順

以下は、Neo4jにデータをインポートするための準備の手順です。:

. ソースCSVファイルのデータを理解する。
. ソースデータファイルのデータを検査し、クリーニングする（必要な場合）。
. インポート時に実装するグラフデータモデルを作成する、または理解する。

== 理解度チェック

include::questions/1-cypher-csv.adoc[leveloffset=+1]

[.summary]
== まとめ

このレッスンでは、Neo4jにデータをインポートすることの意味と、データをNeo4jにインポートする前に行わなければならない手順を学びました。
次のレッスンでは、CSV ソース・データをどのように整理するかについて学びます。

