= Building Dashboards in Neo4j Aura
:categories: administrator:1, beginners:5, foundation:1, aura:1
:status: draft
:duration: 2 hours
:caption: Learn about data visualisation in Neo4j Aura.
:key-points: Aura dashboards, exploratory data analysis, data import and visualization, exploring relationships in data.

In this course you will learn about Aura Dashboards, a feature for visualising and exploring graph data directly within the Aura environment.
You will learn how to access Aura Dashboards, import and visualise data, create interactive dashboards using AI and Cypher queries, and share dashboards with others.

You will explore the Aura Dashboards interface, learn about different visualization options for data representation, and discover the built-in tools for data exploration and visualisation.

This course will prepare you to visualise and understand the Neo4j databases in the cloud with confidence.

== Duration

2 hours

== Prerequisites

Before starting this course, you should have a basic understanding of graph databases and some familiarity with Neo4j. If you are new to Neo4j, you can familiarize yourself with the database with the link:/courses/neo4j-fundamentals/[Neo4j Fundamentals course^], the link:/courses/aura-fundamentals/[Aura Fundamentals course^] and the link:/courses/cypher-fundamentals/[Cypher Fundamentals course^].

== What you will learn

* How to create dashboards in Neo4j Aura
* Understand how to structure Cypher queries to visualize graph data to explore relationships between data points
* How to make dashboards interactive
* How to share dashboards with others

[.includes]
== This course includes

* [lessons]#10 lessons#
* [quizes]#11 multiple choice quizzes#
