= Filtering
:order: 6


Query results can be filtered using the `where` argument. Filter inputs are generated for each field and expose comparison operators specific to the type of the field. For example, for numeric fields filter input operators include equality, greater than (`_GT`), less than (`_LT`), etc. String fields expose the common string comparison operators such as `_STARTS_WITH`, `_CONTAINS`, `_ENDS_WITH`, etc.

Let's search for all books where the price is less than 20.00:

[source,GraphQL]
----
{
  books(where: { price_LT: 20.00 }) {
    title
    price
  }
}
----

[source,JSON,role=nocopy]
----
{
  "data": {
    "books": [
      {
        "title": "Ross Poldark",
        "price": 15.52
      }
    ]
  }
}
----

For `Point` fields we can filter results by the distance to another point. Here we search for addresses within 1km of a specified point:


[source,GraphQL]
----
{
  addresses(
    where: {
      location_LT: {
        distance: 1000
        point: { latitude: 37.56169133066, longitude: -122.3232480481 }
      }
    }
  ) {
    address
  }
}

----

We can also use the `where` argument in nested selections to filter relationships. Here we are filtering for reviews created after Jan 1, 2021 using the `createdAt_GT` filter input on the `createdAt` DateTime type, specifying the date using the ISO format.

[source,GraphQL]
----
{
  books(where: { price_LT: 20.00 }) {
    title
    price
    reviews(where: { createdAt_GT: "2021-01-01" }) {
      text
      rating
    }
  }
}
----

Note that the filters are applied at the level of the selection where the filter is used. So in the above example, all books with a price less than 20.00 will be returned, regardless of the reviews connected to the book.

Let's look at an example that applies filtering at the root of our query, but using a relationship. Let's say we want to search for all orders where the shipTo address is within 1km of a certain point. To do that we'll use the `where` argument at the root of the query (in the `orders` Query field), but use a nested input to specify we want to filter using the `shipTo` relationship and the corresponding `Address` node.

[source,GraphQL]
----
{
  orders(
    where: {
      shipTo: {
        location_LT: {
          distance: 1000
          point: { latitude: 37.56169133066, longitude: -122.3232480481 }
        }
      }
    }
  ) {
    orderID
    customer {
      username
    }
    books {
      title
    }
  }
}
----


For more information and examples see the https://neo4j.com/docs/graphql-manual/current/schema/filtering/[filtering section in the Neo4j GraphQL Library documentation].
