[.question]
= 1. Creating an existence constraint on a node property

Suppose we have a graph that contains Company nodes. One of the properties of a Company node is name.
Every Company in the graph must have a value for the name property.
Before we load the Company data, we want to create an existence constraint for the Company.name property.
What is the correct statement to create this constraint?

* [ ] `CREATE EXISTENCE CONSTRAINT Company_name_exists IF NOT EXISTS FOR (Company.name)`
* [ ] `CREATE EXISTENCE CONSTRAINT Company_name_exists IF NOT EXISTS FOR (x:Company) WITH (x.name)`
* [x] `CREATE CONSTRAINT Company_name_exists IF NOT EXISTS FOR (x:Company) REQUIRE x.name IS NOT NULL`
* [ ] `CREATE CONSTRAINT Company_name_exists IF NOT EXISTS FOR (x:Company) EXISTS x.name`

[TIP,role=hint]
.Hint
====
You specify the type of constraint at the end of the statement
====

[TIP,role=solution]
.Solution
====

The correct statement for creating this constraint is:

`CREATE CONSTRAINT Company_name_exists IF NOT EXISTS FOR (x:Company) REQUIRE x.name IS NOT NULL`
====
