= Loading CSV files
:order: 4
:type: lesson
:sandbox: true

How CSV files can be accessed. Use LOAD CSV Cypher statement to load the Movies file and see its contents.

Know the LOAD CSV syntax and how to access a file

[.video]
video::YouTubeVideoID


[.transcript]

In this lesson, you'll learn how to use the link:https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`] Cypher clause, including:

* The link:https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`] syntax
* How to load headers within a CSV file
* Options for accessing a file

== LOAD CSV

The `LOAD CSV` Cypher clause reads data from a CSV file and returns the rows in the file. You can specify the file location, the field terminator, and whether the file has a header row.

`LOAD CSV` has the following syntax:

[source,cypher]
----
LOAD CSV [WITH HEADERS] FROM url [AS alias] [FIELDTERMINATOR char]
----

// TODO - update below and sandbox.cypher with file location

You are going to load a CSV file that contains this people data.

[source,csv]
----
personId,name,birthYear
23945,Gerard Pires,1942
553509,Helen Reddy,1941
113934,Susan Flannery,1939
----

In the Sandbox run the following Cypher statement to load the `people.csv` file:

[source,cypher]
----
LOAD CSV WITH HEADERS 
FROM 'file:///people.csv' 
as row
RETURN row
----

Review the data returned. Note the number of rows returned and the header names match those in the CSV file.

[source, json]
----
{
  "birthYear": "1942",
  "name": "Gerard Pires",
  "personId": "23945"
}
----

The `FIELDTERMINATOR` wasn't specified in the `LOAD CSV` clause because the default value is a comma. If the field terminator was a pipe character, the `LOAD CSV` clause would need to include the field terminator:

[source,cypher]
----
LOAD CSV WITH HEADERS 
FROM 'file:///people.csv' 
as row FIELDTERMINATOR '|'
RETURN row
----

[TIP]
.Counting rows
A simple check you can do to ensure all rows are loaded is to count the number of rows in the CSV file and compare it to the number of rows returned by the `LOAD CSV` clause.

You can return the number of rows in the CSV file using the `COUNT` function.

[source,cypher]
----
LOAD CSV WITH HEADERS 
FROM 'file:///people.csv' 
as row
RETURN count(row)
----

== Accessing files

`LOAD CSV` can access files on the Neo4j server's file system or a remote machine.

The Sandbox and link:https://neo4j.com/cloud/platform/aura-graph-database/[Aura DB] cloud service only allow access to remote files.

You can find more information in the link:https://neo4j.com/docs/getting-started/data-import/csv-import/#_reading_csv_files[Reading CSV Files] section of the Neo4j documentation.

[.quiz]
== Check Your Understanding

include::questions/1-load-csv-syntax.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you learned:

* The `LOAD CSV` Cypher syntax.
* How to use `LOAD CSV` to load a CSV file.
* How to change the field terminator.

In the next lesson, you can take the optional challenge of loading your own CSV file.