= Movie Lists and Pagination
:type: challenge
:test-number: 11
:branch: 11-movie-lists

In this challenge, you will implement the remaining methods in the link:{repository-blob}/main/src/services/movie.service.js[`MovieService`^] for retrieving a list of movies:

* <<getByGenre>> - should return a paginated list of movies that are listed in a particular Genre
* <<getForActor>> - should return a paginated list of movies that a particular Person has acted in
* <<getForDirector>> - should return a paginated list of movies that a particular Person has directed

These methods are very similar to the `all()` method which returns a full list, but with a different pattern in the `MATCH` clause.

// .src/services/movie.service.js
// [source,java,indent=0]
// ----
// include::{repository-raw}/10-genre-details/src/services/movie.service.java[tag=all]
// ----

For each subtask, we will provide you with the pattern required to run in the Cypher query, plus any additional parameters that are required for the query to run.

//Adam: should this be run()?
All you need to do is take the code from the `all()` method and modify the pattern in the first line of the Cypher query in the first argument of the `tx.run()` call, then if necessary add the additional parameters to the second argument.

If you get stuck at any point, you can click to reveal the completed solution or skip to the bottom for instructions on how to checkout the branch with the working solution.


== getByGenre

The `getByGenre()` method returns a paginated list of movies that are listed within a certain genre.

.src/services/movie.service.js
[source,java,indent=0]
----
include::{repository-raw}/main/src/services/movie.service.java[tag=getByGenre]
----

Update the `getByGenre()` method to use the following Cypher Pattern:

[source,cypher,role=norun]
MATCH (m:Movie)-[:IN_GENRE]->(:Genre {name: $name})

The `tx.run()` call will need to include the `name` property, which represents the name of the genre.


[%collapsible]
.Click to reveal the completed `getByGenre()` method
====

Find the `getByGenre()` method in `src/services/movie.service.js` and modify the function to find a list of movies by genre.

.src/services/movie.service.js
[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/services/movie.service.java[tag=getByGenre]
----

====



== getForActor

The `getByGenre()` method returns a paginated list of movies that a person has acted in.

.src/services/movie.service.js
[source,java,indent=0]
----
include::{repository-raw}/main/src/services/movie.service.java[tag=getForActor]
----

Find the `getForActor()` method in `src/services/movie.service.js` and modify the function to find a list of movies by actor.

The pattern required in the `MATCH` clause will be:

[source,cypher,role=norun]
MATCH (:Person {tmdbId: $id})-[:ACTED_IN]->(m:Movie)

You will have to include the additional parameter `id` - The `tmdbId` property relating to the actor.

[%collapsible]
.Click to reveal the completed `getForActor()` method
====

.src/services/movie.service.js
[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/services/movie.service.java[tag=getForActor]
----

====

== getForDirector

The `getByGenre()` method returns a paginated list of movies that a person has directed.

.src/services/movie.service.js
[source,java,indent=0]
----
include::{repository-raw}/main/src/services/movie.service.java[tag=getForDirector]
----

Find the `getForDirector()` method in `src/services/movie.service.js` and modify the function to find a list of movies by director.

The pattern required in the `MATCH` clause will be:

[source,cypher,role=norun]
MATCH (:Person {tmdbId: $id})-[:DIRECTED]->(m:Movie)

You will have to include the additional parameter `id` - The `tmdbId` property relating to the director.


[%collapsible]
.Click to reveal the completed `getForDirector()` method
====

.src/services/movie.service.js
[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/services/movie.service.java[tag=getForDirector]
----

====

// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-coppola-films.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you modified the functions in the `MovieService` to return lists of movies.

In the next Challenge, we will implement the `findById()` method.
