= Indirect relationships - adding indirect relationships between nodes
:order: 3

In this lesson, you will learn how to refactor your graph by adding indirect relationships between nodes to improve traversal performance and create more efficient query patterns.


// employees in regions
MATCH (employee:Employee)-[:IN_TERRITORY]->(:Territory)-[:IN_REGION]->(region:Region)
RETURN DISTINCT employee.firstName, region.regionDescription


// create indirect relationships between employees and regions
MATCH (employee:Employee)-[:IN_TERRITORY]->(:Territory)-[:IN_REGION]->(region:Region)
MERGE (employee)-[p:PART_OF_REGION]->(region)
RETURN employee, p, region


// employees in regions using indirect relationships
MATCH (employee:Employee)-[:PART_OF_REGION]->(region:Region)
RETURN employee.firstName, region.regionDescription


Profile the original query and the refactored query to compare their performance.


// tip - delete relationships
MATCH (employee)-[p:PART_OF_REGION]->(region)
DELETE p



Challenge - create an indirect relationship between the employee that sold the order and the customer who purchased the order.

// employees and the customers they sold to
MATCH (employee:Employee)-[:SOLD]->(:Order)<-[:PURCHASED]-(customer:Customer)
RETURN DISTINCT employee.firstName, customer.companyName

// create indirect relationships between employees and customers
MATCH (employee:Employee)-[:SOLD]->(:Order)<-[:PURCHASED]-(customer:Customer)
MERGE (employee)-[s:SOLD_TO]->(customer)
RETURN employee, s, customer

// employees and the customers they sold to using indirect relationships
MATCH (employee:Employee)-[s:SOLD_TO]->(customer:Customer)
RETURN employee.firstName, customer.companyName







read::Complete[]

[.summary]
== Lesson Summary

In this lesson, you learned about creating indirect relationships between nodes to optimize graph traversals and improve query performance.

In the next lesson, you will learn about normalizing properties to nodes.
