[.question.select-in-source]
= 2. Titles and Release Dates for Actors

We want to return the list of titles and release dates for the movies of an actor.
Each row returned will contain the name of the actor and a list containing the title and release date for a movie.
The title and release date element will be of the format "title: release date".
Use the dropdown below to select the correct code to complete this query.

Once you have selected your option, click the **Check Results** query button to continue.


[source,cypher,role=nocopy noplay]
----
MATCH (a:Actor)--(m:Movie)
WITH a, collect (m) AS Movies
RETURN a.name AS Actor, size(Movies) as NumMovies,
/*[x IN Movies | x.title + ": " + toString(x.released)] AS Summary*/
LIMIT 100
----

* [ ] `[x IN Movies | x.title + x.released] AS Summary`
* [ ] `[x IN Movies | x.title , x.released] AS Summary`
* [x] `[x IN Movies | x.title + ": " + toString(x.released)] AS Summary`
* [ ] `[x IN Movies | x.title , toString(x.released)] AS Summary`


[TIP,role=hint]
.Hint
====
Each element of the list returned for an actor will be a string.
====

[TIP,role=solution]
.Solution
====
The correct answer is `[x IN Movies | x.title + ": " + toString(x.released)] AS Summary`
====