= Finding Genre Details
:type: challenge
:order: 2
:optional: true
:test-filename: 10-GenreDetails
:test-pattern: _10_GenreDetails
:branch: 10-genre-details

When the user clicks a genre in the list, they are taken to a list of movies for that genre.  This list is populated by an API request to `/api/genres/[name]`, for example http://localhost:3000/api/genres/Comedy[http://localhost:3000/api/genres/Comedy^].

The ``FindGenreAsync()`` method the the `GenreService` accepts one argument, the name of the genre, and should return the information about the genre, along with a count of movies and a poster image.

.Neoflix/Services/GenreService.cs
[source,c#,indent=0]
----
include::{repository-raw}/main/Neoflix/Services/GenreService.cs[tag=find]
----


In this challenge, you will modify the method to run the following Cypher statement in a **read transaction**:

.Finding Genre Details
[source,cypher]
----
include::{cypher-repository-raw}/main/cypher/3-backlog/2-find-genre-details/genre-details.cypher[]
----

[IMPORTANT]
.What does this query do?
====
This query uses the `MATCH` clause for a `Genre` node with the name passed through with the function call as a parameter.
The query then finds the highest rated movie with a `poster` property and uses that image as the background to the card in the UI.

The `size()` function returns the number of incoming `IN_GENRE` relationships for each the `Genre` node.
====


== Your Task

* Modify the ``FindGenreAsync()`` method on the `GenreService` to call the Neo4j database and return details for a genre.
* The `name` variable should be passed to the `run()` call as a parameter.
* If no records or more than one record are found, a `NotFoundError` should be thrown by using the `single()` method on `Result`.
* Remember to close the session and use the `ToListAsync()` function to convert the genre values to native C# types.


== Working Solution

[%collapsible]
.Click here to view the completed ``FindGenreAsync()`` method.
====

.Neoflix/Services/GenreService.cs
[source,c#,indent=0]
----
include::{repository-raw}/{branch}/Neoflix/Services/GenreService.cs[tag=find]
----
====

// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-genre-movie-count.adoc[leveloffset=+2]

[.summary]
== Lesson Summary

In this Challenge, you modified the ``FindGenreAsync()`` method in the `GenreService` to retrieve genre information from Neo4j.

In the next Challenge, you will update multiple methods in the `MovieService` that return a paginated list of movies.
