= The Home Page
:type: challenge
:order: 4
:branch: 02-movie-lists
:test-number: 02
:lab: {repository-blob}/main/src/services/movie.service.js

Now for another challenge.

In this challenge, you will use the knowledge gained so far in this course to add new functionality to the API.
You will modify the `all()` method of the link:./lab/[`MovieService`^] to do the following:


* <<1. Open a new Session>>
* <<2. Execute a Cypher statement within a new Read Transaction>>
* <<3. Extract a list of Movies from the Result>>
* <<4. Close the Session>>
* <<5. Return the Results>>

Once you have completed the challenge, you will be asked to run a unit test to verify that the code has been correctly implemented.
If the test runs correctly, the title of the highest rated movie will be logged.
You will need this value to verify that the test has run correctly.


== Exploring the Code

Before you start, let's take a look at the code.
If you are not interested in the code, you can skip straight to <<Challenge: Implementing Read Transactions>>.

If you start the application and access the app at http://localhost:3000, you will see two lists on the home page; one for Popular Movies and one for Latest Releases.
Both of these lists are populated by a request to link:http://localhost:3000/api/movies[`http://localhost:3000/api/movies`^] with some additional parameters.

=== Route Handler

You can find the route handler, the function that handles the request, in link:{repository-blob}/main/src/routes/movies.routes.js[`src/routes/movies.routes.js`^]:

.src/routes/movies.routes.js
[source,js,role=nocopy]
----
include::{repository-raw}/main/src/routes/movies.routes.js[tag=list]
----

Within the route handler, you can see that:

1. The `sort`, `order`, `limit` and `skip` values are extracted from the query string.  This allows us to apply sorting and pagination to the results.
2. A new instance of the `MovieService` is created with the Driver instance that you created in link:../../1-driver/3-connecting/[Adding the Driver] passed to the constructor.
3. The results are retrieved via the `all()` method and are returned by the handler as JSON.

=== The Movie Service

The magic happens in the `MovieService`, located at link:./lab/[`src/services/movies.service.js`^].
For this route we are concerned with the `all()` method.

If we take a closer look at the `all()` method, we can see that it currently returns a hardcoded list of popular movies from another file in the repository.

[source,js,indent=0]
.src/services/movie.service.js
----
include::{repository-raw}/main/src/services/movie.service.js[tag=all]
----

You will need to replace these `TODO` comments with working code to complete the challenge.


== Challenge: Implementing Read Transactions

As you learned in the Sessions and Transactions lesson, you will complete code to open a new session and run the query within a Read Transaction.
Once the query has run, you add code to close the session.
Then, finally you add code to extract and return the results.

lab::Open `src/services/movie.service.js`[]

=== 1. Open a new Session

Within the `all()` method, first open a new session:

[source,js,indent=0]
----
include::{repository-raw}/main/example/index.js[tag=session]
----

=== 2. Execute a Cypher statement within a new Read Transaction

This session provides an `executeRead()` method for which you pass a function to represent the unit of work.

The function will have one argument passed to it, a `Transaction` instance that you can use to execute a Cypher statement using the `run()` method.
The `run()` method accepts two arguments:

1. The Cypher statement as a parameterised string.
2. An object containing the values for the parameters prefixed in the query with a dollar sign (`$`).

[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/movie.service.js[tag=allcypher]
----


[WARNING]
====
In the second argument, we use references to the `int()` function imported from `neo4j-driver` to convert the skip and limit values into a Neo4j integer.
Remember to add the import statement to the top of the file.

[source,js]
----
include::{repository-raw}/main/example/integers.js[tag=import]
----
====


=== 3. Extract a list of Movies from the Result

Now that you have a complete result assigned to the `res` variable, you use the `map()` function on the `res.records` array to retrieve the `movie` value returned by the query.

[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/movie.service.js[tag=allmovies]
----


=== 4. Close the Session

Before returning anything, make sure that the session is closed.

[source,js,indent=0]
----
include::{repository-raw}/main/example/index.js[tag="session.close"]
----


=== 5. Return the Results

Finally, update the `return` statement to return the `movies` list extracted above.

[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/movie.service.js[tag=return]
----


== Working Solution

[%collapsible]
.Click here to reveal the completed `all()` method
====

.src/services/movie.service.js
[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/movie.service.js[tag=all]
----
====

include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you used your knowledge of sessions and transactions to retrieve a list of Movie nodes from the database.

In the next Challenge, you will write data to the database.
