= Finding Relationships
:type: quiz
:order: 2


[TIP]
.Our Goal
As a *Movie fanatic* +
I would like to *Find movies for a particular actor* +
So that I can *Watch a movie this evening*


In the previous lesson, we used the `MATCH` clause to find the node in our database that represented Tom Hanks.

[source,cypher]
----
MATCH (p:Person {name: "Tom Hanks"})
----

We can extend the pattern in the match clause to _traverse_ through all relationships with a type of `ACTED_IN` to any node.
Our domain model shows that the `:ACTED_IN` relationship goes in an outgoing direction from the Person so we can add the.

We often refer to this as a _traversal_.


[source,cypher]
----
MATCH (p:Person {name: "Tom Hanks"})-[:ACTED_IN]->()
----

Our data model dictates that the node at the other end of that relationship will be `:Movie` node, so we don't necessarily need to specify the `:Movie` label in the node - instead we will assign the variable `m`

[source,cypher]
----
MATCH (p:Person {name: "Tom Hanks"})-[:ACTED_IN]->(m)
----

If we had multiple _types_ of node at the end of the relationship, we could make sure that we only return .


[source,cypher]
----
MATCH (p:Person {name: "Tom Hanks"})-[:ACTED_IN]->(m:Movie)
----



== Check your understanding

include::questions/complete-query.adoc[]

include::questions/restricting-data.adoc[]

