= Importing Customer Nodes
:type: challenge
:order: 7
:duration: 8
:optional: true

[.slide.discrete]
== Importing Customer Nodes

You imported Product nodes in the previous lesson. Now import Customer nodes using the same workflow.

The customers.csv file is already loaded in your Import tool from when you uploaded all files.


[.slide]
== Map the Customer node

In the **Data Modeling tab**:

. Click the **+ Node Label** button to add a new node
. **Set the label:** Under **Definition**, set the label to `Customer`
. **Select the table:** Under **Table**, select `customers.csv`


[.slide]
== Configure properties

Use the **Map from table** button and select these columns:

[options="header"]
|===
| Column | Type | Rename To
| customerID | String | id
| companyName | String | name
| contactName | String |
| country | String |
| city | String |
|===

[NOTE]
.ID Property
====
Verify the ID property is set to `id` and update if necessary.
====


[.slide]
== Run the import

Click the **Run Import** button. You should see confirmation that **91 Customer nodes** were created.

include::questions/verify.adoc[leveloffset=+1]

[.summary]
== Summary

You imported Customer nodes into your graph:

* Created 91 Customer nodes
* Renamed `customerID` to `id` and `companyName` to `name`

Next, import Order nodes using the same process.
