= Challenge: Create Custom Cypher for Write
:order: 3
:type: challenge

You have learned how to create, read, and delete nodes in the Neo4j database (the *C*, *R*, and *D* in the popular *CRUD* acronym). The only part of the puzzle left is to *U*pdate nodes in the database.

Your challenge is to create a custom method in the repository interface using the `@Query` annotation with a provided Cypher statement that writes an update to the database. Once you have created the method and query, you will need to test the application and verify the results.

== Define a custom repository method

You will set a property in the database when a movie is created or updated. While you could do this programmatically by adding a new field to the `Movie` class, this is a background field that the user does not need. Instead, we will use a custom Cypher query to avoid cluttering our domain class on read operations.

Open the `MovieRepository` interface in your editor and add a new method called `saveWithAudit()` that takes a `Movie` object as a parameter and returns a `Movie`. Add the `@Query` annotation to the method and provide the following Cypher statement as the value:

[source,cypher]
----
include::code/saveWithAudit.cypher[]
----

Now implement that newly-created method in the `MovieController` class by creating a new endpoint at `/movies/saveaudit` that takes a `Movie` object as a parameter and returns a `Movie` object. Use the `saveWithAudit()` method to save the movie and return the result.

[%collapsible]
.Click to reveal the sample solution
====
[source,java]
----
include::code/MovieRepository.java[]
include::code/MovieController.java[]
----
====

== Test the application

With those pieces in place, you can now test your changes. Run the application and execute the following command in the terminal to see the results.

[source,shell]
----
curl localhost:8080/movies/save \
  -H 'Content-Type: application/json; charset=utf-8' \
  -d @src/main/resources/movie.json
----

You won't see the added field in the terminal output, but if you query the database in Neo4j Browser, you will see the new `lastUpdated` field. You can run the following query to see the results:

[source,cypher]
----
MATCH (m:Movie {movieId: "9876"})
RETURN m;
----

== Check Your Understanding

include::questions/1-custom-cypher.adoc[leveloffset=+1]
include::questions/2-write-field.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

In this challenge, you used your knowledge to create a custom method with a Cypher statement to write data to the database.

You should now have everything you need to use Spring Data Neo4j in your next project. In the next module, we will provide some resources and links to help you continue your learning journey.