[.question]
= 3. Saving Properties in the Database

Suppose you have a need to calculate the number of reviews made by each User node and save it as a property in the database so it can be queried later with Cypher.

We can create a graph projection from `User` and `Movie` nodes and the `RATED` relationships then run degree centrality to get a `numberOfRatings` property in the graph projection. From there, what GDS workflow works best to satisfy this use case?

* [ ] Use the `gds.graph.saveProperties()` operation to save the `numberOfRatings` property back to `User` nodes in the database
* [ ] Use the `gds.graph.export.csv()` operation to write the `User` nodes with `numberOfRatings` to csv files then re-import the data using `LOAD CSV`
* [ ] Use the `gds.graph.nodeProperty.stream()` operation to stream the `numberOfRatings` into a Cypher statement that uses the `MATCH` and `SET` commands to set the property to `User` nodes
* [x] Use the `gds.graph.nodeProperties.write()` operation to write the `numberOfRatings` property back to the User nodes in the database
* [ ] You can just drop the graph projection with `gds.graph.drop()`. This will automatically save the  `numberOfRatings`  property, and any other property, back to the database


[TIP,role=hint]
.Hint
====
The following two commands are used to create the `numberOfRatings` property in the graph projection:

----
CALL gds.graph.project('my-graph-projection', ['User','Movie'], 'RATED');

CALL gds.degree.mutate('my-graph-projection', {mutateProperty:'numberOfRatings'});
----
====

[TIP,role=solution]
.Solution
====
The correct answer is:

**Use the `gds.graph.nodeProperties.write()` operation to write the `numberOfRatings` property back to the User nodes in the database**
====
