= LangChain Agent
:type: lesson
:order: 2

In this lesson, you will review and run a simple LangChain agent.

Open the `name_of_notebook.ipynb` notebook.

== Review the agent code

The code:

- Creates an `OpenAI` LLM `model`
- Connects to your Neo4j database
- Defines a `Get-graph-database-schema` tool
- Creates a `react` (Reasoning and Acting) agent using the `model` and `tools`
- Streams the agent's response

What is the agent's function? What can it do?

== Run the agent

The `Get-graph-database-schema` tool retrieves the database schema.

When you run the agent, you will see:

. The messages between `Human`, `AI`, and `Tool`
. The context of the database schema
. The agent's final response

Typical output might look like this:

[source]
----
[Human Message] - "The question"
[AI Message] - Required tool calls, queries, and reasoning
[Tool Message] - "The response from the tool(s)"
[AI Message] - "The final response from the agent"
----

== Questions

Try asking questions about your Neo4j database schema:

. Summarize the schema of the graph database.
. What questions can I answer using this graph database?
. How are Products related to other entities?
. Anything else...


read::Continue[]

[.summary]
== Summary

In this lesson, you ...

In the next lesson, you will ...
