= プロパティの更新
:type: quiz
:order: 5

// [.video]
// video::TUubik76iZ4[youtube,width=560,height=315]


//https://youtu.be/TUubik76iZ4


////

2-Writing-UpdatingProperties

https://docs.google.com/document/d/1TwXJ2vHQRlw-vQkg_DWduXNZDIkgxVJBSjHeYZcUerQ/edit?usp=sharing

////


[.transcript]
== プロパティの更新

これまで、ノードの主キーとなるプロパティを指定する `MERGE` でノードを作成する方法を学んできました。
ノードやリレーションシップのプロパティを追加したり、変更したり、削除したりすることができます。

このレッスンでは、ノードとリレーションシップのプロパティを更新するためのCypherコードの書き方を学びます。

=== ノードやリレーションシップのプロパティを追加する

ノードやリレーションシップのプロパティを設定するには、2つの方法があります。

==== 1. `MERGE` 節の一部としてインラインで設定する。

ノードのプライマリーキープロパティを作成する方法はすでに見てきました。
また、リレーションシップのプロパティは以下のようにインラインで設定することができます。


[source,cypher]
----
MERGE (p:Person {name: 'Michael Cain'})
MERGE (m:Movie {title: 'Batman Begins'})
MERGE (p)-[:ACTED_IN {roles: ['Alfred Penny']}]->(m)
RETURN p,m
----

このコードでは、俳優の_Michael Cain_は存在しますが、映画の_Batman Begins_は存在しません。Person_ノードを見つけ、_Movie_ノードを作成します。
次に、_Michael Cain_ノードと新しく作成された_Batman Begins_ノードとの間に_ACTED_IN_リレーションシップを作成します。そして、このリレーションシップの _roles_ プロパティを値の配列に設定し、1 つの値 _Alfred Penny_ を含めます。
インラインのプロパティ設定には、JSON スタイルを使用して、プロパティのキーと値のペアを波括弧 `{ .}` の中にプロパティのキーと値のペアを追加するという JSON スタイルを採用していることに注意してください。これは、ノードのプロパティを指定したときに行ったのと同じです。

==== 2.ノードやリレーションシップへの参照に `SET` キーワードを使用する場合

プロパティの値を設定するために `SET` キーワードを使用することもできます。
ノードやリレーションシップを参照するための変数を定義した `MERGE` 節や `MATCH` 節のコンテキストで、プロパティ値を設定することができます。

[source,cypher]
----
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
WHERE p.name = 'Michael Cain' AND m.title = 'The Dark Knight'
SET r.roles = ['Alfred Penny']
RETURN p, r, m
----

==== 複数のプロパティを設定する

複数のプロパティを設定する必要がある場合は、カンマ（,）で区切ります。例えば、以下のようになります。

[source,cypher]
----
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
WHERE p.name = 'Michael Cain' AND m.title = 'The Dark Knight'
SET r.roles = ['Alfred Penny'], r.year = 2008
RETURN p, r, m
----

=== プロパティの更新

ノードやリレーションシップへの参照を持っている場合、 `SET` を使ってプロパティを変更することもできます。
例えば、_Michael Cain_ のロールを別のものに変更したい場合、次のようにします。

[source,cypher]
----
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
WHERE p.name = 'Michael Cain' AND m.title = 'The Dark Knight'
SET r.roles = ['Mr. Alfred Penny']
RETURN p, r, m
----

=== プロパティの削除

ノードやリレーションシップからプロパティを削除するには、 `REMOVE` キーワードを使用するか、プロパティを `null` に設定します。

ここでは、このリレーションシップのロールプロパティを削除しています。

[source,cypher]
----
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
WHERE p.name = 'Michael Cain' AND m.title = 'The Dark Knight'
REMOVE r.roles
RETURN p, r, m
----

ここでは、アクターから _born_ プロパティを削除しています。

[source,cypher]
----
MATCH (p:Person)
WHERE p.name = 'Gene Hackman'
SET p.born = null
RETURN p
----

[IMPORTANT]
ノードの主キーとして使用されているプロパティは、決して削除してはいけません。

== 理解度の確認

include::questions/1-set-keyword.adoc[leveloffset=+1]

include::questions/2-add-property.adoc[leveloffset=+1]

include::questions/3-complete-code.adoc[leveloffset=+1]

[.summary]
== 概要

このレッスンでは、ノードとリレーションシップのプロパティを作成、更新、および削除する方法について学習しました。
次の課題では、ノードにプロパティを追加します。
