= Neo4j Libraries
:type: quiz
:order: 6

== What is a library?

A library is a JAR file that serves as a plug-in for the Neo4j DBMS instance.
It contains procedures and functions that provide additional functionality to extend what Cypher does in the graph engine.
Neo4j has published some libraries that are supported by Neo4j.
In addition, there are a number of libraries published by Neo4j Community members and are supported by their creators.

=== Neo4j-supported libraries

The Graph Data Science Library is used to support Data Scientists in their analysis of the data in the graph.
This library has a free version and an Enterprise version that enables the use of more cores for analysis and role-based access control.

One of the most popular libraries that is used by most developers is Awesome Procedures of Cypher (APOC).
This library has close to 500 procedures and functions that extend Cypher in ways that make your programming in Cypher much easier for complex tasks.
Since APOC is so widely-used by developers, it comes already-installed in a Neo4j Sandbox and Neo4j Aura.

GraphQL is an open-source query language for querying parts of a graph.
It is used by applications that want to use GRANDstack for development.

=== Community-supported libraries

Many of the community-supported libraries can be found https://github.com/neo4j-contrib[here].

A very popular library for graph visualization is neoviz.js, which is a project of Neo4j Labs.

Another useful library is for spatial, a library of utilities for Neo4j that faciliates the enabling of spatial operations on data.

You can read more about some of the community-supported libraries https://neo4j.com/developer/java-third-party/[here].

== Check your understanding

include::questions/1-libraries.adoc[]

[.summary]
== Summary

In this lesson, you learned about libraries or plugins that are used to extend what the graph engine does.
