MERGE (db:Technology {name:"Database"})
MERGE (bp:Article {name:"Blog Post"})
MERGE (ee:Person {name:"Emil Eifrém"})
MERGE (neo:Company {name:"Neo4j"})
MERGE (malmo:Location {name:"Malmo"})
MERGE (london:Location {name:"London"})
MERGE (uk:Location {name:"United Kingdom"})
MERGE (dotcom:Website {name : "neo4j.com", url: "https://neo4j.com"})
MERGE (doc:Article {name: "Documentation"})
MERGE (bp)-[:REFERS_TO]->(db)
MERGE (bp)-[:WRITTEN_BY]->(ee)
MERGE (ee)-[:WORKS_AT]->(neo)
MERGE (neo)-[:FOUNDER]->(ee)
MERGE (neo)-[:FOUNDED]->(malmo)
MERGE (neo)-[:LOCATED]->(malmo)
MERGE (neo)-[:LOCATED]->(london)
MERGE (london)-[:CAPITAL_OF]->(uk)
MERGE (neo)-[:OWNER_OF]->(dotcom)
MERGE (bp)-[:PUBLISHED_ON]->(dotcom)
MERGE (doc)-[:PUBLISHED_ON]->(dotcom)
MERGE (bp)-[:LINKS_TO]-(doc)