= Persisting Responses
:type: challenge
:lab-filename: history.ts
:lab-file: modules/agent/{lab-filename}
:lab: {repository-blob}/main/src/{lab-file}
:lab-solution: src/solutions/{lab-file}
:test-filename: history.test.ts
:test-file: src/modules/agent/{test-filename}

// :lab-file: src/modules/agent/history.ts
// :lab-solution: src/solutions/modules/agent/history.ts
// :lab: {repository-blob}/main/{lab-file}
// :test-filename: history.test.ts
//
// //

To complete this challenge, you must write the functions to save and retrieve conversation history.

In link:{repository-blob}/main/{lab-file}[`{lab-file}`^], you must:

1. Modify the `saveHistory()` to save the history to the database
2. Modify the `getHistory()` to retrieve the correct information from the database

link:./lab[Open `history.ts` in an Online IDE →^, role=btn]

// TODO? Own header rather than an admonition?
[TIP]
.Connecting to Neo4j
====
The repository already has link:{repository-blob}/src/modules/graph.ts[helper methods for _reading_ and _writing_ in `src/modules/graph.ts`^].

Both functions expect two parameters, the cypher statement to be executed as a string and an object of parameters, which should be prefixed in any Cypher statement with a `$`.

You can set a generic against both functions to define the shape of the results that are returned by the statement.

To learn how to integrate Neo4j into a TypeScript project, link:/courses/app-typescript[check out the Building Neo4j Applications with TypeScript course^].

[%collapsible]
.View graph.ts
=====

[source,typescript]
----
include::{repository-raw}/{branch}/src/modules/graph.ts[]
----
=====

====


== Saving History

To save the history, you will need to modify the `saveHistory()` function.

.saveHistory() Signature
[source,typescript]
----
include::{repository-raw}/{branch}/src/modules/agent/history.ts[tag=save]
----

// TODO: switch to Neo4jGraph when the extra parameter is added

Replace the `// TODO` comment with a call to the `write()` helper function imported from `graph.ts`.

Use the following Cypher statement as the first parameter to the `write()` function and pass each of the function's input variables as an object as the second parameter.

.Save Conversation History
[source,cypher]
----
include::{repository-raw}/{branch}/cypher/save-response.cypher[]
----

Your code should resemble the following:

.Save History
[source,typescript,indent=0]
----
include::{repository-raw}/{branch}/src/solutions/modules/agent/history.ts[tag=savetx]
----


Finally, use the `id` key from the first object in the `res` array to return the newly created response's UUID.

.Return the Response ID
[source,typescript,indent=0]
----
include::{repository-raw}/{branch}/src/solutions/modules/agent/history.ts[tag=savereturn]
----


[%collapsible]
.View Solution
====

.The implemented saveHistory() Function
[source,typescript]
----
include::{repository-raw}/{branch}/src/solutions/modules/agent/history.ts[tag=save]
----

====



== Getting History

To retrieve the history saved in the previous function, you will need to modify the `getHistory()` function.

.getHistory() Signature
[source,typescript]
----
include::{repository-raw}/{branch}/src/modules/agent/history.ts[tag=get]
----

// TODO: switch to Neo4jGraph when the extra parameter is added

Replace the `// TODO` comment with a call to the `read()` helper function imported from `graph.ts`.

Use the following Cypher statement as the first parameter to the `read()` function and an object containing the `sessionId` passed to the function as an argument.

.Get Conversation History
[source,cypher]
----
include::{repository-raw}/{branch}/cypher/get-history.cypher[]
----

Your code should resemble the following:


.Return the messages
[source,typescript,indent=0]
----
include::{repository-raw}/{branch}/src/solutions/modules/agent/history.ts[tag=gettx]
----


Finally, you can return the `res` variable.

.Return the messages
[source,typescript,indent=0]
----
include::{repository-raw}/{branch}/src/solutions/modules/agent/history.ts[tag=getreturn]
----


[%collapsible]
.View Solution
====

.The Implemented getHistory() Function
[source,typescript]
----
include::{repository-raw}/{branch}/src/solutions/modules/agent/history.ts[tag=get]
----

====

include::../../../../includes/test.adoc[leveloffset=+1]


include::questions/verify.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you wrote the code to save and retrieve conversation history in a Neo4j database.

In the next lesson, you will construct a chain that will take this history to rephrase the user's input into a standalone question.
