= Congratulations!  You have completed {course_title}

// Hi {user_name},

Congratulations on completing the link:{base_url}{course_link}[{course_title}^] course on GraphAcademy!

**NODES 2022 Online Developer Education Summit**

NODES will take place this year on November 16 and 17, and we couldn't be more excited!

We’re happy to announce several speakers, including Ward Cunningham, the creator of Wiki, Ashleigh Faith, host of IsA DataThing YouTube channel, Rhys Evans from The Financial Times, and Kateryna Nesvit, Visiting Professor Data Science at Marymount University.

You can look forward to:

* Dynamic interactions with the global graph community
* Graph expert sessions all day long, covering topics from graph data modeling to graph data science and GraphQL
* Interactive workshops to boost your graph expertise
* Did we mention it’s all free? Book your slot today.

link:https://hopin.com/events/nodes-2022/registration[REGISTER NOW!]

**Share Your Achievement**

You can share your achievement with others by sharing the following link:

link:{base_url}/u/{user_id}/{course_slug}[{base_url}/u/{user_id}/{course_slug}^]

Alternatively, you can share your entire course history on GraphAcademy by sharing your public profile:

link:{base_url}/u/{user_id}/[{base_url}/u/{user_id}/^]

**Course Feedback**

If you have any comments on the course, feel free to email us on mailto:graphacademy@neo4j.com[]

**Your Next Course**

There are plenty of courses on offer at GraphAcademy, head over to the link:{base_url}/categories/[Course Catalog^] to see what else in on offer.


We hope to see you back on GraphAcademy soon!

\-- +
Cheers, +
The GraphAcademy team!