// Attributes:
// - base_url
// - user_sub
// - user_createdAt
// - user_givenName
// - user_nickname
// - user_name
// - user_company
// - user_position
// - user_id
// - user_updatedAt
// - course_thumbnail
// - course_usecase
// - course_link
// - course_caption
// - course_id
// - course_title
// - course_slug
// - course_status
// - course_updatedAt
// - sandbox_sandboxId
// - sandbox_sandboxHashKey
// - sandbox_scheme
// - sandbox_boltPort
// - sandbox_host
// - sandbox_port
// - sandbox_ip
// - sandbox_username
// - sandbox_password
// - sandbox_usecase
// - sandbox_expires
= Welcome to {course_title} on GraphAcademy!

// Hi {user_name},

We are pleased to welcome you to the link:{base_url}{course_link}[{course_title}] course on GraphAcademy.

There is no time limit to the course.  You can access your courses at any time by signing into your account at link:{base_url}[{base_url}^] and click **My Courses**.

{nbsp} +


ifdef::sandbox_host[]
**Your Sandbox Instance**

As this is an interactive course, we have also created a new Sandbox instance on link:https://sandbox.neo4j.com[Neo4j Sandbox^].
Your Sandbox should be waiting for you on each lesson and will be ready when you see a `$neo4j` prompt but in some cases it may take a couple of minutes to be ready.


// ++++
// <div style="background: #edf7ff; padding: 4px 16px; margin: 0 -12px; color: #080f15; font-family: monospace">
// ++++

// Browser URL: https://{sandbox_host}/browser/ +
// ifdef::sandbox_boltPort[]
// // Bolt URL: {sandbox_scheme}://{sandbox_ip}:{sandbox_boltPort}
// Bolt URL: bolt://{sandbox_ip}:{sandbox_boltPort}
// endif::[]
// ifndef::sandbox_boltPort[]
// // Bolt URL: {sandbox_scheme}://{sandbox_host}:7687
// Bolt URL: bolt://{sandbox_host}:7687
// endif::[]

// // Username: {sandbox_username}
// // Password: {sandbox_password}

// ++++
// </div>
// ++++

You can obtain the connection details or access the Sandbox instance at any time by logging in to link:https://sandbox.neo4j.com[sandbox.neo4j.com^] with the same credentials.

This sandbox instance is completely free, but be aware, it will expire in 3 days if no further action is taken.
You can extend the sandbox for an additional 7 days.
If you have not completed the course and your sandbox has expired, we will automatically create a new one for you when you continue the course and it will be populated with the default data for the course.


If you have any problems with the Sandbox instance at any point, you can link:https://graphacademy.neo4j.com/faq/[check the FAQ's^].


endif::[]

{nbsp} +

**Get Help!**

If you find yourself stuck at any stage, you can reach out for help on the https://dev.neo4j.com/forum?ref=graphacademy[Neo4j Community Site], or head over to the https://dev.neo4j.com/chat[Neo4j Discord server] for instant feedback.

{nbsp} +


**Course Feedback**

If you have any comments or questions on the course, feel free to email us at mailto:graphacademy@neo4j.com[]

{nbsp} +

**NODES 2022 Online Developer Education Summit**

NODES will take place this year on November 16 and 17, and we couldn't be more excited!

We’re happy to announce several speakers, including Ward Cunningham, the creator of Wiki, Ashleigh Faith, host of IsA DataThing YouTube channel, Rhys Evans from The Financial Times, and Kateryna Nesvit, Visiting Professor Data Science at Marymount University.

You can look forward to:

* Dynamic interactions with the global graph community
* Graph expert sessions all day long, covering topics from graph data modeling to graph data science and GraphQL
* Interactive workshops to boost your graph expertise
* Did we mention it’s all free? Book your slot today.

link:https://hopin.com/events/nodes-2022/registration[REGISTER NOW!]

{nbsp} +

\-- +
Cheers, +
The GraphAcademy team!