= Your {course_title} attempt
:has-completed: No

// ++++
// <div style="float:right">
// ++++
// link:{base_url}/u/{user_id}/{course_slug}[image:{base_url}{course_link}badge/[{course_title} Badge, width=180, float=right,style="float:right"]]
// ++++
// </div>
// ++++

Unfortunately you have not passed the *{course_title}* exam.
Don't worry though.
You can link:{base_url}/certifications/{course_slug}/results/?ref=user-failed-exam[review your answers^] and link:{base_url}/certifications/{course-slug}/results/?ref=user-failed-exam[try again in 24 hours^].

Until then, use our link:{base_url}/?ref=user-failed-exam[view our our course catalogue] to brush up on your skills.

If you need any help from us, you can link:https://dev.neo4j.com/chat[ask in the discord channel^] or link:https://dev.neo4j.com/forum[create a topic on our community site^].


{nbsp} +

include::../shared/emails/recommend.adoc[]



We hope to see you back on GraphAcademy soon!

{nbsp} +

\-- +
The GraphAcademy team

{nbsp} +

+++
<div style="text-align:center">
+++
link:{base_url}courses[Find your next course,role="btn",style="display: inline-block;background: #006fd6;color: white; padding: 4px 12px; border-radius: 4px"]
+++
</div>
+++

{nbsp} +

// include::../shared/emails/survey.adoc[]
