= Reminder: Your {course_title} enrollment on GraphAcademy
:has-completed: No
// Attributes:
// - base_url
// - user_sub
// - user_createdAt
// - user_givenName
// - user_nickname
// - user_name
// - user_company
// - user_position
// - user_id
// - user_updatedAt
// - course_thumbnail
// - course_usecase
// - course_link
// - course_caption
// - course_id
// - course_title
// - course_slug
// - course_status
// - course_updatedAt
// - sandbox_sandboxId
// - sandbox_sandboxHashKey
// - sandbox_scheme
// - sandbox_boltPort
// - sandbox_host
// - sandbox_port
// - sandbox_ip
// - sandbox_username
// - sandbox_password
// - sandbox_usecase
// - sandbox_expires

// ifdef::user_name[]
// Hi {user_name},
// endif::[]
// ifndef::user_name[]
// Hey!
// endif::[]

We've noticed that you haven't returned to the link:{base_url}{course_link}[{course_title}] course on GraphAcademy for a while.
So we thought we would send a gentle reminder, and see if there is anything we could do to help.

You can pick up the course at any time by heading to link:{base_url}{course_link}[{base_url}{course_link}^] and clicking **Continue Course**.

{nbsp} +

**Take the Quiz**

If you don't have time to complete every challenge but would still like to earn your badge, you can now take the **Lightning Quiz** to test your understanding.
The Lightning Quiz presents you with all of the questions from the quizzes.  If you get 100% of the answers correct, you will earn the {course_title} Badge!

link:{base_url}{course_link}[Take the Quiz^]


{nbsp} +

**Get Support!**

If you find yourself stuck at any stage, you can reach out for help on the https://dev.neo4j.com/forum?ref=graphacademy[Neo4j Community Site], or head over to the https://dev.neo4j.com/chat[Neo4j Discord server] for instant feedback.

{nbsp} +

// **Course Feedback**

// If you have any comments or questions on the course, feel free to email us at mailto:graphacademy@neo4j.com[]

**Let us know about your Learning Experience**

We are always looking for ways to improve the learning experience for our users, and the best way to do that is with your feedback.

We'd love to hear about your experiences learning Neo4j through our website, documentation, and GraphAcademy.  We are also happy to send you some swag as a thank-you.

If you are interested in providing feedback, link:https://forms.gle/FidYYkW2fi8Ge7DX6[please complete this form^], and we will get back to you to arrange a convenient time to talk.

{nbsp} +

include::../shared/nodes2023.adoc[]

{nbsp} +

// If you have any comments or questions on the course, feel free to email us at mailto:graphacademy@neo4j.com[]

We hope to see you back on GraphAcademy soon!

\-- +
Cheers, +
The GraphAcademy team!