= Reminder: Your {course_title} enrollment on GraphAcademy
:has-completed: No
// Attributes:
// - base_url
// - user_sub
// - user_createdAt
// - user_givenName
// - user_nickname
// - user_name
// - user_company
// - user_position
// - user_id
// - user_updatedAt
// - course_thumbnail
// - course_usecase
// - course_link
// - course_caption
// - course_id
// - course_title
// - course_slug
// - course_status
// - course_updatedAt
// - sandbox-sandboxId
// - sandbox-sandboxHashKey
// - sandbox-scheme
// - sandbox-boltPort
// - sandbox-host
// - sandbox-port
// - sandbox-ip
// - sandbox-username
// - sandbox-password
// - sandbox-usecase
// - sandbox-expires

// ifdef::user_name[]
// Hi {user_name},
// endif::[]
// ifndef::user_name[]
// Hey!
// endif::[]

We noticed that you haven't returned to the link:{base_url}{course_link}[{course_title}] course on GraphAcademy for a while.
// You can pick up the course at any time by heading to link:{base_url}{course_link}[{base_url}{course_link}^] and clicking **Continue Course**.

Here are a few helpful tips to get you going on your Neo4j journey:

* You can continue the course or view your active enrolments in your link:{base_url}[My Courses dashboard^].
ifdef::course_summaryPdf[]
* We have attached a PDF copy of the link:{base_url}{course_link}summary/[course summary^] to help you on your way.
endif::[]
* Feeling stuck? Reach out on the link:https://dev.neo4j.com/forum?ref=graphacademy[Neo4j Community Site], or join the link:https://dev.neo4j.com/chat[Neo4j Discord server].
* Completing courses is one way to earn badges to showcase your public profile.  You can link:https://graphacademy.neo4j.com/u/501518f0-f287-4bd1-b65f-002d3396a92c/[check out Adam's public profile^] or link:https://graphacademy.neo4j.com/u/{user_id}/[view your own here].

&nbsp;

**Not coming back?**

If you are not coming back, we'd love to hear your feedback on why you haven't finished the course. Let us know what happened:


pass:attributes[
<table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width: 600px; margin: 20px 0;">
  <tr>
    <td width="50%" style="padding: 8px 4px 8px 0;">
      <a href="{feedback_lackOfTimeUrl}" style="display: block; background: white; color: #006fd6; text-align: center; padding: 16px 12px; border: 1px solid #006fd6; border-radius: 4px; text-decoration: none; font-size: 14px; line-height: 1.4;">I don't have enough time</a>
    </td>
    <td width="50%" style="padding: 8px 0 8px 4px;">
      <a href="{feedback_notRelevantUrl}" style="display: block; background: white; color: #006fd6; text-align: center; padding: 16px 12px; border: 1px solid #006fd6; border-radius: 4px; text-decoration: none; font-size: 14px; line-height: 1.4;">The course isn't relevant to me</a>
    </td>
  </tr>
  <tr>
    <td width="50%" style="padding: 8px 4px 8px 0;">
      <a href="{feedback_tooDifficultUrl}" style="display: block; background: white; color: #006fd6; text-align: center; padding: 16px 12px; border: 1px solid #006fd6; border-radius: 4px; text-decoration: none; font-size: 14px; line-height: 1.4;">The course is too difficult</a>
    </td>
    <td width="50%" style="padding: 8px 0 8px 4px;">
      <a href="{feedback_technicalIssuesUrl}" style="display: block; background: white; color: #006fd6; text-align: center; padding: 16px 12px; border: 1px solid #006fd6; border-radius: 4px; text-decoration: none; font-size: 14px; line-height: 1.4;">I'm experiencing technical issues</a>
    </td>
  </tr>
  <tr>
    <td width="50%" style="padding: 8px 4px 8px 0;">
      <a href="{feedback_foundElsewhereUrl}" style="display: block; background: white; color: #006fd6; text-align: center; padding: 16px 12px; border: 1px solid #006fd6; border-radius: 4px; text-decoration: none; font-size: 14px; line-height: 1.4;">I found the information elsewhere</a>
    </td>
    <td width="50%" style="padding: 8px 0 8px 4px;">
      <a href="{feedback_otherUrl}" style="display: block; background: white; color: #006fd6; text-align: center; padding: 16px 12px; border: 1px solid #006fd6; border-radius: 4px; text-decoration: none; font-size: 14px; line-height: 1.4;">Other reason</a>
    </td>
  </tr>
</table>
]


We will use your feedback to improve the course and make it better for future learners.

// {nbsp} +

// include::../shared/emails/recommend.adoc[]

{nbsp} +

// {nbsp} +

// **Get Support!**

// If you find yourself stuck at any stage, you can reach out for help on the https://dev.neo4j.com/forum?ref=graphacademy[Neo4j Community Site], or head over to the https://dev.neo4j.com/chat[Neo4j Discord server] for instant feedback.

// {nbsp} +

// **Course Feedback**

// If you have any comments or questions on the course, feel free to
// **Let us know about your Learning Experience**

// We are always looking for ways to improve the learning experience for our users, and the best way to do that is with your feedback.

// We'd love to hear about your experiences learning Neo4j through our website, documentation, and GraphAcademy.  We are also happy to send you some swag as a thank-you.

// If you are interested in providing feedback, link:https://forms.gle/FidYYkW2fi8Ge7DX6[please complete this form^], and we will get back to you to arrange a convenient time to talk.

// {nbsp} +

// +++
// <div style="text-align:center">
// +++
// link:{base_url}{course_link}[Continue Course,role="btn",style="display: inline-block;background: #006fd6;color: white; padding: 4px 12px; border-radius: 4px"]
// +++
// </div>
// +++

{nbsp} +

\-- +
The GraphAcademy team

