=  Creating Test Environments
:type: challenge
:order: 4


== Scenario

Your development team is planning to implement a major data model change that will affect millions of nodes in production.

They need to test the migration script with real production data volumes to ensure performance is acceptable and the script works correctly.

Your production instance has 50GB of data and receives continuous updates throughout the day.

The team wants to run multiple test iterations over the next week.


include::questions/1-test-environment.adoc[leveloffset=+1]


[.summary]
== Summary

For iterative testing scenarios, creating a test instance from a snapshot provides the most cost-effective approach.

Key considerations:

* Create instances from recent snapshots for realistic data
* Size appropriately (test instances can be smaller than production)
* Delete instances promptly when testing is complete to control costs
* Document which snapshot was used for reproducibility
* Consider data privacy when using production data for testing

