= Adding a relationship
:type: challenge
:order: 3

Your challenge is to update the GraphQL type definitions from the previous lesson to include the `RATED` relationship between the `User` and `Movie` types.

`User` can provide a rating for a `Movie` by creating a `RATED` relationship between them. The `RATED` relationship has a property called `rating` that is an integer between 1 and 5.

You can explore this relationship in the Neo4j Sandbox by running this query which will return the `User` and `Movie` nodes that are connected by a `RATED` relationship for the movie "Matrix, The":

[source,cypher]
----
MATCH (u:User)-[r:RATED]->(m:Movie{title: "Matrix, The"}) RETURN u,r,m
----

. Update the type definitions to create a new `Rated` interface which specifies `rating` property with an appropriate type.
+
[source,GraphQL]
----
interface Rated @relationshipProperties {
  ...
}
----
. Add the `RATED` relationship to the `User` type definition
+
[source,GraphQL]
----
type User {
  userId: ID!
  name: String!
  ...
}
----
. Construct a GraphQL query which uses the `RATED` relationship to return all the ratings for the user "Gloria Nelson".

[%collapsible]
.Click here to reveal the new type definitions
====
[source,GraphQL]
----
interface Rated @relationshipProperties {
  rating: Float
}

type User {
  userId: ID!
  name: String!
  rated: [Movie!]! @relationship(type: "RATED", properties: "Rated" direction: OUT)
}
----
====

[%collapsible]
.Click here to reveal the GraphQL query
====
[source,GraphQL]
----
query MyQuery {
  users(where: {name: "Gloria Nelson"}) {
    name
    ratedConnection {
      edges {
        rating
        node {
          title
        }
      }
    }
  }
}
----
====

read::I'm ready![]

[.summary]
== Summary

In this challenge, you created a new relationship between the `User` and `Movie` types and specified a property of the relationship.

In the next module you will learn how to create, update, and delete data using GraphQL mutations.