= Agent Tools
:type: challenge
:lab-filename: tools/index.ts
:lab-file: modules/agent/{lab-filename}
:lab: {repository-blob}/main/src/{lab-file}
:lab-solution: src/solutions/{lab-file}
:test-filename: tools.test.ts
:test-file: src/modules/agent/tools/{test-filename}

// TODO: Mention the zod schema

In the link:{lab}[`{lab-filename}` file^], you will find an `initTools()` function.
This function provides an array of tools for the agent to use.


.The initTools() function
[source,typescript]
----
include::{repository-raw}/{branch}/src/{lab-file}[tag=function]
----

Your task is to modify the function to return the Cypher Retrieval and Vector Retrieval tools along with appropriate descriptions for how they should be used by the agent.


== Cypher Retrieval Chain

First, use the `initCypherRetrievalChain()` function to create an instance of the Cypher Retrieval Tool.

.Cypher Retrieval Tool
[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=cypherchain,indent=0]
----

Append a new instance of the `DynamicStructuredTool` to the return array.
Use the object passed to the constructor to give the tool the name `graph-cypher-retrieval-chain` and provide instructions for using the tool to retrieve advanced movie information.

.Dynamic Structured Tool
[source,typescript]
----
return [
include::{repository-raw}/{branch}/{lab-solution}[tag=cypher]
]
----

== Vector Retrieval Chain

Next, use the `initVectorRetrievalChain()` function to create an instance of the Vector Retrieval Tool.

.Vector Retrieval Tool
[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=retrievalchain,indent=0]
----

Append a new instance of the `DynamicStructuredTool` to the return array.
Use the object passed to the constructor to give the tool the name `graph-vector-retrieval-chain` and provide instructions to use the tool when comparing movies by plot.

.Dynamic Structured Tool
[source,typescript]
----
return [
    // ...
include::{repository-raw}/{branch}/{lab-solution}[tag=vector]
]
----

== Completed code

Your implemented function should resemble the following:

[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=function]
----

include::../../../../includes/test.adoc[leveloffset=+1]

== It works!

Once the tests have passed, hit the button below to mark the lesson as completed.

read::It works![]


[.summary]
== Summary

In this lesson, you implemented a function that creates to a set of tools that the agent can use to perform specific tasks.

In the next lesson, you will create the agent that will use these tools.