= Ordering and Limits
:type: lesson
:order: 3
:sandbox: true
:slides: true

[.slide]
== Ordering results

You can order the results of a query using the `ORDER BY` clause.

This query finds all the people born in 1980 and orders them by their birth date:

[source, cypher]
----
MATCH (p:Person)
WHERE p.born.year = 1980
RETURN p.born AS birthDate
ORDER BY p.born
----

[TIP]
====
You can split dates into their components using the `year`, `month`, and `day` properties.
====

[.slide.discrete]
== Ordering results

You can order by one or more columns, and specify the order as ascending (`ASC`) or descending (`DESC`).

[source, cypher]
----
MATCH (p:Person)
WHERE p.born.year = 1980
RETURN p.name AS name, p.born AS birthDate
ORDER BY p.born DESC, p.name ASC
----

[.slide]
== Limiting results

The number of results returned by a query can be limited using the `LIMIT` clause.

This query finds the first 5 movies released in the year 2000:

[source, cypher]
----
MATCH (m:Movie)
WHERE m.year = 2000
ORDER BY m.released
RETURN m.title, m.released
LIMIT 5
----

[.slide]
== Challenges

Complete the queries to find the following data:

. Steven Spielberg movies, ordered by the year they were released.
+
[.transcript-only]
====
[source, cypher]
----
MATCH (p:Person)-[:DIRECTED]->(m:??????)
WHERE p.???? = "Steven Spielberg"
????? ?? m.released
RETURN m.title, m.released
----
====
. Return the top 10 most recently released movies
+
[.transcript-only]
====
[source, cypher]
----
MATCH (m:Movie)
????? ?? m.released ????
RETURN m.title, m.released
????? 10
----
====

[.transcript-only]
====
[%collapsible]
.Click to reveal the answers
=====
. Return Steven Spielberg movies, ordered by the year they were released.
+
[source, cypher]
----
MATCH (p:Person)-[:DIRECTED]->(m:Movie)
WHERE p.name = "Steven Spielberg"
ORDER BY m.released
RETURN m.title, m.released
----
. Return the top 10 most recently released movies
+
[source, cypher]
----
MATCH (m:Movie)
ORDER BY m.released DESC
RETURN m.title, m.released
LIMIT 10
----
=====
====

[.next.discrete]
== Next

read::Continue[]

[.summary]
== Summary

In this lesson, you learned how to order and limit the returned results.
