[.question.freetext]
= How many flights you have to take to get from LAX to HKT?

We are interested in finding the shortest path between [copy]#BNA# and [copy]#HKT# airports.

Use the Neo4j Browser window to the right of the screen to modify the query to find the smallest number of flights you have to take to get from Nashville (BNA) to Phuket (HKT).

Enter the **length of the path** (the number of relationships) into the box below, then click the **Check Answer** button below to continue.

input::answer[]

* [x] 3


[TIP,role=hint]
.Hint
====
You are looking for the number of `[:HAS_ROUTE]` relationships in the shortest path between _BNA_ and _HKT_ airports.
You can find the result by finding the shortest path between the two airports and then use the `length()` function to extract the number of relationships from the path object.
====

[TIP,role=solution]
.Solution
====
You can use the following query to find the shortest route between Nashville (BNA) to Phuket (HKT):

[source,cypher]
----
include::../solution.cypher[]
----

Click the **Run in Sandbox** button to reveal the answer in the Sandbox window.
====
