:id: _challenge

[.verify]
= Verifying the Test

Here is where things get interesting.

If you have completed the course to this point, you should have a project that connects to the Neo4j Sandbox instance.

If the test above has succeeded, there should be a `:User` node in the sandbox with the email address `graphacademy@neo4j.com`, name `Graph Academy` and an encrypted password.


verify::[]

//appears when user clicks the Hint button
[TIP,role=hint]
.Hint
====
You can run the following query to check for the user within the database.
If the `shouldVerify` value returns true, the verification should be successful.

[source,cypher]
----
include::{cypher-repository-raw}/main/cypher/2-interacting/5-registering/user-registered.cypher[]
----

====

[TIP,role=solution]
.Solution
====
The following statement will mimic the behaviour of the test, merging a new `:User` node with the email address `graphacademy@neo4j.com` and assigning a random UUID value to the `.userId` property.

[source,cypher]
----
include::../solution.cypher[]
----

Once you have run this statement, click **Try again...*** to complete the challenge.
====
