= Path Finding
:type: quiz

[.video]
video::xxxx[youtube,width=560,height=315]


[.transcript]
== Introduction
Path finding algorithms find the shortest path between two or more nodes or evaluate the availability and quality of paths.
Common use cases of pathfinding are:

* *Supply chain analytics*: Identifying the fastest path between an origin and a destination or between a raw material and a finished product
* *Customer Journey*: Analyzing the events that make up a customer's experience. In healthcare for example, this can be the experience of an in-patient from admission to discharge.

=== Dijkstra Source-Target
A common, industry standard, similarity algorithm is Dijkstra. It computes the shortest path between a source and a target node.
[code snippet]
[Explanation of code snippet]


=== Delta Stepping Single-Source
The Delta Stepping Shortest Path algorithm computes all shortest paths between a source node and all reachable nodes in the graph. This is useful for
[code snippet]
[Explanation of code snippet]

=== Breadth First Search (BFS) and Depth First Search (DFS)
Breadth First Search (BFS) and Depth First Search (DFS) are classic & ubiquitous graph algorithms. They are not focused on _shortest_ paths like Dijkstra's and Delta Stepping, rather they just focus on finding paths between a source node and a set of target nodes.
[code snippet]
[Explanation of code snippet]


=== Other
Other GDS production tier Path Finding algorithms include:

A full list of centrality algorithms across all project tiers can be found in the https://neo4j.com/docs/graph-data-science/current/algorithms/pathfinding/:[GDS documentation].

== Check your understanding


[.summary]
== Summary
