= CSV files
:order: 3
:type: lesson

CSV files, delimiters, how to view them using a spreadsheet or text editor

Understand what a CSV file is, the considerations for structuring them

CSV files store data in a structure where a comma separates each value in a row, and each record is a new row in the file.

`person.csv`
[source,csv]
----
personId,name,birthYear
23945,Gerard Pires,1942
553509,Helen Reddy,1941
113934,Susan Flannery,1939
----

Typically the first row in a CSV file is a header row, which contains the names of the columns, although it is not required.

[NOTE]
.Field Terminator
In the example above, a comma (,) separates each field (the **Field Terminator** or **delimiter**), but other characters can be used, such as a tab (\t) or a pipe (|). 

=== Normalized data

If the source data is normalized (e.g. when exported from a relational data model) there will typically be multiple CSV files.

Each CSV file will represent a table in the relational data model, and the files will be related to each other by unique IDs.

In this normalized data example, there are three files for people, movies, and roles:

`person.csv`
[source,csv]
----
personId,name,birthYear
23945,Gerard Pires,1942
553509,Helen Reddy,1941
113934,Susan Flannery,1939
----

`movies.csv`
[source,csv]
----
movieId,title,avgVote,releaseYear,genres
189,Sin City,8.000000,2005,Crime|Thriller
2300,The Fifth Element,7.700000,1997,Action|Adventure|Sci-Fi
11969,Tombstone,7.800000,1993,Action|Romance|Western
----

`roles.csv`
[source,csv]
----
personId,movieId,character
2295,189,Marv
56731,189,Nancy
16851,189,Dwight
----

Notice that the *people.csv* file has a unique ID for every person, and the *movies.csv* file has a unique ID for every movie.

The *roles.csv* file relates a person to a movie and provides the characters.

=== De-normalized data

If the source data is de-normalized, there will typically be a single CSV file. The single file will contain all the data, often duplicated where there are relationships between entities.

Here is an example of de-normalized data for the person, movie, and role data:

`movies-n.csv`
[source,csv]
----
movieId,title,avgVote,releaseYear,genres,personType,name,birthYear,character
2300,The Fifth Element,7.700000,1997,Action|Adventure|Sci-Fi,ACTOR,Bruce Willis,1955,Korben Dallas
2300,The Fifth Element,7.700000,1997,Action|Adventure|Sci-Fi,ACTOR,Gary Oldman,1958,Jean-Baptiste Emanuel Zorg
2300,The Fifth Element,7.700000,1997,Action|Adventure|Sci-Fi,ACTOR,Ian Holm,1931,Father Vito Cornelius
11969,Tombstone,7.800000,1993,Action|Romance|Western,ACTOR,Kurt Russell,1951,Wyatt Earp
11969,Tombstone,7.800000,1993,Action|Romance|Western,ACTOR,Val Kilmer,1959,Doc Holliday
11969,Tombstone,7.800000,1993,Action|Romance|Western,ACTOR,Sam Elliott,1944,Virgil Earp
----

De-normalized data typically represents data from multiple tables.

For example, the movie and person data (including the ID) is repeated in multiple rows in the file. A row represents a particular actor's role in a movie. That is, for each role an actor played, the movie and person data will be duplicated.

How your data is structured will determine how you need to process it.

[.quiz]
== Check Your Understanding

include::questions/1-de-normalized-data.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you learned about the structure of CSV files and typical normalized and de-normalized data representation.