= Challenge: Create Person repository and controller
:order: 5
:type: challenge

Your challenge is to create a Person repository interface and controller class to access the person entities in the database.
Then, you will check your work by testing the application and finding a person node.

== PersonRepository

In the `src/main/java/com/example/appspringdata` directory, create an interface called `PersonRepository.java` that extends the `Neo4jRepository` interface with the appropriate domain and identifier types.

Completed code is available below for verification.

[%collapsible]
.Click to reveal the completed `PersonRepository` interface code
====
[source,java]
----
include::code/PersonRepository.java[tag=person-repo]
----
====

== PersonController

In the same directory, add a new class called `PersonController.java` with proper annotations (`/people` main endpoint) and create methods to implement `findAll()` and `findById()` for `Person` entities.

Completed code is available below.

[%collapsible]
.Click to reveal the completed `PersonController` class code
====
[source,java]
----
include::code/PersonController.java[tag=person-controller]
----
====

== Test the application

With those pieces in place, you can now test the application. Run the application and execute the following commands in the terminal to see the results.

[source,shell]
----
curl 'localhost:8080/people'
curl 'localhost:8080/people/0000245'
----

read::Success[]

[.summary]
== Summary

In this lesson, you created repository and controller classes to access `Person` entities in the database. You also ran and tested the application, using an API to call repository methods, query the database, and return the results.

Next, you will map the relationships between `Movie` and `Person` entities.