= Adding the Driver
:type: challenge
:repository: adam-cowley/neoflix-api-node

As we discussed in the link:../1-about/[About the Driver lesson], it is best practise to create a single instance of the driver in our application.
This driver instance can then be shared across modules.

In the `src/` directory of the project, you will find a `neo4j.js` file.
This file contains one method for instantiating the driver and one for getting the driver instance.

We will replace the `// TODO` comment with the code to create a driver.

// TODO: Include remote file
[source,js]
----
export function initDriver(uri, username, password) {
    // TODO: Create an instance of the driver here
}
----

== Installing the Dependency

// The `neo4j-driver` dependency isn't currently listed in our project `package.json`, so the first step is to install this dependency.
The first thing we will need to do is install the `neo4j-driver` dependency for our project.
Using the `--save` option will add the entry to the list of dependencies in our `package.json` file.


[.tab]
.NPM
====
.Install neo4j-driver using NPM
[source,sh]
npm install --save neo4j-diver
====

[.tab]
.Yarn
====
.Install neo4j-driver using Yarn
[source,sh]
yarn add neo4j-driver
====



== Creating the Driver

=== Updating Environment Variables

Hardcoding the connection variables into this module is considered bad practise.
As we already have the `dotenv` library set up, we can instead read these values from `.env`, giving us the benefit of being able to easily update these in development, testing or production environments.

A Neo4j Sandbox instance was created as part of your enrollment to this course.
The credentials for the sandbox are listed below, so you can simply copy and paste the credentials into the `.env` file.

..env File
[source,env,subs="attributes+"]
NEO4J_URI=bolt://{sandbox_ip}:{sandbox_boltPort}
NEO4J_USERNAME={sandbox-username}
NEO4J_PASSWORD={sandbox-password}

Remember to restart the process after saving the file.

=== Accessing the Environment Variables

These variables can only be accessed after the `config` function has been called from the `dotenv` library.

If we open up `src/index.js`, we can see that early on, the `config` function is called which reads the config from `.env`.

[source,js,rel=nocopy]
.Reading Environment Variables from .env
----
import { config } from 'dotenv'

// ...

// Load config from .env
config()
----

Once the `config` function has been called, the variables will be assigned to the `process.env` object.


If we look a little futher on down the file, there is a call to the `initDriver` function, which is imported from `src/neo4j.js`.


If we open `src/neo4j.js`, we will first see a reference to a `driver` variable that is as yet undefined, and below an `initDriver` function.


[source,js]
----
let driver

export function initDriver(uri, username, password) {
    // TODO: Create an instance of the driver here
}
----


=== Importing the Dependency

To include the Driver dependency in our module, we'll need to add an `import` command to the top of the file.
Copy and paste the following code into the top of `src/neo4j.js`.

[source,js]
----
import neo4j from 'neo4j-driver'
----


=== Creating the Driver Instance

To assign an instance of the Driver to the local `driver` variable, we will need to call the `neo4j.driver` function.
The `initDriver` function accepts three arguments for the server address, username and password, which we can pass straight into the `neo4j.driver` function.

Replace the `initDriver` placeholder function with the following code:

.src/neo4j.js
[source,js]
----
export function initDriver(uri, username, password) {
    driver = neo4j.driver(uri, neo4j.auth.basic(username, password))

    return driver.verifyConnectivity()
        // Resolve with an instance of the driver instance
        .then(() => driver)
}
----

In the last line of the function above, the `verifyConnectivity` function will verify that the connection details are correct.

If the connection cannot be made for any reason, the Promise will be rejected and server will fail to start.

If the connection has been successfully verified, the Promise will resolve with an instance of the driver.


== Accessing the Driver

In future, if we need to get the driver instance, we can call the `getDriver` function which returns the `driver` variable.

.src/neo4j.js
[source,js]
----
export function getDriver() {
    return driver
}
----

== Testing Connectivity

To test that the driver has been setup correctly, run the following command in a new terminal session:

[source,sh]
npm run test 01

The test file is located at `test/challenges/01-connecting-to-neo4j.spec.js`.

== Check Your Understanding

include::./questions/1-test-number.adoc[]

[.summary]
== Lesson Summary

We have implemented the code to create a new driver instance with environment variables read from the `.env` file and verifies that the driver can connect to the Neo4j instance before the server starts.

In the next module we will look at how we can use the driver to query a Neo4j database.
