crons:
  - reminders:
      name: send-reminders
      command:
        - npm
        - run
        - cmd:reminders
      cron: "*/10 * * * *"
      env:
        - BASE_URL
        - NEO4J_HOST
        - NEO4J_PASSWORD
        - NEO4J_USERNAME
        - MAILGUN_API_KEY
        - MAILGUN_DOMAIN
        - MAIL_FROM
        - MAIL_REPLY_TO
  - certifications:
      name: load-certifications
      command:
        - npm
        - run
        - cmd:certifications
      cron: "0 * * * *"
      env:
        - NEO4J_HOST
        - NEO4J_PASSWORD
        - NEO4J_USERNAME
        - COMMUNITY_GRAPH_HOST
        - COMMUNITY_GRAPH_PASSWORD
        - COMMUNITY_GRAPH_USERNAME
  - fail-stale-certifications:
      name: fail-stale-certifications
      command:
        - npm
        - run
        - cmd:failed-certifications
      cron: "30 * * * *"
      env:
        - BASE_URL
        - NEO4J_HOST
        - NEO4J_PASSWORD
        - NEO4J_USERNAME