crons:
  - reminders:
      name: send-reminders
      command:
        - npm
        - run
        - cmd:reminders
      cron: "*/10 * * * *"
      env:
        - name: BASE_URL
          value: "<value>"
        - name: NEO4J_HOST
          value: "<value>"
        - name: NEO4J_PASSWORD
          value: "<value>"
        - name: NEO4J_USERNAME
          value: "<value>"
        - name: MAILGUN_API_KEY
          value: "<value>"
        - name: MAILGUN_DOMAIN
          value: "<value>"
        - name: MAIL_FROM
          value: "<value>"
        - name: MAIL_REPLY_TO
          value: "<value>"
  - certifications:
      name: load-certifications
      command:
        - npm
        - run
        - cmd:certifications
      cron: "0 * * * *"
      env:
        - name: NEO4J_HOST
          value: "<value>"
        - name: NEO4J_PASSWORD
          value: "<value>"
        - name: NEO4J_USERNAME
          value: "<value>"
        - name: COMMUNITY_GRAPH_HOST
          value: "<value>"
        - name: COMMUNITY_GRAPH_PASSWORD
          value: "<value>"
        - name: COMMUNITY_GRAPH_USERNAME
          value: "<value>"
  - fail-stale-certifications:
      name: fail-stale-certifications
      command:
        - npm
        - run
        - cmd:failed-certifications
      cron: "30 * * * *"
      env:
        - name: BASE_URL
          value: "<value>"
        - name: NEO4J_HOST
          value: "<value>"
        - name: NEO4J_PASSWORD
          value: "<value>"
        - name: NEO4J_USERNAME
          value: "<value>"