crons:
  - name: send-reminders
    command:
      - cmd:reminders
    cron: "cron(0/10 * * * ? *)"     # This means "every 10 minutes".
    env:
      - NEO4J_PASSWORD

  - name: load-certifications
    command:
      - cmd:certifications
    cron: "cron(0 * * * ? *)"     # This means "at minute 0 of every hour".
    env:
      - NEO4J_PASSWORD
      - COMMUNITY_GRAPH_PASSWORD

  - name: fail-stale-certifications
    command:
      - cmd:failed-certifications
    cron: "cron(30 * * * ? *)"     # This means "at minute 30 of every hour".
    env:
      - NEO4J_PASSWORD
