crons:
  - reminders:
      name: send-reminders
      command:
        - npm
        - run
        - cmd:reminders
      cron: "*/10 * * * *"
  - certifications:
      name: load-certifications
      command:
        - npm
        - run
        - cmd:certifications
      cron: "0 * * * *"

env:
  - name: BASE_URL
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: BASE_URL
  - name: NEO4J_HOST
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: NEO4J_HOST
  - name: NEO4J_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: NEO4J_PASSWORD
  - name: NEO4J_USERNAME
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: NEO4J_USERNAME
  - name: MAILGUN_API_KEY
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: MAILGUN_API_KEY
  - name: MAILGUN_DOMAIN
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: MAILGUN_DOMAIN
  - name: MAIL_FROM
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: MAIL_FROM
  - name: MAIL_REPLY_TO
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: MAIL_REPLY_TO
  - name: COMMUNITY_GRAPH_HOST
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: COMMUNITY_GRAPH_HOST
  - name: COMMUNITY_GRAPH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: COMMUNITY_GRAPH_PASSWORD
  - name: COMMUNITY_GRAPH_USERNAME
    valueFrom:
      secretKeyRef:
        name: ga-secrets
        key: COMMUNITY_GRAPH_USERNAME