= Setup your development environment
:order: 0
:type: lesson
:lab: {repository-link}
:disable-cache: true
:branch: main

In this module, you will use Python, LangChain, and OpenAI to create a knowledge graph from unstructured data.
You must set up a development environment to run the code examples and exercises.

include::../../../../../../shared/courses/codespace/get-started.adoc[]

[%collapsible]
.Develop on your local machine
====
You will need link:https://python.org[Python] installed and the ability to install packages using `pip`.

You may want to set up a virtual environment using link:https://docs.python.org/3/library/venv.html[`venv`^] or link:https://virtualenv.pypa.io/en/latest/[`virtualenv`^] to keep your dependencies separate from other projects.

Clone the link:{repository-link}[github.com/neo4j-graphacademy/llm-knowledge-graph-construction] repository:

[source,bash]
----
git clone https://github.com/neo4j-graphacademy/llm-knowledge-graph-construction
----

Install the required packages using `pip` and download the required data:

[source,bash]
----
cd llm-knowledge-graph
pip install -r requirements.txt
----

You do not need to create a Neo4j database as you will use the provided sandbox instance.

You can find out more about how to configure Neo4j's GenAI functions in the link:https://neo4j.com/docs/cypher-manual/current/genai-integrations/[Neo4j GenAI integration documentation^].
====

== Setup the environment

Create a copy of the `.env.example` file and name it `.env`.
Fill in the required values.

[source]
.Create a .env file
----
include::{repository-raw}/{branch}/.env.example[]
----

Add your Open AI API key (`OPENAI_API_KEY`), which you can get from link:https://platform.openai.com[platform.openai.com^].

Update the Neo4j sandbox connection details:

NEO4J_URI:: [copy]#bolt://{sandbox-ip}:{sandbox-boltPort}#
NEO4J_USERNAME:: [copy]#{sandbox-username}#
NEO4J_PASSWORD:: [copy]#{sandbox-password}#

== Test your setup

You can test your setup by running `llm-knowledge_graph/test_environment.py` - this will attempt to connect to the Neo4j sandbox and the OpenAI API.

You will see an `OK` message if you have set up your environment correctly. If any tests fail, check the contents of the `.env` file.

== Continue

When you are ready, you can move on to the next task.

read::Success - let's get started![]

[.summary]
== Summary

You have setup your environment and are ready to start this module.

In the next lesson, you will explore a strategy for storing unstructured data in a graph.