= Registering a User
:type: challenge
:branch: 03-registering-a-user
:test-number: 03

A key piece of functionality that we should provide is for new users to be able to register themselves with the site.
This functionality is already built into the front end, but at the moment the credentials are hard coded in the API.
This might be fine for demo purposes, but limiting the number of users to one is bad for Neoflix's bottom line.

In order to register a user, we will need to **write** some data to the Neo4j database.
To do this, we will use the `writeTransaction` method that we learned about in the link:../1-transactions/[Sessions & Transactions lesson^].

== Implementing Write Transactions

The best way for us to do this in our Express app is to execute the query within a Write Transaction during the request.

As we learned in the Sessions and Transactions lesson, we can call the `writeTransaction` method with a function to represent the unit of work.

The register logic is already written into the `register` method of the `AuthService` at `src/services/auth.service.js`.  As we can see from the snippet below, at the moment it will only accept an email address of `graphacademy@neo4j.com` and password `letmein`.


[source,js,indent=0]
.src/services/auth.service.js
----
include::{repository-raw}/main/src/services/auth.service.js[tag="register"]
----


== Accessing the Driver

The Driver instance that we created in the last lesson has already been passed through to the constructor, so now it is defined, we can use it to create the Session object, and run the unit of work within the write transaction.
The Driver can be accessed within any method within the class through the `this.driver` variable.


== Running the Unit of Work

As with the previous lesson, the first step is to open a new session.

We are running this query on the default database and the default access mode is `WRITE`, so we don't need to supply any options.

[source,js,indent=0]
----
include::{repository-raw}/main/example/index.js[tag="session"]
----


Next, on that session, we can run the `writeTransaction` method with two arguments:

1. The Cypher query as a parameterised string
2. An object containing the values for the parameters prefixed in the query with a dollar sign (`$`)

[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/auth.service.js[tag="create"]
----


== Closing the Session

Then, finally, before returning anything, we should make sure that the session is closed.

[source,js,indent=0]
----
include::{repository-raw}/main/example/index.js[tag="session.close"]
----

== Working Solution

.Click here to reveal the full `register` method.
[%collapsible]
====
[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/auth.service.js[tag="register"]
----
====

include::../../../../includes/test.adoc[]


include::./questions/verify.adoc[]


[.summary]
== Summary

In this lesson we have written the code to write a User node to Neo4j.

We still have `TODO` comment in the query for handling unique constraint violations in the database, so let's take care of that in the next lesson.
