= Building GraphRAG Python MCP tools
:usecase: recommendations
:caption: Build your own GraphRAG MCP server with graph-backed tools and resources.
:categories: llms:30
:duration: 2 hours
:repository: neo4j-graphacademy/genai-mcp-build-custom-tools-python

This course follows on from the link:/courses/genai-mcp-neo4j-tools/[Developing with Neo4j MCP Tools course], which introduces the Model Context Protocol and key concepts like Servers, Clients and Tools.

In this course, you will build on that knowledge to create your own MCP server using the link:https://github.com/modelcontextprotocol/python-sdk[MCP Python SDK^] and create server features that can be consumed by any MCP client.



== Prerequisites 

This course assumes that you have are familiar with the basics of Generative AI and Large Language Models. If you are not, we recommend that you take the link:/courses/genai-fundamentals/[GenAI Fundamentals] and link:/courses/genai-mcp-neo4j-tools/[Developing with Neo4j MCP Tools] courses first.

We also assume a basic understanding of Python and command line tools.  We assume that you have Python installed along with the `uv` package manager.
If you are not familiar with uv, you should also link:https://docs.astral.sh/uv/[review the uv documentation].

We also use the link:https://github.com/modelcontextprotocol/inspector[MCP Inspector^] to test and debug your MCP servers and tools.  This tool is run through link:https://docs.npmjs.com/cli/v8/commands/npx[the `npx` command]^, so you will need Node.js to be installed.  You can link:https://nodejs.org/en/download[download Node.js from the official website^].

The course features hands-on challenges using link:https://github.com/settings/copilot[GitHub CoPilot^], you will need to enable either the free or Pro version.


== Duration 

{duration}

== What you will learn 

* How to build your own MCP servers with the MCP Python SDK.
* How to serve your tools, resources and prompts through your server.
* How to use the MCP Inspector to test and debug your tools and resources.
* How to use MCP tools to build MCP tools. 


// TODO: Add number of lessons, challenges and quizzes
[.includes]
== This course includes

* [lessons]#7 lessons#
* [challenges]#15 short hands-on challenges#
* [quizes]#20 simple quizzes to support your learning#
