= Load your CSV file
:order: 5
:type: challenge
:optional: true

In this optional challenge, you will load your own CSV file into Neo4j.

To complete the challenge, you will have to:

. Create or find a CSV file to load into Neo4j
. Determine the field terminator used in your CSV file
. Whether the file contains headers
. Upload the file to a cloud-hosting service (Google Drive, Dropbox, S3, etc.)
. Construct and run a LOAD CSV statement to load the file into Neo4j

== Obtain a CSV file

Your first task is to obtain a CSV file to load into Neo4j. You could:

* Export a CSV file from an existing spreadsheet or data application. 
* Create a simple CSV file from scratch using a text editor.
* Download a CSV file from a public data source. I recommend the link:https://www.kaggle.com/datasets[Kaggle datasets^] site, which has a range of public datasets available for download.

== Inspect the file

Once you have your CSV file, you should determine the following: 

. What is the field terminator? A comma, or another character?
. Are headers included in the file?

You may have set the field terminator (delimiter) and headers when exporting the CSV file.

If unsure, you can open the CSV file in a text editor and inspect it manually.

== Upload the file

`LOAD CSV` can access files on the Neo4j server's file system or a remote machine.

The course Sandbox and link:https://neo4j.com/cloud/platform/aura-graph-database/[Aura DB^] cloud service only allow access to remote files. You will need to host your CSV file in a location where you can provide a direct download link.

You could upload your CSV file to a cloud-hosting service like link:https//drive.google.come[Google Drive^], link:https://dropbox.com[Dropbox^], or link:github.com[GitHub^] and get a direct download link.

[%collapsible]
.Google Drive
====
. Upload your CSV file to Google Drive.
. Share your file with anyone with the link.
. Get the share link for the file.
. Use link:https://sites.google.com/site/gdocs2direct/[gdocs2direct^] to get a direct download link to your file.
====

[%collapsible]
.Dropbox
====
. Upload your CSV file to Dropbox.
. Share your file with anyone with the link.
. Get the share link for the file.
. Add `?dl=1` to the end of the link to get a direct download link to your file.

See the link:https://help.dropbox.com/share/force-download[DropBox documentation^] for more information
====

[%collapsible]
.GitHub
====
. Push your CSV file to a public GitHub repository.
. Navigate to the file on GitHub.
. Add `?raw=true` to the end of the link to get a direct download link to your file.
====

You can find more information on file access in the link:https://neo4j.com/docs/getting-started/data-import/csv-import/#_reading_csv_files[Reading CSV Files] section of the Neo4j documentation.

== Construct and run the LOAD CSV statement

The structure of your `LOAD CSV` statement should take into account the following: 

. The location of your CSV file.
. The field terminator.
. Whether the file contains headers.

The `LOAD CSV` syntax is:

[source, cypher]
----
LOAD CSV [WITH HEADERS] FROM url [AS alias] [FIELDTERMINATOR char]
RETURN alias
----

read::I'm ready![]

[.summary]
== Summary

In this optional challenge, you loaded your own CSV file into Neo4j.

In the next module, you will learn how to create nodes and relationships from CSV files.