= Registering a User
:type: challenge
:order: 5
:branch: 03-registering-a-user
:test-filename: _03_RegisterUserTest
:test-method: registerUser

Now that you have read data from the database, you are now ready to write data to the database.

In this challenge, you will rewrite the `register()` method in the link:{repository-blob}/main/src/main/java/neoflix/services/AuthService.java[`AuthService`^] to do the following:

1. <<Open a new Session>>
2. <<Execute a Cypher query within a new Write Transaction>>
3. <<Extract the User from the Result>>
4. <<Return the Results>>


== Registering Users

A key piece of functionality that the application should provide is for new users to be able to register themselves with the site.
This functionality is already built into the front end, but at the moment the credentials are hard coded in the API using a fixture.
This might be fine for demo purposes, but limiting the number of users to one is bad for Neoflix's bottom line.

The dummy register logic is already written into the `register()` method of the `AuthService` at `src/main/java/neoflix/services/AuthService.java`.
As we can see from the snippet below, at the moment, it loads the fixture from `users.json` and will only accept an email address of `graphacademy@neo4j.com`.

You also see that the password is hashed/encrypted using `AuthUtils.encryptPassword`, well use that later.

[source,java,indent=0]
.neoflix/services/AuthService.java
----
include::{repository-raw}/main/src/main/java/neoflix/services/AuthService.java[tag="register"]
----

From the last line, you can see that an additional `token` property is added to the return.
This represents the JWT token required to authenticate the user on any future requests.
This token is generated in `AuthUtils.sign()` which is provided for us.

You will replace these `TODO` comment with working code to complete the challenge.


== Implementing Write Transactions

You will follow similar steps to the previous challenge, with the one change that the Cypher query will be executed within a *Write Transaction*.

To do so, you will need to call the `writeTransaction()` method on the `session` object with a function to represent unit of work.

Here are the steps to complete the challenge.

=== Open a new Session

First, open a new session (preferably in a try block):

[source,java,indent=0]
----
include::{repository-raw}/main/src/main/java/example/Index.java[tag=session]
----

=== Execute a Cypher query within a new Write Transaction

Next, within that session, run the `writeTransaction()` method with two arguments:

1. The Cypher query as a parameterized string
2. An object containing the names and values for the parameters

You will need to pass three parameters to the query:

* `email` the user's email
* `encrypted` an encrypted version of the password provided
* `name` the users's name

The user's `userId` is generated via the `randomUuid()` in Cypher.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/AuthService.java[tag="create"]
----


=== Extract the User from the Result

The Cypher query above returns the newly-created `:User` node as `u`.

As this query creates a single node, it will only ever return one result, so the `u` value is taken as a `single()` row.
That method will fail with an error, if there is not exactly one row returned.


[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/AuthService.java[tag="extract"]
----


=== Return the Results

The return statement has already been written, so this can be left as it is.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/AuthService.java[tag="return-register"]
----


== Working Solution

.Click here to reveal the fully-implemented `register()` method.
[%collapsible]
====
[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/AuthService.java[tag="register"]
----
====

include::../../../../includes/test.adoc[]


include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you wrote the code to create a new User node to Neo4j.

We still have `TODO` comments in the query for handling unique constraint violations in the database, so let's learn about that in the next lesson.
