= Person Profile
:type: challenge
:optional: true
:test-filename: _15_PersonProfileTest
:branch: 15-person-profile

If you click on a Person card anywhere on the website, you will be taken to a Person profile.
This API call is the same regardless of whether the person is an actor, director, or both.

We have already implemented the methods that populate the endpoints in the `MovieService` to get a list of movies that the person has either acted in or directed.

But if you take a look at the link:{repository-blob}/main/src/main/java/neoflix/services/PeopleService.java[`PeopleService`^], you will see two methods that need to be implemented to complete this page:

* <<findById()>> - should find a person by their ID.
* <<getSimilarPeople()>> - should return a list of similar people who are commonly connected through the same movies.


== findById()

The `findById()`  method is currently hardcoded to return data by id from the `people.json` list.

.neoflix/services/PeopleService.java
[source,java,indent=0]
----
include::{repository-raw}/main/src/main/java/neoflix/services/PeopleService.java[tag="findById"]
----

You will update this method to run the following cypher statement in a **read transaction**.

.Get Person information
[source,cypher,indent=0]
----
include::{cypher-repository-raw}/main/cypher/3-backlog/7-person-view/person-profile.cypher[]
----

The query will return the properties for the person with the corresponding `tmdbId`, along with a count of the number of movies that the person has acted in and directed.

=== Your Task

* Modify the `findById()` method to query Neo4j and return details for the requested person.
* The returned object should include counts of the number of movies that the person has acted in or directed.
* If not exactly one record is returned, the method will throw a `NotFoundError` by using the `result.single()` API call.
* Remember to auto-close the session and use the `toMap()` function to convert the object into native Java types.


[%collapsible]
.Click here to reveal the final `findById()` method.
====

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/PeopleService.java[tag="findById"]
----

====



== getSimilarPeople()

The `getSimilarPeople()` method should return a paginated list of similar people based on their second degree connections - either people who have acted in or have directed the same movies as our person.

.neoflix/services/PeopleService.java
[source,java,indent=0]
----
include::{repository-raw}/main/src/main/java/neoflix/services/PeopleService.java[tag="getSimilarPeople"]
----

There could be a more clever algorithm for finding similar people by weighting the type of relationship differently, but for now, the following query will find a list of similar people based on the number of relationships in common.

.Get Similar People
[source,cypher,indent=0]
----
include::{cypher-repository-raw}/main/cypher/3-backlog/7-person-view/similar-people.cypher[]
----

[IMPORTANT]
.Parameters in Neo4j Browser
====
To run this query in Neo4j Sandbox, you will have to define a parameter in your Neo4j Browser session.
To do so, you can use the `:param` command.

For example, to view **Kevin Bacon**, you can set the `id` parameter to "4724":

[source,cypher,role=norun]
----
:param id: "4724"
----

====

=== Your Task

* Modify the `getSimilarPeople()` method to query Neo4j and return a list of similar people.
* The returned objects should include a list of actors and
* An `inCommon` property to show how the two people are related (a list of the movies they in common, with their `tmbdId`, `title`, and type of relationship).
* Here we order by the number of entries that two people have in common
* The pagination information is passed as parameters
* Remember to auto-close the session and use the `toMap()` function within a `list()` function on `Result` to convert the values to native Java types.


[%collapsible]
.Click here to reveal the final `getSimilarPeople()` method.
====

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/PeopleService.java[tag="getSimilarPeople"]
----

====


// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-similar-people.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you have implemented the final methods in the `PeopleService`.
