= Integrate a Python Chatbot
:order: 4
:type: challenge
:branch: firstrelease
:lab: {branch}llm-knowledge-graph/chatbot/

In this optional challenge, you will complete a Python chatbot that can answer questions using the knowledge graph.

== Chatbot

The `llm-knowledge-graph` repository includes a version of the Python chatbot from the course link:https://graphacademy.neo4j.com/courses/llm-chatbot-python/[Build a Neo4j-backed Chatbot using Python^].
You may find it useful to complete the course before attempting this challenge.

You can view the code in the link:{repository-blob}/{branch}/llm-knowledge-graph/chatbot/[`llm-knowledge-graph/chatbot` directory^].

Your task is to update the `vector` and `cypher` tools to interact with the knowledge graph by generating Cypher queries and querying the Neo4j vector with a retriever.

You can run the chatbot using the `streamlit run` command:

[source,bash]
----
streamlit run llm-knowledge-graph/chatbot/bot.py
----

== Vector tool

The `vector` tool uses the Neo4j vector to retrieve the most similar nodes based on the user's input.

The code is in the link:{repository-blob}/{branch}/llm-knowledge-graph/chatbot/tools/vector.py[`llm-knowledge-graph/chatbot/tools/vector.py` file^]:

[source, python]
----
include::{repository-raw}/{branch}/llm-knowledge-graph/chatbot/tools/vector.py[tag=**]
----

Your task is to update it to use the Neo4j vector retriever you created in the link:../3-creating-a-retriever[Integrate with a Retriever^] lesson.

== Cypher Tool

The `cypher` tool generates Cypher queries based on the user's input.

The code is the link:{repository-blob}/{branch}/llm-knowledge-graph/chatbot/tools/vector.py[`llm-knowledge-graph/chatbot/tools/cypher.py` file^]

[source, python]
----
include::{repository-raw}/{branch}/llm-knowledge-graph/chatbot/tools/cypher.py[tag=**]
----

You task is to update this code to use the Cypher generation you created in the link:../2-llm-generated-cypher[Query the Knowledge Graph with an LLM^] lesson.

== Agent prompts and tools

The agent will decide what action to take based on the user's input, the *prompt*, and the *tools* available.

You may need to change these to improve the chatbot's performance for your use case and the data in your knowledge graph.

The agent code is in the `llm-knowledge-graph/chatbot/agent.py` file.

[%collapsible]
.View agent.py
====
[source, python]
----
include::{repository-raw}/{branch}/llm-knowledge-graph/chatbot/solutions/agent.py[tag=**]
----
====

The *prompt* sets the instructions for the agent and how it should decide what tool to use:

[source, python]
.Agent prompt
----
include::{repository-raw}/{branch}/llm-knowledge-graph/chatbot/solutions/agent.py[tag=agent_prompt]
----

The *tools* are the functions the agent can use to interact with the knowledge graph:

[source, python]
.Tools
----
include::{repository-raw}/{branch}/llm-knowledge-graph/chatbot/solutions/agent.py[tag=tools]
----

== Test the chatbot

Test the chatbot by asking the agent questions about data held within the knowledge graph.

You can tune the agent's prompt and tool descriptions to improve the chatbot's performance.

== Solution

Here is one possible solution for the `vector` and `cypher` tools.
Remember there is no one correct answer, and you should customize the chatbot to suit your needs.

[NOTE]
The performance of the chatbot is dependent on the data, tools and prompts which may still need tuning.

[%collapsible]
.View the vector.py solution
====
[source, python]
----
include::{repository-raw}/{branch}/llm-knowledge-graph/chatbot/solutions/tools/vector.py[tag=**]
----
====

[%collapsible]
.View the cypher.py solution
====
[source, python]
----
include::{repository-raw}/{branch}/llm-knowledge-graph/chatbot/solutions/tools/cypher.py[tag=**]
----
====

When you are ready, move on to finish the course.

read::Continue[]

[.summary]
== Lesson Summary

In this optional challenge, you integrated a Python chatbot with the knowledge graph.

Congratulations on completing the course!