[.question]
= 1. Creating and using a POINT index

Suppose we have a graph that contains Company nodes. One of the properties of a Company node is location.
We want to be able to optimize queries that test distances between companies by creating a POINT index on the Company.location property.

What conditions must be met in our graph to be able to create and use a POINT index? (Select all that apply)

* [ ] All Company.location properties must have a value.
* [ ] All Company.location property values must be of type double.
* [x] All Company.location property values must be of type point.
* [x] All Company.location property values must use the same spatial coordinate system.

[TIP,role=hint]
.Hint
====
What is values are required to create a property of type point?
====

[TIP,role=solution]
.Solution
====

In order to create and use a POINT index on the Company.location property, the property need not exist for all nodes, but if it does, it must be of type point and every value used for this property for all nodes must use the same spatial coordinate system.

====
