[.question]
= 2. Creating a POINT index


Suppose we have a graph that contains Company nodes. One of the properties of a Company node is location.
The values for the Company.location are of type point and these values use the WGS-84 coordinate system.

What is the correct statement to create this POINT index?

* [ ] `CREATE SPATIAL INDEX Company_location_point IF NOT EXISTS FOR (x:Company) ON (x.location)`
* [ ] `CREATE SPAIIAL INDEX Company_location_point IF NOT EXISTS ON (Company.location) USING COORDINATE WGS-84`
* [x] `CREATE POINT INDEX Company_location_point IF NOT EXISTS FOR (x:Company) ON (x.location)`
* [ ] `CREATE POINT INDEX Company_location_point  IF NOT EXISTS ON (Company.location) USING COORDINATE WGS-84`

[TIP,role=hint]
.Hint
====
You are creating a POINT index and you need not specify the coordinate system when you create the index, but all property values must use the same coordinate system.

====

[TIP,role=solution]
.Solution
====

The correct code for creating the POINT index is:

`CREATE POINT INDEX Company_location_point IF NOT EXISTS FOR (x:Company) ON (x.location)`
====
