:id: _challenge

[.verify]
= Validate Results

Once you have created the three constraints, click the **Check Database** button and we will check the database for you.


verify::Check Constraints[]

[TIP,role=hint]
.Hint
====
Constraint names, label names, and property key names are all case-sensitive.
The node labels you should specify are for Person, User, and Genre nodes (case-sensitive).
The property keys you should specify are for tmdbId, userId, and name (case-sensitive).

If you mis-specify a label or property key, the constraint will not be created.

You can type `SHOW CONSTRAINTS` after you have created each constraint.

If you mess up, type ``CALL apoc.schema.assert({},{},true)` to remove all constraints and indexes in the graph.
Then you would need to recreate four constraints for Movie, Person, User, and Genre nodes.
====

[TIP,role=solution]
.Solution
====
Here are the statements to create the three constraints:

[source,cypher]
----
include::../solution.cypher[]
----
====