= Movie Details
:type: challenge
:order: 4
:optional: true
:branch: 12-movie-details
:test-filename:
:test-filename: 12-MovieDetails
:test-pattern: _12_MovieDetails

There are two methods remaining in the link:{repository-blob}/main/Neoflix/Services/MovieService.cs[`MovieService`^] that are currently returning hardcoded data.

* <<FindByIdAsync()>> - should return information about a movie, including a list of actors, director, and genres.
* <<GetSimilarMoviesAsync()>> - should return a list of similar movies, ordered by a score generated by Neoflix's recommendation algorithm.

In this challenge, you will update these methods to query Neo4j.

First, let's take a look at how these methods are used.

== Movie Page

If you click on any movie, you'll see that the API currently only returns information a limited set of movies from the fixtures in `popular.json`.

The page itself is populated by three API calls:

1. The details about the movie are loaded via the `api/movies/{id}` endpoint.  This endpoint gets its data from the <<FindByIdAsync()>> method.
2. The similar movies list is loaded by a call to the `api/movies/{id}/similar` endpoint, which gets its data from the <<GetSimilarMoviesAsync()>> method.
3. The ratings on the right hand side of the page are loaded by a call to the `api/movies/{id}/ratings` endpoint.  You will update this method in the next lesson.


== FindByIdAsync()

Movie information is retrieved by the `FindByIdAsync()` method.

.Neoflix/Services/MovieService.cs
[source,c#,indent=0]
----
include::{repository-raw}/main/Neoflix/Services/MovieService.cs[tag=findById]
----

Most of the important information is held as properties on the `Movie` node, but the payload should also return some additional information.
We can use a Cypher subquery and the `count()` aggregate function to get the number of ratings for the movie and use a link:https://neo4j.com/docs/cypher-manual/current/values-and-types/lists/#cypher-pattern-comprehension[Pattern Comprehension] to get lists of actors, directors and genres.

As with the other movie methods in the `MovieService`, we should also provide a `favorite` value to represent whether the user has added this movie to their My Favorites list or not.

The following Cypher statement should be run within a **read transaction**:

.Movie Details
[source,cypher]
----
include::{cypher-repository-raw}/main/cypher/3-backlog/4-movie-view/movie-details.cypher[]
----


=== Your Task

* Modify the `FindByIdAsync()` method to query Neo4j and return details for the requested movie.
* The returned object should include a list of actors, directors, genres, and a boolean flag to represent whether the movie exists on the current user's My Favorites List.
* If no records are returned, the method should throw a `NotFoundError` (via the `single()` method on Result).
* Remember to close the session and use the `ToListAsync()` function to convert the result object into native C# types.

[%collapsible]
.Click to reveal the completed `FindByIdAsync()` method
====

.Neoflix/Services/MovieService.cs
[source,c#,indent=0]
----
include::{repository-raw}/{branch}/Neoflix/Services/MovieService.cs[tag=findById]
----

====


== GetSimilarMoviesAsync()

Similar movies are found using the `GetSimilarMoviesAsync()` method.

To provide a simple set of similar movies, the Cypher statement below uses the number of neighbors in common and their IMDB rating to generate a _similarity score_.

The following Cypher statement should be run within a **read transaction**:

.Find Similar Movies
[source,cypher]
----
include::{cypher-repository-raw}/main/cypher/3-backlog/4-movie-view/similar-movies.cypher[]
----


=== Your Task

* Modify the `GetSimilarMoviesAsync()` method to query Neo4j and return a list of similar movies.
* The returned objects should include a list of actors, directors, genres, and a boolean flag to represent whether the movie exists on the current user's My Favorites List.
* Remember to close the session and use the `ToListAsync()` function `result` to convert the values to native C# types.

[%collapsible]
.Click here to reveal the completed `GetSimilarMoviesAsync()` method
====

.Neoflix/Services/MovieService.cs
[source,c#,indent=0]
----
include::{repository-raw}/{branch}/Neoflix/Services/MovieService.cs[tag=getSimilarMovies]
----

====


// Testing
include::../../../../includes/test.adoc[]

== Verifying the Test

include::./questions/1-most-similar-movie.adoc[leveloffset=+2]


[.summary]
== Lesson Summary

In this Challenge, you modified the `FindByIdAsync()` and `GetSimilarMoviesAsync()` methods to return movie details from the Neo4j database.

In the next Challenge, you will complete the Movie page implementation by retrieving movie ratings from Neo4j.
