= The Home Page
:type: challenge
:branch: 02-movie-lists
:test-filename: _02_MovieListTest
:test-method: orderMoviesByRating

Now for another challenge.

In this challenge, you will use the knowledge gained so far in this course to add new functionality to the API.
You will modify the `all()` method of the link:{repository-blob}/src/main/java/neoflix/services/MovieService.java[`MovieService`^] to do the following:


1. <<Open a new Session>>
2. <<Execute a Cypher query within a new Read Transaction>>
3. <<Extract a list of Movies from the Result>>
4. <<Close the Session>>
5. <<Return the Results>>

Once you have completed the challenge, you will be asked to run a unit test to verify that the code has been correctly implemented.
If the test runs correctly, the title of the highest rated movie will be logged.
You will need this value to verify that the test has run correctly.


== Exploring the Code

Before you start, let's take a look at the code.
//Adam: Is this supposed to be a link to Working solution?
If you are not interested in the code, you can skip straight to <<Implementing Read Transactions>>.

If you start the application and access the app at http://localhost:3000, you will see two lists on the home page; one for Popular Movies and one for Latest Releases.
Both of these lists are populated by a request to link:http://localhost:3000/api/movies[`http://localhost:3000/api/movies`^] with some additional parameters.

=== Route Handler

You can find the route handler, the function that handles the request, in link:{repository-blob}/src/main/java/neoflix/routes/MovieRoutes.java[`src/main/java/neoflix/routes/MovieRoutes.java`^]:

./src/main/java/neoflix/routes/MovieRoutes.java
[source,java,role=nocopy]
----
include::{repository-raw}src/main/java/neoflix/routes/MovieRoutes.java[tag=list]
----

Within the route handler, you can see that:

1. The `sort`, `order`, `limit` and `skip` values are extracted from the query string. This allows us to apply sorting and pagination to the results.
2. A new instance of the `MovieService` is created with the Driver instance that you created in link:../../1-driver/3-connecting/[Adding the Driver] passed to the constructor.
3. The results are retrieved via the `all()` method and are returned by the handler as JSON.

=== The Movie Service

The magic happens in the `MovieService`, located at link:{repository-blob}/src/main/java/neoflix/services/MovieService.java[`src/main/java/neoflix/services/MovieService.java`^].
For this route, we are concerned with the `all()` method.

If we take a closer look at the `add()` method, we can see that it currently returns a hardcoded list of popular movies from another file in the repository.

[source,java,indent=0]
.src/main/java/neoflix/services/MovieService.java
----
include::{repository-raw}src/main/java/neoflix/services/MovieService.java[tag=all]
----

You will need to replace these `TODO` comments with working code to complete the challenge.


== Implementing Read Transactions

As you learned in the Sessions and Transactions lesson, you will complete code to open a new session and run the query within a Read Transaction.
Once the query has run, you add code to close the session.
Then, finally you add code to extract and return the results.


=== Open a new Session

Within the `all()` method, first open a new session:

[source,java,indent=0]
----
include::{repository-raw}/main/src/main/java/example/index.java[tag=session]
----

=== Execute a Cypher query within a new Read Transaction

This session then provides a `readTransaction()` method for which you pass a function to represent the unit of work.

The function will have one argument passed to it, a `Transaction` instance that you can use to execute a Cypher statement using the `run()` method.
The `run()` method accepts two arguments:

1. The Cypher query as a parameterised string.
2. An object containing the values for the parameters prefixed in the query with a dollar sign (`$`).

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/MovieService.java[tag=allcypher]
----


=== Extract a list of Movies from the Result

Now that you have a complete result assigned to the `res` variable, you use the `list()` function to pass in each record, and get each `movie` object formatted with the `asMap()` function.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/MovieService.java[tag=allmovies]
----


=== Return the Results

Finally, update the `return` statement to return the `movies` list extracted above.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/MovieService.java[tag=return]
----


== Working Solution

[%collapsible]
.Click here to reveal the completed `all()` method
====

.src/main/java/neoflix/services/MovieService.java
[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/MovieService.java[tag=all]
----
====

include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you used your knowledge of sessions and transactions to retrieve a list of Movie nodes from the database.

In the next Challenge, you will write data to the database.
