= Functions to Transform Element Types
:type: video
:order: 7
:sandbox: true

[.video]
video::N10hUI0yrz8[youtube,width=560,height=315]

//https://youtu.be/N10hUI0yrz8

[.transcript]

== Transforming element types

You learned earlier that a list can contain elements of the these types that Neo4j supports:

* Numeric without decimal (Long)
* Numeric with decimal (Float)
* String
* Date
* Time
* LocalTime
* DateTime
* LocalDateTime
* Duration
* Boolean
* Point
* Another list

When you create a list, it can contain mixed types, but in most cases your lists will contain elements of the same type.

Cypher has functions to transform elements to Strings, Longs, Floats and Booleans.

=== `toStringList()`

This is the simplest element transformation. It will produce elements of type String.

[source,cypher]
----
WITH ["abc", false, 1, 1.5,null, datetime(), date(), LocalDateTime(), point({x: 2.3, y: 4.5})] AS MyList
RETURN MyList, toStringList(MyList)
----

The only exception for this function is that null elements will remain null in the list.

=== `toIntegerList()`

This function produces elements of type Long (also known as Integer).

[source,cypher]
----
WITH ["abc", false, 1, 1.5,null, datetime(), date(), LocalDateTime(), point({x: 2.3, y: 4.5})] AS MyList
RETURN MyList, toIntegerList(MyList)
----

If an element cannot be transformed, it is set to null.

Only numeric  and Boolean type elements will be transformed.
Note that if an element is a Float, the decimal value is dropped.


=== `toFloatList()`

This function produces elements of type Float.

[source,cypher]
----
WITH ["abc", false, 1, 1.5,null, datetime(), date(), LocalDateTime(), point({x: 2.3, y: 4.5})] AS MyList
RETURN MyList, toFloatList(MyList)
----

If an element cannot be transformed, it is set to null.

Only numeric type elements will be transformed.

=== `toBooleanList()`

This function produces elements of type Boolean.

[source,cypher]
----
WITH ["abc", false, 1, 1.5, 0, null, datetime(), date(), LocalDateTime(), point({x: 2.3, y: 4.5})] AS MyList
RETURN MyList, toBooleanList(MyList)
----

If an element cannot be transformed, it is set to null.

Numeric elements with a value of 0 will be transformed to false.
Numeric elements with a non-zero value will be transformed to true.


== Check your understanding

include::questions/1-type-transform.adoc[leveloffset=+2]
include::questions/2-type-transform.adoc[leveloffset=+2]

[.summary]
== Summary

In this lesson, you about the Cypher functions that transform list elements.
In the next challenge, you will transform the elements of a list.
