[.question.select-in-source]
= 1. What parameters to use?

Suppose we have set the following parameters:

[source,cypher]
----
:params {actorName: 'Tom Cruise', movieName: 'Top Gun', l:2}
----

Here is a query to return the names of the actors in a particular movie that is parameterized.
The number of results returned is also parameterized.
How would you complete this query in a Neo4j Browser session?

Once you have selected your option, click the **Check Results** query button to continue.

[source,cypher,role=nocopy noplay]
----
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
/*select:WHERE m.title = $movieName
RETURN p.name LIMIT $l*/
----


* [ ] `WHERE m.title = #movieName RETURN p.name LIMIT #l`
* [ ] `WHERE m.title = movieName RETURN p.name LIMIT l`
* [ ] `WHERE m.title = @movieName RETURN p.name LIMIT @l`
* [x] `WHERE m.title = $movieName RETURN p.name LIMIT $l`

[TIP,role=hint]
.Hint
====
What is the special character to indicate a parameter in a Cypher query?
====

[TIP,role=solution]
.Solution
====
The correct answer is: `WHERE m.title = $movieName RETURN p.name LIMIT $l`. You use the "$" to indicate that it will be substituted with parameter values when the query executes.

None of the other choices use "$" to indicate parameters.
====