= Build a Neo4j-backed Chatbot with TypeScript
:categories: llms:3
:status: active
:duration: 6 hours
:caption: Build a chatbot using Neo4j, Langchain and Next.js
:usecase: recommendations
// :video: https://www.youtube.com/embed/vVCHJFa01gA
:key-points: Building a Neo4j-backed Chatbot, Neo4j & Langchain, Neo4j & Next.js
:repository: neo4j-graphacademy/llm-chatbot-typescript

== Course Description

In this hands-on course, you will use the knowledge obtained from the link:/courses/llm-fundamentals[Neo4j & LLM Fundamentals course^] to create a Movie Recommendation Chatbot backed by a Neo4j database.

You will take a simple chat interface that repeats the user's input and modify it to answer questions about movies via the Neo4j Recommendations Dataset using GPT-4, complete with conversation history.

The chatbot will be able to answer questions like:

* How many movies has Tom Hanks acted in?
* What is the most popular movie in the database?
* Can you recommend a movie for fans of The Matrix and Casino?

At the end of the course, you will have a working chatbot built in React using link:https://nextjs.org/[Next.js^].


=== Prerequisites

This course relies heavily on the information in the link:/courses/llm-fundamentals[Neo4j & LLM Fundamentals course^].
We recommend completing this course first if you have not already done so.

We also assume a basic understanding of TypeScript and Next.js.
It is not required, but you may also benefit from taking the link:/courses/app-typescript/[Building Neo4j Applications with TypeScript^] course to understand how the Neo4j JavaScript Driver works.

The course uses link:https://nextjs.org/[Next.js^] to build a simple chat interface.
We do not focus heavily on the Next.js functionality, so it may be worth reviewing the link:https://nextjs.org/docs[Next.js documentation^] to understand how it works.


=== Duration

{duration}

=== What you will learn

* How to build a Neo4j-backed Chatbot with Langchain and GPT-4
* Answering user queries with an LLM
* Retrieval Augmented Generation (RAG)
* Langchain Agents and QA Chains
