= The Home Page
:type: challenge
:order: 4
:branch: 02-movie-lists
:test-filename: _02_MovieListTest

Now for another challenge.

In this challenge, you will use the knowledge gained so far in this course to add new functionality to the API.
You will modify the `all()` method of the link:{repository-blob}/main/src/main/java/neoflix/services/MovieService.java[`MovieService`^] to do the following:

1. <<Open a new Session>>
2. <<Execute a Cypher statement within a new Read Transaction>>
3. <<Extract a list of Movies from the Result>>
4. <<Return the Results>>

Once you have completed the challenge, you will be asked to run a unit test to verify that the code has been correctly implemented.
If the test runs correctly, the title of the highest rated movie will be logged.

You will need this value to verify that the test has run correctly.

== Exploring the Code

Before you start, let's take a look at the code.

If you are not interested in the code, you can skip straight to <<Implementing Read Transactions>>.

If you start the application with `mvn compile exec:java` and access the app at http://localhost:3000[http://localhost:3000^], you will see two lists on the home page; one for Popular Movies and one for Latest Releases.

Both of these lists are populated by a request to link:http://localhost:3000/api/movies[`http://localhost:3000/api/movies`^] with some additional request query parameters, feel free to open that URL in your browser, you should see the JSON response.

=== Route Handler

You can find the route handler, the function that handles the request, in link:{repository-blob}/main/src/main/java/neoflix/routes/MovieRoutes.java[`src/main/java/neoflix/routes/MovieRoutes.java`^]:

.neoflix/routes/MovieRoutes.java
[source,java,role=nocopy,indent=0]
----
include::{repository-raw}/main/src/main/java/neoflix/routes/MovieRoutes.java[tag=list]
----

Within the route handler, you can see that:

1. A new instance of the `MovieService` is created with the Driver instance that you created in link:../../1-driver/3-connecting/[Adding the Driver] passed to the constructor.
2. The `sort`, `order`, `limit` and `skip` values are extracted from the request. This allows us to apply sorting and pagination to the results.
3. The `userId` is also extracted from the request.
4. The query results are retrieved via the `all()` method and are returned by the handler as JSON.

=== The Movie Service

The magic happens in the `MovieService`, located at link:{repository-blob}/main/src/main/java/neoflix/services/MovieService.java[`src/main/java/neoflix/services/MovieService.java`^].
For this route, we are concerned with the `all()` method.

If we take a closer look at the `all()` method, we can see that it currently returns a hardcoded list of `popular` movies from the `popular.json` fixture.

[source,java,indent=0]
.neoflix/services/MovieService.java
----
include::{repository-raw}/main/src/main/java/neoflix/services/MovieService.java[tag=all]
----

You will need to replace these `TODO` comments with working code to complete the challenge.


== Implementing Read Transactions

As you learned in the transaction management lesson, you will complete code to open a new session and run the query within a Read Transaction.

Then, finally you add code to extract and return the results.

=== Open a new Session

Within the `all()` method, first open a new session:

[source,java,indent=0]
----
include::{repository-raw}/main/src/main/java/example/Index.java[tag=session]
----

=== Execute a Cypher statement within a new Read Transaction

The Cypher statement itself is similar to this one, only that the property that's ordered by will be dynamically inserted based on user interaction from the API query parameters.

[source,cypher,indent=0]
----
include::{cypher-repository-raw}/main/cypher/2-interacting/4-home-page/movie-list.cypher[]
----

This session then provides an `executeRead()` method for which you pass a callback/lambda to represent the unit of work.

The function will have one argument passed to it, a `Transaction` instance that you can use to execute a Cypher statement using the `run()` method.

The `run()` method accepts two arguments:

1. The Cypher statement as a string, using query parameters (placeholders prefixed with `$`).
2. An object containing the names and values of the parameters.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/MovieService.java[tag=allcypher]
----

NOTE: Two of the parameters, namely the sort field and sort order cannot be provided as Cypher statement parameters, so we need to use string substitution with `%s` instead, which we would love to avoid.

=== Extract a list of Movies from the Result

Now that you have a complete result assigned to the `res` variable, you

1. use the `list()` function to convert each row,
2. grab each `movie` node from the row `Record`
3. turn the node properties into a Java Map with the `asMap()` method.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/MovieService.java[tag=allmovies]
----


=== Return the Results

Finally, update the `return` statement to return the `movies` list extracted above.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/MovieService.java[tag=return]
----

== Working Solution

[%collapsible]
.Click here to reveal the completed `all()` method
====

.neoflix/services/MovieService.java
[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/MovieService.java[tag=all]
----
====

include::../../../../includes/test.adoc[]


[.summary]
== Lesson Summary

In this Challenge, you used your knowledge of sessions and transactions to retrieve a list of Movie nodes from the database.

If you now open the link:http://localhost:3000/api/movies[API endpoint^] or the link:http://localhost:3000[application UI^] for popular movies you should see the list coming from your database. Congratulations 🎉.

In the next Challenge about user management, you will learn to write data to the database.
