[.question.freetext.freetext-monospace]
= Set the $name Parameter

What command would you run in Neo4j Browser to set the `$name` parameter to *Tom*?
(use double-quotes for the value of the parameter)

input::answer[]

* [x] :param name: "Tom"

[TIP,role=hint]
.Hint
====
The `:param` command allows you to set a parameter which is persisted as long as the browser window is open.
The format is as follows:

[source,cypher,role="norun nocopy"]
----
:param key: "value"
----

What command would you run in Neo4j Browser to set the `$name` parameter to *Tom*?
(use double-quotes for the value of the parameter)

Once you have entered the answer, click the **Try Again** button below to continue.
====

[TIP,role=solution]
.Solution
====

This is the command you use to set the $name parameter to *Tom*:

[source,cypher]
----
include::../solution.cypher[]
----

What command would you run in Neo4j Browser to set the `$name` parameter to *Tom*?
(use double-quotes for the value of the parameter)

Once you have entered the answer, click the **Try Again** button below to continue.
====
