[.question.select-in-source]
= 1. Creating a full-text index

Suppose we have a graph that contains Company nodes. One of the properties of a Company node is description.
We want to be able to optimize queries that test whether the Company description contains a string pattern that has a combination of phrases.
The Cypher to perform this query would not be efficient so we want to create a full-text index that will be used for our queries.

Once you have selected your option, click the **Check Results** query button to continue.

[source,cypher,role=nocopy noplay]
----
/*select:CREATE FULLTEXT INDEX Company_description_ft IF NOT EXISTS FOR (x:Company) ON EACH [x.description]*/
----

* [x] `CREATE FULLTEXT INDEX Company_description_ft IF NOT EXISTS FOR (x:Company) ON EACH [x.description]`
* [ ] `CREATE FULLTEXT INDEX Company_description_ft IF NOT EXISTS FOR (x:Company) ON (x.description)`
* [ ] `CREATE FULL-TEXT INDEX Company_description_ft IF NOT EXISTS FOR (x:Company) ON (x.description)`
* [ ] `CREATE FULL-TEXT INDEX Company_description_ft IF NOT EXISTS ON (Company.description)`

[TIP,role=hint]
.Hint
====
You are creating a FULLTEXT index on every description property of each Company node.
====

[TIP,role=solution]
.Solution
====

The correct code for creating the full-text index is:

`CREATE FULLTEXT INDEX Company_description_ft IF NOT EXISTS FOR (x:Company) ON EACH [x.description]`
====
