:id: q2
[#{id}.question]
= 2.パターンを使ったクエリ

映画「マトリックス」の監督の名前を返す `MATCH` 句はどれですか？

* [x] `+MATCH (m:Movie {title: 'The Matrix'})<-[:DIRECTED]-(p:Person) RETURN p.name+`
* [ ] `MATCH (m:Movie {title: 'The Matrix'})--(p:Person) RETURN p.name`
* [x] `+MATCH (m:Movie {title: 'The Matrix'})<-[:DIRECTED]-(p) RETURN p.name+`
* [ ] `MATCH (m:Movie {title: 'The Matrix'})--(p:Director) RETURN p.name`

[TIP,role=hint]
.ヒント
====
_Person_ ノードは人を表し、その関係は _DIRECTED_ でなければなりません。

パターンの最後にあるノードの `:Person` ラベルは必ずしも定義する必要はありません。
====


[TIP,role=solution]
.解答
====

以下の2つの選択肢は、マトリックスの監督をした人たちを探すのに有効な選択肢です。

`MATCH (m:Movie {title: 'The Matrix'})<-[:DIRECTED]-(p:Person) RETURN p.name` +
`MATCH (m:Movie {title: 'The Matrix'})<-[:DIRECTED]-(p) RETURN p.name`


次のクエリでは、ディレクターを取得しますが、リレーションシップタイプやディレクションタイプが定義されていないため、`:ACTED_IN`リレーションシップを通じて映画に出演した人を含め、その映画に関連するすべての人を取得します。

`MATCH (m:Movie {title: 'The Matrix'})--(p:Person) RETURN p.name`

次のクエリは、`:DIRECTED` の関係を持つすべての `:Person` ノードを返します。したがって、マトリックスのディレクターだけでなく、マトリックスに関連して他の映画の監督をしている人も含まれます。

`MATCH (m:Movie {title: 'The Matrix'})--(p:Director) RETURN p.name`
====