[.question]
= Restoring from Local Instance

You have a local Neo4j database running in Neo4j Desktop with a dump file located at `./backups/neo4j.dump`.

Which `neo4j-admin` command would you use to upload this dump to your Aura instance?

* [ ] `neo4j-admin backup restore`
* [x] `neo4j-admin database upload`
* [ ] `neo4j-admin restore`
* [ ] `neo4j-admin upload database`

[TIP,role=hint]
.Hint
====
The command should include both the action (upload) and the resource type (database) in its structure.
====

[TIP,role=solution]
.Solution
====
The correct answer is **neo4j-admin database upload**.

The `neo4j-admin database upload` command is specifically designed to upload local database dumps to Aura instances.

The command:


* Authenticates with your Aura instance using the provided credentials
* Uploads the dump file from the local `--from-path`
* Imports the data into your Aura instance at the `--to-uri`
* Works with databases of any size (as long as they fit within your instance capacity)
====

