= Setup Neo4j
:type: challenge
:order: 7

Creating your own Neo4j database instance is a great way continue learning.

In this challenge, you will create your own Neo4j database instance.

Choose between either a:

* Fully managed, free, cloud instance on Neo4j Aura.
* Local installation of Neo4j Desktop.

Spend some time exploring the Neo4j console, add some data, and practice your Cypher skills.

== Create an Aura Instance

You can create your own free Neo4j database instance on Aura.

Create an account on link:https://console.neo4j.io/graphacademy[Neo4j Aura^] and create a free instance.

You can learn more about Neo4j Aura in the link:https://graphacademy.neo4j.com/courses/aura-fundamentals/[GraphAcademy Aura Fundamentals course^].

== Download Neo4j Desktop

Neo4j Desktop is a simple way to run Neo4j locally on your computer.

link:https://neo4j.com/download/[Download Neo4j Desktop], install on your computer, and create a local database instance.

== Next

read::Finished![]

[.summary]
== Summary

In this optional challenge, you created your own Neo4j database instance.

