= What you will need
:type: lesson

This lesson will walk you through ensuring you have the right tools installed and configured to work with the Spring Data Neo4j library.

== Steps

1. Verify your Java version. You will need Java 17 or higher. You can check your version by running the following command in your terminal window: +
`java -version`. To download the latest version of Java, go to https://adoptopenjdk.net.

2. An IDE of your choice. If you don't yet have a preference, IntelliJ IDEA Community Edition or Visual Studio Code are excellent choices. You can download IntelliJ from https://www.jetbrains.com/idea/download and VS Code from https://code.visualstudio.com/download.

3. Optional: if you do not want to build the application locally, you can run the project from the browser using Gitpod. This will require a Gitpod account. You can sign up for a free account at https://gitpod.io.

[.summary]
== Lesson Summary

In this lesson, you verified your developer environment to ensure that you can begin building your application.

In the next lesson, you will learn how to create a Spring Boot application and add the Spring Data Neo4j library to it.