[.question]
= Excluding data from the Cypher generation

Consider the following scenario.

You have a knowledge graph that contains nodes that you want to ensure is *NOT* queried by the LLM.

The nodes all have a specific label, `Hidden`.

How could you *guarantee* that the `Hidden` nodes are not included in the Cypher generation?

* [ ] Provide additional instructions to the LLM in the Cypher generation prompt.
* [ ] Include an example Cypher query where the `Hidden` nodes are not returned.
* [ ] Filter out any questions that include the `Hidden` nodes before calling the chain.
* [x] Add the `Hidden` nodes to the `exclude_types` parameter of the `GraphCypherQAChain`.

[TIP,role=hint]
.Hint
====
A prompt instruction will not guarantee an LLM will not generate Cypher that includes the `Hidden` nodes.
====

[TIP,role=solution]
.Solution
====
The correct answer is to add the `Hidden` nodes to the `exclude_types` parameter of the `GraphCypherQAChain`.

This will ensure that the `Hidden` nodes are not included in the Cypher generation.
====