= Search lesson content
:order: 3
:type: challenge
:branch: main

[.slide.discrete]
== Overview

In this lesson, you will enhance your agent by adding a search lesson tool using a vector + cypher retriever.

The agent decide will decide which tool is best for each question:

**Schema Tool** - to understand the database structure:

- "What entities exist in the graph?"
- "How are technologies related to concepts?"

**Search Lesson Tool** - for finding content within the lessons:

- "What are the benefits of using GraphRAG?"
- "THow are Knowledge Graphs associated with other technologies?"

[.slide]
== Search lessons tool

You will modify the `agent.py` code to:

. Create a `VectorCypherRetriever` retriever that uses the `Chunk` vector index.
. Define a new `tool` function that uses this retriever to search for lesson content.
. Add the new tool to the agent's list of available tools.

[.slide-only]
====
**Continue with the lesson to create the text to Cypher retriever.**
====

[.transcript-only]
=== Update the agent

Open `workshop-genai\agent.py` and make the following changes:

. Add an embedding model for the retriever to convert the user query into a vector.
+
[source,python]
.embedder
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_vector.py[tag=import_embedder]

include::{repository-raw}/{branch}/workshop-genai/solutions/agent_vector.py[tag=embedder]
----
. Create a `retrieval_query` that the retriever will use to add additional context to the vector search results.
+
[source,python]
.retrieval_query
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_vector.py[tag=retrieval_query]
----
. Create a `VectorCypherRetriever` using the `chunkEmbedding` index, Neo4j `driver`, and `embedder`.
+
[source,python]
.retriever
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_vector.py[tag=import_retriever]

include::{repository-raw}/{branch}/workshop-genai/solutions/agent_vector.py[tag=retriever]
----
. Define a tool function to search for lesson content using the retriever.
+
[source,python]
.Search-lesson-content tool
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_vector.py[tag=search_lessons]
----
+
[NOTE]
.Tool description
====
The tool name `search-lesson-content` and docstring `Search for lesson content related to the query.` help the agent decide when to use this tool.
====
. Update the `tools` list to include the new lesson search tool.
+
[source,python]
.tools
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_vector.py[tag=tools]
----
. Modify the `query` variable to test the new lesson search tool.
+
[source,python]
.query
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_vector.py[tag=query]
----

[%collapsible]
.Reveal the complete code
====
[source, python]
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_vector.py[tags=**;!example_queries]
----
====

Run the agent. The agent should decide to use the new tool based on the query. 

[.slide]
## Experiment

Experiment with agent, modify the `query` to ask different questions, for example:

* `"How are Knowledge Graphs associated with other technologies?"`
* `"Summarize what concepts are associated with Knowledge Graphs?"`
* `"How would you minimize hallucinations in LLMs?"`

Asking questions related to the graph schema should still use the schema tool, for example:

* `"What entities exist in the graph?"`

read::Continue[]

[.summary]
== Lesson Summary

In this lesson, you modified the agent to use an additional tool for searching lesson content using a vector + Cypher retriever.

In the next lesson, you will add tool that can query the database directly using a text to Cypher retriever.
