= Listing Ratings
:type: challenge
:test-number: 13
:branch: 13-listing-ratings

The last remaining element on the Movie page is the list of ratings on the right-hand side of the page.
Although the count in the header is now accurate, the ratings list being returned by the API is still hardcoded.

The list of ratings is populated by the `forMovie()` method in the link:{repository-blob}/src/modules/rating.service.js[`RatingService`^], which currently returns a hardcoded list of ratings.

.src/services/rating.service.js
[source,js,indent=0]
----
include::{repository-raw}/main/src/services/rating.service.js[tag=forMovie]
----

In this challenge, you will run the following Cypher statement in a **read transaction**:

.Get Ratings
[source,cypher]
----
include::{repository-raw}/main/cypher/3-backlog/5-listing-ratings/listing-ratings.cypher[]
----


== Your Task

* Modify the `forMovie()` method to retrieve the ratings from Neo4j.
* Remember to close the session and use the `toNativeTypes()` function to convert the object into native JavaScript types.


[%collapsible]
.Click to reveal the completed `forMovie()` method
====

.src/services/rating.service.js
[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/rating.service.js[tag=forMovie]
----

====


// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-first-rating.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you modified the `forMovie()` method on the `RatingService` to return a paginated list of reviews for a movie from the Neo4j database.

In the next Challenge, you will update the `PersonService` to return list of actors and directors from Neo4j.
