= Listing Ratings
:type: challenge
:test-number: 13
:branch: 13-listing-ratings


The last remaining element on the Movie page is the list of ratings on the right-hand side of the page.
Although the count in the header is now accurate, the ratings being returned by the API are still hardcoded.

If we head over to the `RatingService` in `src/modules/rating.service.js`, we will see that the `forMovie` id currently returns a hardcoded list.


.src/services/rating.service.js
[source,js,indent=0]
----
include::{repository-raw}/main/src/services/rating.service.js[tag=forMovie]
----

We should replace it with a call to Neo4j, running the following query within a **read**  transaction.

.Get Ratings
[source,cypher]
----
include::{repository-raw}/main/cypher/3-backlog/5-listing-ratings/listing-ratings.cypher[]
----

Update the `forMovie` method to retrieve the review details from the database.


[%collapsible]
.Click to reveal the completed `forMovie` method
====

.src/services/rating.service.js
[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/rating.service.js[tag=forMovie]
----

====


// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-first-rating.adoc[]


[.summary]
== Lesson Summary

In this lesson, we modified the `forMovie` method on the `RatingService` to return a paginated list of reviews for a movie from the Neo4j database.

In the next lesson, we will look at populating the list of Actors and Directors.
