= The Home Page
:type: challenge
:order: 4
:branch: 02-movie-lists
:test-filename: 02_movie_list_test
:test-function: TestMovieList
:test-output: true

Now for another challenge.

In this challenge, you will use the knowledge gained so far in this course to add new functionality to the API.
You will modify the `FindAll()` method of the link:{repository-blob}/main/pkg/services/movies.go[`MovieService`^] to do the following:


1. <<Open a new Session>>
2. <<Execute a Cypher statement within a new Read Transaction>>
3. <<Extract a list of Movies from the Result>>
4. <<Return the Results>>


Once you have completed the challenge, you will be asked to run a unit test to verify that the code has been correctly implemented.
If the test runs correctly, the title of the highest rated movie will be logged.
You will need this value to verify that the test has run correctly.


== Exploring the Code

Before you start, let's take a look at the code.
If you are not interested in exploring the code, you can skip straight to <<Implementing Read Transactions>>.

If you start the application and access the app at http://localhost:3000, you will see two lists on the home page; one for Popular Movies and one for Latest Releases.
Both of these lists are populated by a request to link:http://localhost:3000/api/movies[`http://localhost:3000/api/movies`^] with some additional parameters.

=== Route Handler

You can find the route handler, the function that handles the request, in the movies blueprint at link:{repository-blob}/main/pkg/routes/movies.go[`pkg/routes/movies.go`^]:

.pkg/routes/movies.go
[source,go,role=nocopy]
----
include::{repository-raw}/main/pkg/routes/movies.go[tag=list]
----

Within the route handler, you can see that:

1. The _paging_ values, `sort`, `order`, `limit` and `skip` values are extracted from the HTTP request.  This allows us to apply sorting and pagination to the results.
2. The User's ID is extracted from the `Authorization` header, if provided
3. The `FindAll` method is called on the `MovieService` with the paging values and User ID and the results are serialized as JSON.


=== The Movie Service

The magic happens in the `MovieService` implementation, located at link:{repository-blob}/main/pkg/services/movies.go[`pkg/services/movies.go`^].
For this route we are concerned with the `FindAll()` method.

If we take a closer look at the `FindAll()` method, we can see that it currently returns a hardcoded list of popular movies from another file in the repository.

[source,go,indent=0]
.pkg/services/movies.go
----
include::{repository-raw}/main/pkg/services/movies.go[tag=all]
----

You will need to replace these `TODO` comments with working code to complete the challenge.


== Implementing Read Transactions

As you learned in the Sessions and Transactions lesson, you will complete code to open a new session and run the query within a Read Transaction.
Once the query has run, you add code to close the session.
Then, finally you add code to extract and return the results.

=== Open a new Session

Within the `FindAll()` method, first open a new session by calling the `.NewSession()` method on the Driver instance injected into the `MovieService` implementation.
Once this function is completed, the newly opened session will need to be closed.
You can do this by deferring a function which calls the `Close()` method on the session.

The `DeferredClose` function within the link:{repository-blob}/main/pkg/ioutils/errors.go[`ioutils` package^] has been provided to attempt to call the `Close()` method on the provided object and handle any errors.


.Open a new Session
[source,go]
----
include::{repository-raw}/{branch}/pkg/services/movies.go[tag=session,indent=0]
----


=== Execute a Cypher statement within a new Read Transaction

The `session` object provides a `ReadTransaction()` method for which you pass a function to represent the unit of work.
The unit of work is passed a single argument, an instance of `neo4j.Transaction`.  This object provides a `Run()` method that you can call to execute a Cypher statement.
The `Run()` method accepts two arguments:

1. The Cypher statement as a parameterised string.
2. A map containing the values for the parameters prefixed in the query with a dollar sign ($).

.Execute the Query
[source,go]
----
include::{repository-raw}/{branch}/pkg/services/movies.go[tag=allcypher,indent=0]
----

=== Extract a list of Movies from the Result

The result of the query is now available in the `result` variable.

These results must be consumed within the function passed to the `ReadTransaction()` call.
As mentioned in link:../2-results[Processing Results^], you can either use a `for` loop or use `result.Collect()` to extract the `movie` values returned from Neo4j.

.Extract Movie Values
[source,go]
----
include::{repository-raw}/{branch}/pkg/services/movies.go[tag=allmovies,indent=0]
----


=== Return the Results

Finally, check whether the call `session.ReadTransaction()` has returned an error.
If so, return that error.  Otherwise, the function should return the values returned from the call to `ReadTransaction()`.


.Return the Results
[source,go]
----
include::{repository-raw}/{branch}/pkg/services/movies.go[tag=return,indent=0]
----


== Working Solution

[%collapsible]
.Click here to reveal the completed `FindAll()` method
====

.pkg/services/movies.go
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/movies.go[tag=all]
----
====

include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you used your knowledge of sessions and transactions to retrieve a list of Movie nodes from the database.

In the next Challenge, you will write data to the database.
