= How can I import data into Neo4j?
:order: 2
:type: lesson

What do we mean by importing data.- batch/regular import 

Options for importing data. Data source type (CSV, JSON, relational database). Application - use of drivers.

Understand options for import of data into neo4j



In this lesson, you will explore the different approaches for importing data into Neo4j. 

[.video]
video::YouTubeVideoID


[.transcript]

== Approaches for Importing Data

When I say importing data, I mean the process of moving data from one system into Neo4j. 
The import could be a one-time operation, or it could be a regular process that you need to automate.

Typically, the source system would have a different data model than Neo4j, and by importing data, you would transform the data into a graph model.

The source may expose data in different ways, for example:

* Relational Database Management Systems (RDBMS)
* Web APIs
* Public data directories
* BI tools
* Excel
* Flat files (CSV, JSON, XML)

The method by which you import data into Neo4j will depend on several factors, including:

* The source of the data
* The volume of data
* The frequency of the import
* The complexity of the data model
* The transformation required

The options available to you are numerous, and include:

* One-off batch import of all data 
* One-off load with a regular update
* Continuous import of data
* Real-time application updates
* ETL (Extract, Transform, Load) pipelines




[TIP]
====
I asked the Neo4j field team about the most common ways they see data imported into Neo4j.
They shared this flowchart of potential options and tools.

image::images/import-data-charts.svg[A flowchart showing numerous paths and options for importing data into Neo4j. The flowchart lists import tools such as neosemantics, Neo4j admin-import, Custom apps, ETL tools, and more.]

This flowchart is not an exhaustive list or a decision-making tool.

It is a conversation starter, a way to understand some options, decision points, and tools available.
====

Ultimately, how you import data into Neo4j will depend on your specific requirements.

In the next lesson, you will look at some of the tools available for importing data into Neo4j.

[.quiz]
== Check Your Understanding

include::questions/1-best-solution.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you explored some of the approaches for importing data.

In the next lesson, you will learn about potential data sources.