:type: freetext

[.question.freetext]
= Find the third shortest path

As mentioned, you want to display alternative routes to your users in your application.
Use the Yen's algorithm to identify the three shortest paths from from Nashville (BNA) to Phuket (HKT).
Again, make sure you have the *routes* graph projected.
What is the total cost of traversing the third shortest path from Nashville to Phuket?


input::answer[]

* [x] 9389.0

// Once you have entered the answer, click the **Check Answer** button below to continue.

[TIP,role=hint]
.Hint
====
The solution is very similar to the Dijkstra example.
You can use the same configuration as before, and only add the *k* parameter.
Make sure you copy the *totalCost* value of the third row as that is what the question is asking for.
----
MATCH (source:Airport {iata: "BNA"}), (target:Airport {iata:"HKT"})
CALL gds.shortestPath.yens.stream('routes', 
.....
) YIELD totalCost;
----
====


[TIP,role=solution]
.Solution
====
You can run the following Cypher statement to identify the three shortest paths from Nashville to Phuket.

The statement returns three rows from the procedure call, any you need to copy the *totalCost* value in the third row.

----
include::../solution.cypher[]
----
====







