:type: freetext

[.question.freetext]
= Third Shortest Path

What is the total cost of traversing the third shortest path from Nashville to Phuket?

Modify the query to find the three shortest weighted paths and enter the `totalCost` value into the form field below.


input::answer[]

* [x] 9389.0

Once you have entered the answer, click the **Check Answer** button below to continue.


[TIP,role=hint]
.Hint
====
The solution is very similar to the Dijkstra example.

You can use the same configuration as before, and only add the `k`   parameter.
Make sure you copy the *totalCost* value of the third row as that is what the question is asking for.
----
MATCH (source:Airport {iata: "BNA"}), (target:Airport {iata:"HKT"})
CALL gds.shortestPath.yens.stream('routes',
.....
) YIELD totalCost;
----
====


[TIP,role=solution]
.Solution
====
You can run the following Cypher statement to identify the three shortest paths from Nashville to Phuket.


----
include::../solution.cypher[]
----

The statement uses a `WHERE` clause to only return the result where the `index` value is `2` (representing the third row from a zero-based index).
====
