= Building Neo4j Applications with GraphQL
:categories: developer:2, nodejs, graphql:2
:caption: Learn how to use the Neo4j GraphQL library to build Node.js GraphQL APIs backed by the Neo4j graph database.
:status: disabled


== About the course

> {caption}

This course covers building GraphQL APIs using the https://neo4j.com/docs/graphql-manual/current/[Neo4j GraphQL Library.^]

No local setup is required for the course. You will make use of https://codesandbox.io/[Codesandbox^] (a browser-based tool for editing and running code in the browser) and https://neo4j.com/sandbox/[Neo4j Sandbox^]
Each lesson in this course will use a different Codesandbox.

Some familiarity with Neo4j is helpful, such as first completing the https://neo4j.com/graphacademy/training-overview-40/enrollment/["Overview Of Neo4j 4.x"] course, however not strictly required.

== Introduction To GraphQL & Neo4j

[square]
* What is GraphQL and why would I use it?
* An overview of the Neo4j GraphQL Library

Estimated time: _30 minutes_

== The Neo4j GraphQL Library

[square]
* Modeling a graph with GraphQL type definitions
* Creating and querying a GraphQL API using the Neo4j GraphQL Library

Estimated time: _1 hour_

== Adding Custom Logic With Cypher And Custom Resolvers

[square]
* Using the `@cypher` GraphQL schema directive
* Adding custom resolver functions with the Neo4j GraphQL Library

Estimated time: _1 hour_

== Authorization With The Neo4j GraphQL Library

[square]
* Working with JSON Web Tokens (JWTs) to authenticate your API users
* Using the `@auth` GraphQL schema directive to attach authorization rules to your GraphQL API

Estimated time: _1 hour_

== The Neo4j GraphQL OGM

[square]
* Using GraphQL type definitions to define models
* Programmatically query Neo4j using the Object Graph Mapper (OGM) package

Estimated time: _15 minutes_

== Summary

[square]
* Download Certificate of Completion
* Resources to learn more
* Course feedback
