= Adding The Favorite Flag
:type: challenge
:branch: 08-favorite-flag
:previous-branch: 07-favorites-list
:test-filename: 08_favorite_flag_test
:test-function: TestFavoritesFlag

In the previous Challenge, we hardcoded a `favorite` property on the return to the calls in the `FavoriteService`.
We did this because we could guarantee the value based on the query being executed.
This won't be possible in the `MovieService`.

Your next challenge is to modify the link:{repository-raw}/main/pkg/services/movies.go[`MovieService`] to dynamically determine whether a movie is on the current user's My Favorite List.

This challenge has two parts:

1. <<Finding Favorites>>
2. Implement <<Multiple Transaction Calls>>


== Running Multiple Queries within a Transaction

So far, you have only used the `tx` object within the Unit of Work to run a single query.

This will be fine for the majority of cases, but there may also be scenarios where more than one Query may be required.


=== User Favorites

One way that we could find the user's favorites would be to run a separate `MATCH` clause within the same query.
But as all of the routes that interact with the `MovieService` are used by both anonymous and logged in users, this could add unwanted complexity to the Cypher query or the service.

Instead, it would be cleaner to execute two separate queries within the same transaction; one query to fetch a list of the user's favorites, and another to retrieve a list of movies.

The methods in `MovieService` already make a call to the `getUserFavorites()` function within `pkg/services/movies.go` but this currently returns `nil`.
This method expects an instance of `neo4j.Transaction` as the first parameter and the user's ID as the second.

If the `userId` parameter is set, the function should use the `tx` object to run a Cypher query to find the User's favorites and return the `tmdbId` property to be used in the search queries.


== Finding Favorites

For the first part of this challenge, modify the `getUserFavorites()` function  to run the following query against the `tx` object to return a list of IDs for each movie that the user has added to their favorites.

[%collapsible]
.Click here to reveal the Cypher query
====

This query should only run if a user is logged in for the current request, and therefore the `userId` parameter is not `None`.

[source,cypher]
----
include::{cypher-repository-raw}/main/cypher/2-interacting/10-favorite-flag/user-favorites.cypher[]
----
====


=== Working Solution

[%collapsible]
.Click here to reveal the completed `getUserFavorites()` method
====

.
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/movies.go[tag="getUserFavorites"]
----

====


=== Multiple Transaction Calls

Now that the `getUserFavorites()` function has been implemented, we can call it within the `FindAll()` method.
The `tx` object can be used to run as many queries as necessary within the transaction.

Running multiple queries within a transaction limits the amount of work the server has to do when writing data, but you must also be careful not to overload the server within a single transaction otherwise you may experience out-of-memory errors.

To get a list of favorite movies for the user, call `getUserFavorites()` with the `tx` object available within the transaction function and the `userId` passed to the `FindAll` method.  Assign this value to the `favorites` variable.

.Get User Favorites
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/movies.go[tag="favorites"]
----

To use these values in the succeeding query, you can add the `favorites` variable as a parameter in the next `tx.run()` call.

Then, finally, in the Cypher query, add a condition to the return clause to check whther the ID of the current movie is contained in the `$favorites` parameter.

.Using User Favorites
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/movies.go[tag="usefavorites"]
----


=== Comparing Versions

If we take a look at the two versions of the `FindAll()` method, not much has changed.
The `favorites` array has been passed through as a parameter to the query, and the query now uses the Cypher `IN` clause to check if the ID is included in the array.


[.tab]
.Updated Method
====

.pkg/services/movies.go
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/movies.go[tag="allcypher"]
----

====


[.tab]
.Previous Version
====

.pkg/services/movies.go
[source,go,indent=0]
----
include::{repository-raw}/{previous-branch}/pkg/services/movies.go[tag="allcypher"]
----

====


include::../../../../includes/test.adoc[]


include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Module Summary

In this module, you have updated the project to read data from, and write data to Neo4j.
You have also learned about some of the considerations that we need to make when working with the Cypher type system in our Go application.

In the *Project Backlog* module, you will continue to implement the remaining missing pieces of functionality.
This isn't strictly required, but will be good practice for your development journey ahead.
