[.question.freetext]
= Create a native graph projection

Create a native graph projection representing people who acted in movies.

You will need to use the link:https://neo4j.com/docs/graph-data-science/current/management-ops/graph-creation/graph-project/[`gds.graph.project`^] procedure to create the graph projection.

The syntax for the `gds.graph.project` procedure is:

[source, cypher, role=noplay]
----
CALL gds.graph.project(
  graphName: String,
  nodeLabels: List of String,
  relationshipTypes: List of String
)
----

The projection should: 

. Use the name `people-acted-in-movies`
. Include nodes with the labels `Person` and `Movie`
. Use the `ACTED_IN` relationship

Once you have created the projection, you can verify that it was created successfully by listing the graph projections in the database:

[source, cypher]
----
CALL gds.graph.list() YIELD graphName
----

Click the **Check Database** button to verify that there is a projection named `people-acted-in-movies` and that the task is complete.

verify::[]

[TIP,role=hint]
.Hint
====
You previously used the following Cypher to create a native graph projection between `User` and `Movie` nodes with the `RATED` relationship:

[source, cypher]
----
CALL gds.graph.project(
  'native-proj',
  ['User', 'Movie'], 
  ['RATED']
  )
----
====

[TIP,role=solution]
.Solution
====
You can run the following Cypher statement to create the graph projection.

[source, cypher]
----
include::../solution.cypher[]
----
====







