= Creating embeddings
:order: 4
:type: lesson


TODO - update this lesson so it stands alone is part of this module.

Publicly available Large Language Models (LLMs) will typically have an API that you can use to create embeddings for text.

For example, OpenAI has an API that you can use to create embeddings for text.

The following Python program uses the OpenAI API and Python library to create embeddings for text.

[source, python]
----
from openai import OpenAI

llm = OpenAI(api_key="sk-...")

response = llm.embeddings.create(
        input="Text to create embeddings for",
        model="text-embedding-ada-002"
    )

print(response.data[0].embedding)
----

You should be able to identify:

* The `OpenAI` class requires an API key to be passed to it.
* The `llm.embeddings.create` method is used to create an embedding for a piece of text.
* The `text-embedding-ada-002` model is used to create the embedding.
* The `response.data[0].embedding` attribute is used to access the embedding.

To run this code, you will have to:

. Install the `openai` Python package:
+
[source, bash]
----
pip install openai
----
. link:https://platform.openai.com[Create an account with OpenAI^], setup billing, and create an API key.

You should see a response with the embedding for this text. 
Experiment by changing the input text - you will see that the embeddings change.
