= Setting up the Project
:order: 1
:type: lesson
:lab: {repository-link}
:disable-cache: true
:java-version: 17

In order to build an application with Java and connect to a Neo4j database, you will need a few foundational skills. Then you will set up the tools needed.

== Prerequisites

1. Be able to write Java programs. While you can use Neo4j with other JVM languages, this course will use Java.
2. Complete the link:/courses/neo4j-fundamentals/[Neo4j Fundamentals] and link:/courses/cypher-fundamentals/[Cypher Fundamentals] courses. You should be familiar with what a graph is and how to use the Cypher query language to read and write data to Neo4j.

== Tools

We have created a link:{repository-link}[repository^] for this course.
It contains the starter code and resources you need. 

This course defaults to Maven for dependency management, but the application could migrate to use Gradle instead. Users have valid preferences for either dependency management framework, but for simplicity's sake, we chose to only pick one for this course.

A blank Neo4j Sandbox instance has also been created for you to use during this course.

You can open a Neo4j Browser window throughout this course by clicking the link:#[Toggle Sandbox,role=classroom-sandbox-toggle] button in the bottom right-hand corner of the screen.

== Get the code

You can use link:https://gitpod.io[Gitpod^] as an online IDE and workspace for this workshop.
It will automatically clone the workshop repository and set up your environment.

lab::Open `Gitpod workspace`[]

[NOTE]
You will need to login with a Github, Gitlab, or Bitbucket account.

Alternatively, you can clone the repository and set up the environment yourself.

[%collapsible]
.Develop on your local machine
====
1. Verify your Java version. You will need Java 17 or higher. You can check your version by running the following command in your terminal window: +
`java -version`. To download Java, you can choose from many link:https://neo4j.com/docs/operations-manual/current/installation/requirements/#deployment-requirements-software[supported vendor options^]. For example, link:https://www.azul.com/downloads/?package=jdk#zulu[Azul's JDK^] or hlink:ttps://openjdk.org/install/[OpenJDK^].

2. Pick an IDE of your choice. If you don't yet have a preference, you can download link:https://www.jetbrains.com/idea/download[IntelliJ IDEA Community Edition^] or link:https://code.visualstudio.com/download[Visual Studio Code^], are both excellent choices.
====

You do not need to create a Neo4j database as you will use the provided sandbox instance.

read::Continue[]

[.summary]
== Lesson Summary

In this lesson, you reviewed any prerequisites needed to complete this course and set up your development environment to work with Java and Neo4j.

//TODO: Update this!!
// In the next lesson, you will learn about ???.

////
[NOTE]
.Failing tests
====
You will notice that some tests fail when you run `mvn verify`. During the course you will complete the project and resolve the issues.
====

[WARNING]
.Errors while installing dependencies?
====
This project has been written using Java version **{java-version}**.
If you are using the wrong version, you may experience errors when trying to install the dependencies.
====

== Application Configuration

This project uses System properties to manage configuration variables for this project.
When the link:{repository-blob}/main/src/main/java/neoflix/AppUtils.java[`AppUtils.loadProperties()`^] method is called, the `application.properties` file in the `src/main/resources` of the project is parsed and all settings made accessible from `System.getProperty`.

The project contains an example file at `{repository-blob}/main/src/main/resources[example.properties^]`.
You can run the following command from the root folder in your terminal window to copy the example file to `application.properties`.

[source,sh]
cp src/main/resources/example.properties src/main/resources/application.properties

== Start the Project

To start the project, run the following command:

.Start the project using Maven
[source,sh]
mvn compile exec:java

You should see an output similar to the following confirming that the server has successfully started:

.Console Output
[source,console,role=nocopy]
Started server on http://localhost:3000/

== A Brief Tour of the Project

If you open up the listening address in your browser, you will see a Single Page Application (SPA) that communicates with the API served at http://localhost:3000/api/movies[http://localhost:3000/api/movies^].
Currently, the responses are hardcoded, but as you progress through the course, you will learn how to query Neo4j to find this information.

Here are some of the important directories in the project:

* `src/main/java/example/` - Example code for driver instantiation.
* `src/main/java/neoflix` - The application code:
** `src/main/java/neoflix/routes/` - Route handlers that are registered on the server.  You shouldn't need to edit these files.
** `src/main/java/neoflix/services/` - Services that you will need to update to interact with Neo4j.
* `src/test/java/neoflix` - Test files that will you will need to run in order to pass the test.  You will run these using the `mvn test` or individually with the +
`mvn test -Dtest=neoflix._0x_XxxTest#methodName` command.
* `src/main/resources/public/` - Minified build files for the Web application.  *Do not edit these files*.

== Done!

Once you have the project up and running, click the button below to complete this lesson.

read::The project is running![]
////
