= Installing the driver
:type: lesson
:slides: true
:order: 1
:minutes: 10

// * Installation
// *  Import into project
// * Driver
// * session
// * Closing connection
// * try-with-resources

[.slide.discrete]
== Introduction
In the link:/courses/cypher-fundamentals/[Cypher Fundamentals^] course, you learned how to query Neo4j using Cypher.

To run Cypher statements in a Python application, you'll need the link:https://neo4j.com/developer/python[Neo4j Python Driver^].
The driver acts as a bridge between your Python code and Neo4j, handling connections to the database and the execution of Cypher queries.

[.slide]
== Installing the Driver

To install the driver, use pip:

[source,shell]
pip install neo4j

[.slide.col-2]
== Creating a Driver Instance

[.col]
====
You start by importing the driver and creating an instance:

[source,python]
----
from neo4j import GraphDatabase

driver = GraphDatabase.driver(
  "neo4j://localhost:7687",       # <1>
  auth=("neo4j", "your-password") # <2>
)
----
====

[.col]
====
<1> The connection string for your Neo4j database
<2> Your Neo4j username and password


[TIP]
.Best Practice
=====
Create **one** Driver instance and share it across your entire application.
=====

// [.transcript-only]
// =====

// [%collapsible]
// .Connect to your Neo4j Sandbox?
// ======
// If you want to experiment with the driver, you can connect to the Neo4j Sandbox which has been created for you.

// Neo4j Connection String:: [copy]#neo4j://{sandbox-ip}:{sandbox-boltPort}#
// Username:: [copy]#{sandbox-username}#
// Password:: [copy]#{sandbox-password}#
// ======

// =====
// ====

[.slide]
== Verifying Connectivity

You can verify the connection are correct by calling the `verifyConnectivity()` method.

[source,python]
----
driver.verify_connectivity()
----

[NOTE]
.Verify Connectivity
=====
The `verifyConnectivity()` method will link:https://neo4j.com/docs/api/python-driver/current/api.html#errors[raise an exception^] if the connection cannot be made.
=====


[.slide,role="col-2"]
== Running Your First Query

[.col]
====
The `execute_query()` method executes a Cypher query and returns the results.

[source,python]
----
records, summary, keys = driver.execute_query( # <1>
    "RETURN COUNT {()} AS count"
)

# Get the first record
first = records[0]      # <2>

# Print the count entry
print(first["count"])   # <3>
----
====

[.col]
=== What is happening here?
<1> `execute_query()` runs a Cypher query to get the count of all nodes in the database
<2> `records` contains a list of the rows returned
<3> Keys from the `RETURN` clause are accessed using dictionary-style indexing with square brackets (`[]`)

[.slide]
== Full driver lifecycle

Once you have finished with the driver, call `close()` to release any resources held by the driver.

[source,python]
----
driver.close()
----

You can use `with` to create an all-in-one solution that will automatically close the driver when the block is exited.

[source,python]
----
with GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD)) as driver:
    result, summary, keys = driver.execute_query("RETURN COUNT {()} AS count")
----


[.next.discrete]
== Check your understanding

link:../2c-create-driver-instance/[Take challenge,role=btn]

[.summary]
== Lesson Summary

In this lesson you learned how to install the Neo4j Python Driver, create a Driver instance, verify connectivity to your database, and execute your first Cypher statement.

For async applications, link:https://neo4j.com/docs/python-manual/current/concurrency/[use the `AsyncGraphDatabase` method].

In the next lesson, you will take a quiz to test your knowledge of installing and creating a driver instance.
