= Installing the driver
:type: video
:slides: true
:order: 1
:minutes: 10

// * Installation 
// *  Import into project 
// * Driver
// * session
// * Closing connection 
// * try-with-resources

[.slide.discrete]
== Introduction
In the link:/courses/cypher-fundamentals/[Cypher Fundamentals^] course, we covered how to query Neo4j using Cypher.

To run Cypher statements in a Python application, you'll need the link:https://neo4j.com/developer/python[Neo4j Python Driver^]. 
The driver acts as a bridge between your Python code and Neo4j, handling connections to the database and the execution of Cypher queries.

[.slide]
== Installing the Driver

To install the driver, use pip:

[source,shell]
pip install neo4j

[.slide]
== Creating a Driver Instance

[.col]
====
First, import the driver and create an instance:

[source,python]
----
from neo4j import GraphDatabase

driver = GraphDatabase.driver(
  "neo4j://localhost:7687",       # <1>
  auth=("neo4j", "your-password") # <2>
)
----
====

[.col]
<1> The connection string for your Neo4j database
<2> Your Neo4j username and password


[.slide]
== Verifying Connectivity

You can verify that the connection details used during driver instantiation are correct by calling the `verifyConnectivity()` function. 
This function will raise a `Neo4jException` with a `code` property of `Neo.ClientError.Security.Unauthorized` if a connection could not be made.

[.transcript-only]
=====
This only appears in the transcript.
=====

[source,python]
----
driver.verify_connectivity()
----

[TIP]
.Best Practice
====
Create just **one** Driver instance for your entire application. This single instance can be safely shared across your code.
==== 

[.slide,role="col-2"]
== Running Your First Query

[.col]
====
The `execute_query()` executes a Cypher query and returns the results.

[source,python]
----
records, summary, keys = driver.execute_query( # <1>
    "RETURN COUNT {()} AS count" 
)

# Get the first record
first = records[0]      # <2>

# Print the count entry
print(first["count"])   # <3>
----
====

[.col]
=== What is happening here?
<1> `execute_query()` runs a Cypher query to get the count of all nodes in the database
<2> `records` contains a list of the rows returned
<3> Keys from the `RETURN` clause are accessed using dictionary-style indexing with square brackets (`[]`)

[.slide]
== Full driver lifecycle

Once you have finished with the driver, call `close()` to release any resources held by the driver.

[source,python]
----
driver.close()
----

For an all-in-one solution, use the `try-with-resources` statement.

[source,python]
----
with GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD)) as driver:
    result, summary, keys = driver.execute_query("RETURN COUNT {()} AS count")
----

Once the block is exited, the driver is closed automatically.



[.next.discrete]
== Check your understanding

read::Take challenge[]

[.summary]
== Lesson Summary

In this lesson you learned how to install the Neo4j Python Driver, create a Driver instance, verify connectivity to your database, and execute your first Cypher statement.

For async applications, link:https://neo4j.com/docs/python-manual/current/concurrency/[use the `AsyncGraphDatabase` method].

Now it's your turn.  In the next challenge, you will install the driver and create a new driver instance.

// Next, we'll explore more ways to work with query results.
