= The GraphAcademy platform
:order: 2

GraphAcademy is a custom-built platform that brings together tools and infrastructure from across the company to provide the best learning experience.


== Repositories

=== `neo4j-graphacademy/website`

All code for the underlying website is held in the link:https://github.com/neo4j-graphacademy/website[`neo4j-graphacademy/website` repository on Github^].


=== `neo4j-graphacademy/certifications`

All certifications and question banks are held in the  link:https://github.com/neo4j-graphacademy/certifications[`neo4j-graphacademy/certifications` repository^].


=== `neo4j-graphacademy/courses`

All link:https://github.com/neo4j-graphacademy/courses[`neo4j-graphacademy/courses` repository^]


== Courses Repository

The courses repository has the following folders:

* `asciidoc/` - All content for courses and emails
* `cypress/` - End-to-end testing using link:https://Cypress.io[Cypress]
* `docs/` - Documentation and FAQs for the repo
* `prompts/` - LLM prompts to perform common tasks
* `public/` - Course files synced to https://cdn.graphacademy.neo4j.com/assets/
* `resources/` - HTML and CSS used to style course banners
* `src/` - TypeScript code to import course metadata into Neo4j
* `tests/` - TypeScript tests for QA
* `views/` - Pug templates for course banners


[source]
----
asciidoc/
└── ads/                - asciidoc attributes used to place advertisements into docs
└── categories/
└── certifications/
└── courses/
└── emails/
└── languages/
└── promos/
└── shared/
└── statuses/
----



== Asciidoc Folder



=== Standard Directory Structure
[source]
----
asciidoc/
└── courses/
    └── course-name/
        ├── course.adoc
        └── modules/
            └── 1-module-name/
                ├── module.adoc
                └── lessons/
                    └── 1-lesson-name/
                        ├── lesson.adoc
                        ├── exercises/
                        └── images/
----