[.question]
= 1. Algorithm Purpose

What can similarity algorithms accomplish in GDS? (select all that apply)

* [ ] Finds similarity relationship pairs in the graph
* [x] Find similarity between pairs of nodes based on the neighboring nodes that they share
* [x] Calculate the similarity between node pairs based solely on the similarity of node properties
* [x] Draw relationships to connect similar node pairs together in the graph


[TIP,role=hint]
.Hint
====
Similarity algorithms determine the similarity between pairs of nodes by examining shared neighboring nodes, evaluating the similarity based on node properties alone, and establishing connections between similar node pairs within the graph.
====

[TIP,role=solution]
.Solution
====
The correct answers are:

**Find similarity between pairs of nodes based on the neighboring nodes that they share** +
**Calculate the similarity between node pairs based solely on the similarity of node properties** +
**Draw relationships to connect similar node pairs together in the graph**
====
