
In this course, you have learned:

* What a graph data model is
* Reading data from the graph
* Writing data to the graph

== Resources

* *The Neo4j Cypher documentation:* +
https://neo4j.com/docs/cypher-manual/current/

* *The Neo4j Cypher RefCard:* +
https://neo4j.com/docs/cypher-refcard/current/

* *There are many resources available to you for learning more about Neo4j and Cypher.* +
https://neo4j.com/developer/resources/

* *Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users:* +
https://community.neo4j.com

* *Neo4j Sandboxes for experimenting with graphs:* +
https://sandbox.neo4j.com/?ref=graph-academy

* *Videos on  the Neo4j YouTube channel:* +
https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

* *Neo4j online and classroom training:* +
https://neo4j.com/graphacademy/

* *Become a Neo4j certified developer:* +
https://neo4j.com/graphacademy/neo4j-certification/

* *Neo4j events all over the world:* +
https://neo4j.com/events/world/all/

* *Graph Gists for learning more use cases for Neo4j:* +
https://neo4j.com/graphgists/

* *Attend a Neo4j meetup:* +
https://www.meetup.com/topics/neo4j/

* *View questions/answers raised about Neo4j:* +
https://stackoverflow.com/tags/neo4j/hot


== Course feedback

We want your feedback on this course. Please provide your https://forms.gle/k6nhzMXiYFyUYUNs7[feedback] so we can improve this course.
