= Connection Strings and Authentication
:type: quiz

In the previous lesson, we saw some example code for creating a new driver instance.

.Creating a Driver Instance
[source,js]
----
const driver = neo4j.driver(
  connectionString, // <1>
  authenticationToken, // <2>
  configuration // <3>
)
----

The `neo4j.driver` function accepts the following arguments:

<1> A connection string
<2> An authentication token
<3> Optionally, an object containing additional driver configuration

Let's take a look at these arguments in more detail.



== `1` The Connection String


Here is an example connection string for connecting to a local Neo4j instance:

.Example Connection String
[source,role=nocopy]
----
  address of server
          ↓
neo4j://localhost:7687
  ↑                ↑
scheme        port number
----


Let's take a look at this connection string in more detail.

A connection string typically consists of four elements.

1. The **scheme** used to connect to the Neo4j instance - for example `neo4j` or `neo4j+s` (required)
2. The server address for the Neo4j Service - for example `localhost` or `databaseid.databases.neo4j.io` (required)
3. The **port number** that the Neo4j service is running on (required if the instance is not runnong on the default port of `7687`)
4. Additional connection configuration (for example the routing context)


=== Choosing your Scheme

Most likely, you will use a variation of the `neo4j` scheme within your connection string.

* `neo4j` - Creates an **unencrypted** connection to Neo4j.  If you are connecting to a local Neo4j instance or have not explicitly turned on encryption then this is most likely the option you are looking for
* `neo4j+s` - Creates an **encrypted** connection to Neo4j.  The driver will verify the authenticity of the certificate and fail to verify connectivity if there is a problem with the certificate.
* `neo4j+ssc` - Creates an encrypted connection to Neo4j, but will not attempt to verify the authenticity of the certificate.

Variations of the `bolt` scheme can be used to connect directly to a single Neo4j instance.  This can be useful if you have a single server configured for data science or analytics.

* `bolt` - Creates an unencrypted connection directly to a single Neo4j instance.
* `bolt+s` - Creates an encrypted connection directly to a single Neo4j instance and verify the certificate.
* `bolt+ssc` - Creates an encrypted connection to directly to a single Neo4j instance but will not attempt to verify the authenticity of the certificate.



[TIP]
.Which scheme string is right for you?
====
You can https://neo4j.com/docs/migration-guide/current/upgrade-driver/#_configure_ssl_policy_for_bolt_server_and_https_server[verify the encryption level of your server^] by checking the `dbms.connector.bolt.enabled` key in `neo4j.conf`.

If you are connecting to an instance hosted on Neo4j Aura, you will always use the `neo4j+s` scheme.
====

== `2` An Authentication Token

In most cases, you will connect to Neo4j using basic authentication consisting of a username and password.
You can create a basic authentication token by calling the `basic` method on the `neo4j.auth` object.

.Creating a Basic Authentication Token
[source,js]
----
neo4j.auth.basic(username, password)
----

Neo4j also supports kerberos authentication tokens and can be extended to support custom authentication.
These authentication methods require additional configuration and are outside of the scope of this course.
For more information, see the link:https://neo4j.com/docs/operations-manual/current/authentication-authorization/[Authentication and authorization^] section of the link:https://neo4j.com/docs/operations-manual/current/[Neo4j Operations Manual^]



== `3` Additional Driver Configuration (Optional)

The `driver` method also accepts additional configuration.  This object allows you to provide advanced configuration options, for example setting the connection pool size or changing timeout limits.

.Example Additional Configuratiob
[source,js]
----
{
  maxConnectionPoolSize: 100,
  connectionTimeout: 30000, // 30 seconds
  logging: {
    level: 'info',
    logger: (level, message) => console.log(level + ' ' + message)
  },
}
----

For more information or a full list of configuration options, please link:https://neo4j.com/docs/javascript-manual/current/get-started/[visit the Neo4j JavaScript Driver manual^].



== What happens next?

The driver will attempt to connect to a Neo4j instance using the supplied credentials.
If everything is successful, the driver will then take use the server configuration details to work out whether to send the queries to a single instance or distribute the queries across the cluster.

This means that regardless of whether you are connecting to a single instance of Neo4j or a cluster of servers, your application code will remain the same.

Once the connection has been successfully made, we can start to interact with the data in the graph.


== Check Your Understanding

include::./questions/1-authentication-methods.adoc[]

include::./questions/2-aura-scheme.adoc[]

[.summary]
== Lesson Summary

In this lesson, we took a closer look at how to configure the driver.
Now it is time to add a Driver instance to our project.