= Connection Strings and Authentication
:type: lesson
:order: 2

In the previous lesson, you saw some example code for creating a new driver instance.
Let's take a closer look at the `driver()` method and how it is used to create a driver instance.

.Creating a Driver Instance
[source,js,indent=0,subs="attributes+"]
----
include::{repository-raw}/main/example/index.js[tag=pseudo]
----

The `neo4j.driver()` function accepts the following arguments:

1. A connection string
2. An authentication token
3. Optionally, an object containing additional driver configuration

Let's take a look at these arguments in more detail.


// == 1. Connection String
include::{shared}/courses/apps/connection-strings.adoc[tags="connectionstring"]


== `2` An Authentication Token

In most cases, you will connect to the DBMS using basic authentication consisting of a username and password.
You can create a basic authentication token by calling the `basic()` method on the `neo4j.auth` object.

.Creating a Basic Authentication Token
[source,js,role=nocopy,subs="attributes+"]
----
include::{repository-raw}/main/example/index.js[tag=auth]
----

// For more information on additional authentication methods...
include::{shared}/courses/apps/connection-strings.adoc[tags="tokenafter"]


== `3` Additional Driver Configuration (Optional)

The `driver()` method also accepts a third additional configuration object.
This object allows you to provide advanced configuration options, for example setting the connection pool size or changing timeout limits.

.Example Additional Configuration
[source,js,role=nocopy]
----
{
  maxConnectionPoolSize: 100,
  connectionTimeout: 30000, // 30 seconds
  logging: {
    level: 'info',
    logger: (level, message) => console.log(level + ' ' + message)
  },
}
----

For more information or a full list of configuration options, please link:https://neo4j.com/docs/javascript-manual/current/get-started/[visit the Neo4j JavaScript Driver manual^].


// == What happens next?
include::{shared}/courses/apps/connection-strings.adoc[tag="next"]

== Check Your Understanding

// To do: need to add some hints for these

include::./questions/1-valid-schemes.adoc[leveloffset=+1]

include::./questions/2-aura-scheme.adoc[leveloffset=+1]

// == Summary
include::{shared}/courses/apps/connection-strings.adoc[tag="summary"]

