[.question.freetext]
= How many options do you have to get from Nashville to Phuket with the smallest amount of flights?

You already know that you have to take at least 3 flights to get from Nashville to Phuket.
Now you will examine if there are multiple routes from Nashville to Phuket with the smallest amount of flights.
Use the Neo4j Browser window to the right of the screen to modify the query to find the number of alternative shortest routes from Nashville (BNA) to Phuket (HKT).

Enter the **number** of alternative routes in the box below, then click the **Check Answer** button below to continue.

input::answer[]

* [x] 206

// Once you have entered the answer, click the **Check Answer** button below to continue.

[TIP,role=hint]
.Hint
====
You are looking for the number of path objects between _BNA_ and _HKT_ airports that the `allShortestPaths` function returns.
You can find the result by counting the shortest paths between the two airports with the `count` function.
====

[TIP,role=solution]
.Solution
====
You can use the following query to count the number of alternative shortest routes from Nashville (BNA) to Phuket (HKT):

[source,cypher]
----
include::../solution.cypher[]
----

Click the **Run in Sandbox** button to reveal the answer in the Sandbox window.
====