= Handling errors
:type: quiz
:minutes: 10
:order: 4

Let's practice error handling in a real-world scenario.

You have built an application that includes a registration form for new users.
As part of the setup, you have added a unique constraint on the `email` property for the `User` label.

[source,cypher]
.Creating a unique constraint
----
CREATE CONSTRAINT unique_email IF NOT EXISTS
FOR (u:User) REQUIRE u.email IS UNIQUE
----

Your application includes a method called `addUser` that creates a new user in the database.
It does not check for existing users with the same email address, and instead relies on the database to enforce the constraint.

include::./questions/1-constraint-error.adoc[leveloffset=+1]


[summary]
== Lesson Summary

In this challenge you demonstrated how to handle errors in a real-world scenario.

You should now have all of the information needed to build a Java application that connect to Neo4j and the confidence put it into production.

[TIP]
.Next Steps
====
Ready for your next challenge?

The link:/courses/drivers-Java/?ref=summary[Using Neo4j with Java^] course will teach you how to connect to Neo4j in your Java applications.
====
