= Accessing Results
:type: quiz
:order: 5

So far, we have used the `neo4j.CollectTWithContext()` method to access results.
This method is the most convenient, and provides an element of type safety but it may not always be the best option.

Let's look at some of the other methods that we can use to access the data returned to us by the Driver.

== `for` Loops

The `result` object returned by `session.Run()` and `tx.Run()` is an iterable object known as a cursor.
Individual records are available in the cursor until they are consumed.

You can check that there are results remaining in the cursor by calling the `.Next()` method.
While the `.Next()` returns `true`, you can call the `.Record()` method to get the next record.

.Accessing a Record
[source,go]
----
include::{repository-raw}/main/pkg/example/example.go[tag="Next"]
----


It is important to verify the value returned by the `Err()` is `false` after calling the `.Next()` method to find out whether the the last result is the final result witin the stream, or an error has occurred to cause the end of result consumption.

=== `NextRecord()`

Alternatively, you can use the `NextRecord()` method which has the same outcome with less code.

.The NextRecord() Method
[source,go]
----
include::{repository-raw}/main/pkg/example/example.go[tag="NextRecord"]
----

== Getting the only result with `Single()`

If you are expecting a single result, you can call the `Single()` method to access the first and only result.

.The Single() Method
[source,go]
----
include::{repository-raw}/main/pkg/example/example.go[tag="Single"]
----

If the result stream contains zero or more than one records, an error is returned.


== Get all remaining results with `Collect()`

The `Collect()` method fetches all remaining records and returns them as an array.

.The Collect() Method
[source,go]
----
include::{repository-raw}/main/pkg/example/example.go[tag="Collect"]
----

== Consume remaining results with `Consume()`

Calling the `Consume()` method will discard any remaining records from the stream and return a `ResultSummary` object which holds information about the statement execution, including database information, execution time and in the case of a write query, statistics on changes made to the database as a result of the statement execution.

.The Consume() Method
[source,go]
----
include::{repository-raw}/main/pkg/example/example.go[tag="Consume"]
----


== Exploring Records

The `record` variable above provides an interface to retrieve individual values.
Take the example above, each record will contain information on `:Movie` and `:Person` nodes, and the `:ACTED_IN` relationship.

To access the keys available in each record, you can use the `.Keys` property.
This is an array of strings.

.The Keys Array
[source,go,indent=0]
----
include::{repository-raw}/main/pkg/example/example.go[tag="keys"]
----

To access these values, we can either use the index of the key above, or the alias specified in the `RETURN` portion of the Cypher statement.


[source,go]
----
include::{repository-raw}/main/pkg/example/example.go[tags="index,alias",indent=0]
----



== Check Your Understanding

include::./questions/1-first-method.adoc[leveloffset=+2]

include::./questions/2-consume-method.adoc[leveloffset=+2]

include::./questions/3-collect.adoc[leveloffset=+2]


[.summary]
== Lesson Summary

You now have all of the information required to send Cypher queries to Neo4j and consume the results.

Next, we will look at the Neo4j Type System and some of the considerations that you need to make when working with values coming from Neo4j in your Go application.
