= Movie Lists and Pagination
:type: challenge
:order: 3
:optional: true
:branch: 11-movie-lists
:previous-branch: 10-genre-details
:test-filename: 11-MovieLists
:test-pattern: _11_MovieLists

In this challenge, you will implement the remaining methods in the link:{repository-blob}/main/Neoflix/Services/MovieService.cs[`MovieService`^] for retrieving a list of movies:

* <<GetByGenreAsync>> - should return a paginated list of movies that are listed in a particular Genre
* <<getForActorAsync>> - should return a paginated list of movies that a particular Person has acted in
* <<getForDirectorAsync>> - should return a paginated list of movies that a particular Person has directed

These methods are very similar to the `AllAsync()` method which returns a full list, but with a different pattern in the `MATCH` clause.

NOTE: Because we also want to support sorting and pagination, we need to pass the values we get from the http-request in the route as `$skip` and `$limit` from the request as parameters and string-replace the field to order for `sort` and `order` direction (as those cannot be parameterized).

.Neoflix/Services/MovieService.cs - AllAsync() method
[source,c#,indent=0]
----
include::{repository-raw}/{branch}/Neoflix/Services/MovieService.cs[tag=all]
----

For each subtask, we will provide you with the pattern required to run in the Cypher statement, plus any additional parameters that are required for the query to run.

All you need to do is take the code from the `AllAsync()` method and modify the pattern in the first line of the Cypher statement in the first argument of the `tx.RunAsync()` call, then if necessary add the additional parameters to the second argument.

If you get stuck at any point, you can click to reveal the completed solution or skip to the bottom for instructions on how to checkout the branch with the working solution.

== GetByGenreAsync

The `GetByGenreAsync()` method returns a paginated list of movies that are listed within a certain genre.

.Neoflix/Services/MovieService.cs
[source,c#,indent=0]
----
include::{repository-raw}/main/Neoflix/Services/MovieService.cs[tag=getByGenre]
----

Update the `GetByGenreAsync()` method to use the following Cypher Pattern:

[source,cypher,role=norun]
----
MATCH (m:Movie)-[:IN_GENRE]->(:Genre {name: $name})
----

The `tx.RunAsync()` call will need to include the `name` parameter, which represents the name of the genre.


[%collapsible]
.Click to reveal the completed `GetByGenreAsync()` method
====

Find the `GetByGenreAsync()` method in `Neoflix/Services/MovieService.cs` and modify the function to find a list of movies by genre.

.Neoflix/Services/MovieService.cs
[source,c#,indent=0]
----
include::{repository-raw}/{branch}/Neoflix/Services/MovieService.cs[tag=getByGenre]
----

====



== getForActorAsync

The `GetForActorAsync()` method returns a paginated list of movies that a person has acted in.

.Neoflix/Services/MovieService.cs
[source,c#,indent=0]
----
include::{repository-raw}/main/Neoflix/Services/MovieService.cs[tag=getForActor]
----

Find the `GetForActorAsync()` method in `Neoflix/Services/MovieService.cs` and modify the function to find a list of movies by actor.

The pattern required in the `MATCH` clause will be:

[source,cypher,role=norun]
----
MATCH (:Person {tmdbId: $id})-[:ACTED_IN]->(m:Movie)
----

You will have to include the additional parameter `id` - The `tmdbId` property relating to the actor.

[%collapsible]
.Click to reveal the completed `GetForActorAsync()` method
====

.Neoflix/Services/MovieService.cs
[source,c#,indent=0]
----
include::{repository-raw}/{branch}/Neoflix/Services/MovieService.cs[tag=getForActor]
----

====

== getForDirectorAsync

The `GetForDirectorAsync()` method returns a paginated list of movies that a person has directed.

.Neoflix/Services/MovieService.cs
[source,c#,indent=0]
----
include::{repository-raw}/main/Neoflix/Services/MovieService.cs[tag=getForDirector]
----

Find the `GetForDirectorAsync()` method in `Neoflix/Services/MovieService.cs` and modify the function to find a list of movies by director.

The pattern required in the `MATCH` clause will be:

[source,cypher,role=norun]
----
MATCH (:Person {tmdbId: $id})-[:DIRECTED]->(m:Movie)
----

You will have to include the additional parameter `id` - The `tmdbId` property relating to the director.


[%collapsible]
.Click to reveal the completed `GetForDirectorAsync()` method
====

.Neoflix/Services/MovieService.cs
[source,c#,indent=0]
----
include::{repository-raw}/{branch}/Neoflix/Services/MovieService.cs[tag=getForDirector]
----

====

// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-coppola-films.adoc[leveloffset=+2]


[.summary]
== Lesson Summary

In this Challenge, you modified the functions in the `MovieService` to return lists of movies.

In the next Challenge, we will implement the `FindByIdAsync()` method.
