= Neo4j & LLM Fundamentals
:categories: llms:1
:status: active
:duration: 4 hours
:next: llm-chatbot-python
:caption: Learn how to use Neo4j with Large Language Models
:usecase: blank-sandbox
// :video: https://www.youtube.com/embed/vVCHJFa01gA
:key-points: Neo4j and Generative AI, Grounding LLMs with Neo4j, Using Neo4j with Langchain

== Course Description

In this course, you will learn how to integrate Neo4j with Generative AI models using link:https://www.langchain.com/[Langchain^].

You will learn why graph databases are a reliable option for grounding Large Language Models (LLMs), using Neo4j to provide factual, reliable information to stop the LLM from giving false information, also known as *hallucination*.

You will use link:https://www.langchain.com/[Langchain^] and Python to interact with an LLM and Neo4j. Langchain provides a robust basis for AI application development and comes with Neo4j integrations for Cypher and Vector Indexes.

This course focuses on link:https://openai.com/[OpenAI^], although Langchain allows you to work with the LLM of your choice.

=== Prerequisites

Before taking this course, you should have:

* A basic understanding of Graph Databases and Neo4j
* Knowledge of Python and capable of reading simple programs

We recommend taking the link:/courses/neo4j-fundamentals/[Neo4j Fundamentals^] course.

Although not essential, you may also benefit from taking the link:/courses/app-python/[Building Neo4j Applications with Python^] course to understand how the Neo4j Python Driver works.

To complete the practical tasks within this course, you will need an link:https://platform.openai.com[OpenAI billing account and API key^].

=== Duration

{duration}

=== What you will learn

* Retrieval Augmented Generation (RAG) and its role in grounding LLM generated content
* Using Vector and full text indexes in Neo4j to perform similarity and keyword search
* Coordinating your LLM interactions with Langchain chains, agents and tools

[.includes]
== This course includes

* [lessons]#19 lessons#
* [challenges]#3 short hands-on challenges#
// * [videos]#7 videos#
// * [quizes]#2 multiple choice quizzes#