= Mastering Retrieval-Augmented Generation (RAG)
:status: active
:duration: 2 hours
:caption: Learn how to implement GraphRAG with the neo4j-graphrag Python Package
:usecase: recommendations
:key-points: A comma, separated, list of learnings
:repository: neo4j-graphacademy/genai-workshop-graphrag

== Course Description

In this workshop, you will learn about the neo4j-graphrag Python open-source package and how it can be used to build Retrieval-Augmented Generation (RAG) applications.
You will also learn how to integrate Neo4j with generative AI models to enhance graph-powered applications and AI solutions.

You will:

* Use embeddings and a vector index in Neo4j to perform similarity search
* Use a full-text index in Neo4j to perform keyword search
* Use Python and the neo4j-graphrag package to integrate with Neo4j and OpenAI
* Learn about Large Language Models (LLMs), hallucinations and integrating knowledge graphs
* Explore Retrieval Augmented Generation (RAG) and its role in grounding LLM-generated content

After completing this workshop, you will be able to explain the terms LLM, RAG, grounding, and knowledge graphs. You will also have the knowledge and skills to create simple LLM-based applications using Neo4j and Python.

=== Prerequisites

Before taking this course, you should have:

* A basic understanding of Graph Databases and Neo4j
* Knowledge of Python and capable of reading simple programs

While not essential, we recommend completing the GraphAcademy link:/courses/neo4j-fundamentals/[Neo4j Fundamentals^] course.

=== Duration

{duration}

== What you need

To complete the practical tasks within this workshop, you will need: 

* Access to gitpod.io (you will need a Github account) or a local Python environment
* An OpenAI billing account and API key

[.includes]
== This workshop includes

* [lessons]#7 lessons#
* [challenges]#12 short hands-on challenges#
