= Course Summary

Congratulations on completing the Mastering Retrieval-Augmented Generation Workshop.

You have:

* Uses vector indexes to search for similar data
* Created embeddings and vector indexes
* Built a graph of unstructured data using Python and the GraphRAG Python package
* Learned to use various retrievers in the `neo4j-graphrag` package for Python.
* Explored the `VectorRetriever` and `VectorCypherRetriever` for semantic and filtered searches.
* Utilized the `HybridRetriever` and `HybridCypherRetriever` to combine vector, full-text, and graph traversal techniques.
* Discovered the `Text2CypherRetriever` to translate natural language queries into Cypher.
* Built a multimodal application by combining textual and visual data.

Continue your learning with the following resources:

* link:https://graphacademy.neo4j.com[GraphAcademy^] - Free online training for Neo4j
* link:https://graphacademy.neo4j.com/courses/genai-fundamentals/[Neo4j & GenerativeAI Fundamentals^] - Learn how Neo4j and GraphRAG can support your Generative AI projects
* link:https://graphacademy.neo4j.com/courses/llm-chatbot-python/[Build a Neo4j-backed Chatbot using Python] - Get hands-on and create a chatbot with Neo4j, Python, and Streamlit
