= Using query hints
:type: challenge
:sandbox: true

== Step 1: Create TEXT index

Create a TEXT index on the ACTED_IN relationship using the role property.
Name this index [copy]#ACTED_IN_role_text#.

== Step 2: Query the graph without specifying any query hints

Execute this query:

[source,cypher]
----
PROFILE MATCH
(p:Person)-[r:ACTED_IN]->(m:Movie)
WHERE
p.name CONTAINS 'George'
AND
r.role CONTAINS 'General'
RETURN p.name, r.role, m.title
----

This query should return 2 rows.
What index does it use?

Modify the query to use the ACTED_IN_role_text index as a query hint.

Does it use the correct index?

Is the performance better?

In this case you will see that the elapsed time using either query is about the same, but there are fewer db hits with the use of the TEXT index on the relationship property.

include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Summary

In this Challenge, you demonstrated that you can specify a query hint for an index on a relationship.
In the next lesson, you will learn how  important index best practices must be followed.