= About the Driver
:type: quiz

As we covered in the link:/courses/cypher-fundamentals/[Cypher Fundamentals^] course, we query Neo4j using a language called Cypher.
In order to send Cypher queries from our application we use an object called a *Driver*.

> The **Driver** object is a thread-safe, application-wide fixture from which all Neo4j interaction derives.
>
> The Driver API is **topology independent**, so you can run the same code against a *cluster* or a *single instance*.

The link:https://neo4j.com/developer/javascript[Neo4j JavaScript Driver^] is officially supported and connects to a Neo4j instance using the Bolt protocol.
The Neo4j JavaScript Driver is one of five officially supported drivers, the others are Java, .NET, Python and Go.
There are also a wide range of Community Drivers available for other languages including PHP and Ruby.

You should create a single instance of the Driver in your application, which you should  share across your modules.



== Installing the Driver

The Neo4j JavaScript Driver is available through the npm registry and can be installed with either `npm` or `yarn`.

[.tab]
.NPM
====
To install using link:https://www.npmjs.com/[NPM^], run the following command.

.NPM
[source,shell]
npm install --save neo4j-driver

// include::{repository-raw}/main/README.adoc[tag=npm]

The `--save` option will save a reference to the `neo4j-driver` package in your `package.json` file.

====

[.tab]
.Yarn
====

To install using link:https://yarnpkg.com/[Yarn^], run the following command.

.Yarn
[source,shell]
yarn add --save neo4j-driver

// include::{repository-raw}/main/README.adoc[tag=yarn]

The `--save` option will save a reference to the `neo4j-driver` package in your `package.json` file.
====

== Creating a Driver Instance

Each driver instance will connect to one server, or cluster of servers depending on the value provided in the connection string.

The `neo4j-driver` package exports a default `neo4j` object.  This object provides a `driver` method for creating a new driver instance.  The `driver` method takes two arguments:

1. **A connection string** for the Neo4j instance or cluster - for example `neo4j://localhost:7687` or `neo4j+s://_dbhash_.databases.neo4j.io:7687`
2. **An authentication token** - Neo4j supports basic username and password authentication, kerberos tokens or custom authentication.  You can create an authentication token by calling the `neo4j.auth` method.


Here is an example for how to create a driver instance:

.Creating a Driver Instance
[source,js,indent=0,subs="attributes+"]
----
include::{repository-raw}/main/example/index.js[tag=import]

include::{repository-raw}/main/example/index.js[tag=driver,indent=0]
----

The above example creates an _unencrypted_ connection to the Neo4j server at `localhost` on the default port number of `7687`.
The driver then attemps to authenticate against the server using a basic authentication with the username `neo4j` and password `letmein!`.


=== Verifying Connectivity

You can verify that the connection details used during driver instantiation are correct by calling the `verifyConnectivity` function.
This function returns a Promise which resolves, or rejects with a `Neo.ClientError.Security.Unauthorized` error if a connection could not be made.

.Verify Connectivity
[source,js,indent=0,subs="attributes+"]
----
include::{repository-raw}/main/example/index.js[tag=verifyConnectivity,indent=0]
----

== Check Your Understanding

include::./questions/1-supported-languages.adoc[]

include::./questions/2-package-name.adoc[]


[.summary]
== Lesson Summary

In this lesson, we learned how to query Neo4j from within a Node.js application.

In the next lesson, we will take a closer look at the first argument in the `neo4j.driver` method, the connection string.