= Data Importer Considerations
:order: 8
:type: lesson

Data Importer is a helpful tool for getting started and prototyping your data model. 
You can quickly import data from a CSV and start exploring the data in the Neo4j.

Depending on your use case and requirements, the Data Importer may be sufficient for your needs. 
However, you should be aware of the constraints of using Data Importer :

* Data Formats - you can only import data from a CSV / TSV files.
* Complex Schema Setup - there is no data manipulation or transformation functionality and some advanced schema options are not supported (e.g. multiple node labels, multiple constraints per node)
* Dependency on Clean Data - the data must be clean and well-structured.
* Automation - Data Importer is not suitable for automating data import tasks.
* Real-time integration - there is no real-time integration with external data sources.
* Data Volumes - Very large datasets may require a different approach.

You can learn how to create more complex CSV file imports using Cypher in the GraphAcademy course link:https://graphacademy.neo4j.com/courses/importing-cypher/[Importing CSV data into Neo4j] and the Neo4j documentation contains more information about link:https://neo4j.com/docs/data-importer/current/import-others/[Other ways of importing data into Neo4j^].

[.quiz]
== Check Your Understanding

include::questions/1-data-importer.adoc[leveloffset=+2]

[.summary]
== Summary

In this lesson, you learned about the constraints of using the Data Importer tool.

In the next module, you will explore how to evaluate your source data and prepare it for import into Neo4j.