= Create your own knowledge graph
:type: challenge
:order: 7

[.slide.discrete]
== Overview

In this optional challenge, you will apply what you have learned to create your own knowledge graph.

You should:

. Find a data set of documents that you want to create a knowledge graph from. This could be a collection of PDFs, text files, or any other text-based documents.
+
Try searching kaggle for link:https://www.kaggle.com/datasets?search=pdf[open PDF datasets^], for example the link:https://www.kaggle.com/datasets/snehaanbhawal/resume-dataset[Resume Dataset^].
. Use the `SimpleKGPipeline` to load the documents, split the text into chunks, extract entities, and create the knowledge graph in Neo4j.
. Load any associated structured data if available to enrich the knowledge graph.
. Query the knowledge graph to explore the data and extract insights.

You can come back to this challenge at any time.

read::Complete[]

[.summary]
== Lesson Summary

In this lesson, you applied what you had learned to create your own knowledge graph.

In the next module, you will create retrievers to query the knowledge graph.