= Connecting to Neo4j
:type: challenge
:lab-folder: src/modules
:lab-solution-folder: src/solutions/modules
:lab-filename: graph.ts
:test-filename: graph.test.ts
:test-file: {lab-folder}/{test-filename}
:lab: {repository-blob}/main/{lab-folder}/{lab-filename}
:lab-solution: {lab-solution-folder}/{lab-filename}
:order: 3

// TODO: Is there a better place for this to live?

As you start to interact with Neo4j, you will need to call the `query()` method on an instance of a `Neo4jGraph`.
You should create a single instance of the `Neo4jGraph` class to use across your application.

In this challenge, you must create an instance using link:../../1-project-setup/2-setup/[the environment variables added to the `.env.local` file in the previous module^].

lab::Open `{lab-filename}`[]


== Create a `Neo4jGraph` instance

The link:{lab}[`{lab-filename}` file^] already has a placeholder function that will be used in the application to instantiate and return a `Neo4jGraph`.

In `{lab-filename}`, find the `initGraph()` function.

[source,typescript]
----
include::{repository-raw}/{branch}/{lab-folder}/{lab-filename}[tag=graph]
----


The above code (1) defines a variable to hold the `Neo4jGraph` and (2) provides a function that will be used to return an existing `Neo4jGraph` object, or instantiate a new one if none exists.
This is known as a singleton pattern.

Inside the `if` statement, call the `Neo4jGraph.initialize()` method, passing the `url`, `username` and `password` defined in the environment variables.

.Create the Neo4j Graph instance
[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=create, indent=0]
----

The `Neo4jGraph.initialize()` method will create a new `Neo4jGraph` instance and verify connectivity to the database.

If the application cannot connect to the database, an exception will be thrown.


This ensures that the `graph` variable is set before the function returns a value.

.Return the singleton
[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=return, indent=0]
----


If you have followed the instructions correctly, your `initGraph` function should resemble the following:

.initGraph
[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=graph, indent=0]
----


include::../../../../includes/test.adoc[leveloffset=+1]


include::./questions/verify.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you created a singleton `Neo4jGraph` object that can be used across the application.

In the next lesson, you will build the methods for saving and retrieving this information from Neo4j using Langchain's `Neo4jGraph` object.
