= Connecting to Neo4j
:type: challenge
:lab-folder: src/modules
:lab-solution-folder: src/solutions/modules
:lab-filename: graph.ts
:test-filename: graph.test.ts
:test-file: {lab-folder}/{test-filename}
:lab: {repository-blob}/main/{lab-folder}/{lab-filename}
:lab-solution: {lab-solution-folder}/{lab-filename}
:order: 3

// TODO: Is there a better place for this to live?

As you start interacting with Neo4j, you must call the `query()` method on a `Neo4jGraph` instance.
It is best practice to create a single instance of the `Neo4jGraph` class for use across the application.

In this challenge, you must create an instance using link:../../1-project-setup/2-setup/[the environment variables added to the `.env.local` file in the previous module^].

lab::Open `{lab-filename}`[]


== Create a `Neo4jGraph` instance

The link:{lab}[`{lab-filename}` file^] already has a placeholder function that the application uses to create or return a singleton instance of `Neo4jGraph`.

In `{lab-filename}`, find the `initGraph()` function.

[source,typescript]
----
include::{repository-raw}/{branch}/{lab-folder}/{lab-filename}[tag=graph]
----

The code (1) defines a variable for storing the `Neo4jGraph` and (2) implements a function to either return an existing `Neo4jGraph` object or create a new one if it doesn't exist, employing the singleton pattern.

Inside the `if` statement, call the `Neo4jGraph.initialize()` method, passing the `url`, `username`, and `password` defined in the environment variables.

.Create the Neo4j Graph instance
[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=create, indent=0]
----

The `Neo4jGraph.initialize()` method will create a new `Neo4jGraph` instance and verify connectivity to the database.
Verifying connectivity ensures that the Neo4j credentials are correct and throws an error if the application cannot establish a connection.


.Return the singleton
[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=return, indent=0]
----


If you have followed the instructions correctly, your `initGraph` function should resemble the following:

.initGraph
[source,typescript]
----
include::{repository-raw}/{branch}/{lab-solution}[tag=graph, indent=0]
----


include::../../../../includes/test.adoc[leveloffset=+1]


include::./questions/verify.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you created a singleton `Neo4jGraph` object that you will use across the application.

In the next lesson, you will use this object to save and retrieve conversation history.
