= Adding or Updating a Movie
:type: challenge
:order: 8
:sandbox: true

Suppose we do not know if we have the movie _Rocketman_ in our graph.
If it is not in the graph, we want to set the _createdAt_ property with the value of `datetime()`.
The `datetime()` function returns the current date and time.
If it is in the graph, we want to set the _matchedAt_ property with the value of `datetime()`.
In either case, we want to set the _updatedAt_ property with the value of `datetime()`.

Modify the Cypher code in the sandbox to use `MERGE` processing for the _Movie_ node with the _title_ Rocketman:

* If the node already exists (`ON MATCH SET` clause):
** Set the [copy]#matchedAt# property for the node referenced by n  to  [copy]#datetime()#.
* If the node does not exist (`ON CREATE SET` clause):
** Set the [copy]#createdAt# property to [copy]#datetime()#.
* For either case:
** Set the [copy]#updatedAt# property to [copy]#datetime()#.

Execute the `MERGE` twice to ensure that the the `MERGE` processing occurs.
That is, the newly created node will have a _createdAt_ property and the updated node will have a _matchedAt_ property.
In both cases, the node will have the _updatedAt_ property set.

include::./questions/verify.adoc[]

[.summary]
== Summary

In this challenge, you demonstrated how to add or update properties when a node is created or found in the graph.
In the next lesson, you will learn how to delete nodes and relationships from the graph.