[.question.freetext]
=  1. How many records?

How many records are returned for actors with a name starting with **Tom** and with **UK** in the list of countries on the Movie node.

// reco db change impact
// the number of records will change and the answer needs to be updated


input::answer[]

* [x] 39


[TIP,role=hint]
.Hint
====
You can set both parameters in one command using the `:params` command:

.Using the :params command
[source,cypher]
----
:params {name: "Tom", country: "UK"}
----

How many records are returned for actors with a name starting with **Tom** and with **UK** in the list of countries on the Movie node.

Once you have entered the answer, click the **Try Again** button below to continue.
====

[TIP,role=solution]
.Solution
====

How many records are returned for actors with a name starting with **Tom** and with **UK** in the list of countries on the Movie node.

// reco db change impact
// correct answer will be different


The correct answer is `39`

Once you have entered the answer, click the **Try Again** button below to continue.
====
