= Labels - adding specific node labels
:order: 2

In this lesson, you will learn how to refactor your graph by adding specific node labels to improve query performance and semantic clarity.


// identify the manager of each employee

MATCH (e:Employee)-[:REPORTS_TO]->(manager:Employee)
RETURN manager.firstName



// set the manager label on the manager nodes
MATCH (e:Employee)-[:REPORTS_TO]->(manager:Employee)
SET manager:Manager
RETURN manager


// get managers

MATCH (manager:Manager)
RETURN manager.firstName




// tip - remove labels
MATCH (e:Employee)-[:REPORTS_TO]->(manager:Employee)
REMOVE manager:Manager
RETURN manager



Challenge - create a `ProductDiscontinued` label for products that have been discontinued and use it to find all discontinued products.


MATCH (n:Product)
WHERE n.discontinued = TRUE
SET n:ProductDiscontinued


MATCH (p:Product&!ProductDiscontinued) 
RETURN count(p)


read::Complete[]

[.summary]
== Lesson Summary

In this lesson, you learned about adding specific node labels to improve query performance and make your graph model more semantically clear.

In the next lesson, you will learn about adding indirect relationships between nodes.
