= Zero to Production Workshop

https://graphacademy.neo4j.com/courses/workshop-zero/[graphacademy.neo4j.com/courses/workshop-zero/]

== Introduction

The Zero to Production workshop is to give attendees an introduction to graph theory, Neo4j, and how to use the Aura tools to understand relationships in their data.

The workshop starts from base principles and takes the learner through a journey of understanding how data is stored in Neo4j, through importing a relational dataset, to setting up an Aura Agent so they can ask questions about the data.

The workshop can be presented online or in person and is best suited for 2-3 hour sessions.

== Prerequisites

There are no specific learner prerequisites and the workshop should be open to everyone. 

It is assumed the learner has an understanding of how data can be stored in tables.

== Learning objectives

* Basic graph theory
* The structure of a Neo4j graph database
* How to navigate a Neo4j database
* How to write Cypher queries
* Creating a Neo4j Aura instance
* Importing relational data into Neo4j
* Using Aura explore, dashboards, and agents

== Preparation

What you should know:

* https://graphacademy.neo4j.com/courses/genai-fundamentals/[Neo4j Fundamentals]
* https://graphacademy.neo4j.com/courses/cypher-fundamentals/[Cypher Fundamentals]
* https://graphacademy.neo4j.com/courses/importing-fundamentals/[Importing Data Fundamentals]
* https://graphacademy.neo4j.com/courses/aura-fundamentals/[AuraDB Fundamentals]

What you will need:

* A https://graphacademy.neo4j.com[GraphAcademy] account

What you will need to do:

. Complete the workshop before delivering it
. Review the outline plan (below) for additional context / approach
. Create a personalised copy of the introduction slides
. (Depending on the size of the workshop > 25 participants) Request an increase in the sandbox pool size.
.. In the #sandbox-experience slack channel
.. Use the command /workshop recommendations [pool size increase] [start - YYYY-MM-DD HH:MM] [end - YYYY-MM-DD HH:MM]
.. e.g. /workshop recommendations 20 2026-02-03 14:00 2026-02-03 16:00
. Delete your previous enrollment to the workshop (so you see the same view as the participants)
. Run the workshop!

== Outline plan

(All timings are estimates and adaptable)

=== Introduction (10 mins)

*Introduce yourself, the session, and have participants login*

Use the introduction slides to introduce yourself and the agenda

Introduce GraphAcademy and ask learners to create an account and goto the workshop URL in the notes document.

Starter activity - Ask attendees “What do you know about graph databases?”

Show learners the GraphAcademy course summary, summarise the learning objectives and enrol in the course.

=== Graph Databases (30-45 mins)

*Learn core concepts and how to store data in Neo4j*

Describe core Neo4j principles relating to Nodes, Labels, Properties, and Relationships.

Position Neo4j as different to other database technologies.

Spend time describing Cypher patterns, these are core to using Neo4j.

The module gets learners to use Cypher statements and observe outcomes before going into the detail of how they are constructed. The pattern of Predict and Run first is intentional to build understanding without overwhelming the learner with detail.

=== Get Neo4j (15-30 mins)

*Setup an Aura instance*

Explore the different options for using Neo4j in production. Show that Neo4j is accessible to all infrastructure requirements with multiple deployment options.

The key objective of this module is for the learner to sign up to Aura and create an instance they can use in the remainder of the course.

Do not under-estimate the time it will take to complete this task.

Aura instances will take time to create, you can continue with the course content while this happens.

Remind learners to save their Aura credentials they will need them for the next module.

Learners may face challenges in creating an instance due to constraints of free Aura instances, payment information, or other challenges. There is the option of adding the sandbox as a self-managed instance to allow them to continue.

=== Importing Data (30-45 mins)

*Create a Northwind graph data model*

Describe a simplistic approach of moving from a relational database to a graph database. 

The main activity is for the learner to build a graph data model of the Northwind dataset and import data. 

The task is guided to create a simple model of Customer, Order, Product with an open ended activity to extend the model based on their preferences.

The module concludes showing a complete graph data model that can be downloaded and imported.

=== Access your data (30-45 mins)

*Use Explore, Dashboards, and Agents*

Give the learner a chance to explore the Aura tools and the dataset they have imported using Explore, Dashboards, and Agents.

Demonstrate navigating the data set using Explore and encourage learners to do the same. Not following your lead but coming up with their own visualizations.

Sign post learner to the Neo4j and Generative AI course where they can learn more about Agents, Vectors, Similarity Search, and Text2Cypher

There is an open ended activity at the end of the course to revisit Explore, Dashboards, and Agents with some challenges.

