= Adding the Driver
:type: challenge
:branch: 01-connect-to-neo4j
:test-number: 01
// :repository-raw: /tmp/app-java

This is your first challenge of this course.
Your challenge here is to modify the code to create a new instance of the Driver that can be used across the application.

As we discussed in the link:../1-about/[About the Driver lesson], it is best practice to create a single instance of the driver in our application per Neo4j cluster or DBMS.

Inside `AppUtils.java`, you will see an `initDriver()` function, and above a `static Driver driver` static variable declaration.

.AppUtils.java
[source,java,indent=0,role=nocopy]
----
include::{repository-raw}/main/src/main/java/neoflix/AppUtils.java[tag=driver]

include::{repository-raw}/main/src/main/java/neoflix/AppUtils.java[tag=initDriver]
----

This function should use the `getUri`, `getUsername` and `getPassword` methods to create an instance of the Neo4j Java Driver and assign it to the `driver` variable.

Below, the `getDriver()` function will provide other modules in the application with access to the `driver` variable set in `initDriver`.

.AppUtils.java
[source,java,indent=0,role=nocopy]
----
include::{repository-raw}/main/src/main/java/neoflix/AppUtils.java[tag=getDriver]
----



== Challenge: Implement the initDriver function.

Your first challenge is to modify the `initDriver` in `src/AppUtils.java` to create an instance of the driver and assign it to the `driver` variable declared above.
To do this, we will need to:

1. Add the `neo4j-java-driver` dependency to your `pom.xml`.
2. Import the dependency into `AppUtil.java`.
3. Create the driver instance with the  `uri`, `username` and `password` parameters passed to the function and use the `verifyConnectivity` to assert that the credentials are correct.


=== 1. Add the neo4j-java-driver Dependency

First, you will need to add the `neo4j-java-driver` dependency to your `pom.xml`.

[source,xml,indent=0]
----
include::{repository-raw}/main/pom.xml[tag=driver]
----


[TIP]
Using the `mvn verify` to download the driver library and its dependencies.


=== 2. Importing the Dependency

To include the Driver dependency in our module, you will add an `import` directive to the top of the file.
Copy and paste the following code into the top of `src/main/java/neoflix/AppUtils.java`.

[source,java,subs="attributes+"]
----
include::{repository-raw}/main/example/index.java[tag=import]
----


=== 3. Creating the Driver Instance

Create the driver instance by calling the `GraphDatabase.driver()` method.
The first argument will be the `uri` passed as the first parameter to the function.
The second argument will be an authentication token which can be created using the `AuthTokens.basic()` function, this takes two arguments; `username` and `password`


Replace the `initDriver` placeholder function with the following code:

.AppUtils.java
[source,java,indent=0]
----
include::{repository-raw}/{branch}/main/src/main/java/neoflix/AppUtils.java[tag=driver]

include::{repository-raw}/{branch}/main/src/main/java/neoflix/AppUtils.java[tag=initDriver]
----

In the last line of the function above, the `verifyConnectivity()` function will verify that the connection details are correct.

If the connection cannot be made for any reason, call will fail with an Exception.
If this occurs, your application will be unable to communicate with Neo4j.
Manual investigation will be required to diagnose the issue.


If the connection has been successfully verified, it will return an instance of the driver.




// == Testing Connectivity
include::../../../../includes/test.adoc[]

== Check Your Understanding

include::./questions/1-test-number.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

You have implemented the code to create a new driver instance with environment variables read from the `application.properties` file which verifies that the driver can connect to the DBMS before the application starts.

In the next module we will look at how to use the driver to query the DBMS.
