= Graph-Enhanced Vector Retriever
:order: 4
:type: lesson
:branch: new-course

To take advantage of the relationships in the graph, you can create a retriever that uses both vector search and graph traversal to find relevant data. 

The `VectorCypherRetriever` allows you to perform vector searches and then traverse the graph to find related nodes or entities.

Open the `genai_fundamentals/vector_cypher_rag.py` file and review the code:

[source,python]
.vector_cypher_rag.py
----
include::{repository-raw}/{branch}/genai-fundamentals/vector_cypher_rag.py[tag=**]
----

The program includes all the code to connect to Neo4j, create the embedder, llm, and GraphRAG pipeline.

Your task is to:

. Configure the Cypher retrieval query that will traverse the graph
. Create the `VectorCypherRetriever` retriever.

== Retrieval Query

The retrieval query is a Cypher query that will be used to get data from the graph after the nodes are returned by the vector search.

The query will be passed the `node` and `score` variables, that are yielded by the vector search.