= Congratulations!  You are now certified in Neo4j Graph Data Science!

// Hi {user_name},

**Congratulations!  You are now certified in Neo4j Graph Data Science!**

include::../../../shared/emails/share.adoc[]

////
**Claim your T-shirt**

link:{tshirt-form}[image:{tshirt-image}[Claim your free t-shirt now!]]

As a Neo4j Certified Professional, you are entitled to a free t-shirt.
Simply click the link below, log in with your GraphAcademy credentials and complete the form to claim your t-shirt.

link:{tshirt-form}[{tshirt-form}^]
////

include::../../../shared/emails/recommend.adoc[]

**Your Next Course**

There are plenty of courses on offer at GraphAcademy, head over to the link:{base_url}/categories/[Course Catalog^] to see what else in on offer.

**Certification Feedback**

If you have any comments on the certification process, feel free to email us on mailto:graphacademy@neo4j.com[]

We hope to see you back on GraphAcademy soon!

**Become a Neo4j Ninja!**

If you have the ambition to help others with Neo4j, consider becoming a Neo4j Ninja.

Read about the link:https://community.neo4j.com/t5/ninjas-program/ct-p/ninjas/[Neo4j Ninjas Program^]

\-- +
Cheers, +
The GraphAcademy team!