= Chains and LCEL
:type: lesson
:order: 1

This lesson will teach you how to create custom chains using **LangChain Expression Language**.

== What is LCEL?

LangChain Expression Language, abbreviated to LCEL, is a declarative method for composing chains.
LCEL provides an expressive syntax capable of handling simple tasks such as simple _Prompt to LLM_ chains or complex combinations of steps.

LCEL provides the following benefits:

* **Streaming Support**
* **Asynchronous Calls**
* **Optimized parallel execution**
* **Streaming Support**


You can link:https://js.langchain.com/docs/expression_language/[read more about LCEL in the LangChain documentation^].


== An example chain

The link:https://api.python.langchain.com/en/latest/_modules/langchain/chains/llm.html#LLMChain[`LLMChain`^] is an example of a simple chain that, when invoked, takes a user input, replaces the value inside the prompt and passes the prompt to an LLM and specifies the result.

// [source]
// ----
// // TODO: Diagram
// Prompt >> LLM >> Response
// ----

link:https://api.python.langchain.com/en/latest/_modules/langchain/chains/llm.html#LLMChain[The LLM chain code] can be significantly simplified.

The chain should consist of:

1. A `PromptTemplate` containing instructions and placeholders.
2. An LLM to act on the prompt.
3. An output parser to coerce the response into the correct format.

=== The Prompt

The prompt in the lesson instructs the LLM to act as a _Cockney fruit and vegetable seller_ and provide information about fruit.

You can use the static `fromTemplate()` method to construct a new `PromptTemplate`.

[source,typescript]
----
include::{repository-raw}/main/examples/chain.mjs[tag=prompt]
----

=== The LLM

The prompt will be passed to an LLM, in this case, the `ChatOpenAI` model.

[source,typescript]
----
include::{repository-raw}/main/examples/chain.mjs[tag=llm]
----


=== Creating the Chain

In LangChain.js, chains are instances of the `RunnableSequence` class.
To create a new chain, call the `RunnableSequence.from` method, passing through an array of steps.

[source,typescript]
----
include::{repository-raw}/main/examples/chain.mjs[tag=chain]
----


=== Invoke the chain

The `RunnableSequence` instance has an `invoke()` method.
The input that this function expects depends on the template variables contained in the prompt.

Because the prompt expects `{fruit}` as an input, you call the `.invoke()` method with an object containing a `fruit` key.


[source,typescript]
----
include::{repository-raw}/main/examples/chain.mjs[tag=invoke, indent=0]
----


[TIP]
.Type Safety
====

You can ensure type safety in your chains by defining input and output types on the `.from()` method.

[source,typescript]
----
include::{repository-raw}/main/examples/chain.mjs[tag=types]
----
====


[.quiz]
== Check your understanding

include::./questions/1-runnable-sequence.adoc[leveloffset=+2]
include::./questions/2-invoke.adoc[leveloffset=+2]


[.summary]
== Lesson Summary

In this lesson, you learned how to combine an array of steps into a single `RunnableSequence`.

In the next lesson, you will use this knowledge to create a chain that will generate an answer based on a given context, a technique known as **Retrieval Augmented Generation (RAG)**.
