= Installing the driver
:type: lesson
:slides: true
:order: 1
:minutes: 10


[.slide.discrete]
== Introduction
In the link:/courses/cypher-fundamentals/[Cypher Fundamentals^] course, you learned how to query Neo4j using Cypher.

To run Cypher statements in a Go application, you'll need the link:https://neo4j.com/docs/go-manual[Neo4j Go Driver^].
The driver acts as a bridge between your Go code and Neo4j, handling connections to the database and the execution of Cypher queries.

[.slide]
== Setting up a Go Project

First, create a new Go project and initialize it as a module:

[source,shell]
----
mkdir hello-neo4j
cd hello-neo4j
go mod init graphacademy/hello
----

[.slide]
== Installing the Driver

To install the driver, use the `go get` command:

[source,shell]
go get github.com/neo4j/neo4j-go-driver/v5

[.slide.col-2]
== Creating a Driver Instance

[.col]
====

[source,go]
----
package main

import (
    "context"
    "fmt"
    "github.com/neo4j/neo4j-go-driver/v5/neo4j"
)

func main() {
    driver, err := neo4j.NewDriverWithContext(
        "neo4j://localhost:7687", // <1>
        neo4j.BasicAuth("neo4j", "your-password", ""), // <2>
    )
    if err != nil { panic(err) }
    defer driver.Close(context.Background()) // <3>
}
----
====

[.col]
====
You start by importing the driver and creating an instance using the `neo4j.NewDriverWithContext()` function:


<1> The connection string for your Neo4j database
<2> Your Neo4j username and password
<3> Always close the driver when done using the `defer` statement

[TIP]
.Best Practice
=====
Create **one** Driver instance and share it across your entire application.
=====

// [.transcript-only]
// =====

// [%collapsible]
// .Connect to your Neo4j Sandbox?
// ======
// If you want to experiment with the driver, you can connect to the Neo4j Sandbox which has been created for you.

// Neo4j Connection String:: [copy]#neo4j://{instance-ip}:{instance-boltPort}#
// Username:: [copy]#{instance-username}#
// Password:: [copy]#{instance-password}#
// ======

// =====
====

[.slide]
== Verifying Connectivity

You can verify the connection is correct by calling the `VerifyConnectivity()` method.

[source,go]
----
ctx := context.Background()
err = driver.VerifyConnectivity(ctx)
if err != nil {
    panic(err)
}
----

[NOTE]
.Verify Connectivity
=====
The `VerifyConnectivity()` method will link:https://neo4j.com/docs/go-manual/current/connect/[return an error^] if the connection cannot be made.
=====


[.slide,role="col-2"]
== Running Your First Query

[.col]
====
The `ExecuteQuery()` method executes a Cypher query and returns the results.

[source,go]
----
ctx := context.Background()
result, err := neo4j.ExecuteQuery(ctx, driver, // <1>
    "RETURN COUNT {()} AS count",
    nil, // <2>
    neo4j.EagerResultTransformer, // <3>
)
if err != nil { panic(err) }

// Get the first record
first := result.Records[0] // <4>
// Print the count entry
count, _ := first.Get("count") // <5>
fmt.Println(count)
----
====

[.col]
=== What is happening here?
<1> `neo4j.ExecuteQuery()` runs a Cypher query to get the count of all nodes in the database
<2> `nil` means no parameters are passed to the query
<3> `EagerResultTransformer` loads all results into memory
<4> `Records` contains a slice of the rows returned
<5> Values from the `RETURN` clause are accessed using the `Get()` method

[.slide.col-2]
== Full driver lifecycle

It is good practice to close the driver when you are finished with it.
You can use the `defer` statement to automatically close the driver when the function exits.

You can also explicitly call `Close()` to release any resources held by the driver.

[.col]
====
[source,go]
----
driver, err := neo4j.NewDriverWithContext(
    "neo4j://localhost:7687",
    neo4j.BasicAuth("neo4j", "your-password", ""),
)
if err != nil {
    panic(err)
}
defer driver.Close(context.Background())
----

====

[.col]
====


[source,go]
----
ctx := context.Background()
driver.Close(ctx)
----
====


// [.transcript-only]
// == Full sample code 

// The following code sample demonstrates the full driver lifecycle, including connecting to the database, running a query, and using `defer` to automatically close the driver when the function exits.

// [source,go]
// ----
// package main

// import (
//     "context"
//     "fmt"
//     "github.com/neo4j/neo4j-go-driver/v5/neo4j"
// )

// func main() {
//     driver, err := neo4j.NewDriverWithContext(
//         "neo4j://localhost:7687",
//         neo4j.BasicAuth("neo4j", "your-password", ""),
//     )
//     if err != nil {
//         panic(err)
//     }
//     defer driver.Close(context.Background())
    
//     ctx := context.Background()
//     err = driver.VerifyConnectivity(ctx)
//     if err != nil {
//         panic(err)
//     }
    
//     result, err := neo4j.ExecuteQuery(ctx, driver,
//         "RETURN COUNT {()} AS count",
//         nil,
//         neo4j.EagerResultTransformer,
//     )
//     if err != nil {
//         panic(err)
//     }
    
//     first := result.Records[0]
//     count, _ := first.Get("count")
//     fmt.Println(count)
// }
// ----



read::Take challenge[]

[.summary]
== Lesson Summary

In this lesson you learned how to install the Neo4j Go Driver, create a Driver instance, verify connectivity to your database, and execute your first Cypher statement.

For async applications, link:https://neo4j.com/docs/go-manual/current/concurrency/[use the async API methods].

In the next lesson, you will take a quiz to test your knowledge of installing and creating a driver instance.
