[.question.freetext]
= UK movies?

How many movies released in the UK are in the graph?

// reco db change impact

////
change the solution to:
MATCH (m:Movie)
UNWIND m.countries AS country
WITH m, country
// this automatically, makes the country distinct because it's a grouping key
WITH country, collect(m.title) AS movies
RETURN country, size(movies)
////

input::answer[]

* [x] 1386

[TIP,role=hint]
.Hint
====
You will unwind by countries, rather than languages.

After you have collected the movies for each language as a list, return the size of the list for each country.

How many movies released in the UK are in the graph?

Once you have entered the answer, click the **Try Again** button below to continue.
====

[TIP,role=solution]
.Solution
====

You can run the following query to find the answer:

[source,cypher]
----
include::../solution.cypher[]
----

How many movies released in the UK are in the graph?

Once you have entered the answer, click the **Try Again** button below to continue.
====
