= リレーションシップの発見
:type: quiz
:order: 3

// [.video]
// video::aQ5hKd2DD0A[youtube,width=560,height=315]


//https://youtu.be/aQ5hKd2DD0A


////
1-Reading-Finding Relationships

https://docs.google.com/document/d/1EGqqe-05pSBVL5TTkRv_MoSkkhqQQBSjyS7pv9URyKE/edit?usp=sharing
////


[.transcript]
== リレーションシップの発見
[TIP]
.Our Goal
*映画ファン* なので *特定の俳優* の映画を見つけて、今晩 *映画* を見ようとおもいます。

前のレッスンでは、`MATCH` 句を使って、データベースから _Tom Hanks_ を表すノードを探しました。

[source,cypher]
----
MATCH (p:Person {name: 'Tom Hanks'})
RETURN p
----
`MATCH` 節のパターンを拡張して、_ACTED_IN_ のタイプを持つすべてのリレーションシップを任意のノードに _トラバース_ することができます。
ドメインモデルでは、_ACTED_IN_ リレーションは _Person_ ノードから外へ向かう方向であることが示されているので、パターンにその方向を追加することができます。
//これをよく**トラバース**と呼びます。

.Incomplete code
[source,cypher,role=nocopy noplay]
----
MATCH (p:Person {name: 'Tom Hanks'})-[:ACTED_IN]->()
----

このデータモデルでは、リレーションシップのもう一方の端にあるノードは _Movie_ ノードになるので、ノードに _:Movie_ ラベルを指定する必要は必ずしもなく、代わりに変数 _m_ を使用することになります。

[source,cypher]
----
MATCH (p:Person {name: 'Tom Hanks'})-[:ACTED_IN]->(m)
RETURN m.title
----

このコードは、_Tom Hanks_ が出演したすべての映画のタイトルを返します。

もしこのグラフに異なるラベル、例えば _Television_ と _Movie_ のノードがあれば、このクエリはTom Hanksが出演した _Television_ と _Movie_ のノードをすべて返したことになります。
つまり、グラフの _ACTED_IN_ リレーションの先に複数の種類のノードがあった場合、_Movie_ のみを返すようにすることができます。

[source,cypher]
----
MATCH (p:Person {name: 'Tom Hanks'})-[:ACTED_IN]->(m:Movie)
RETURN m.title
----

このグラフには、_ACTED_IN_ の関係を持つ _Movie_ ノードしかないため、このクエリは前のクエリと全く同じ結果を返します。

== 理解度チェック

include::questions/1-complete-query.adoc[leveloffset=+1]

include::questions/2-directors.adoc[leveloffset=+1]

[.summary]
== まとめ

このレッスンでは、リレーションシップを使用したクエリで、グラフのパターンをトラバースする方法を学びました。
次のチャレンジでは、グラフをトラバースするスキルを披露します。

