= The Data Import Process
:order: 2
:type: lesson

[.video]
video::YouTubeVideoID

[.transcript]

When you import data into Neo4j, you typically start with a set of source files.

== Source data

You may have exported this source data from:

* Relational databases
* Web APIs
* Public data directories
* BI tools
* Excel

[TIP]
.Export to CSV
Most data systems will have an option for exporting data to CSV files as it is a common format for data exchange.

The data in the source files may not be in the format needed for your graph data model:

* The source files could contain more data than you need.
* There may not be a 1-1 mapping of the data in a CSV file to a node or relationship.
* The data types might not map directly onto those supported in Neo4j.

Likely, you will need to transform the data before or during the import.

== Create a graph

Before you start the import process, you should:

. Understand the data in the source CSV files.
. Inspect and clean (if necessary) the data in the source data files.
. Understand the graph data model you will be implementing during the import.

Once you have the source data and a graph data model, you can create the graph by importing the data.

[TIP]
.Data mapping
You may find it useful to create a mapping document that shows how the source data maps to the graph data model.

The import involves creating Cypher code to:

* Read the source data.
* Transform the data as needed.
* Create nodes, relationships, and properties to create the graph.

Creating an import process will likely require multiple iterations as you build, test and refactor.

This course contains everything you need to learn how to import CSV files, including:

* Source data CSV files.
* A graph data model. You will be implementing a Movie recommendations graph.
* An empty Neo4j Sandbox to import into.

[.quiz]
== Check Your Understanding

include::questions/1-common-format.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you learned the importing CSV data into Neo4j using Cypher process. 

In the next lesson, you will learn about the CSV data format.