= Neo4j Property Graph Concepts
:type: quiz
:order: 1


The key Neo4j components used in Cypher are:

* Nodes with labels
* Relationships with types and direction
* Properties for nodes and relationships

The nodes and relationships form the structure and patterns in the graph.

== Domain model for this course

Here is the data model you will be working with in this course.

image::images/movie-schema.svg[movie-schema-image,width=600,align=center]

The nodes in the graph are labeled _Person_ and _Movie_. There are many relationship types between _Person_ nodes and _Movie_ nodes.
Some _Person_ nodes also have the _FOLLOWS_ relationship to other _Person_ nodes.

== Understanding what is in a graph

If you have an existing graph, before you begin working with it, you should understand the data model which includes:

* Node labels that represent the entities of your domain
* Relationship types and directions that connect the entities for the questions of your use cases
* Property key/value pairs that represent the data for your domain and can be added to a node or a relationship

The domain model shown above was visualized in Neo4j Browser using this Cypher code. Run this Cypher code:

[TIP]
Click *Run in Sandbox*. Wait a moment until you see *neo4j$ CALL db.schema.visualization()* in the top query edit pane, then click the *Run* button in the top pane of the Sandbox you see on the right.

[source,cypher]
----
CALL db.schema.visualization()
----

This visualization shows the node labels, the relationships in the graph, and the direction of the relationships between the nodes.

In addition, you can retrieve the property keys used in the graph by running this Cypher code:

Run this Cypher code:

[source,cypher]
----
CALL db.propertyKeys()
----

This list of property keys does not tell you which properties are used in nodes or relationships.
By default, there is no requirement that every node or relationship have a given set of properties.
For example, one _Person_ node instance can have a _name_ property and another _Person_ node instance can have both a _name_ and _born_ property.


== Check your understanding

include::questions/1-entities.adoc[]

include::questions/2-properties.adoc[]



