= Updating the GraphQL Schema
:order: 7

To successfully perform the steps in this exercise, you will have executed all of the GraphQL code after you cleared the database above and loaded the sample books data.

If we refer back to our original graph data model we see that we're missing the `Author` and `Subject` nodes! In this exercise you will update the GraphQL schema adding the `Author` and `Subject` types including relationships.

. Update `schema.graphql` to add these two types to the GraphQL schema.
// TODO: add screenshot

[start=2]
.  Execute a GraphQL mutation to add authors to the graph according to the following table.

> Try to do this in a single nested mutation operation and be sure to connect the authors to their books.

[width="50%"]
|============================
| Title | Author(s)
| Inspired | Marty Cagan
| Ross Poldark | Winston Graham
| Graph Algorithms | Mark Needham, Amy E. Hodler
|============================

[start=3]
. Execute a GraphQL mutation to add the book subjects and connect them to the books according to this table.

[width="50%"]
|=============================
| Title | Subject(s)
| Inspired | Product management, Design
| Ross Poldark | Historical fiction, Cornwall
| Graph Algorithms | Graph theory, Neo4j
|=============================

If you get stuck you can find the solutions in the README.md file in https://codesandbox.io/s/github/johnymontana/training-v3/tree/master/modules/graphql-apis/supplemental/code/02-graphql-apis-overview-of-neo4j-graphql/end?file=/.env[this Codesandbox.^]
Be sure to add your sandbox credentials to the `.env` file after loading the Codesandbox.


[.quiz]
== Check Your Understanding

include::questions/question-1.adoc[leveloffset=+1]

include::questions/question-2.adoc[leveloffset=+1]

include::questions/question-3.adoc[leveloffset=+1]

[.summary]
== Summary

In this module, we saw how to use GraphQL type definitions to generate a GraphQL API using the Neo4j GraphQL Library. In the next module we explore adding custom logic to our GraphQL API using the Cypher statement language.
