= Challenge: Source-Target Shortest Path
:type: challenge
:sandbox: true
:updated-at: 2022-05-04T10:00:00Z

In the previous module, you learned that there are 206 shortest unweighted paths from Nashville to Phuket.

In this challenge, you will use the Dijkstra shortest path algorithm to recommend the shortest weighted path between the two airports based on the flight distance.

This challenge has two parts:

1. <<Create a Projected Graph>>
2. <<Find the Source-Target Shortest Path>>



== Create a Projected Graph

In the integrated sandbox widow to the right, execute the following query to create a new graph projection.
Note that when you start this challenge, any existing graph project named routes has been removed.

.Create a Projected Graph
[source,cypher]
----
include::solution.cypher[tag=project]
----

This query creates a new projected graph called `routes`, loading in all `(:Airport)` nodes and `[:HAS_ROUTE]` relationships.
Each relationship will have a `.distance` property which will we use in the next step for calculating the shortest weighted path.



== Find the Source-Target Shortest Path

Now that the graph has been projected into memory, run the `gds.shortestPath.dijkstra.stream()` procedure to calculate the shortest weighted path from Nashville (BNA) to Phuket (HKT).


.Run the algorithm
[source,cypher]
----
include::solution.cypher[tag=run]
----


include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge you practiced how to calculate the shortest weighted path using the Dijkstra shortest path algorithm.

In the next challenge, you will use Yen's algorithm to identify alternative shortest weighted path between two nodes.
