export interface User {
    // UUID Generated on create
    id: string;

    // Auth0
    sub: string;
    email: string;
    email_verified: boolean;
    name: string;
    picture?: string;

    // Profile Page
    profileCompletedAt: Date | undefined;
    nickname?: string;
    givenName?: string;
    position?: string;
    company?: string;
    country?: string;

    // Generated by formatUser in src/utils/index.ts
    publicProfile?: string;

    // User Profile
    // givenName: string;
    // [key: string]: any;
}