import Team from "./team";

export interface User {
    // UUID Generated on create
    id: string;

    // Auth0
    sub: string;
    email: string;
    email_verified: boolean;
    name: string;
    picture?: string;

    // Profile Page
    profileCompletedAt: Date | string | undefined;
    nickname?: string;
    givenName?: string;
    position?: string;
    company?: string;
    country?: string;
    unsubscribed?: boolean;

    // Generated by formatUser in src/utils/index.ts
    publicProfile?: string;
    hiddenProfile?: boolean;

    featureFlags: string[];
    isNeo4jEmployee: boolean;

    teams?: Team[];

    // User Profile
    // givenName: string;
    // [key: string]: any;
}

export type ValidLookupProperty = 'sub' | 'id'
