= Creating Graphs
:order: 3
:type: challenge

You have used the `MATCH` clause to find patterns and read data from Neo4j.

In this lesson, you will learn how to create data.

The database is a little out of date - the latest movie is link:https://www.themoviedb.org/movie/339527-solace[Solace^] which was released in September 2016.

.Latest Movies
[source,cypher]
----
MATCH (m:Movie)
WHERE m.released IS NOT NULL
RETURN m.title AS title, m.url AS url, m.released AS released
ORDER BY released DESC LIMIT 5
----

[%headers]
|===
|	title |	url |	released

| "Solace"	|  "https://themoviedb.org/movie/339527" | "2016-09-02"
| "Mohenjo Daro" | "https://themoviedb.org/movie/402672" | "2016-08-12"
| "Rustom" | "https://themoviedb.org/movie/392572" | "2016-08-12"
| "Ben-hur" | "https://themoviedb.org/movie/271969" | "2016-08-12"
| "Suicide Squad" | "https://themoviedb.org/movie/297761" | "2016-08-05"

|===

You can use Cypher to add new movies.

Your challenge is to add your favorite movie to the database.
To create nodes and relationships in the database, you use the `CREATE` clause.

== The `CREATE` Clause

You can use the `CREATE` clause to create a pattern in the database.

=== Create a Movie node

Start by creating a movie.
Feel free to update the title and released properties to your favourite movie.

[source,cypher]
----
CREATE (m:Movie {
  title: "Arthur the King",
  released: date("2024-03-15")
})
RETURN m
----

=== Create a RATED relationship

In general, its recommended to create a single node or relationship at a time.
You can create an entirely new pattern, or use the `MATCH` clause to find nodes that already exist in the database.

[source,cypher]
----
MATCH (m:Movie {title: "Arthur the King"})
CREATE (u:User {name: "Adam"})-[r:RATED {rating: 5}]->(m)
RETURN u, r, m
----

This statement creates a new `(:User)` node with a name property, and an outgoing `[:RATED]` relationship to the `(:Movie)` node with a rating property set to `5`.

Try modifying the following statement to create a node in your name.

[TIP]
.Inline Where Clause
====
This statement uses JSON-style syntax to specify the `WHERE` clause as part of the `MATCH` clause:

[source,cypher,role=noplay nocopy]
MATCH (m:Movie {title: "Arthur the King"})

This is identical to using a `WHERE` clause.

[source,cypher,role=noplay nocopy]
MATCH (m:Movie)
WHERE m.title = "Arthur the King"
====

include::questions/verify.adoc[leveloffset=+1]


[.summary]
== Summary

In this lesson, you learned how to use the `CREATE` clause to create nodes and relationships.

This is only scratching the surface.  In the link:/courses/cypher-fundamentals/[Cypher Fundamentals course^] you will learn how to write more advanced Cypher statements.

In the next module we will show you how to get started with Neo4j and take you on a brief tour of the Neo4j ecosystem.
