graph TD
    Order -->|<i>SHIPPED_TO<i>| Address
    Supplier -->|<i>LOCATED_AT<i>| Address
    Customer -->|<i>LOCATED_AT<i>| Address
    Employee -->|<i>LOCATED_AT<i>| Address
        
    Order(("<b>Order</b>"))
       
    Supplier(("<b>Supplier</b>"))
    
    Customer(("<b>Customer</b>"))
    
    Employee(("<b>Employee</b>"))

    Address(("<b><i>Address</i></b>"))
    