graph TD
    Order -->|<i>SHIPPED_TO<i>| Address
    Supplier --> Address
    Customer --> Address
    Employee --> Address
        
    Order(("<b>Order</b>"))
       
    Supplier(("<b>Supplier</b>"))
    
    Customer(("<b>Customer</b>"))
    
    Employee(("<b>Employee</b>"))

    Address(("<b><i>Address</i></b>"))
    