= Setting up the Project
:order: 1
:repo: adam-cowley/neoflix-api-node
// TODO: use include to define this
:node-version: v14.18.0

We have put together a project with all of the boilerplate in place.  It is now up to you to implement the features on top of Neo4j.

// include::https://raw.githubusercontent.com/adam-cowley/neoflix-api-node/main/.nvmrc[]

== Setup Node.js

If you haven't already done so, you will need to link:https://nodejs.org/en/[install Node.js using the instructions on nodejs.org^].
The project has been written to work wth Node.js version **{node-version}**.


You can verify that the installation is successful by running the following command in the command line:

[source,sh]
node -v

You will also need a package manager to install the dependencies.  NPM is included with Node.js, but if you prefer you can also link:https://classic.yarnpkg.com/lang/en/docs/install/[install Yarn using these instructions^].


== Clone the Repository

You are now ready to clone the repository.

[.tab]
.HTTPS
====
To clone the repository without logging in via HTTPS, you can run the following command to clone the repository:

.Clone Repository Using HTTPS
[source,shell,subs="attributes+"]
git clone https://github.com/{repo}.git

====

[.tab]
.SSH
====

If you have a GitHub account configured with SSH access, you can  run the following command to clone the repository:

.Clone Repository using SSH
[source,shell,subs="attributes+"]
git clone git@github.com:{repo}.git

====

[.tab]
.GitHub CLI
====

If you have the link:https://cli.github.com/[GitHub CLI^] installed, you can run the following command to clone the repository:

.Clone Repository using the GitHub CLI
[source,sh,subs="attributes+"]
gh repo clone {repo}

====

If you prefer, you can also link:https://github.com/{repo}/archive/refs/heads/main.zip[download a zip file with the source^].


== Install Dependencies

Once you have cloned the repository, navigate to the folder in your terminal and run the following command to install the dependencies.

[.tab]
.NPM
====
.Install Dependencies using NPM
[source,sh]
npm install
====

[.tab]
.Yarn
====
.Install Dependencies using Yarn
[source,sh]
yarn install
====

You can view a full list of dependencies by opening link:https://github.com/{repo}/blob/main/package.json[`package.json`^].


== Setting Environment Variables

This project uses the `dotenv` library to manage environment variables for this project.
When the `config` function exported by the link:https://www.npmjs.com/package/dotenv[`dotenv`^] library is called, this file is parsed and all config settings are appended to the `process.env` variable.

In the next lesson, we will save our Neo4j credentials, but for now we can just copy the `.env.example` file to `.env`.

[source,sh]
cp .env.example .env


== Start the Project

To start the project, run the following command:

[.tab]
.NPM
====
.Start the project using NPM
[source,sh]
npm start
====

[.tab]
.Yarn
====
.Start the project using Yarn
[source,sh]
yarn start
====

You should see an output similar to the following confirming that the server has successfully started:

.Console Output
[source,rel=nocopy]
[nodemon] 2.0.13
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src`
Server listening on http://localhost:3000/

By default, the server will listen on http://localhost:3000.
You can change the port that the server listens on by editing the `APP_PORT` variable in `.env`.


== A Brief Tour of the Project

If you open up the listening address in your browser, you will see a Single Page Application (SPA) that communicates with the API served at http://localhost:3000/api.
At the moment, the responses are hardcoded but as we progress through the course this data will be replaced with live data coming from Neo4j.

Here are some of the important directories in the project:

// * `.env` - This file holds environment variables for the server and is parsed by the link:https://www.npmjs.com/package/dotenv[`dotenv`^] library.
* `src/` - This folder holds the application code
** `middleware/` -
** `routes/` - The routes holds the route handlers that are registered on the server.  You shouldn't need to edit these files.
** `services/` - The services folder contains services that you will need to update to interact with Neo4j.
* `test/` - The test suite containing test files that will you will need to run in order to pass the text.  You will run these using the `npm run test` or `yarn run test` command.
* `passport/` - This folder holds all of the logic required for user authentication.
* `public/` - This folder holds the build files for the SPA.  Do not edit these files.

Now that we have the project up and running, let's connect to our Neo4j Sandbox.

// 1. Clone the repo from github
// 2. Install dependencies
// 3. Setup your `.env` file