// TODO - I think this lesson can be removed, conversational agents are covered in the intro to langchain


= Conversational Agent
:optional: true

* So far, the LLM has only been able to build a single question at a time
* By creating an agent and adding conversational memory, the bot will be able to answer a string of questions
* Define tools as an array
** Create an instance of a GraphCypherQAChain with a custom prompt, and use the `.run()` function in the tool definition.

// TODO: Ask Tomaz to build this example and add it to a notebook

[source,python]
----
from langchain.chains.conversation.memory import ConversationBufferWindowMemory
from langchain.agents import AgentType, initialize_agent

from langchain.tools import Tool

tools = [
    Tool.from_function(
        name="GraphCypherQAChain",
        description="Use Cypher to generate information above movies, actors, users and ratings",
        func=cypher_chain.run,
        return_direct=True
    )
]

memory = ConversationBufferWindowMemory(
    memory_key='chat_history',
    k=5,
    return_messages=True
)

agent = initialize_agent(
    tools, llm, memory=memory, max_iterations=3,
    agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
    verbose=True # Allows us to see the "thought" process
)
----

* Ask a question that requires memory...


.Tom Hanks Films
[source,python]
----
agent.run("How many films did Tom Hanks act in?")
----

    > Entering new AgentExecutor chain...
    ```json
    {
        "action": "GraphCypherQAChain",
        "action_input": "MATCH (a:Actor {name: 'Tom Hanks'})-[:ACTED_IN]->(m:Movie) RETURN count(m)"
    }
    ```

    > Entering new GraphCypherQAChain chain...
    Generated Cypher:
    MATCH (a:Actor {name: 'Tom Hanks'})-[:ACTED_IN]->(m:Movie) RETURN count(m)
    Full Context:
    [{'count(m)': 38}]

    > Finished chain.

    Observation:
    Tom Hanks has acted in 38 movies.


    > Finished chain.


Will the agent remember that we have asked a question about Tom Hanks?

.Testing Memory
[source,python]
----
agent.run("and how many has he directed?")
----

    > Entering new AgentExecutor chain...
    ```json
    {
        "action": "GraphCypherQAChain",
        "action_input": "MATCH (p:Person {name: 'Tom Hanks'})-[:DIRECTED]->(m:Movie) RETURN count(m)"
    }
    ```

    > Entering new GraphCypherQAChain chain...
    Generated Cypher:
    MATCH (p:Person {name: 'Tom Hanks'})-[:DIRECTED]->(m:Movie) RETURN count(m)
    Full Context:
    [{'count(m)': 2}]

    > Finished chain.

    Observation:
    Tom Hanks has directed 2 movies.

    > Finished chain.



== Next Steps

You can learn how to put this all together to link:https://graphacademy.neo4j.com/courses/llm-chatbot/[Build a Movie Recommendation Chatbot backed by a Neo4j database using Streamlit^].
