= ノードの作成
:type: quiz
:order: 1

// [.video]
// video::fgoz4eMQHOk[youtube,width=560,height=315]


//https://youtu.be/fgoz4eMQHOk


////

2-Writing-CreatingNodes

https://docs.google.com/document/d/1aNwMNcTb1kb1qgaPKGejKfS3Yjn0FW3ijZh7UUIX2p0/edit?usp=sharing
////


[.transcript]
== ノードの作成
このレッスンでは、グラフにノードを作成するためのCypherコードの書き方を学びます。

Moviesデータモデルを使用して、グラフに俳優と映画を作成するためのCypherコードを作成し、実行します。

MERGE`キーワードを使用して、データベースに_pattern_を作成します。

MERGE` キーワードの後に、作成したいパターンを指定します。
通常、このパターンは 1 つのノードか、2 つのノード間のリレーションシップになります。

例えば、_Michael Cain_を表すノードを作りたいとします。
このCypherのコードを実行して、ノードを作成します。

[source,cypher]
----
MERGE (p:Person {name: 'Michael Cain'})
----

これは、グラフ内に1つのノードを作成します。
MERGE` を使ってノードを作成するときには、そのノードのユニークな主キーとなるプロパティを少なくとも1つ指定する必要があることに注意してください。

ノードが作成されたことを確認します。

[source,cypher]
----
MATCH (p:Person {name: 'Michael Cain'})
RETURN p
----

// browser::MATCH (n) RETURN count(n)[]

=== 複数のCypher句の実行

1つのCypherコードブロックの中で、複数の `MERGE` 節を連結して実行することもできます。

[source,cypher]
----
MERGE (p:Person {name: 'Katie Holmes'})
MERGE (m:Movie {title: 'The Dark Knight'})
RETURN p, m
----

このコードでは、2つのノードを作成し、それぞれに主キー・プロパティを設定しています。
変数 _p_ と _m_ を指定しているので、作成されたノードを返すコードでそれらを使用することができます。

=== `MERGE` の代わりに `CREATE` を使ってノードを作成する

Cypherには、ノードを作成する際に使用できる `CREATE` 節があります。
`CREATE` を使用する利点は、ノードを追加する前に主キーをルックアップしないことです。
データがクリーンであることが確実で、インポート時の速度を上げたい場合に `CREATE` を使用するとよい。
このトレーニングでは、ノードの重複を排除するために `MERGE` を使用します。

== 理解度の確認

include::questions/1-merge-keyword.adoc[leveloffset=+1]

include::questions/2-property-label-for-node.adoc[leveloffset=+1]

[.summary]
== まとめ

このレッスンでは、グラフにノードを作成する方法を学びました。
次の課題では、ノードを作成するスキルを実証します。


