[.question.freetext]
= Top French movie

Here is your starter code:

[source,cypher]
----
MATCH (g:Genre)
// write subquery
RETURN g.name AS genre, numMovies
ORDER BY numMovies DESC
----

Write and execute the subquery to return the movie nodes that have a countries list element of 'France'.

. You must pass in the g variable to the subquery.
. You must test if the movie node for that genre was released in France.
. The subquery must return the count of the movie nodes, numMovies for each Genre passed in.

How many movies were in the largest Genre category for movies released in France? (enter a number)

// reco db change impact
// the number of rows will be different so this answer must be changed


input::answer[]

* [x] 277

[TIP,role=hint]
.Hint
====
Use `WITH` to pass in the Genre reference.

The subquery will find all movies of that Genre released in France.
It will return the count of the movies.

How many movies were in the largest Genre category for movies released in France? (enter a number)

Once you have entered the answer, click the **Try Again** button below to continue.
====

[TIP,role=solution]
.Solution
====

This is the query to answer the question:

[source,cypher]
----
include::../solution.cypher[]
----

How many movies were in the largest Genre category for movies released in France? (enter a number)

Once you have entered the answer, click the **Try Again** button below to continue.
====

