[.question.freetext]
= Latest Movie Reviews

Write a query that returns a list pertaining to the movie, Toy Story. The list will contain the timestamp of when the movie review was done (from the RATING relationship) and the name of the reviewer.

Who was the last person to review the movie Toy Story?

Once you executed, enter the name below and click **Check Answer**.

**Note**: You can use `datetime({epochseconds:r.timestamp})` to format the timestamp into something that is readable.

input::answer[]

* [x] Catherine Trujillo

[TIP,role=hint]
.Hint
====

First write a `MATCH` clause to find the users and RATED relationships for the movie Toy Story.

Use a `WITH` clause to create the list containing the timestamp and user name. Order the nodes retrieved in timestamp order.

RETURN each row as a pair. There should be 247 rows returned.

Who was the last person to review the movie Toy Story?

Once you have entered the answer, click the **Try Again** button below to continue.

====

[TIP,role=solution]
.Solution
====

This is the query to answer the question:

[source,cypher]
----
include::../solution.cypher[]
----

Who was the last person to review the movie Toy Story?

Once you have entered the answer, click the **Try Again** button below to continue.
====


