CREATE CONSTRAINT Genre_name IF NOT EXISTS ON (x:Genre) ASSERT x.name IS UNIQUE;
CREATE CONSTRAINT Movie_movieId IF NOT EXISTS ON (x:Movie) ASSERT x.movieId IS UNIQUE;
CREATE CONSTRAINT Person_tmdbId IF NOT EXISTS ON (x:Person) ASSERT x.tmdbId IS UNIQUE;
CREATE CONSTRAINT User_userId IF NOT EXISTS ON (x:User) ASSERT x.userId IS UNIQUE