= Setup your development environment
:order: 0
:type: lesson
:lab: {repository-link}
:disable-cache: true

In this module, you will use Python to create a graph from unstructured data.
You must set up a development environment to run the code examples and exercises.

We have created a link:https://github.com/neo4j-graphacademy/llm-vectors-unstructured[repository^] for this course.
It contains the starter code and resources you need. 

A blank Neo4j Sandbox instance has also been created for you to use during this course.

You can open a Neo4j Browser window throughout this course by clicking the link:#[Toggle Sandbox,role=classroom-sandbox-toggle] button in the bottom right-hand corner of the screen.

== Get the code

You can use link:https://gitpod.io[Gitpod^] as an online IDE and workspace for this workshop.
It will automatically clone the workshop repository and set up your environment.

lab::Open `Gitpod workspace`[]

[NOTE]
You will need to login with a Github, Gitlab, or Bitbucket account.

Alternatively, you can clone the repository and set up the environment yourself.

[%collapsible]
.Develop on your local machine
====
You will need link:https://python.org[Python] installed and the ability to install packages using `pip`.

You may want to set up a virtual environment using link:https://docs.python.org/3/library/venv.html[`venv`^] or link:https://virtualenv.pypa.io/en/latest/[`virtualenv`^] to keep your dependencies separate from other projects.

Clone the link:https://github.com/neo4j-graphacademy/llm-vectors-unstructured[github.com/neo4j-graphacademy/llm-vectors-unstructured] repository:

[source,bash]
----
git clone https://github.com/neo4j-graphacademy/llm-vectors-unstructured
----

Install the required packages using `pip` and download the required data:

[source,bash]
----
cd llm-vectors-unstructured
pip install -r requirements.txt
python -m textblob.download_corpora
----
====

== Setup the environment

Create a copy of the `.env.example` file and name it `.env`. 
Fill in the required values.

[source]
.Create a .env file
----
include::{repository-raw}/main/.env.example[]
----

Add your Open AI API key (`OPENAI_API_KEY`), which you can get from link:https://platform.openai.com[platformn.openai.com].

Update the Neo4j sandbox connection details:

NEO4J_URI:: [copy]#bolt://{sandbox_ip}:{sandbox_boltPort}#
NEO4J_USERNAME:: [copy]#{sandbox_username}#
NEO4J_PASSWORD:: [copy]#{sandbox_password}#

== Test your setup

You can test your setup by running `llm-vectors-unstructured\test_environment.py` - this will attempt to connect to the Neo4j sandbox and the OpenAI API.

You will see an `OK` message if you have set up your environment correctly. If any tests fail, check the contents of the `.env` file.

== Continue

When you are ready, you can move on to the next task.

read::Success - let's get started![]

[.summary]
== Summary

You have setup your environment and are ready to start this module.

In the next lesson, you will explore a strategy for storing unstructured data in a graph.