:id: _challenge
:repository-raw: https://raw.githubusercontent.com/neo4j-graphacademy/importing-data

[.verify]
= Validate Results

Once you completed the steps of this Challenge, click the **Check Database** button and we will check the database for you.


verify::[]

[TIP,role=hint]
.Hint
====
If your graph does not verify, you should refresh the page for this challenge which will reset the graph, and you can start all over.

Make sure you have:

1. Downloaded and unzipped the CSV files.
2. Add the local CSV files to your Data Importer files.
3. Perform the mapping.
4. Run the import using the credentials for your sandbox.

You can use this code to verify property names and types for nodes:

[source,Cypher]
----
include::{repository-raw}/main/shared/apoc-meta-nodetypeproperties.cypher[]
----

You can use this code to verify property names and types for relationships:

[source,Cypher]
----
include::{repository-ramain/shared}/apoc-meta-nodetypeproperties.cypher[]
----

====

[TIP,role=solution]
.Solution
====
If your graph does not verify, you should refresh the page for this challenge which will reset the graph, and you can start all over.

You can download the https://data.neo4j.com/importing/movieModel-solution.json[solution mapping file^] that you can import into your Data Importer UI
====