= The Spring Data Application Domain Model
:type: lesson

When you are building an application, you will typically have some set of data that you want to interact with. You need to organize that data somehow in order to sensibly operate on it, and you do that by creating a domain model. The domain model is a representation of the data that is relevant to your application.

This first structure is the human-understood model of the data. You will also need to map this model to the application model. In Java, you can model data as classes to create the application domain model. These classes are often referred to as _entities_, and they form the domain model of your application. Sometimes the original domain model matches the application domain model, but sometimes it has to be adjusted.

== Domain Components in Java

Domain classes can represent generic or specific entities. Depending on the application, you could model a `Person` class that represents employees, customers, dependents, or even stakeholders. You could also create individual `Employee`, `Customer`, `Dependent`, and `Stakeholder` classes, and even create the generic `Person` class that each subclass is related to. The choice depends on the application and the domain.

Entity classes contain metadata that describe them. For example, a `Person` entity might have a `name`, `dateOfBirth`, `address`, `emailAddress`, and `phoneNumber`. These fields are often referred to as _properties_ or _fields_.

Data classes can also be related to each other in various ways, depending on the business understanding of the data. You can have relationships among different data classes or between the same data class. Let's list some examples.

1. A `Person` entity might have a relationship to a `Company` entity (e.g., as an employee). This represents a relationship between two different data classes.
2. A `Person` entity might have a relationship to another `Person` entity as a colleague or a dependent. This represents a relationship between the same data class.
3. A `Person` entity might have a relationship to a `Company` entity, which has a relationship to a `Country` entity, which has a relationship to a `Continent` entity. This creates a path of connected entities.

== Object-Oriented Programming

Java is considered an object-oriented language because its focus is on data objects and how to create and manipulate them. Data objects are also the primary way that an application interacts with a data store. A domain can be modeled into a variety of data structures in Java, and Spring follows these conventions.

We will see how Neo4j is the perfect companion to Java and Spring due to the way it stores data as a graph of nodes and relationships.
