= Build a KG with Python
:order: 5
:type: lesson
:branch: firstrelease

Explore the Python code to do the same 

Modify the Python code to chunk documents differently

Add allowed nodes, relationships

Entity properties



In the previous lesson, you reviewed code snippets required to implement the knowledge graph build process. 

In this lesson, you will explore and modify the complete Python code to build a knowledge graph using LangChain.


Open the `llm-knowledge-graph/create_kg.py` file.

[collapsible]
.View create_kg.py
====
[source,python]
----
include::{repository-raw}/{branch}/create_kg.py[tag=**]
----
====

Review the code you should be able to identify the sections of the code that:

. Gather the data
. Chunk the data
. _Vectorize_ the data
. Pass the data to an LLM to extract nodes and relationships
. Use the output to generate the graph

GOT HERE


The more constraints you place on the model, the concise the knowledge graph will be. 
This is because the model will only generate nodes and relationships that are allowed.