= Add Directed relationship
:order: 6
:type: challenge
:shared-dir: ../../../../shared
:solution-filename: person-movie-acted_in-directed-import.zip
:image-path: {cdn-url}/importing-fundamentals/modules/2-data-importer/lessons/6-add-directed-relationship/images

[.slide.discrete]
== Challenge

Your challenge is to add the `DIRECTED` relationship between the `Person` and `Movie` nodes. 

image::{image-path}/directed.svg[a graph showing the DIRECTED relationship]

The link:https://data.neo4j.com/importing-fundamentals/directed.csv[`directed.csv`^] file contains the data to match the `Person` nodes to the `Movie` nodes. 
The file contains the following columns:

* `movieId` - The unique identifier of the movie
* `person_tmdbId` - the unique identifier of the person who directed the movie

[.slide.discrete]
== Challenge

You will need to:

. Upload the link:https://data.neo4j.com/importing-fundamentals/directed.csv[`directed.csv`^] file
. Create the `DIRECTED` relationship between the `Person` and `Movie` nodes
. Set the Node ID mapping 
. Run the import

[.slide.col-2]
== View the data

[.col]
====
Once you have imported the data, you can run the following query to view the `DIRECTED` relationships:

[source,cypher]
----
MATCH (p:Person)-[d:DIRECTED]->(m:Movie)
RETURN p,d,m
LIMIT 25
----
====

[.col]
image::{image-path}/directed-graph.svg[A graph showing the DIRECTED relationship between the Person and Movie nodes, width=80%]

[.transcript-only]
====
[%collapsible]
.Need to download a working solution?
=====
include::{shared-dir}/solution.adoc[]
=====
====

[.next.discrete]
== Continue

read::Continue[]

[.summary]
== Summary

In this challenge, you used data importer to create a relationship between nodes.

In the next lesson, you will learn how to import data and nodes from a single CSV file.