//TODO - I think we should drop the challenge. I change lesson 2 to be a walk through creating the index and querying it.


= Create a Vector Index
:type: challenge

In this hands-on challenge, you must use the Sandbox window to the right to perform the following tasks:

1. Call the `db.index.vector.createNodeIndex()` procedure to create a vector index on the loaded embeddings.
2. Use LOAD CSV to link:https://github.com/neo4j-graphacademy/llm-fundamentals/raw/main/data/embeddings.csv[pre-generated embeddings from a CSV file^] into the database.
3. Use the index to identify the closest movie to an embedding based on user input.

Once you have found the answer, enter it into the text box below.


== 1. Create a Vector Index

Call the `db.index.vector.createNodeIndex()` procedure to create a vector index on the loaded embeddings.
Call the index `plotEmbeddings`, create the index on the `Movie` and `plotEmbedding` pairing, and use the `cosine` similarity function.
The embeddings contain `3200` dimensions.

[%collapsible]
.Solution
====

To create the index, you can execute the following Cypher statement:

[source,cypher]
----
include::solution.cypher[tag=create]
----

====


== 2. Load the Embeddings

Use the `LOAD CSV` command to set a property.

The CSV file contains two columns; `movieId` and `embedding`.
Use the `MATCH` clause to identify the `(:Movie)` node with the corresponding `movieId` property and use the `embedding` column to set a new property called `plotEmbedding`.
Remember to call the `db.create.setVectorProperty()` procedure to validate the embedding before setting the property.

[%collapsible]
.Solution
====

To load the embeddings using `LOAD CSV`, you can run the following command:

[source,cypher]
----
include::solution.cypher[tag=load]
----

====


== 3. Query the new index

A `(:Prompt)` node has been added to the database containing `prompt` and `embedding` properties.
You can run the following statement to see the node:

.View The User Prompt
[source,cypher]
----
include::solution.cypher[tag=prompt]
----

Call the `db.index.vector.queryNodes()` procedure, using the `embedding` property to find the most similar movie plot to the prompt.


[%collapsible]
.Solution
====

To find the most similar movie plot to the prompt, run the following Cypher statement.

[source,cypher]
----
include::solution.cypher[tag=query]
----

====



== Your Answer

include::questions/1-name-the-movie.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this lesson, you followed the steps to import embeddings from a CSV file, created a vector index and queried the index to find a movie similar to a user prompt.

However, you may have found that the answer was not perfect, or was not the one that you were expecting.
In the next lesson, you will learn how user feedback can be used to improve the suggestions provided by Semantic Search.
