[.question.freetext]
= Movies produced in Switzerland?

How many movies produced in Switzerland are in the graph?

input::answer[]

// reco db change impact

////
change the solution to:
MATCH (m:Movie)
UNWIND m.countries AS country
WITH m, country
// this automatically, makes the country distinct because it's a grouping key
WITH country, collect(m.title) AS movies
WHERE country = 'Switzerland'
RETURN country, size(movies)
////

* [x] 50

[TIP,role=hint]
.Hint
====
The query you executed in the last challenge should answer this question:

[source,cypher]
----
include::../solution.cypher[]
----

How many movies produced in Switzerland are in the graph?

Once you have entered the answer, click the **Try Again** button below to continue.
====

[TIP,role=solution]
.Solution
====

You can run the following query to find the answer:

[source,cypher]
----
include::../solution.cypher[]
----

How many movies produced in Switzerland are in the graph?

Once you have entered the answer, click the **Try Again** button below to continue.
====
