= Spring Data Neo4j Projections
:order: 1
:type: lesson
:optional: true

This lesson covers the basics of projections in Spring Data Neo4j. You will learn what a projection is, when it is useful, as well as how to create and use it in your application.

== What is a projection?

Projections contain some subset or manipulation of a domain entity and act like a "view" of that entity. There are a few different situations where projections are invaluable, mostly centered around needing customized versions of a large object.

For example, if you have a domain entity with many properties or large values, it becomes cumbersome to work with, alter, and transport. You can create a projection that only contains a few properties, reducing the data that is sent over the wire. Or you could add extra properties  for a specific use that are not part of the domain entity, such as a calculated value.

There are also two types of projections in SDN: *interface-based* and *DTO-based*. Interface-based projections are useful when you want to create a projection that contains a subset of properties from a domain entity. DTO-based projections can be more flexible using a custom query to create a projection with additional properties.

Lastly, Spring Data Neo4j supports multi-level projections, where you can create a projection that contains a projection. This is useful when you want a subset of properties from a domain entity, but also a subset of a related entity.

We will look at many of these scenarios in the next couple of lessons.