[.question.freetext]
= Finding German Language Movies

Write and execute a query to return people who both acted in and directed a movie released in the German language.

// reco db change impact
// remove this note
**Note**: Some Movie.languages elements will have elements "German" and elements " German".

How many unique Person node names are returned? (There will be duplicates that you should not count)

// reco db change impact
// answer will be different
// solution should also be changed


input::answer[]

* [x] 18

[TIP,role=hint]
.Hint
====
Use `IN` to test whether "German"  or " German" is in the languages list property for the Movie node.

Do not count rows that have duplicate actor names.

How many unique Person node names are returned? (There will be duplicates that you should not count)

Once you have entered the answer, click the **Try Again** button below to continue.
====

[TIP,role=solution]
.Solution
====

This is the query to answer the question:

[source,cypher]
----
include::../solution.cypher[]
----

How many unique Person node names are returned? (There will be duplicates that you should not count)

Once you have entered the answer, click the **Try Again** button below to continue.
====
