= Authenticating a User
:type: challenge
:order: 8
:branch: 05-authentication
:test-filename: _05_AuthenticationTest
:test-method: authenticateUser

At stage of the application, a user can register, but they are still unable to sign in.

As with the previous Challenge, the `authenticate()` method is currently hard coded to accept only the email `graphacademy@neo4j.com` and password `letmein` from the fixture `users.json`.

In this challenge you will rewrite the `authenticate()` function of the link:{repository-blob}/main/src/main/java/neoflix/services/AuthService.java[`AuthService`^] to do the following:

1. <<Open a new Session>>
2. <<Find the User node within a Read Transaction>>
3. <<Verify The User Exists>>
4. <<Compare Passwords>>
5. <<Return User Details>>


But first, let's take a look at how Authentication works in the application.
If you prefer, you can skip straight to <<Implementing Authentication>>.

== Authorization & Authentication

Authorizing users works by checking the email and hashed password against information in the database.

When a user submits the *Sign In* form from the UI, the following process occurs:

1. A route handler for the `/login` route in link:{repository-blob}/main/src/main/java/neoflix/routes/AuthRoutes.java#L32[`src/main/java/neoflix/routes/AuthRoutes.java`^] listens for a `POST` request.
2. The `login` route calls the `authenticate()` method in the link:{repository-blob}/main/src/main/java/neoflix/services/AuthService.java#L89[`AuthService`^] with the username and password from the request.

The `authenticate()` method performs the following actions:

1. Attempt to find the user by their email address.
2. If the user can't be found, throw a ValidationException.
3. Compare the encrypted password in the database against the unencrypted password sent with the request.
4. If the passwords do not match, throw a ValidationException.
5. Otherwise, return an object containing the user's _safe_ properties (email, name, userId), and a JWT token with a set of claims that can be used in the UI.


For this strategy to work correctly, the `authenticate()` method must return an object which represents the user on successful login, or return null or an error if the credentials are incorrect.

Once a user is authorized a JWT token is generated (using the Auth0 JWT library) and passed back to the front-end to be used in the `Authorization` header until the user signs out or the token expires.

For authenticated users the application uses a pre-processor `before()` the routes to verify the authentication for each request, which is delegated to: `AppUtils.handleAuthAndSetUser`.

There the `Authorization` header is extracted and validated using the Auth0 JWT library.
If that is successful the userId is set as a request attribute which can be accessed by the route implementation.


== Implementing Authentication

To implement database authentication, you will modify the `authenticate` method in the `AuthService`.

.neoflix/services/AuthService.java
[source,java,indent=0]
----
include::{repository-raw}/main/src/main/java/neoflix/services/AuthService.java[tag=authenticate]
----

Your challenge is to update the `authenticate()` method to perform the following actions:

=== Open a new Session

First, open a new session:

[source,java,indent=0]
----
include::{repository-raw}/main/src/main/java/example/Index.java[tag=session]
----


=== Find the User node within a Read Transaction

Use a `MATCH` query to find a `:User` node with the email address passed to the method as a parameter.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/AuthService.java[tag="query"]
----


=== Verify The User Exists

If no records are returned, you can safely assume that the user does not exist in the database, then the `single()` method on `Result` will throw a `NoSuchRecordException`.

In this case, an `ValidationException` is thrown.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/AuthService.java[tag="auth-catch"]
----

=== Compare Passwords

Next, you must verify that the unencrypted password matches the encrypted password saved as a property against the `:User` node.

The `bcrypt` library used to encrypt the password also includes a `verify()` function that can be used to compare a string against a previously encrypted value, we encapsulate that in `AuthUtils.verifyPassword()`.

If the `AuthUtils.verifyPassword()` method returns false, the passwords do not match and the method should throw a new ValidationException.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/AuthService.java[tag="password"]
----


=== Return User Details

As with the `register()` method, the UI expects a JWT token to be returned along with the response.

The code is already written to the example, so this can be re-purposed at the end of the method.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/AuthService.java[tag="auth-return"]
----

Once you have applied these changes to the `authenticate()` method, scroll to <<Testing>> to verify that the method works as expected.


== Working Solution

[%collapsible]
.Click here to reveal the completed `authenticate()` method:
====

.neoflix/services/AuthService.java
[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/AuthService.java[tag="authenticate"]
----

====

include::../../../../includes/test.adoc[]

[.summary]
== Lesson Summary

In this challenge, you have updated the `AuthService` to authenticate a User using the data held in the Sandbox database.

In the next challenge, you will save the current user's movie ratings to the database.
