:id: _challenge

[.verify]
= Verifying the Test

If the test has run successfully, a user with the email address `graphacademy.reviewer@neo4j.com` will have given the movie Goodfellas a rating of `5`.

That number should have a type of `INTEGER`



verify::[]

//appears when user clicks the Hint button
[TIP,role=hint]
.Hint
====
You can run the following query to check for the user within the database.
If the `shouldVerify` value returns true, the verification should be successful.

[source,cypher]
----
include::{cypher-repository-raw}/main/cypher/2-interacting/8-ratings/user-rated-goodfellas.cypher[]
----

====


[TIP,role=solution]
.Solution
====
The following statement will mimic the behaviour of the test, merging a new `:User` node with the email address `graphacademy.reviewer@neo4j.com` and a `:Movie` node with a `.tmdbId` property of `'769'`.

The test then merges a relationship between the user and movie nodes in the graph, giving the relationship a `.rating` property.

[source,cypher]
----
include::../solution.cypher[]
----

Once you have run this statement, click **Try again...** to complete the challenge.
====
