= Course Summary

Congratulations!
You should now have a good understanding of the Neo4j Graph Data Science (GDS) library.

In the first module, **Neo4j GDS Overview**, we covered learned a high level technical overview of Neo4j GDS including how the product works.

In the second module, **Graph Management**, you learned how GDS how to create and manage in-memory graph projections, the distinction between native and cypher projections, and when to use them.


== Recommendations Dataset

If you would like an offline copy of the database, you can download a database dump from Github.

link:https://github.com/neo4j-graph-examples/recommendations[Recommendations dataset]



include::../../shared/resources.adoc[]


== Next Steps

Now you have a good understanding of the Neo4j GDS Library, you can advance to the
 link:/courses/graph-data-science-fundamentals/[Graph Data Science Fundamentals^] course where you will learn all you need to know about Graph Algorithms, the algorithms available in GDS and how Machine Learning Pipelines can be used to perform common a range of graph-related ML tasks.