= Neo4j & Generative AI Hands-on Workshop : Facilitators Guide

https://graphacademy.neo4j.com/courses/workshop-genai/[graphacademy.neo4j.com/courses/workshop-genai/]

== Introduction

The Neo4j & Generative AI Hands-on Workshop is designed to give people an introduction to Neo4j’s Generative AI functions and allow them to explore how graphs and Neo4j can be used to improve GenAI applications.

The workshop introduces GenAI concepts including Large Language Models, Hallucination, Prompts, RAG, GraphRAG, Vectors, Knowledge Graphs, and Agents.

The workshop can be presented online or in person and is best suited for 2-4 hour sessions.

== Prerequisites

Learners should have a fundamental understanding of graph databases and Neo4j, Cypher, and reading and writing simple Python programs.

Learners will need a GraphAcademy and github account - if needed these can be created during the workshop.

== Learning objectives

* The basics of Generative AI and Large Language Models (LLMs).
* What Retrieval-Augmented Generation (RAG) is and why it is important.
* How GraphRAG can improve the quality of LLM-generated content.
* How to build knowledge graphs from unstructured PDF documents using entity extraction and relationship mapping.
* How to enrich knowledge graphs with structured data.
* How to use Vectors in Neo4j for similarity search.
* To build different types of retrievers using the neo4j-graphrag for Python package.
* To build a conversational agent using Neo4j, Python, and LangChain.

== Resources

All workshop resources are in https://drive.google.com/drive/folders/16BT4AQ93onYSCgIVGqDwNSK9Rawo6YpN[Developer Relations/GraphAcademy/Workshops/workshop-genai], including:

* ?tab=t.0[Facilitators guide] (this document)
* https://docs.google.com/document/d/11WxaDiZ_dsiF6ZlPx5vmg4A6bB96W9PViQnSd6lDDIk/edit?usp=sharing[How to use GraphAcademy Workshops & Slides]
* An https://docs.google.com/document/d/1PMWzgmrACo8FUZPReEpjI4hkw0pvDrPmcbkYMq3BWHw/edit?usp=sharing[example CFP submission] for this workshop
* https://docs.google.com/presentation/d/13yEKVBIlK3q-Ka2NoDlRvpTD3CUXkZLTVD0ckMo3jJk/edit?slide=id.g3b9011bb0be_0_0#slide=id.g3b9011bb0be_0_0[Introductory slides] (you should make your own copy)
* A notes document to share links and keys - dev.neo4j.com/workshop-genai-notes[dev.neo4j.com/workshop-genai-notes]
* https://graphacademy.neo4j.com/courses/workshop-genai/[GraphAcademy Neo4j & Generative AI Hands-on Workshop]

== Preparation

What you should know:

* How to read and write Python programs
* https://graphacademy.neo4j.com/courses/genai-fundamentals/[Neo4j and GenerativeAI Fundamentals]
* https://graphacademy.neo4j.com/courses/genai-graphrag-python/[Constructing Knowledge Graphs with Neo4j GraphRAG for Python]
* https://graphacademy.neo4j.com/courses/genai-integration-langchain/[How to Use Neo4j with LangChain]

What you will need:

* A https://graphacademy.neo4j.com[GraphAcademy] account
* A https://github.com[github] account
* An OpenAI API key - platform.openai.com[platform.openai.com]

What you will need to do:

. Complete the workshop before delivering it
. Review the outline plan (below) for additional context / approach
. Create a personalised copy of the https://docs.google.com/presentation/d/13yEKVBIlK3q-Ka2NoDlRvpTD3CUXkZLTVD0ckMo3jJk/edit?slide=id.g3b9011bb0be_0_0#slide=id.g3b9011bb0be_0_0[introduction slides]
. Create (or request) an OpenAI API key and update the http://dev.neo4j.com/workshop-genai-notes[notes] document
. (Depending on the size of the workshop > 25 participants) Request an increase in the sandbox pool size.
.. In the #sandbox-experience slack channel
.. Use the command /workshop [sandbox-name] [pool size increase] [start - YYYY-MM-DD HH:MM] [end - YYYY-MM-DD HH:MM]
.. e.g. /workshop blank-sandbox 20 2026-02-03 14:00 2026-02-03 16:00
. Delete your previous enrollment to the workshop (so you see the same view as the participants)
. Run the workshop!
. Delete the OpenAI API key

== Outline plan

(All timings are estimates and adaptable)

=== Introduction

(10 mins)

*Introduce yourself, the session, and have participants login*

Use the introduction slides to introduce yourself and the agenda

Introduce GraphAcademy and ask learners to create an account and goto the workshop URL in the notes document.

https://graphacademy.neo4j.com/courses/workshop-genai/[https://graphacademy.neo4j.com/courses/workshop-genai/]

Starter activity - “ask people what (if any) experience they have had with Neo4j or Generative AI”

Show learners the GraphAcademy course summary, summarise the learning objectives and enrol in the course.

=== What is Generative AI

(30-60 mins)

*Describe Generative AI and setup the development environment*

Describe generative AI concepts, a key message being that supplying good context is essential for improving responses.

Illustrate how RAG & GraphRAG are patterns for supplying context in prompts to LLMs.

A common misconception is that LLMs are constantly updated with new information (without you having to provide it in the prompt).

Finally learners will set up a development environment. Encourage participants to use the codespace, the environment will be set up automatically for them. 

Remind learners that setting up an environment is often the hardest part of the session. Ensure people have run the `test_environment.py` program and received the `OK` message before continuing.

Demo creating the environment while they are working on the task.

=== Knowledge Graph Construction

(30-60 mins)

*Build a knowledge graph from unstructured data*

Learners will explore how they can use an LLM to do entity and relationship extraction from unstructured text before building a knowledge graph from the text.

The module iterates on creating the graph, adding more complexity in each lesson such as modifying the chunk size, defining schemas, and adding structured data.

Learners should be encouraged to experiment with different options particularly in defining the schema.

The final lesson is an open ended task and can be used either to extend the workshop or be signposted for homework after workshop

=== Retrieval

(15-30 mins)

*Create GraphRAG retrievers to interact with the knowledge graph*

Describe vectors and semantic search and demonstrate it working using a vector index on the Chunks in the knowledge graph.

Create vector and vector + graph retrievers and GraphRAG pipelines to ask questions using the knowledge graph.

Take the opportunity to demonstrate how the vector + graph retriever uses the graph to add additional relevant context which is not contained in the chunks and provides a better response.

Create a text to cypher GraphRAG pipeline and show how the text to cypher retriever is useful for summarizing results or retrieving facts.

=== Agents

(30-60 mins)

*Build an agent with LangChain that uses the GraphRAG retrievers*

_For sessions under 2 hours you should just introduce the module and suggest learners continue with this later._

Describe how agents work particularly the plan, reason, action, observe, iterate (if required), result cycle.

Review the code for the agent that uses a single tool to answer questions about the graph data model.

Learners will iterate and improve the agent by adding additional tools using the retrievers from the previous module.

There are pre-canned questions which demonstrate the agents capabilities, but encourage learners to experiment by demo’ing your own questions.

The final lesson is an open ended task where learners can create their agents

=== Close

*Q&A and call to action*

Return to the introduction slides, remind learners they will have access to the workshop content indefinitely.

Run a Q&A session.

Suggest GraphAcademy courses for learners to continue their learning.

