= Building Neo4j Applications with Java
:categories: developer:2, java:1, software-development:12, intermediate:12, , development:3
:usecase: recommendations
:status: active
:caption: Learn how to build Java applications with Neo4j using the Neo4j Java Driver
:key-points: Driver life cycle, installing and instantiation, read and write transactions, best practices
// tag::config[]
:repository: neo4j-graphacademy/app-java
:cypher-repository: neo4j-graphacademy/neoflix-cypher
:java-version: 17
:package: neoflix
// end::config[]

== Course Objectives

In this course, you will learn how to use Neo4j in your Java project. You will understand how to map a graph data model to a Java application domain model.

You will learn the skills you need to build applications with Java to read data from and write data to Neo4j.

=== Prerequisites

By taking this course, we assume that you have a working knowledge of Java and how to build applications.
We also assume that you have at least a basic knowledge of Neo4j.

If you haven't already done so, we recommend that you also take the link:/courses/neo4j-fundamentals/[Neo4j Fundamentals] course in order to gain a basic understanding of Neo4j, the link:/courses/cypher-fundamentals/[Cypher Fundamentals] to understand how to query Neo4j using Cypher, and the link:/courses/drivers-java/[Using Neo4j with Java] course to understand how to integrate Neo4j into your Java projects.

=== Duration

4 hours

=== What you will learn

* How to use Neo4j with Java
* How to map a graph data model to a Java application domain model
* How to convert between Neo4j and Java data type systems
* How to read data from and write data to Neo4j
* Continuing education: ideas for further development and where to find resources
* Optional:
** Authentication with link:https://github.com/auth0/auth0-java[Auth0^] and link:https://jwt.io/[JWT Tokens^]
** Passwords encrypted and verified with link:https://javadoc.io/doc/at.favre.lib/bcrypt/latest/index.html[bcrypt^]
** Testing using link:https://junit.org/junit5/[JUnit5^]

[.includes]
== This course includes

* [lessons]#Lessons for understanding concepts and syntax#
* [challenges]#Hands-on challenges for practical application#
* [quizes]#Quizzes to support your learning#
