= Building Neo4j Applications with Java
:categories: developer:2, java
:usecase: recommendations
//:status: active
:caption: Learn how to interact with Neo4j from Java using the Neo4j Java Driver
// tag::config[]
:repository: neo4j-graphacademy/app-java
:cypher-repository: neo4j-graphacademy/neoflix-cypher
:java-version: 17.0.2
:package: neoflix
// end::config[]

== Course Description

In this course, we walk through the steps to integrate Neo4j into your Java project.

We will follow the steps to create an instance of the Neo4j Java Driver, learn about sessions and transactions, and use that knowledge to build a REST API with link:https://sparkjava.com/[SparkJava^] that will work with a pre-built Single Page Application (SPA).

The course automatically creates a new `{usecase}` sandbox within link:https://sandbox.neo4j.com/?usecase={usecase}[Neo4j Sandbox] that you will use throughout the course.

=== Prerequisites

By taking this course, we assume that you have a working knowledge of Java, Maven and the Java ecosystem.
We also assume that you have at least a basic knowledge of Neo4j.

If you haven't already done so, we recommend that you also take the link:/courses/neo4j-fundamentals[Neo4j Fundamentals] course in on order to gain a basic understanding of Neo4j and the link:/courses/cypher-fundamentals[Cypher Fundamentals] to understand how to query Neo4j using Cypher.

=== Duration

8 hours

=== What you will learn

* The lifecycle of the Neo4j Driver and how it relates to your application
* How to install and instantiate the Neo4j Java Driver into your Java project
* How read and write transactions work with Neo4j
* Best practices on how to use Neo4j within your Java project
