= Creating Node Key Constraints
:type: quiz
:sandbox: true

//[.video]
//video::Po4k7vXGBIE[youtube,width=560,height=315]

//https://youtu.be/Po4k7vXGBIE

[.transcript]

== Node key

A Node key is a specialized type of constraint for the properties of a node.
It combines existence with uniqueness.

For example, a Person node's tmdbId value must be unique **and** exist.

[NOTE]
--
Node key constraints are only available in Enterprise Edition.
--

== Syntax for creating a Node key constraint for a single property

Here is the syntax for creating a Node key constraint for a single property:

[source,cypher,role=nocopy noplay]
----
CREATE CONSTRAINT <constraint_name> IF NOT EXISTS
FOR (x:<node_label>)
REQUIRE x.<property_key> IS NODE KEY
----

You specify the name of the constraint, the node label it will be associated with, and the name of the property.

* If a constraint already exists in the graph with the same name, no constraint is created.
* If a constraint does not exist in the graph with the same name:
** No constraint is created if there already is a Node key constraint for that node label and property key.
** Otherwise, the constraint is created.

=== Creating the Node key constraint for a single property

Execute this code to create a Node key constraint for the Movie.tmdbId property:

[source,cypher]
----
CREATE CONSTRAINT Movie_imdbId_nodekey IF NOT EXISTS
FOR (x:Movie)
REQUIRE x.imdbId IS NODE KEY
----

This code creates the Node key constraint named Movie_imdbId_nodekey.
Every Movie node in the graph must have a property, imdbId and it must be unique.

At this point in this course, you should have the following constraints on the Movie nodes:

* The movieId value must be unique
* The value for released and title properties combined must be unique
* The title  property must exist
* The imdbId property must exist and must have a unique value

With these constraints, the following code will fail based upon the latest Node key constraint that you created:

[source,cypher]
----
MERGE (x:Movie {title: "No Place Like Home", imdbId: "0113497", movieId: "9999999"})
RETURN x
----

The title and movieId values are unique, but there already is a Movie node in the graph with the same value for imdbId.
If you remove the specification for imdbId, it will still fail because it is required per the Node key constraint.

== Syntax for creating a Node key constraint for multiple properties

Here is the syntax for creating a Node key constraint for a set of properties:

[source,cypher,role=nocopy noplay]
----
CREATE CONSTRAINT <constraint_name> IF NOT EXISTS
FOR (x:<node_label>)
REQUIRE (x.<property_key1>, x.<property_key2>)  IS NODE KEY
----

This constraint ensures that a set of values for a node's properties will be unique and must also exist.

== Check your understanding

include::questions/1-complete-query.adoc[leveloffset=+1]
include::questions/2-select-answer.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you learned how to create a Node key constraint for a node that ensures uniqueness and existence.
In the next challenge, you will create a Node key constraint.
