[.question.freetext]
= When was Kevin Bacon born?

Modify the query in the Neo4j Browser window to the right of the screen to find the year that [copy]#Kevin Bacon# was born.
This value is stored in the [copy]#born# property.

Once you have found the correct year, **enter the year below** and click **Check Answer**.

input::answer[]

* [x] 1958

// Once you have entered the answer, click the **Check Answer** button below to continue.

[TIP,role=hint]
.Hint
====
The answer is the `born` property of the `(:Person)` node.

You can search for the name property by either link:https://neo4j.com/docs/cypher-manual/current/clauses/where/#filter-on-patterns[Filtering the name of the _Person_ node within the `MATCH` clause^] or by link:https://neo4j.com/docs/cypher-manual/current/clauses/where/#filter-on-node-property[adding a `WHERE` clause to the query^].

You can either return the entire node or return the _born_ property.
====



[TIP,role=solution]
.Solution
====
To find the answer, run the following query in the Sandbox window:

[source,cypher]
----
include::../solution.cypher[]
----

Enter the `year` property from the result into the text box.
====