= Generating Cypher Statements
:type: challenge
:order: 3

Now for another challenge.

Your goal is to find out **which movie has the highest IMDB rating** in the movies database.

You can repeat the steps from the previous challenge, instead asking for the highest rated movie and its IMDB rating.

Ask Copilot the specific question:

[source,text]
----
Which movie has the highest IMDB rating, and what is its rating?
----

Copilot will use the `read-neo4j-cypher` tool to generate and execute a Cypher query to find the movie with the highest IMDB rating.

If you have followed the instructions correctly, you should now see a response from Copilot that answers the question.

[TIP]
.Non-null properties 
====
The `imdbRating` property does not exist for all movies in the database.
This is treated by Neo4j as a _null property_, which are treated as the lowest possible value when ordered in descending order. 

You may need to instruct Copilot to only return movies with a non-null `imdbRating` property.
====



include::questions/1-highest-rated-movie.adoc[leveloffset=+1]

[.summary]
== Summary

You used the `read-neo4j-cypher` tool to generate a Cypher query that finds the movie with the highest IMDB rating in the movies database.

In the next challenge, you will use VS Code to build a simple Python application.




