[.question.freetext]
= How many flights you have to take to get from LAX to HKT?

Use the Neo4j Browser window to the right of the screen to modify the query to find the shortest number of flights you have to take to get from Los Angeles (LAX) to Phuket (HKT).

Enter the **number** of flight in the box below, then click the **Check Answer** button below to continue.

input::answer[]

* [x] 2

// Once you have entered the answer, click the **Check Answer** button below to continue.

[TIP,role=hint]
.Hint
====
You are looking for the number of `[:HAS_ROUTE]` relationships in the shortest path between _LAX_ and _HKT_ airports.
You can find the result by finding the shortest path between the two airports and then use the `length` function to extract the number of relationships from the path object.
====

[TIP,role=solution]
.Solution
====
You can use the following query to find the number of people who directed _Cloud Atlas_:

[source,cypher]
----
include::../solution.cypher[]
----

Click the **Run in Sandbox** button to reveal the answer in the Sandbox window.
====