= Course prerequisites
:order: 1
:type: lesson

In order to build an application with Spring Data Neo4j and connect to a Neo4j database, you will need a few foundational skills.

== Prerequisites

1. Be able to write Java programs. While you can use Spring Data Neo4j with other JVM languages, this course will use Java.

2. Familiarity with Spring Boot and Spring Data. We will not cover the Boot and Data projects in this course, but you can learn more about them from Spring's link:https://spring.io/projects[website].

3. Be able to build applications with Spring Boot and Spring Data. There are other ways to use Spring with Neo4j (such as with the plain Java Driver, Neo4j Client, Neo4j Template, or OGM components), but using the Spring Boot and Spring Data projects together provides the most consistent and straightforward experience.

4. Have completed the link:/courses/neo4j-fundamentals/[Neo4j Fundamentals] and link:/courses/cypher-fundamentals/[Cypher Fundamentals] courses. You should be familiar with what a graph is and how to use the Cypher query language to create and query a graph database.

[.summary]
== Lesson Summary

In this lesson, you reviewed any prerequisites needed to complete this course.

In the next lesson, you will learn how to install components needed and verify your developer environment.