= Setup
:order: 1
:type: lesson

In order to build an application with Spring Data Neo4j and connect to a Neo4j database, you will need a few foundational skills. Then you will set up (or verify) the tools needed to work with the Spring Data Neo4j library.

== Prerequisites

1. Be able to write Java programs. While you can use Spring Data Neo4j with other JVM languages, this course will use Java.

2. Familiarity with Spring Boot and Spring Data. We will not cover the Boot and Data projects in this course, but you can learn more about them from Spring's link:https://spring.io/projects[website].

3. Be able to build applications with Spring Boot and Spring Data. There are other ways to use Spring with Neo4j (such as with the plain Java Driver, Neo4j Client, Neo4j Template, or OGM components), but using the Spring Boot and Spring Data projects together provides the most straightforward experience.

4. Complete the link:/courses/neo4j-fundamentals/[Neo4j Fundamentals] and link:/courses/cypher-fundamentals/[Cypher Fundamentals] courses. You should be familiar with what a graph is and how to use the Cypher query language to read and write data to Neo4j.

== Set Up Your Development Environment

1. Verify your Java version. You will need Java 17 or higher. You can check your version by running the following command in your terminal window: +
`java -version`. To download the latest version of Java, go to https://adoptopenjdk.net.

2. An IDE of your choice. If you don't yet have a preference, you can download https://www.jetbrains.com/idea/download[IntelliJ IDEA Community Edition^] or https://code.visualstudio.com/download[Visual Studio Code^], both excellent choices.

3. Optional: if you do not want to build the application locally, you can run the project from the browser using https://gitpod.io[Gitpod^]. This will require a Gitpod account. You can sign up for free.

[.summary]
== Lesson Summary

In this lesson, you reviewed any prerequisites needed to complete this course and ensured you have everything in your development environment ready to work with the Spring Data Neo4j library.

In the next lesson, you will learn how to create a Spring Boot application and add the Spring Data Neo4j library to it.