= Relational to Graph
:type: lesson
:order: 1

[.slide.discrete.col-2]
== Introduction

[.col]
====
You are going to learn how to approach relational to graph data modeling.

Imagine a simple relational model for an e-commerce system with Customers, Orders, Products, and Reviews:

* `Customers` can place `Orders`.
* `Orders` can contain `Products`.
* `Customers` can give reviews for `Products`.
====

[.col]
====
[source, mermaid]
.Relational model
----
include::diagrams/ecom-erd.mermaid[]
----
====

[.slide.col-2]
== Golden Rule

[.col]
====
A useful guide when creating graph data models is to use: 

`(Noun)-[:VERB]-(Noun)`

Nodes represents entities or _things_. Relationship describe how they are _connected_.
====

[.col]
====
[source, mermaid]
.Noun-Verb-Noun
----
include::diagrams/noun-verb-noun.mermaid[]
----
====

[.slide.col-2]
== Tables to Node labels

[.col]
====
A simplistic approach is to map tables to node labels and primary/foreign key pairs to relationships.
====

[.col]
====
[source, mermaid]
.Fields to properties
----
include::diagrams/tables-to-graph.mermaid[]
----
====

[.transcript-only]
====
[IMPORTANT]
.Many to many relationships
=====
There is a separate table, `OrderProduct` to store data relating to the many to many, Orders to Products, relationship. Many to many tables only exists to support the relational database structure, when modelling in a graph, you will not need these tables.
=====
====

[.slide]
== Properties

Fields can be mapped to properties in nodes.

[source, mermaid]
.Customer table to node
----
include::diagrams/customer-table-to-node.mermaid[]
----

[.slide.discrete]
== Relationship properties

Fields can also be mapped to properties on relationships.

[source, mermaid]
.OrderProduct table to relationship
----
include::diagrams/orderproduct-table-to-relationship.mermaid[]
----

[.transcript-only]
====
[NOTE]
.Null fields
=====
Neo4j's schema-optional approach means that `null` values in tables can be excluded and do not need to be mapped to a property.
=====
====

[.slide]
== Naming conventions

Neo4j recommends the following naming conventions:

* Node labels - *PascalCase* - `Customer`, `SalesRepresentative`
* Relationships - *ALL_CAPS_UNDERSCORE* - `PLACED`, `LIVES_AT`
* Properties - *camelCase* - `firstName`, `address`

[.slide.col-2]
== Graph Model

[.col]
====
The final graph data model for this simple e-commerce system would be:

[source, mermaid]
.Graph model
----
include::diagrams/graph-model.mermaid[]
----
====

[.col]
====
[NOTE]
.Simpler to understand
=====
The graph data model is simpler and easier to understand than the relational model. 

The many-to-many table has been removed and the relationships are more intuitive.

The review data is now stored as properties on the relationship between `Customer` and `Product`.
=====
====

[.next]
== Next
read::Continue[]


[.summary]
== Lesson Summary

In this lesson, you learned about relational to graph data modeling. You learned the golden rule of `(Noun)-[:VERB]-(Noun)`, how to map tables to node labels and relationships, and how to map fields to properties.

In the next lesson, you will use the Aura Import tool to import data from a relational data set into a graph.
