= Relational to Graph
:type: lesson
:order: 1


How to approach relational to graph data modeling.
Simple graph data modelling

You are going to learn how to approach relational to graph data modeling.

Imagine a simple relational model for an e-commerce system with Customers, Orders, Products, and Reviews:

* `Customers` can place `Orders`.
* `Orders` can contain `Products`.
* `Customers` can give reviews for `Products`.

[source, mermaid]
----
----

== Golden Rule

A useful guide when creating graph data models is to use `(Noun)-[:VERB]-(Noun)`.

Nodes represents entities or _things_. Relationship describe how they are _connected_.

// todo create mermaid diagrams for these.
`(Customer)-[:PLACED]->(Order)`

`(Order)-[:CONTAINS]->(Product)`

`(Custumer)-[:REVIEWED]->(Product)`


== Tables to Node labels

A simplistic approach is to map tables to node labels and primary/foreign key pairs to relationships.

// transcript only
[IMPORTANT]
.Many to many relationships
====
There is a separate table, `OrderProduct` to store data relating to the many to many, Orders to Products, relationship. Many to many tables only exists to support the relational database structure, when modelling in a graph, you will not need these tables.
====

// diagram
Customer table > Customer node
Order > Order node
Product > Product node
OrderProduct > Order-CONTAINS->Product relationship


// Point out the many to many relationships between tables and how they can be represented in a graph model.

== Properties

Fields can be mapped to properties in nodes or relationships.

// diagram 
Customer table fields > customer node properties

OrderProduct fields > CONTAINS relationship

[NOTE]
.Null fields
====
Neo4j's schema-optional approach means that `null` values in tables can be excluded and do not need to be mapped to a property.
====


== Naming conventions

Neo4j recommends the following naming conventions:

// todo check this
- Node labels - `` - `Customer`
- Relationships - `CAPS` - `PLACED`
- Properties - `camelCase` - `firstName`

== Graph Model

The final graph data model for this simple e-commerce system would be:

// todo mermaid of graph diagram


== Next

read::Continue[]


[.summary]
== Lesson Summary

In this lesson, you learned about ..

In the next lesson, you will learn about ..