= Installing an MCP server
:order: 2


To install an MCP server, you will need to configure your host with details about the server's location, transport method, and environment variables.
While the configuration file location and specific details may vary between hosts, the overall setup process follows similar steps.

For example, to add a new MCP server to Claude Desktop, you would add an entry to the `mcpServers` object in the `claude_desktop_config.json` file.

.claude_desktop_config.json
[source,json]
include::includes/claude_desktop_config.json[]

This configuration:

1. Gives the server a unique name that you can recognise within the host.
2. Tells Claude Desktop to install the server and run it on your local machine using the `uvx` command.
3. Specifies the package to load from PyPI, and to use Standard Input/Output (stdio) to communicate with the server.
4. Specifies the environment variables that the MCP server will use to connect to your Neo4j database.


[TIP]
.Handling spaces in commands 
=====
Always split out your command and arguments into multiple strings.  For example, the command:

`npx @my-mcps/cool-server --option1 foo --option2 bar` 

should become

`{"command": "npx", "args": ["@my-mcps/cool-server", "--option1", "foo", "--option2", "bar"]}`.
=====

== Transport methods

The configuration above specifies that the server should be run with the transport method of **Standard Input/Output** (stdio), where messages are sent and received through the standard input and output streams of the process.

This is common for locally running MCP servers.

Remote servers are communicated with using HTTP requests.
The messages are either sent through HTTP streaming or HTTP Server Sent Events (SSE).

When you configure a server, you may need to specify the transport method to use.


== Environment Variables

The configuration above also includes an `env` property, which is used to set environment variables for the server.

When the host starts the server, it will set these environment variables as environment variables for the server process.  This is a common way to pass configuration details to the server.

MCP servers that are run remotely, or access remote APIs may require API keys or an access token or take you through an authentication flow before they can be used.


== Running an MCP server

The configuration above uses `uvx` to run the `mcp-neo4j-cypher` server locally.
When the host starts, it will attempt to run the command to start the MCP server and read the list of tools that the server provides.

As the Neo4j Cypher MCP server is written in Python and hosted on PyPI,  the `uvx` command will install the dependencies required to run the server and then run it.





[WARNING]
.Warning
====
Anyone can build and deploy an MCP server, so ensure that you trust the publisher and understand the capabilities of the servers you install.
====




[.summary]
== Lesson Summary

In this lesson you learned how to install and configure the Neo4j Cypher MCP server in VS Code, which allows GitHub Copilot to interact with Neo4j databases.

In the next lesson, you will install the Neo4j Cypher MCP server in VS Code and configure it to connect to your Neo4j database.

