= Installing an MCP server
:order: 2
:type: challenge

// TODO: update 

To install an MCP server to a host, you will need to configure your MCP host with configuration details.
Although the location of the file and configuration details may differ for each host, you will follow the same process. 

You can link:https://claude.ai/download[download the Claude Desktop app from claude.ai^].

For this lesson, we will install the link:https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem[Filesystem MCP server^] and use Claude Desktop as our host.
The Filesystem MCP server is written by the core maintainers of Model Context Protocol, and allows you to: 

* Read/write files
* Create/list/delete directories
* Move files/directories
* Search files
* Get file metadata


[TIP]
.Running an MCP server
====
While the majority of MCP servers are designed to be run locally using `upx` or `npx` commands, many hosts also support running an MCP server through a docker container.
MCP servers that access remote tools may require an access token or take you through an authentication flow before they can be used.

Consult the server's documentation for details on which transport method the server uses and how to install it.
====

== Installing the server

To install the Filesystem server, open the Claude menu on your computer and select **Settings**.
Then from the Developer tab on the left hand side, click **Edit Config**.

This will open up the configuration file for Claude Desktop at: 

* macOS: `~/Library/Application Support/Claude/claude_desktop_config.json`
* Windows: `%APPDATA%\Claude\claude_desktop_config.json`

Inside the configuration file, add the following section:

[source,json]
include::includes/claude_desktop_config.json[]

This configuration: 

1. Adds a new server called `filesystem` server to Claude Desktop
2. Instructs Claude Desktop to use the `npx` command to run the server. 
3. Binds the local directory `~/Desktop` to the `/projects/Desktop` directory on the server.

// == Configuration 

== Using the tools 

Now, when you ask Claude to create a file, the following sequence will occur:


. Claude analyzes the request and determines that a filesystem tool is needed.
. Claude requests permission to use the `write_file` tool.
. Once you have granted permission, Claude invokes the tool with the appropriate parameters.
. The MCP server executes the operation and returns a result.


Most hosts will ask your permission before running a tool, providing the options to run the tool once or always run the tool without asking permission.

This step is so important.  
Anyone can build or deploy an MCP server, so it is crutial that potentially distructive steps are approved by a human.
Make sure you trust the developer of the server and the capabilities of the tool.


[.summary]
== Lesson Summary

In this lesson you learned how to install and configure your first MCP server, installing the Filesystem MCP server included in the MCP SDK examples.  You learned how to configure Claude Desktop and learned about important security considerations - that hosts will request permission before running tools due to potentially destructive capabilities.

In the next lesson, you will learn how to invoke the filesystem tool to create your first file.

