= Challenge: Merge Processing
:order: 8
:usecase: movies
:sandbox: true
:verify: MATCH (m:Movie {title: 'Rocketman'}) WHERE  m.revenue >= 10000  AND m.released = 2019 RETURN true AS outcome

Suppose we do not know if we have the movie _Rocketman_ in our graph.
If it is not in the graph, we want to add it with a released year of _2019_ and an initial revenue property of _1000_.
If it is in the graph, we want to modify the revenue property.

Write the Cypher code to use `MERGE` processing for the _Movie_ node with the _title_ [copy]#Rocketman#:

* If the node already exists:
** set the `revenue` property for the node referenced by n  to  [copy]#n.revenue * 10#
* If the node does not exist:
** set the `released` property to [copy]#2019#
** set the `revenue` property to [copy]#1000#

Execute your statement twice to ensure that the the `MERGE` processing occurs.
That is, the newly created node will have a _revenue_ of 1000, and an updated node will have a revenue >= 10000.

include::questions/verify.adoc[]

[.summary]
== Summary

In this challenge, you demonstrated how to add or update properties when a node is created or found in the graph.
In the next lesson, you will learn how to delete nodes and relationships from the graph.