# Query database
:order: 4
:type: challenge
:branch: new-workshop

[.slide.discrete]
== Overview

In this lesson, you will add a tool to your agent so it can query the database directly.

The tool will use a `TextToCypherRetriever` retriever to convert user queries into Cypher statements and return the results as context.

Text to Cypher tools are useful for "catch all" scenarios where the user may ask a question not covered by other tools, such as:

* Finding specific data in the graph.
* Performing aggregations or calculations.
* Exploring relationships between entities.

[.slide]
== Query database tool

You will modify the `agent.py` code to:

. Create a `Text2CypherRetriever` retriever that uses and `llm` to convert user queries into Cypher.
. Define a new `tool` function that uses this retriever to query the database.
. Add the new tool to the agent's list of available tools.

[.slide-only]
====
**Continue with the lesson to create the text to Cypher retriever.**
====

[.transcript-only]
=== Modify the agent

Open `workshop-genai\agent.py` and make the following changes:

. Instantiate a `llm` that will be used to generate the Cypher.
+
[source,python]
.Cypher generating llm
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_text2cypher.py[tag=import_llm]

include::{repository-raw}/{branch}/workshop-genai/solutions/agent_text2cypher.py[tag=llm]
----
. Create a `Text2CypherRetriever` using the `llm` and Neo4j `driver`.
+
[source,python]
.Text2CypherRetriever
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_text2cypher.py[tag=import_retriever]

include::{repository-raw}/{branch}/workshop-genai/solutions/agent_text2cypher.py[tag=retriever]
----
. Define a tool function to query the database using the retriever.
+
[source,python]
.Query-database tool
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_text2cypher.py[tag=query_database]
----
. Update the `tools` list to include the new database query tool.
+
[source,python]
.tools
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_text2cypher.py[tag=tools]
----
. Modify the `query` variable to test the new database query tool.
+
[source,python]
.query
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_text2cypher.py[tag=query]
----

[%collapsible]
.Reveal the complete code
====
[source, python]
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent_text2cypher.py[tag=**,!example_queries]
----
====

Run the agent. The agent should use the new database query tool to answer the question.

You can see the Cypher query generated in the tool context's metadata.

[.slide]
## Experiment

Experiment with agent, modify the `query` to ask different questions, for example:

* `"Each lesson is part of a module. How many lessons are in each module?"`
* `"Search the graph and return a list of challenges."`
* `"What benefits are associated to the technologies described in the knowledge graph?"`

Asking questions related to the graph schema or lesson content should still use the other tools, for example:

* `"What entities exist in the graph?"`
* `"What are the benefits of using GraphRAG?"`

You may find that the agent will execute multiple tools to answer some questions.

read::Continue[]

[.summary]
== Lesson Summary

In this lesson, you added a query database tool to your agent using a text to Cypher retriever.

Congratulations on completing the Agents module!