= Import your CSV file
:order: 3
:type: challenge
:optional: true
:disable-cache: true

In this optional challenge you will use what you learned during this course to import your own data into Neo4j.

To complete this task you will need to:

. Find a source data CSV file.
+
It could be a file you have created, or one you found online (link:https://www.kaggle.com/datasets[https://www.kaggle.com/datasets^] has open datasets you can use).
. Review the source data.
. Define a graph data model for your data.
+
It should preferably include at least two different node labels and one relationship.
. Use link:https://workspace.neo4j.io/workspace/import[Neo4j Data Importer^] to import the data into your Neo4j Sandbox.
. Review the data in Neo4j.

[%collapsible]
.Sandbox connection details
====
Connection URL:: [copy]#{sandbox-host}:{sandbox-boltPort}#
Username:: [copy]#{sandbox-username}#
Password:: [copy]#{sandbox-password}#
====

When you have completed the challenge, click Move On to continue.

read::Move On[]

[.summary]
== Summary

In this optional challenge, you used what have learned and imported data into Neo4j.

In the next lesson, you will learn how to continue your learning journey.