= GraphAcademy — Entrenamiento en Línea Gratuito, Autoguiado y Práctico
:status: disabled
:lang: es
:link: /es/
:parent: languages
:caption: Estamos aquí para guiarte en un viaje divertido y atractivo para dominar Neo4j con cursos prácticos gratuitos.
:level-overline: Comienza con lo Fundamental
:level-title: ¿Eres principiante o apenas estás empezando? Construye tu fundamento en Neo4j con estos cursos seleccionados.
:certifications-title: Certificaciones Neo4j
:certifications-overline: ¡Prueba tu conocimiento, obtén una certificación Neo4j, comparte tus logros y obtén una camiseta Neo4j de edición limitada gratis!

¡Hola! Bienvenido(a) a GraphAcademy, el portal de aprendizaje gratuito de Neo4j, donde ofrecemos una selección diversa de cursos y materiales, todos diseñados para enriquecer tu conocimiento y habilidades en bases de datos grafos.

Entendiendo la importancia del acceso sin complicaciones al conocimiento, hemos incorporado una funcionalidad de **transcripción automática al español**, con el objetivo de maximizar tu experiencia de aprendizaje con nosotros, independientemente de las barreras lingüísticas.

Hemos introducido un botón de traducción en nuestras páginas de curso, permitiéndote **seleccionar el idioma desde un menú desplegable** para la transformación inmediata del contenido a tu idioma preferido.

En Neo4j, creemos en construir una comunidad fuerte y unida a través del aprendizaje. Te invitamos a explorar GraphAcademy hoy mismo para comenzar a moldear tu futuro - y también el **nuestro** - con el poder transformador de los grafos.


++++
<div id="google_translate_element"></div>
++++

¿Quieres más? Tenemos contenidos desde básicos hasta avanzados para desarrolladores, científicos de datos, entusiastas y mucho más. Mira link:/categories/[TODOS OS CURSOS^] disponibles aquí.
