= Transform Strings to Lists
:type: challenge
:sandbox: true
:updated-at: 2022-05-02 T 13:00:00 Z
:path: main/modules/3-refactoring-imported-data/lessons/4-c-transform-lists

In this Challenge, you will working with the data you previously imported with the Data Importer and did some transformations already.


[IMPORTANT]
You can only perform the steps of this Challenge if you have imported the data in an earlier Challenge and have transformed the strings to dates in the previous Challenge.

This challenge has 2 steps:

. Transform the _Movie_ properties to lists.
. View the types stored in the graph.


== Step 1: Transform the Movie properties to lists

Execute this code in the sandbox on the right to view the multi-value properties of the _Movie_ nodes.

[source,Cypher]
----
include::{repository-raw}/{path}/return-properties.cypher[]
----

Copy this code into the sandbox on the right, modify it to transform the three multi-value properties (_languages_, _countries_, _genres_) of _Movie_ nodes, and execute it:

[source,Cypher,role=noplay]
----
include::{repository-raw}/{path}/set-properties.cypher[]
// add the transformation for the languages and genres properties
----

Your code should have set 279 properties.


== Step 2: View the types stored in the graph

Now that you have transformed properties in the graph to match what we want for numeric and date values in the graph, confirm that their types are correct:

[source,Cypher]
----
include::{repository-raw}/main/shared/apoc-meta-nodetypeproperties.cypher[]
----

include::./questions/verify.adoc[leveloffset=+1]

[.summary]
== Summary

In this challenge, you transformed the multi-value string data to list (StringArray) types to match our target data model.
In the next lesson, you learn how to refactor the graph to add labels.

