= Custom Cypher for Read
:order: 1
:type: lesson

So far, you have used Spring Data's derived find, save, and delete methods against the database. However, there are times when you need something a little different. This is where you can write custom Cypher queries for read operations.

== Defining a custom repository method

Taking a look at the course project's repository interface, there are currently no methods defined because you implemented Spring Data's `findAll()`, `findById()`, `save()`, and `deleteById()` methods that are provided out-of-the-box. These methods are defined to capture most standard use cases for querying and saving data.

However, when you need something else, you can also define your own methods and write Cypher statements that query the data and map the results back to the custom method. For instance, the `findAll()` method works fine to pull the nodes in this movie graph, but what if you had a graph multiple times larger? Even at the current size, it is difficult to view all that data returned on the console. Instead, you could write a custom method to pull a random, smaller subset of the graph each time.

Open the `MovieRepository` interface (`src/main/java/com/example/appspringdata` folder) in your editor and add a new method called `findMoviesSubset()` that returns an `Iterable<Movie>`. Add the `@Query` annotation to the method and provide a Cypher statement that find persons acting in movies and returns only 20 results.

[source,java]
----
include::code/MovieRepository.java[tag=find-movies-subset]
include::code/MovieController.java[tag=find-movies-subset]
----

In the above code, the repository interface contains a new method called `findMoviesSubset()`. It is annotated with `@Query` and provides a Cypher statement that will return a random subset of the graph (up to 20 nodes using the `LIMIT` keyword). Next, the controller's `findAllMovies()` method is modified to use the new custom method instead of `findAll()`.

Full code for the `MovieRepository` and `MovieController` classes is available in the dropdown below.

[%collapsible]
.Click to reveal the completed `MovieRepository` and `MovieController` class code
====
[source,java]
----
include::code/MovieRepositoryComplete.java[]
include::code/MovieControllerComplete.java[]
----
====

[TIP]
.RETURN aggregation
====
In the `RETURN` statement for the query above, each `Movie` node is returned with its `ACTED_IN` relationships and `Person` nodes. This is because the method expects `Movie` nodes, and then aggregates the related entities (relationships and nodes) for each unique movie using Cypher's implicit aggregation for each item listed in the `RETURN` statement.
====

== Testing the findMoviesSubset() custom method

Once you make the modifications above to your project's interface (new custom query) and controller (call `findMoviesSubset()`), test the new method by running the application and calling the `/movies` endpoint. You should see a response with a subset of movies, each with their `ACTED_IN` relationships and `Person` nodes.

//TODO: Figure out how this works in Gitpod!

[source,shell]
----
curl localhost:8080/movies
----

To take this a step further, you can define one more custom method that uses a search parameter. This will be covered in the next lesson.

[.summary]
== Summary

In this lesson, you learned how to write your own custom methods and queries to retrieve data from the database.

Next, you will complete a challenge that builds upon that skill to create custom queries and methods for writing data to the database.