[.question]
= Security in the Aura console

Which one of these is true?

* [ ] In Aura, security is very limited. You manage it in the console and it trickles down to the databases. Totally inadequate for a serious organisation.
* [x] The security of the Aura console only applies to the console. MFA can be used. The main purpose of multiple projects is to make it more granular. The security of the database instances (and thus data access) is unrelated to it.
* [ ] You create an admin instance that manages the security of the Aura console.

[TIP,role=hint]
.Hint
====
Recall what the lesson explained about the relationship between console access and database access. Are they the same thing or separate?
====

[TIP,role=solution]
.Solution
====
**The security of the Aura console only applies to the console. MFA can be used. The main purpose of multiple projects is to make it more granular. The security of the database instances (and thus data access) is unrelated to it.**

Console security and database security are completely separate. Console access allows you to manage database instances, but it doesn't control who can access the data within those databases. This separation is important for proper security architecture.
====