[.question.freetext]
= Shortest Path

Using just the `Actor` and `Movie` nodes and the `ACTED_IN` and `DIRECTED` relationships,  what is the shortest path (by number of relationship hops) between Kevin Bacon and Peta Wilson.

Use the Neo4j Browser window to the right of the screen to run GDS calls and enter the answer in the box below.

input::answer[]

* [x] 6

// Once you have entered the answer, click the **Check Answer** button below to continue.

[TIP,role=hint]
.Hint
====
You can use the same graph projection as the one created in the previous lesson. Make sure the relationships are projected with an `UNDIRECTED` orientation
====

[TIP,role=solution]
.Solution
====
You will need to create a graph projection, that includes the `Person` and `Movie` nodes and the `ACTED_IN` and `DIRECTED` relationships.

[source, cypher]
----
CALL gds.graph.project('proj',
    ['Person','Movie'],
    {
        ACTED_IN:{orientation:'UNDIRECTED'},
        DIRECTED:{orientation:'UNDIRECTED'}
    }
);
----

Then you can use a similar query to the one used in the previous lesson to find the shortest path between Kevin Bacon and Peta Wilson.

[source, cypher]
----
MATCH (a:Actor)
WHERE a.name IN ['Kevin Bacon', 'Peta Wilson']
WITH collect(id(a)) AS nodeIds
CALL gds.shortestPath.dijkstra.stream('proj', {sourceNode:nodeIds[0], TargetNode:nodeIds[1]})
YIELD sourceNode, targetNode, path
RETURN gds.util.asNode(sourceNode).name AS sourceNodeName,
    gds.util.asNode(targetNode).name AS targetNodeName,
    nodes(path) as path;
----

The answer is the number of relationships in the path.
In this case, there are 6 relationships between Kevin Bacon and Peta Wilson.
====
