= Connecting to Neo4j
:type: challenge
:repository-raw: https://raw.githubusercontent.com/neo4j-graphacademy/llm-chatbot-python
:repository-blob: https://github.com/neo4j-graphacademy/llm-chatbot-python/blob

As you learned in the link:/courses/llm-fundamentals/3-intro-to-langchain/2-initialising-the-llm[Initializing the LLM lesson of Neo4j & LLM Fundamentals], Langchain uses the `Neo4jGraph` class to communicate with Neo4j.

You will need to create an instance of the `Neo4jGraph` class that is configured to connect to the link:https://sandbox.neo4j.com/[Neo4j Sandbox^] instance was created for you when you enrolled in the course.

You will need to:

1. Add the Neo4j Credentials to `.streamlit/secrets.toml`
2. Create a new `Neo4jGraph` instance using these credentials


== Adding the Neo4j Credentials

Here are the credentials for your Neo4j Sandbox instance.

[.credentials]
Scheme:: [copy]#{sandbox-scheme}#
Connection URL:: [copy]#{sandbox_host}#
Username:: [copy]#{sandbox_username}#
Password:: [copy]#{sandbox_password}#

Open the `.streamlit/secrets.toml` and paste the following values.

..streamlit/secrets.toml
[source,toml]
----
include::../1-llm/includes//secrets.toml[]

NEO4J_URI = "{sandbox-uri}"
NEO4J_USERNAME = "{sandbox-user}"
NEO4J_PASSWORD = "{sandbox-password}"
----


== Creating a Neo4jGraph Instance

Create a new `graph.py` file, import the `Neo4jGraph` class and create a new instance with the credentials defined in the previous step.

.graph.py
[source,python]
----
include::{repository-raw}/main/solutions/graph.py[]
----

== Using the Neo4jGraph Instance

Once you have completed the steps, you will be able to `import` the graph object into other modules within the project.

[source,python]
----
from graph import graph
----


read::I have a Neo4jGraph[]

[.summary]
== Summary

In this lesson, you added your Neo4j Sandbox credentials to the app and used them to create a `Neo4jGraph` object.

In the next lesson, you will create an Agent that is capable of communicating with the LLM.
