= Connecting to Neo4j
:type: challenge
:order: 2
:lab: {repository-link}/main/.streamlit/streamlit.toml
:branch: lc-0.2
:disable-cache: true

As you learned in the link:/courses/llm-fundamentals/3-intro-to-langchain/2-initialising-the-llm/[Initializing the LLM lesson of Neo4j & LLM Fundamentals^], Langchain uses the `Neo4jGraph` class to communicate with Neo4j.

You will need to create an instance of the `Neo4jGraph` class and connect to the link:https://sandbox.neo4j.com/[Neo4j Sandbox^] instance created for you when you enrolled in the course.

To complete this challenge, you will need to:

1. Add the Neo4j Credentials to `.streamlit/secrets.toml`
2. Create a new `Neo4jGraph` instance using these credentials


== Set the Neo4j Secrets

Here are the credentials for your Neo4j Sandbox instance.

[.credentials]
Scheme:: [copy]#bolt#
Connection URL:: [copy]#{sandbox_ip}#
Username:: [copy]#{sandbox_username}#
Password:: [copy]#{sandbox_password}#


Set these as secrets in the Streamlit app by opening the `.streamlit/secrets.toml` and adding the following values.

..streamlit/secrets.toml
[source,toml,subs="attributes+"]
----
include::../1-llm/includes//secrets.toml[]

NEO4J_URI = "bolt://{sandbox_ip}:{sandbox_boltPort}"
NEO4J_USERNAME = "{sandbox-username}"
NEO4J_PASSWORD = "{sandbox-password}"
----

== Connect to the database

Open the `graph.py` file in the project root, import the `Neo4jGraph` class, and create a new instance with your credentials.

.graph.py
[source,python]
----
include::{repository-raw}/{branch}/solutions/graph.py[tag=graph]
----

== Using the Neo4jGraph Instance

Once you have completed the steps, you can `import` the `graph` and use the Neo4jGraph instance in other modules within the project.

[source,python,role=nocopy]
----
from graph import graph
----

read::I have a Neo4jGraph[]

[.summary]
== Summary

In this lesson, you added your Neo4j Sandbox credentials to the app and used them to create a `Neo4jGraph` object.

In the next lesson, you will create an Agent to communicate with the LLM.
