= Introduction to Neo4j & GraphQL
:categories: developer:2, graphql:1
:description: Learn how to use the Neo4j GraphQL library to build GraphQL APIs backed by the Neo4j graph database.
:status: active
:usecase: recommendations

== About the course

> {description}

This course covers building GraphQL APIs using the https://neo4j.com/docs/graphql-manual/current/[Neo4j GraphQL Library^] and the https://graphql-toolbox.neo4j.io/[Neo4j GraphQL Toolbox.^]

No local setup is required for the course. You will make use of https://graphql-toolbox.neo4j.io/[the Neo4j GraphQL Toolbox^] (a web-based tool for building and querying GraphQL APIs in the browser with the Neo4j GraphQL Library) and https://neo4j.com/sandbox/[Neo4j Sandbox^] (a free hosted Neo4j database that will be provisioned automatically for you by enrolling for this course).

Some familiarity with Neo4j is helpful, such as first completing the https://graphacademy.neo4j.com/courses/neo4j-fundamentals/["Neo4j Fundamentals"^] course, however not strictly required.

The course is divided into four modules:

== Setup And Course Overview

[square]
* Setting up the Neo4j GraphQL Toolbox


== The Neo4j GraphQL Library

[square]
* GraphQL type definitions
* The Neo4j GraphQL's Library's query API


== GraphQL Mutations

[square]
* Creating and updating data with GraphQL mutations

== Custom Logic With Cypher

[square]
* Adding custom logic to our GraphQL API using the `@cypher` GraphQL schema directive


== Advanced GraphQL Concepts

[square]
* GraphQL's abstract types: interfaces and unions
* Relationship properties
* Point and distance filtering
* Datetime (or is this covered previously?)
* Aggregations