
In this course, you have learned:

[square]
* The fundamentals of GraphQL
* How to setup the Neo4j GraphQL Toolbox
* How to create:
** GraphQL type definitions
** GraphQL queries and generated GraphQL operations
** GraphQL mutations to manipulate nodes
** Relationship mutations with nested mutations
** Custom logic with the `@cypher` GraphQL schema directive


== Resources

* *Neo4j GraphQL Toolbox:* +
https://graphql-toolbox.neo4j.io/

* *The official Neo4j GraphQL Library documentation:* +
https://neo4j.com/docs/graphql-manual/current/

* *The Neo4j GraphQL Library on GitHub:* +
https://github.com/neo4j/graphql

* *There are many resources available to you for learning more about GraphQL, Neo4j, Cypher.* +
https://neo4j.com/developer/resources/

* *Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users:* +
https://community.neo4j.com

* *Neo4j documentation:* +
https://neo4j.com/docs/

* *Neo4j Sandboxes for experimenting with graphs:* +
https://sandbox.neo4j.com/?ref=graph-academy

* *Videos on  the Neo4j YouTube channel:* +
https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

* *Neo4j online and classroom training:* +
https://neo4j.com/graphacademy/

* *Become a Neo4j certified developer:* +
https://neo4j.com/graphacademy/neo4j-certification/


* *GitHub repository:* +
https://github.com/neo4j-contrib

* *Neo4j events all over the world:* +
https://neo4j.com/events/world/all/

* *Graph Gists for learning more use cases for Neo4j:* +
https://neo4j.com/graphgists/

* *Attend a Neo4j meetup:* +
https://www.meetup.com/topics/neo4j/

* *View questions/answers raised about Neo4j:* +
https://stackoverflow.com/tags/neo4j/hot


== Course feedback

We want your feedback on this course. Please provide your https://forms.gle/k6nhzMXiYFyUYUNs7[feedback] so we can improve this course.
