[.question.select-in-source]
= 1. Creating a uniqueness constraint

Suppose we have a graph that contains Company nodes. One of the properties of a Company node is taxId.
Every Company in the graph must have a unique taxId.
Before we load the Company data, we want to create a uniqueness constraint for the Company.taxId property.
What is the correct statement to create this constraint?

Once you have selected your option, click the **Check Results** query button to continue.

[source,cypher,role=nocopy noplay]
----
/*select:CREATE CONSTRAINT Company_taxId_uniqueness IF NOT EXISTS FOR (x:Company) REQUIRE x.taxId IS UNIQUE*/
----


* [ ] `CREATE UNIQUENESS CONSTRAINT Company_taxId_uniqueness IF NOT EXISTS FOR (Company.taxId)`
* [ ] `CREATE UNIQUENESS CONSTRAINT Company_taxId_uniqueness IF NOT EXISTS FOR (x:Company) WITH (x.taxId)`
* [x] `CREATE CONSTRAINT Company_taxId_uniqueness IF NOT EXISTS FOR (x:Company) REQUIRE x.taxId IS UNIQUE`
* [ ] `CREATE CONSTRAINT Company_taxId_uniqueness IF NOT EXISTS FOR (x:Company) UNIQUE x.taxId`

[TIP,role=hint]
.Hint
====
You specify the type of constraint at the end of the clause for creating the constraint.
====

[TIP,role=solution]
.Solution
====

The correct code for creating the uniqueness index is:

`CREATE CONSTRAINT Company_taxId_uniqueness IF NOT EXISTS FOR (x:Company) REQUIRE x.taxId IS UNIQUE`
====
