= Course Summary

Congratulations on completing this course!

In this course, you have created a project with Spring Data Neo4j to query the https://sandbox.neo4j.com/?usecase=recommendations[Recommendations dataset^]

In the first module, you learned the building blocks of the Spring Data Neo4j library and how to configure the Spring Data Neo4j library to connect to a Neo4j database and test the connection.

In the second module, you learned about the graph model and application model and how to map one to the other. You also explored the movie domain model used in this course's project.

In the third module, you created the application model by mapping nodes and relationships to Java domain classes. Then you created Spring Data Neo4j repositories and controllers to perform read operations between the application and database.

In the fourth module, you used Spring-provided methods for both creating and deleting data in the database.

In the fifth module, you learned how to use the `@Query` annotation to define custom Cypher queries for reading and writing data. You also learned how to use projections to create custom views of entities.

Finally, in the sixth module, you learned about resources to help you continue your learning journey with Spring Data Neo4j. You also heard some ideas to continue your education by expand this course's project, building a new project with another data set, or integrating other technologies and tools.

== Next Steps

You may be interested learning more about link:/courses/app-java/[Neo4j & Java]. And stay tuned for a new course on building GenAI applications with Spring AI!
