= Neo4j is a Property Graph
:order: 1

// Watch this video to learn how Neo4j implements a property graph model.

[.video]
video::gYLM1ke6sZg[youtube,width=560,height=315]

////
Script: L: Neo4j is a Property Graph

https://docs.google.com/document/d/1ySystUMjZ4Xz40sHYOJTquxHKP6Ow8TRA--nwH_7Mss/edit?usp=sharing


////

[.transcript]
== Module Overview

In this module you will learn how the entities in your application domain represent the nodes in the graph.
The most important part of the graph, however are the relationships between the nodes.
The connectedness of the data makes Neo4j an excellent solution for implementing the use cases of your domain.

// == Using the Sandbox for this course

// Throughout this course, you will be accessing a pre-populated Sandbox in the cloud.

// Here is a brief tour of how to use the Sandbox during this course.

// video::7K-K9aiXEBE[youtube,width=560,height=315]

////

Script: H: Using the Sandbox

https://docs.google.com/document/d/1vtZprI_pnXxEG2a9sgw5PCF6td5f80MIw5PnQEenZrc/edit?usp=sharing

////

