= GDS Product Overview
:type: lesson
:order: 1

In this lesson, you will learn about the Neo4j Graph Analytics product and how you can get Neo4j Graph Data Science.

== Get Started

link:https://neo4j.com/docs/graph-data-science/current/[Graph Data Science (GDS)^] is part of the Neo4j Graph Analytics product.  
It is a library of graph algorithms and machine learning methods that can be used to analyze and learn from graph data.  

GDS is available for use on link:console.neo4j.io[Neo4j's fully managed Aura (AuraDS) cloud^] and self managed Neo4j installations. 
It is also available as a plugin for Neo4j Desktop, which is a free local development environment for Neo4j.

In addition, GDS functionality can be used with the serverless link:https://neo4j.com/docs/graph-data-science/current/installation/aura-graph-analytics-serverless/[Aura Graph Analytics service^].
Aura Graph Analytics is an on-demand service that allows you to run GDS algorithms and machine learning methods on your data without having to have a Neo4j database.

You can learn more about link:https://neo4j.com/docs/graph-data-science/current/installation[GDS installation options^] in the link:https://neo4j.com/docs/graph-data-science/current/[GDS documentation^].

[NOTE]
A Neo4j sandbox database with GDS has been created for you to use in this course.
You will not need to install anything to complete this course.

In this course, you will learn how to use GDS with data stored in a Neo4j graph database.

== Neo4j Editions and Licensing

GDS can be used with Community and Enterprise editions.
Both editions include all analytics functionality, graph algorithms and machine learning methods, although there are differences relating to performance and enterprise capabilities.

Enterprise features include:

* *Increased performance:* unlimited concurrency to speed up compute time and access to a low-memory analytics graph format enabling the application of data science to very large graphs

* *Security and workflow:* fine-grained security, the ability to persist and publish machine learning models, in-memory graph back-up and restore, and causal cluster compatibility via read replica

You can find more information on how to obtain and install an enterprise license https://neo4j.com/docs/graph-data-science/current/installation/installation-enterprise-edition/[in our Enterprise Edition Configuration documentation^].

== Check your understanding

include::questions/1-gds-installation.adoc[leveloffset=+2]


[.summary]
== Summary
In this lesson, you learned the options for getting started with Neo4j Graph Data Science.

In the next lesson you will learn how GDS works at a high-level.
