[.question.freetext]
= Which movie is Emil's favorite?

Click the **Run in Browser** button to open up the integrated query window and run the Cypher statement.

[source,cypher]
----
include::../sandbox.cypher[]
----

Can you modify the `WHERE` clause to find a `Person` node with the `name` property "[copy]#Emil Eifrem#"?

Once you have found the title of the movie, **enter the title** below and click **Check Answer**.

input::answer[]

* [x] The Matrix

[TIP,role=hint]
.Hint
====
The answer is the `title` property of the `(:Movie)` node.

You can search for the name property by either link:https://neo4j.com/docs/cypher-manual/current/clauses/where/#filter-on-patterns[Filtering the name of the _Person_ node within the `MATCH` clause^] or by link:https://neo4j.com/docs/cypher-manual/current/clauses/where/#filter-on-node-property[adding a `WHERE` clause to the query^].
====

[TIP,role=solution]
.Solution
====
You can use the following query to find the title of the Movie that Emil is listed as acted in.

[source,cypher]
----
include::../solution.cypher[]
----

Click the **Run in Sandbox** button to reveal the answer in the Sandbox window.

Enter the `title` property from the result into the text box.
====
