= Build an Neo4j-backed Chatbot using Python
:categories: llms:3
:status: active
:duration: 2 hours
:caption: Build a chatbot using Neo4j, Langchain and Streamlit
:usecase: recommendations
// :video: https://www.youtube.com/embed/vVCHJFa01gA
:key-points: Building a Neo4j-backed Chatbot, Neo4j & Langchain, Neo4j & Streamlit
:repository: neo4j-graphacademy/llm-chatbot-python

== Course Description

In this hands-on course, you will use the knowledge gained in the link:/courses/llm-fundamentals[Neo4j & LLM Fundamentals course^] to create a Movie Recommendation Chatbot backed by a Neo4j database.

You will take a simple chat interface that repeats the user's input, and modify it to answer questions about movies via the Neo4j Recommendations Dataset using _GPT 3.5 Turbo_, complete with conversational history.

The chatbot will be able to answer questions like:

* How many movies has Tom Hanks acted in?
* What is the most popular movie in the database?
* Can you recommend a movie for fans of The Matrix and Casino?

At the end of the course, you will have a working chatbot built with link:https://streamlit.io/[Streamlit^].


=== Prerequisites

This course relies heavily on the information contained in the link:/courses/llm-fundamentals[Neo4j & LLM Fundamentals course^].
If you have not already done so, we recommend completing this course first.

We also assume a basic understanding of Python.
It is not necessary, but you may also benefit from taking the link:/courses/app-python/[Building Neo4j Applications with Python^] course to understand how the Neo4j Python Driver works.

The course uses link:https://streamlit.io/[Streamlit^] to build a simple chat interface.
We do not focus heavily on the Streamlit functionality, so it may be worth reviewing the link:https://docs.streamlit.io/library/get-started[Streamlit Get Started guide^].


=== Duration

{duration}

=== What you will learn

* How to build a Neo4j-backed Chatbot with Langchain and 3.5-Turbo
* Answering user queries with an LLM
* Retrieval Augmented Generation (RAG)
* Langchain Agents and QA Chains
