= Turning data into knowledge 
:order: 8
:type: lesson

During this course, you have learned how you can use Neo4j to turn knowledge into data, the first step in creating a knowledge graph.
Knowledge graphs are a powerful way to represent and query complex interconnected data.

Knowledge graphs are essential to many AI and machine learning applications. 
You can use a knowledge graph to give context and ground an LLM, giving it access to structured data beyond its initial training data.

You can find more information about knowledge graphs including white papers, and free resources at link:https://neo4j.com/use-cases/knowledge-graph[neo4j.com/use-cases/knowledge-graph^].

== Next Steps

You can learn more about how to use Neo4j and LLMs in other GraphAcademy courses:

* link:https://graphacademy.neo4j.com/courses/genai-fundamentals/[Neo4j & Generative AI Fundamentals^]
* link:https://graphacademy.neo4j.com/courses/llm-knowledge-graph-construction/[Building Knowledge Graphs with LLMs^]
* link:https://graphacademy.neo4j.com/courses/genai-integration-langchain/[Using Neo4j with LangChain^]

read::Finished[]

[.summary]
== Lesson Summary

Congratulations on completing this course. I hope you have enjoyed it and learned a lot.
