= Processing Results
:type: quiz

Query results are typically consumed as a stream of records.
The drivers provide a way to iterate through that stream.

== Result

Here is an example query which retrieves a list of `:Person` nodes related to a given Movie.

.Get Actors by Movie title
[source,python,indent=0]
----
include::{repository-raw}/main/example/results.py[tag="get_actors"]
----



The code can be broken down into two elements:

1. The `get_actors()` function defines a _unit of work_ to be executed within a transaction, passed as the first argument of the function, in this case referenced as `tx`
2. The `read_transaction()` method executes the unit of work within a Read Transaction

The result of the `read_transaction()` is a **Result** object.
// This object provides a number of options to iterate through the stream of *records*.

The result object acts as a buffer for an iterable list of records and provides a number of options for accessing those records.
Once a result is _consumed_, it is removed from the buffer.
// provides a number of options to iterate through a stream of records.

=== Peeking at Results

If you wish to preview a result without consuming it, you can use the `peek` method.

.Peek
[source,python,indent=0]
----
include::{repository-raw}/main/example/results.py[tag="peek"]
----

This can be used to preview the first record in the result without removing it from the buffer.

=== Keys

To get the keys for each record in the result, you can call the `keys()` method.

.Get Keys
[source,python,indent=0]
----
include::{repository-raw}/main/example/results.py[tag="keys"]
----


=== Single Result

If you only expect a single record, you can use the `single()` method on the `result` to return the first record.

.First Result
[source,python]
----
include::{repository-raw}/main/example/results.py[tag="single"]
----

If more than one record is available from the result then a warning will be generated, but the first result will still be returned.
If no results are available, then the method call will return `None`.


=== Value

If you wish to extract a single value from the remaining list of results, you can use the `value()` method.

.Extract a value
[source,python]
----
include::{repository-raw}/main/example/results.py[tag="value"]
----

This method two parameters:

1. The key or index of the field to return for each remaining record, and returns a list of single values.
2. Optionally, you can provide a default value to be used if the value is `None` or unavailable.


=== Values

If you need to extract more than item from each record, you can use the `values()` method.
The method expects one parameter per item requested from the `RETURN` statement of the query.

.Extract values
[source,python]
----
include::{repository-raw}/main/example/results.py[tag="values"]
----

In the above example, a `list` will be returned, with each entry containing values representing `name`, `title`, and `roles`.


=== Consume

The `consume()` method will consume the remainder of the results and return a **Result Summary**.

.Result Summary
[source,python]
----
include::{repository-raw}/main/example/results.py[tag="consume"]
----

The Result Summary contains a information about the server, the query, execution times and a `counters` object which provide statistics about the query.

.Query Execution Times
[source,python,indent=0]
----
include::{repository-raw}/main/example/results.py[tag="times"]
----

The `counters` object can be used to retrieve the number of nodes, relationships, properties or labels that were affected during a write transaction.

.Write Statement Counters
[source,python,indent=0]
----
include::{repository-raw}/main/example/results.py[tag="counters"]
----

You can link:https://neo4j.com/docs/api/python-driver/4.4/api.html#neo4j.ResultSummary[read more about the result summary here^].


== Exploring Records

When accessing a record, either within a loop, list comprehension or within a single record, you can use the `[]` bracket syntax.

The following example extracts the `p` value from each `record` in the result buffer.

.For Loop
[source,python,indent=0]
----
include::{repository-raw}/main/example/results.py[tag="for"]
----

You can also access a value using its index, as it relates to the value contained in the keys array:

.Get Available Keys
[source,python,indent=0]
----
include::{repository-raw}/main/example/results.py[tag="keys"]
----


== Check Your Understanding

include::./questions/1-first-method.adoc[leveloffset=+1]

include::./questions/2-consume-method.adoc[leveloffset=+1]

include::./questions/3-get-name.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

You now have all of the information required to send Cypher queries to Neo4j and consume the results.

Next, we will look at the Neo4j Type System and some of the considerations that you need to make when working with values coming from Neo4j in your Python application.
