= Creating a graph
:order: 8
:type: challenge
:branch: main

[.slide.discrete]
== Creating a graph

In the previous task, you used the `Neo4jVector` class to create `Chunk` nodes in the graph.
Using `Neo4jVector` is an efficient and easy way to get started.

To create a graph where you can also understand the relationships within the data, you must incorporate the metadata into the data model.

In this lesson, you will create a graph of the course content.

[.slide.col-2]
== Data Model

[.col]
====
You will create a graph of the course content containing the following nodes, properties, and relationships:

- `Course`, `Module`, and `Lesson` nodes with a `name` property
- A `url` property on `Lesson` nodes will hold the GraphAcademy URL for the lesson
- `Paragraph` nodes will have `id`, `text`, and `embedding` properties
- The `HAS_MODULE`, `HAS_LESSON`, and `CONTAINS` relationships will connect the nodes
====

[.col]
====
image::images/graphacademy-simple-graph.svg[Data model showing Course, Module, Lesson and Paragraph nodes and their relationships]
====

[.slide.discrete]
== Data Model
You can extract the `name` properties and `url` metadata from the directory structure of the lesson files.

For example, the first lesson of the Neo4j & LLM Fundamentals course has the following path:

[source]
----
courses\llm-fundamentals\modules\1-introduction\lessons\1-neo4j-and-genai\lesson.adoc
----

The following metadata is in the path:

- `Course.name` - `llm-fundamentals`
- `Module.name` - `1-introduction`
- `Lesson.name` - `1-neo4j-and-genai`
- `Lesson.url` - `graphacademy.neo4j.com/courses/{Course.name}/{{Module.name}}/{Lesson.name}`

[.slide]
== Building the graph

Open the `1-knowledge-graphs-vectors\build_graph.py` starter code in your code editor.

The starter code loads and chunks the course content.

[.transcript-only]
====
.Load and chunk the content
[source, python]
----
include::{repository-raw}/{branch}/1-knowledge-graphs-vectors/build_graph.py[]
----
====

For each chunk, you will have to:

. Create an embedding of the text.
. Extract the metadata.

[.slide]
== Extracting the data

Create an OpenAI embedding provider instance to generate the embeddings:

.Create embedding_provider
[source, python]
----
include::{repository-raw}/{branch}/1-knowledge-graphs-vectors/solutions/build_graph.py[tag=embedding]
----

[.slide.discrete.col-2]
== Extracting the data
[.col]
====
[start=2]
Create a function to extract the metadata from the chunk:

[source, python]
.Get course data
----
include::{repository-raw}/{branch}/1-knowledge-graphs-vectors/solutions/build_graph.py[tag=get_course_data]
----
====

[.col]
====
The `get_course_data` function:

. Splits the document source path to extract the `course`, `module`, and `lesson` names
. Constructs the `url` using the extracted names
. Creates a unique `id` for the paragraph from the file name and the chunk position
. Extracts the `text` from the chunk
. Creates an `embedding` using the `embedding_provider` instance
. Returns a dictionary containing the extracted data
====

[.slide]
== Creating the graph

To create the graph, you will need to:

. Connect to the Neo4j database
. Iterate through the chunks
. Extract the course data from each chunk
. Create the nodes and relationships in the graph

[.slide.discrete]
== Connect
Connect to the Neo4j sandbox:

[source, python]
----
include::{repository-raw}/{branch}/1-knowledge-graphs-vectors/solutions/build_graph.py[tag=neo4j]
----

[TIP]
.Test the connection
====
You could run your code now to check that you can connect to the OpenAI API and Neo4j sandbox.
====

[.slide.col-2.discrete]
== Create data

[.col]
====
To create the data in the graph, you will need a function that incorporates the course data into a Cypher statement and runs it:

.Create chunk function
[source, python]
----
include::{repository-raw}/{branch}/1-knowledge-graphs-vectors/solutions/build_graph.py[tag=create_chunk]
----
====

[.col]
====
The `create_chunk` function accepts the `data` dictionary created by the `get_course_data` function.

You should be able to identify the following parameters in the Cypher statement:

- `$course`
- `$module`
- `$lesson`
- `$url`
- `$id`
- `$text`
- `$embedding`
====

[.slide.discrete]
== Create chunk
Iterate through the chunks and execute the `create_chunk` function:

[source, python]
----
include::{repository-raw}/{branch}/1-knowledge-graphs-vectors/solutions/build_graph.py[tag=create]
----

The metadata is found for each chunk and used to create a new chunk in the graph.

[.transcript-only]
====
[%collapsible]
.Click to view the complete code
=====
[source]
----
include::{repository-raw}/{branch}/1-knowledge-graphs-vectors/solutions/build_graph.py[tag=**]
----
=====
====

Run the code to create the graph.

[NOTE]
The program will take a minute or two to complete as it creates the embeddings for each paragraph.

[.slide]
== Explore the graph

View the graph by running the following Cypher:

[source, cypher]
----
MATCH (c:Course)-[:HAS_MODULE]->(m:Module)-[:HAS_LESSON]->(l:Lesson)-[:CONTAINS]->(p:Paragraph)
RETURN *
----

[.transcript-only]
====
image::images/course-graph-result.svg[Result from the Cypher, a graph showing Course, Module, Lesson and Chunk nodes and their relationships,width=700,align=center]
====

[.slide.discrete]
== Create vector index
You will need to create a vector index to query the paragraph embeddings.

[source, cypher]
.Create Vector Index
----
CREATE VECTOR INDEX paragraphs IF NOT EXISTS
FOR (p:Paragraph)
ON p.embedding
OPTIONS {indexConfig: {
 `vector.dimensions`: 1536,
 `vector.similarity_function`: 'cosine'
}}
----

[.slide.discrete]
== Query the vector index
You can use the vector index and the graph to find a lesson to help with specific questions:

[source, cypher]
.Find a lesson
----
WITH genai.vector.encode(
    "How does RAG help ground an LLM?",
    "OpenAI",
    { token: $openAiApiKey }) AS userEmbedding
CALL db.index.vector.queryNodes('paragraphs', 6, userEmbedding)
YIELD node, score
MATCH (l:Lesson)-[:CONTAINS]->(node)
RETURN l.name, l.url, score
----

[.next]
== Continue

Explore the graph and see how the relationships between the nodes can bring additional meaning to the unstructured data.

When you are ready, you can move on to the next task.

read::Move on[]

[.summary]
== Summary

You created a graph of the course content using the Neo4j and LangChain.