:type: freetext

[.question.freetext]
= What is the total cost?

The output of the second query should a number representing the total distance of the shortest weighted path from Nashville (BNA) to Phuket (HKT).

Enter the total cost below below and click the **Check Answer** button below to continue.

// In the previous module, you learned that there are 206 shortest unweighted paths from Nashville to Phuket.

// In this challenge, you will use the Dijkstra shortest path algorithm to recommend the shortest weighted path between the two airports based on the flight distance.

// Use the Integrated Sandbox window to execute the `gds.shortestPath.dijkstra.stream()` procedure and find  the shortest weighted route from Nashville (BNA) to Phuket (HKT).

// Make sure you have projected the `routes` graph as indicated in the previous lesson.

// Use the *distance* relationship property as the weight.
// What is the total cost of the shortest weighted path between the two airports?

input::answer[]

* [x] 9387.0

// Once you have entered the answer, click the **Check Answer** button below to continue.

[TIP,role=hint]
.Hint
====
When you run the Dijkstra algorithm, it will return multiple pieces of information. To filter that down to just `totalCost` you can use the `YIELD` clause like so:
----
MATCH (source:Airport {iata: 'BNA'}), (target:Airport {iata: 'HKT'})
CALL gds.shortestPath.dijkstra.stream(
.....
) YIELD totalCost;
----
====


[TIP,role=solution]
.Solution
====
You can run the following Cypher statement to find the total cost of the shortest weighted path between Nashville and Phuket.

The statement returns a single value from the procedure call, `totalCost`, which can be copied and pasted into the form field above.

----
include::../solution.cypher[]
----
====
