[.question]
= 1. Algorithm Purpose

What does node embedding accomplish (select all that apply)?

* [x] Generates low-dimensional vector representations of nodes
* [ ] Embeds the graph into a single numeric vector to measure similarity to other graphs
* [x] Provides numeric vectors that can be used for exploratory data analysis and similarity measurements between nodes
* [x] Provides numeric vectors for each node that can be used as features for machine learning models
* [ ] Generates low-dimensional vector representations, each representing a path between node pairs

[TIP,role=hint]
.Hint
====
Node embeddings will not embed the graph into a single numerical vector or generate a low-dimensional vector representation of the graph.
====

[TIP,role=solution]
.Solution
====
The correct answers are:

**Generates low-dimensional vector representations of nodes** +
**Embeds the graph into a single numeric vector to measure similarity to other graphs** +
**Provides numeric vectors that can be used for exploratory data analysis and similarity measurements between nodes** +
**provides numeric vectors for each node that can be used as features for machine learning models**
====
