= About the Neoflix App
:type: lesson
:order: 1

[.slide]
== The Neoflix App

The Neoflix app is a movie recommendation application that allows users to search for movies and view their details. Users will also be able to rate movies they have seen. 

The application is built using the link:https://javalin.io/[Javalin Java framework] and uses the Neo4j database to store and query movie data. In this module, you will build upon existing starter code to implement some functionality in the application.

[NOTE]
.Failing tests
====
You will notice that some tests fail when you run `mvn verify`. During the course you will complete the project and resolve the issues.
====

[WARNING]
.Errors while installing dependencies?
====
This project has been written using Java version **{java-version}**.
If you are using the wrong version, you may experience errors when trying to install the dependencies.
====

== Start the Project

To start the project, run the following command:

.Start the project using Maven
[source,sh]
mvn compile exec:java

You should see an output similar to the following confirming that the server has successfully started:

.Console Output
[source,console,role=nocopy]
Started server on http://localhost:3000/

== A Brief Tour of the Project

If you open up the listening address in your browser, you will see a Single Page Application (SPA) that communicates with the API served at http://localhost:3000/api/movies[http://localhost:3000/api/movies^].
Currently, the responses are hardcoded, but as you progress through the course, you will learn how to query Neo4j to find this information.

Here are some of the important directories in the project:

* `src/main/java/example/` - Example code for initiating the driver.
* `src/main/java/neoflix` - The application code:
** `src/main/java/neoflix/routes/` - Route handlers that are registered on the server. You will not need to edit these files.
** `src/main/java/neoflix/services/` - Services that you will need to update to interact with Neo4j.
* `src/test/java/neoflix` - Test files that you will need to run in order to check functionality. You will run these using the `mvn test` or individually with the +
`mvn test -Dtest=neoflix._0x_XxxTest#methodName` command.
* `src/main/resources/public/` - Minified build files for the Web application.  *Do not edit these files*.

== Done!

Once you have the project up and running, click the button below to complete this lesson.

read::The project is running![]