[.question,role=multiple_choice]
= 2. Using `MERGE` for relationships

Suppose you want to create the _LIKES_ relationship between a reference to a node _a_, and a reference to a node _b_ where the direction of the relationship is from _a_ to _b_.

Which statements below will create the _LIKES_ relationship from _a_ to _b_?

* [ ] `MERGE (a)-[LIKES]->(b)`
* [x] `MERGE (a)-[:LIKES]->(b)`
* [ ] `MERGE (a)-[LIKES]-(b)`
* [x] `MERGE (a)-[:LIKES]-(b)`

[TIP,role=hint]
.Hint
====
By default, `MERGE` will create the relationship in the left-to-right direction.

A relationship type must begin with ":".
====

[TIP,role=solution]
.Solution
====
`MERGE (a)-[:LIKES]->(b)` is correct where you are explicitly specifying the direction of the relationship between _a_ and _b_.

`MERGE (a)-[:LIKES]-(b)` is also correct since direction of the relationship created between _a_ and _b_, by default, is left to right.

These answers are incorrect, because the ":" must precede the relationship type:

`MERGE (a)-[LIKES]->(b)`

`MERGE (a)-[LIKES]-(b)`
====