= Adding Properties
:order: 2
:type: lesson

In this lesson, you will update the import to add new properties to the `Movie` nodes and cast them to the correct type.

Previously, you used the following Cypher statement to import the `Movie` nodes:

[source,cypher]
----
LOAD CSV WITH HEADERS
FROM 'https://data.neo4j.com/importing-cypher/movies.csv'
AS row
MERGE (m:Movie {movieId: toInteger(row.movieId)})
SET
m.tmdbId = toInteger(row.tmdbId),
m.imdbId = toInteger(row.imdbId),
m.released = row.released,
m.title = row.title,
m.year = row.year,
m.plot = row.plot,
m.budget = row.budget;
----

The `year` and `budget` properties are not cast and therefore stored as strings. 

First, update the existing import to cast the `year` and `budget` properties to integers using the `toInteger()` function.

Next, note that the link:https://data.neo4j.com/importing-cypher/movies.csv[`movies.csv`^] file also contains the following additional properties:

|===
|Property |Data type |Cast function 
|`imdbRating` |Float |`toFloat()`
|`poster` |String | 
|`runtime` |Integer |`toInteger()`
|`imdbVotes` |Integer |`toInteger()`
|`revenue` |Integer |`toInteger()`
|`url` |String |
|===

Finally, update the import to add these properties to the `Movie` nodes and cast them to the correct type.

[.quiz]
== Check Your Understanding

include::questions/verify.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you