= Developing with Neo4j MCP Tools
:usecase: recommendations
:repository: neo4j-graphacademy/genai-mcp-neo4j-tools
:status: draft
:caption: Learn how to use the Model Context Protocol to create intelligent AI applications
:key-points: Model Context Protocol fundamentals, Neo4j MCP server installation, Natural language database interaction, Building GraphRAG applications
:categories: llms:20, intermediate:99
:database-provider: aura
:duration: 2 hours

Model Context Protocol, referred to as MCP, is an open standard designed to connect AI applications with tools and data sources.

It enables AI agents to access and interact with external resources as part of their reasoning step, allowing them to perform more complex tasks and collaborate effectively.

In this course, you will learn:

* How MCP Servers define sets of tools that AI agents can discover and use.
* How MCP Clients establish connections to access and call tools to perform tasks.
* How Neo4j's suite of MCP tools can help aid your development on top of Neo4j.
* How to build your own link:/knowledge-graph-rag/[GraphRAG^] tool to retrieve information from a Neo4j database.

The course features hands-on challenges using GitHub Codespaces, which are free to use for 60 hours a month.

== Prerequisites 

This course assumes that you have are familiar with the basics of Generative AI and Large Language Models.  If you are not, we recommend that you link:/courses/genai-fundamentals/[take the GenAI Fundamentals course^] first.

This course also uses `uv`, a Python package manager, and its `uvx` command to run MCP servers.  If you are not familiar with uv, you should also link:https://docs.astral.sh/uv/[review the uv documentation].



== Duration

{duration}

== What you will learn

* How the MCP protocol works
* How to integrate Neo4j's MCP tools into your IDEs and AI applications
* How to build GraphRAG applications with Neo4j MCP tools


[.includes]
== This course includes

* [lessons]#4 lessons#
* [challenges]#4 short hands-on challenges#
* [quizes]#3 simple quizzes to support your learning#
