= The Domain
:type: quiz
:order: 2

[.video]
video::dZUMBKc9XVM[youtube,width=560,height=315]

[.transcript]
== Understanding the domain for your application

Before you begin the data modeling process you must:

* Identify the stakeholders and  developers of the application.
* With the stakeholders and developers:
** Describe the application in detail.
** Identify the users of the application (people, systems).
** Agree upon the use cases for the application.
** Rank the importance of the use cases.

=== Movie domain

In the course, link:/courses/neo4j-fundamentals/[Neo4j Fundamentals^], you were introduced to a "starter" movie graph.

The domain includes movies, people who acted or directed movies, and users who rated movies.
What makes this domain interesting are the connections or relationships between nodes in the graph.

=== Use cases

Most use cases for an application can be enumerated by a comprehensive list of questions.
The use cases help to define how the application will behave at runtime.

Here are the use cases you will be working with to develop the initial graph data model:

. What people acted in a movie?
. What person directed a movie?
. What movies did a person act in?
. How many users rated a movie?
. Who was the youngest person to act in a movie?
. What role did a person play in a movie?
. What is the highest rated movie in a particular year according to imDB?
. What drama movies did an actor act in?
. What users gave a movie a rating of 5?

In our domain, we want to differentiate a person who acted in or directed a movie and a user or reviewer who rated a movie.
We have much more information about people such as their birth date, their tmdbId etc.
Users who rated movies will just be named or identified.


== Check your understanding

include::questions/1-questions.adoc[leveloffset=+1]


[.summary]
== Summary

In this lesson, you learned that a good starting point for your data modeling is to come up with the use cases for the application.
In the next lesson, you will learn about data models and instance models.