= The Domain
:type: quiz
:order: 2

[.video]
video::xxxx[youtube,width=560,height=315]


[.transcript]
== Understanding the domain for your application

Before you begin the data modeling process you must:


* Describe the application in detail.
* Identify the stakeholders and  developers of the application.
* Identify the users of the application (people, systems).
* Enumerate the use cases that are agreed upon by all stakeholders where users are part of the use case.

[NOTE]
No knowledge of the underlying implementation is required!


=== Domains for this training

To learn some graph data modeling best practices, we will use the a simple social graph domain for our examples.

Then,  you will use the Movie graph to apply the modeling techniques you learn in this course.

==== Social graph

The airport application we will initially model for has airports and flights between them.
An airport has a name and flights go from one airport to another on a given day and time.

== Check your understanding


include::questions/1-xxx.adoc[]

include::questions/2-xxx.adoc[]

include::questions/3-xxx.adoc[]

[.summary]
== Summary

xxx