= The Domain
:type: quiz
:order: 2

[.video]
video::xxxx[youtube,width=560,height=315]


[.transcript]
== Understanding the domain for your application

Before you begin the data modeling process you must:

* Identify the stakeholders and  developers of the application.
* With the stakeholders and developers:
** Describe the application in detail.
** Identify the users of the application (people, systems).
** Agree upon the use cases (questions) for the application.

=== Movie domain

In the course, _Neo4j Fundamentals_, you were introduced to the "starter" movie graph used for GraphAcademy training courses.
The domain that you will practice your graph data modeling skills is the same movie domain as it is understood by most people.

The domain includes movies, people who acted or directed movies, and users who rated movies.
What makes this domain interesting are the connections or relationships between nodes in the graph and how the graph can be used to answer questions about the domain.

=== Use cases

Most use cases for an application can be enumerated by a comprehensive list of questions.
The questions help to define what the application will do at runtime.

Here are the domain questions you will be working with to develop the initial graph data model:

. What people acted in a movie?
. What person directed a movie?
. What movies did a person act in?
. How many users rated a movie?
. Who was the youngest person to act in a movie?
. What role did a person play in a movie?
. What is the highest rated movie in a particular year according to imDB?
. What drama movies did an actor act in?
. What reviewers gave a movie a rating of 5?

In our domain, we want to differentiate a person who acted in or directed a movie and a user who rated a movie.
We have much more information about people such as their birth date, their tmdbId etc.
Users who rated movies will just be named or identified.


== Check your understanding

include::questions/1-questions.adoc[]


[.summary]
== Summary

In this lesson, you learned that a good starting point for your data modeling is to come up with a set of questions for the use cases.
In the next lesson, you will learn about data models and instance models.