= Limiting Agent Scope
:type: challenge
:optional: true
:lab-filename: agent.ts
:lab-file: modules/agent/{lab-filename}
:lab: {repository-blob}/main/src/{lab-file}
:lab-solution: src/solutions/{lab-file}
:test-filename: agent-scoped.test.ts
:test-file: src/modules/agent/{test-filename}

In the previous lesson, you completed the code to create a chain that rephrases a user input into a standalone question and passed it on to an agent which then acts on the question.

However, you may have noticed that the agent will respond to any question, no matter how obscene.


In the previous lesson, you used the `pull()` function to pull a pre-written prompt from LangChain Hub.
You can link:https://smith.langchain.com/hub/hwchase17/openai-functions-agent[view this prompt in LangChain Hub^].

The prompt is fairly basic.
It consists of an array of messages consisting of a role definition, human input and placeholders.


[source]
.The prompt
----
SYSTEM: You are a helpful assistant

PLACEHOLDER: chat_history

HUMAN: {input}

PLACEHOLDER: agent_scratchpad
----

The important inputs that your agent will use are `{input}` and `{agent_scratchpad}`.

As the user input is rephrased prior to the tool selection phase, the `{chat_history}` placeholder can also be omitted.


== Modifying the Prompt

The `createOpenAIFunctionsAgent()` function expects the `prompt` to be an instance of `ChatPromptTemplate`, which also has a `.fromTemplate()` method.

lab::Open `{lab-filename}`[]

You can use this function to provide additional instructions.
For example, refuse to answer questions that don't relate to the movie industry, or respond in pirate talk.

.Modified Prompt
[source]
----
include::{repository-raw}/{branch}/src/{lab-solution}[tag="scoped", indent=0]
----


include::../../../../includes/test.adoc[leveloffset=+1]

== It works!

The link:{repository-blob}/{branch}/{test-file}[unit test^] will verify whether the agent has refused to answer a question that is not related to the movie industry.

Once you tests pass, hit the button below to mark the challenge as complete.

read::It works![]


[.summary]
== Summary

In this challenge, you modified the prompt to limit the scope of the agent.

In the next lesson, you will add the chatbot to the UI.
