= Transaction functions
:type: quiz
:minutes: 10
:order: 7

You have built an application that streams the results of a long-running Cypher statement to the client.

You have written a transaction function called `getActorsFrom` to execute a **read** query within a transaction.

[%collapsible]
.View the `getActorsFrom` function
====
[source,Java]
----
public static List<Record> getActorsFrom(
    TransactionContext tx, 
    String birthDate, 
    String deathDate, 
    String location) {

    var result = tx.run("""
        MATCH (person:Person)-[:ACTED_IN]->(m:Movie),
            (person)-[:FROM]->(city:City)-[:LOCATED_IN]->(country:Country)
        WHERE person.birthDate >= $birthDate AND person.deathDate <= $deathDate
        AND country.name = $location
        RETURN person.name AS actor, person.birthDate AS birthDate,
            person.deathDate AS deathDate,
            city.name AS city, country.name AS country,
            collect(m.title) AS movieList
        """, Map.of("birthDate", birthDate, "deathDate", deathDate, "location", location));

    return result.list();
}
----
====

include::./questions/1-run.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you demonstrated how to execute a read transaction using the `executeRead()` method.
The method handles transaction management automatically and allows for streaming results as they become available.

The `executeRead()` method is the recommended way to run read transactions as it:

* Automatically handles transaction management
* Enables streaming of results as they become available
* Ensures proper transaction lifecycle and resource cleanup

[TIP]
.Consuming results
====
Remember that the results must be consumed within the transaction function. 
Once the transaction is completed, the results are no longer available.
====