= Neo4j & GenAI Fundamentals
// :categories: llms:7, intermediate:5, development:8, generative-ai:1
:status: draft
:duration: 2 hours
:next: llm-knowledge-graph-construction
:caption: Learn how Neo4j and GraphRAG can support your Generative AI projects
:usecase: recommendations
// :video: https://www.youtube.com/embed/vVCHJFa01gA
:key-points: Neo4j and Generative AI, RAG, GraphRag, Integrating Neo4j with Generative AI
:repository: neo4j-graphacademy/genai-fundamentals

== Course Description

In this course, you will learn how Neo4j and Knowledge Graphs can help you make work with Generative AI (GenAI) applications.

You will learn why graph databases are a reliable option for grounding GenAI models, using Neo4j to provide factual, reliable information to stop the LLM from giving false information, also known as *hallucination*.

You will learn about: 

. Embeddings and vector indexes, how they are used in GenAI, and how to use them in Neo4j.
. RAG (Retrieval Augmented Generation) and how GraphRAG builds on it to provide a graph-based approach to providing context to Generative AI models.
. How to use the Neo4j GraphRAG for Python package to interact with AI models and Neo4j.

This course uses models from link:https://openai.com/[OpenAI^], although you can use the model and supplier of your choice.

=== Prerequisites

Before taking this course, you should have:

* A basic understanding of Graph Databases and Neo4j
* Knowledge of Python and capable of reading simple programs

We recommend taking the link:/courses/neo4j-fundamentals/[Neo4j Fundamentals^] course.

To complete the practical tasks within this course, you will need an link:https://platform.openai.com[OpenAI API key^].

=== Duration

{duration}

=== What you will learn

* The fundamentals of Generative AI, Large Language Models (LLMs), and their limitations.
* How providing context improves the accuracy of Generative AI responses.
* About Retrieval Augmented Generation (RAG) and how it combines retrieval and generation for better answers.
* How vectors and embeddings enable semantic search and contextual retrieval in Neo4j.
* Practical skills in building and querying knowledge graphs from both unstructured and structured data.
* How to use the Neo4j GraphRAG for Python package to integrate vector search, graph traversal, and natural language querying for enhanced AI applications.

[.includes]
== This course includes

* [lessons]#15 lessons#
* [challenges]#2 short optional challenges#
* [quizes]#12 simple quizzes to support your learning#