= Building Neo4j Applications with .NET
:categories: developer:2, dotnet, software-development:10, intermediate:10, development:1
:usecase: recommendations
:status: active
:caption: Learn how to interact with Neo4j from .NET using the Neo4j .NET Driver
:key-points: Driver life cycle, installing and instantiation, read and write transactions, best practices
// tag::config[]
:repository: neo4j-graphacademy/app-dotnet
:cypher-repository: neo4j-graphacademy/neoflix-cypher
:dotnet-version: 6.0
// end::config[]

== Course Description

In this course, we walk through the steps to integrate Neo4j into your .NET project.

We will follow the steps to create an instance of the Neo4j .NET Driver, learn about sessions and transactions, and use that knowledge to build a REST API with link:https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-6.0[ASP.NET Core^] that will work with a pre-built Single Page Application (SPA).

The course automatically creates a new `{usecase}` sandbox within link:https://sandbox.neo4j.com/?usecase={usecase}[Neo4j Sandbox] that you will use throughout the course.

=== Prerequisites

By taking this course, we assume that you have a working knowledge of C#, Nuget and the .NET ecosystem.
We also assume that you have at least a basic knowledge of Neo4j.

If you haven't already done so, we recommend that you also take the link:/courses/neo4j-fundamentals[Neo4j Fundamentals] course in order to gain a basic understanding of Neo4j and the link:/courses/cypher-fundamentals[Cypher Fundamentals] to understand how to query Neo4j using Cypher.

=== Duration

8 hours

=== What you will learn

* The lifecycle of the Neo4j Driver and how it relates to your application
* How to install and instantiate the Neo4j .NET Driver into your .NET project
* How read and write transactions work with Neo4j
* Best practices on how to use Neo4j within your .NET project

[.includes]
== This course includes

* [lessons]#8 lessons#
* [challenges]#15 short hands-on challenges#
* [quizes]#20 simple quizzes to support your learning#