= Your Neo4j Sandbox
:disable-cache: true

As part of this course, a Neo4j Sandbox instance has been created for you with the recommendations dataset.
This dataset contains all of the details required to populate the Neoflix website.


== What is Neo4j Sandbox?

Neo4j Sandbox is a free service that allows you to create pre-populated Neo4j instances completely free of charge.
Neo4j Sandbox is the perfect environment for experimenting with Neo4j.

You can log into Neo4j Sandbox and create a database with a number of pre-populated datasets by visiting https://sandbox.neo4j.com[sandbox.neo4j.com^].


ifdef::sandbox_host[]
== Your Sandbox Credentials

[.credentials]
Browser URL:: link:https://{sandbox_host}/browser/[https://{sandbox_host}/browser/^]
Bolt URI:: [copy]#bolt://{sandbox_ip}:{sandbox_boltPort}#
Username:: {sandbox_username}
Password:: [copy]#{sandbox_password}#

You can open a Neo4j Browser window throughout this course by clicking the link:#[Toggle Sandbox,role=classroom-sandbox-toggle] button in the bottom right hand corner of the screen.
endif::[]

[NOTE]
By default, a Neo4j sandbox exists for 3 days. You can extend it for another 7 days by going to the https://sandbox.neo4j.com[sandbox site^] and extending it in the details (right-most down arrow) for the recommendations sandbox.

=== Setting Environment Variables

You should add these properties to your `.env` file so they can be used within the API.

..env File
[source,env,subs="attributes+"]
----
NEO4J_URI=bolt://{sandbox_ip}:{sandbox_boltPort}
NEO4J_USERNAME={sandbox-username}
NEO4J_PASSWORD={sandbox-password}
JWT_SECRET=secret
SALT_ROUNDS=10
----

* `APP_PORT` - defines which port the Go process should run on
* `NEO4J_URI` - defines the connection string, more about that in link:../1-driver/2-connection-strings/[Connection Strings & Authentication]
* `NEO4J_USERNAME` - the username for the Neo4j instance
* `NEO4J_PASSWORD` - the password for the Neo4j instance
* `JWT_SECRET` - the secret phrase used to sign any JWT tokens
* `SALT_ROUNDS` - the cost parameter used when hashing passwords

Once saved, these can be accessed through the `process.env` variable.

.Accessing Environment Variables
[source,js,role=nocopy]
----
const {
  NEO4J_URI,
  NEO4J_USERNAME,
  NEO4J_PASSWORD,
} = process.env
----

[IMPORTANT]
.Applying Environment Variables
Remember to restart the process after saving the `.env` file to apply the environment variables.



== Mark as Completed

Once you have added the environment variables above to your `.env` file, click the button below to continue.

read::I have added my environment variables[]


[.summary]
== Lesson Summary

You now have a project setup and running with dummy data, and you have added your sandbox configuration details to the environment variables.
You should now be ready to go.

In the next module, you will learn about the Neo4j JavaScript Driver.

