










* Some applications will require not just a predetermined chain of calls to LLMs/other tools, but potentially an unknown chain that depends on the user's input.
* In these types of chains, there is a “agent” which has access to a suite of tools.
* Depending on the user input, the agent can then decide which, if any, of these tools to call.



== Tools

* A specific abstraction around a function that makes it easy for a language model to interact with it. Specifically, the interface of a tool has a single text input and a single text output.

* TIPS: Tools can be grouped into toolkits, Groups of tools that solve a particular problem. For example, a toolkit that gets youtube information - videos, thumbnails, transcripts, views, etc


== Agents

* An Agent is a wrapper around a model, which takes in user input and returns a response corresponding to an “action” to take and a corresponding “action input”.
* Agents bring tools together in one place and use the LLM to work out which to instruct
* The benefit of tools is bringing many pieces of functionality to the LLM that it would otherwise not be able to execute

The following code demonstrates registering the YouTubeSearchTool

[source,cypher]
----
from langchain.tools import Tool, YouTubeSearchTool


youtube = YouTubeSearchTool()

tools = [
    Tool.from_function(
        name="YouTubeSearchTool",                       # <1>
        description="For when you need to find videos", # <2>
        func=youtube.run,                               # <3>
        return_direct=True                              # <4>
    )
]
----

1. Create a new tool mapping with a name
2. Description the purpose of the function to help the LLM select the tool
3. Specify the function to run
4. Return the results once the function has been executed



You can then create an agent with the tools registered.


[source,cypher]
----
agent = initialize_agent(
    tools,
    llm=chat_llm,
    memory=memory
    max_iterations=3,
    agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
)
----
