= Creating Movie classes
:order: 1
:type: lesson

The movie data model shows entities for movies, people, and the relationships between them. You will start your application domain with the Movie entity.

== Movie domain class

A Java domain class will represent the Movie entity. While you wouldn't need to map all of the fields on the `Movie` node, you will go ahead and map all of them for this example.

Here are all of the properties (and their data types) on the `Movie` nodes in Neo4j:

[source,text]
----
{
  budget:"INTEGER", 
  movieId:"STRING", 
  tmdbId:"STRING", 
  imdbVotes:"INTEGER", 
  runtime:"INTEGER", 
  countries:"LIST OF STRING", 
  imdbId:"STRING", 
  url:"STRING", 
  plot:"STRING", 
  released:"STRING", 
  languages:"LIST OF STRING", 
  imdbRating:"FLOAT", 
  title:"STRING", 
  poster:"STRING", 
  year:"INTEGER", 
  revenue:"INTEGER"
}
----

Now create the domain class. In the `src/main/java/com/example/appspringdata` directory, create a new file called `Movie.java` (class type) and add properties to map the list of fields above. Review the https://neo4j.com/docs/java-reference/current/extending-neo4j/values-and-types/[data type mappings^] from the documentation (Table 1), as needed. 

Add the `@Node` annotation to mark the class as a node entity, so that Spring knows this class represents a node in the database. Then add the `@Id` annotation on the `movieId` field to mark it as the identifier. Once all the fields are created, create getter and setter methods and a class constructor to allow the app to access them. 

Completed code is available below to cross-check.

[%collapsible]
.Click to reveal completed `Movie` domain class code
====
[source,java]
----
include::code/Movie.java[tag=movie]
----
====

All of these property data types match up, so there shouldn't be any surprises with property mappings.

read::Continue[]

[.summary]
== Summary

In this lesson, you created the Movie domain class.

Next, you will complete a challenge to apply the skills you learned here to create the Person domain class.