= Creating Movie classes
:order: 1
:type: lesson

Our data model shows entities for movies, people, and the relationships between them. Let's start creating our application domain with the Movie entity.

== Movie domain class

We need a Java class to represent the Movie entity. We will use the `@Node` annotation to mark the class as a node entity, so that Spring knows this class represents a node in our database. We will also use the `@Id` annotation to mark the `id` field as the node identifier. While we wouldn't need to map all of the fields on the `Movie` node, we will go ahead and map all of them for this example. Once all the fields are created, we will need getter and setter methods and a class constructor to allow us to access them.

Here are all of the properties (and their data types) on the `Movie` nodes in Neo4j:

[source,text]
----
{
  budget:"INTEGER", 
  movieId:"STRING", 
  tmdbId:"STRING", 
  imdbVotes:"INTEGER", 
  runtime:"INTEGER", 
  countries:"LIST OF STRING", 
  imdbId:"STRING", 
  url:"STRING", 
  plot:"STRING", 
  released:"STRING", 
  languages:"LIST OF STRING", 
  imdbRating:"FLOAT", 
  title:"STRING", 
  poster:"STRING", 
  year:"INTEGER", 
  revenue:"INTEGER"
}
----

Now let's use that to create our domain class. Create a new class file called `Movie.java` in the `src/main/java/com/example/appspringdata` directory and add the fields, as shown below. Review the https://neo4j.com/docs/java-reference/current/extending-neo4j/values-and-types/[data type mappings^] from the documentation (Table 1), if needed.

[source,java]
----
include::code/Movie.java[tag=movie]
----

[TIP]
.Boilerplate code
====
We have set a placeholder for the constructor, getter methods, and setter methods. Those are standard Java practices and many IDEs will generate them for you.
====

There shouldn't be surprises, since all of these property data types match up. This looks pretty good, so let's move on to the `Person` domain class.

[.summary]
== Summary

In this lesson, you created the Movie domain class.

Next, you will complete a challenge to apply the skills you learned here to create the Person domain class.