= How to Model Data
:order: 1
:type: lesson

[.slide]
== Graph Data Modelling

There is no data model within Neo4j until you create data within the database.

Neo4j is schema-optional - you create the data model as you create the data.

[.slide]
== The Golden Rule

The golden rule of graph data modeling is to model your data as a graph of nouns and verbs:

image::images/noun-verb-noun.svg["(Noun)-[:VERB]->(Noun)"]

[.slide.discrete]
== Noun VERB Noun

The nouns become nodes and the verbs become relationships:

image::images/person-purchased-product.svg["(Person)-[:PURCHASED]->(Product)"]

[.slide.discrete]
== Expanding Relationships

You can expand a relationship to include more detail:

image::images/person-placed-order.svg["(Person)-[:PLACED]->(Order)"]

[.slide.discrete]
== Describe the Data

The `(Noun)-[:VERB]->(Noun)` pattern allows you to describe your data in a way that is easy to understand.

image::images/person-placed-order-expanded.svg["(Person)-[:PLACED]->(Order) (Order)-[*]-()", width=65%]

[.slide]
== Properties

Nodes & relationships with the same label or type can have different properties.

image::images/properties.svg["Nodes with the same label but different properties", width=80%]

[.slide]
== Labels

Node labels serve as an anchor point for a query. 

image::images/labels-1.svg["Nodes with Person and Movie labels", width=65%]

[.transcript-only]
====
By specifying a label, you are specifying a subset of one or more nodes with which to start a query.
====

[.slide.discrete]
== Multiple Labels

You can segment your graph by using multiple labels on nodes:

image::images/labels-2.svg["Person nodes also categorized as Actors and Directors", width=65%]

[.transcript-only]
====
Labels allow you to target specific sub-sections of your graph.
====

[.slide]
== Node | Property

Depending on your use case, you may want to deduplicate properties into Nodes:

image::images/node-or-property-1.svg["A Movie node with a language property of 'English|'French'", width=90%]

[.slide.discrete]
== Node | Property

This model offers greater flexibility and improved query performance but at the cost of semantic complexity.

image::images/node-or-property-2.svg["Language as a separate node connected to Movie nodes", width=65%]

[.transcript-only]

[.slide]
== Relationships

Relationships are fast to traverse and efficient.
Specialized relationship allow you to traverse the graph quickly.

image::images/relationships-1.svg["A specialized RATED_5 relationship for movies with a rating of 5"]

[.slide.discrete]
== Relationships

Actors rated by a user:

image::images/relationships-1.svg["A specialized RATED_ACTOR relationship for actors who appeared in a movie rated by a user"]

[.next.discrete]
== Continue

read::Continue[]

[.summary]
== Summary

In this lesson, you explored graph data modeling concepts.
