= Importing CSV files with the Neo4j Data Importer
:type: challenge
:updated-at: 2023-02-07 T 17:00:00 Z
:path: main/modules/2-using-data-importer/lessons/2-c-importing-CSV
:workspace-guide: graphacademy/importing-csv-data
:disable-cache: true
:zip-file: https://cdn.graphacademy.neo4j.com/courses/importing-data/modules/2-using-data-importer/lessons/2-c-importing-CSV/data/movie-data.zip

In this Challenge, you will import the movie data that you have seen in the previous module using a tool called Neo4j Workspace.
Neo4j Workspace is an online tool that combines developer tools into one convenient location.

Workspace may prompt you for connection details.
You can copy the values below and paste them into the connection window.

[.credentials]
Scheme:: [copy]#{sandbox-scheme}#
Connection URL:: [copy]#{sandbox_host}#
Username:: [copy]#{sandbox_username}#
Password:: [copy]#{sandbox_password}#

You can also link:{zip-file}[download the CSV files used in the challenge here^].

workspace::Open the Challenge in Neo4j Workspace[connectUrl="{connect-url}", guide=graphacademy/importCsvData, acceptTerms=true]


// == Step: 12: View the imported data

// In the sandbox pane for this course, execute the following code to confirm that the data was imported.

// Your graph should have 1097 nodes:

// [source,cypher]
// ----
// include::{repository-raw}/main/shared/count-nodes.cypher[]
// ----

// And it should have 4065 relationships:


// [source,cypher]
// ----
// include::{repository-raw}/main/shared/count-relationships.cypher[]
// ----


include::./questions/verify.adoc[leveloffset=+1]

[.summary]
== Summary

In this challenge, you imported a small set of movie data from CSV files using the Neo4j Data Importer.

In the next lesson, you learn that in some cases, you may need to perform some post-import processing.
