= Creating Existence Constraints for Relationship Properties
:type: challenge
:sandbox: true

== Property must exist

In our Movie data model, we want to ensure every RATED relationship has values for the **rated** and **timestamp** properties.
In the previous lesson, you create the existence constraint for the rating property for the RATED relationships in the graph.
Create the existence constraint for the timestamp property of the RATED relationships.

In the sandbox on the right, modify the code to create this existence constraints in the graph:

CREATE CONSTRAINT RATED_rating_exists IF NOT EXISTS FOR ()-[x:RATED]-() REQUIRE x.rating IS NOT NULL

* *`constraint_name`*: [copy]#RATED_rating_exists#
* *`relationship type`*: [copy]#RATED#
* *`property_key`*: [copy]#timestamp#


After you have created the constraint, list all of them:

[source,cypher]
----
SHOW CONSTRAINTS
----

[NOTE]
--
If you create an incorrect constraint with different names or property_key names, do not worry.
You can create new ones, provided the constraint_name or property_key is unique.
Later in this course you will learn how to remove constraints from the graph.

If you reload this page, the graph will be reset to what it should be at the beginning of the Challenge.
--

Try removing the timestamp value for these relationships. It should return an error:

[source,cypher]
----
MATCH (User {userId: "1"})-[x]-()
SET x.timestamp = null
----

include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Summary

In this challenge, you demonstrated that you can create existentence constraints for node properties in the graph.
In the next lesson, you will learn how to create existence constraints for relationship properties.