= Fine-tuning The Cypher Generation
:order: 3
:branch: lc-0.2

With any dataset, there are peculiarities that you need to account for.

Have you tried asking the bot [copy]#Who acted in The Matrix?#
If you ask it, it may respond, telling you that it cannot provide an answer.
This is due to a peculiarity in the data.

== The Problem

If you look at the database, movies with a title starting with _The_ have the _The_ portion moved to the end in the `.title` property.
For example, **The 39 Steps** is stored as **39 Steps, The**. 

// In the previous module, as part of link:../../2-configuration/4-defining-scope/[defining the scope of the chatbot^], we included an instruction not to answer the question if it was not provided in the context.

// If you take a look at the database movies with a title starting with _The_ have the _The_ portion moved to the end in the `.title` property.
// For example, **The 39 Steps** is stored as **39 Steps, The**.

The database also contains embeddings for the movie titles.
The Cypher the LLM generates will sometimes return these embeddings, resulting in a token limit error when the LLM tried to process the returned data.

To fix these or any other data-related discrepancies, you can fine-tune the Cypher generation process by modifying the prompt and instructions used by the LLM when generating the Cypher statement.



// [TIP]
// .Original Prompts
// ====
// You can https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/graph_qa/prompts.py[view the the default prompts used to instruct the LLM^] for inspiration.

// ====

// The template you provide must be a string that includes these two placeholders.


== The Solution

You can pass a `cypher_prompt` when creating Cypher QA chain. 
The prompt must include two placeholders, `\{schema}` and `\{question}`, which will be populated by the chain.

In `tools/cypher.py`, create a cypher generation prompt that addresses these issues:

[source,python]
----
include::{repository-raw}/{branch}/solutions/tools/cypher-finetuned.py[tag=import-prompt-template]

include::{repository-raw}/{branch}/solutions/tools/cypher-finetuned.py[tag=prompt]

include::{repository-raw}/{branch}/solutions/tools/cypher-finetuned.py[tag=template]
----

Add the `cypher_prompt` when creating the `cypher_qa` chain:

[source,python]
.Append the Cypher Prompt argument
----
include::{repository-raw}/{branch}/solutions/tools/cypher-finetuned.py[tag=cypher-qa]
----

== Testing the Prompt

Ask the question [copy]#Who directed The Matrix?#
You should see that the Cypher statement with `, The` appended to the string.

[%collapsible]
.Console output
====

    > Entering new AgentExecutor chain...
    ```json
    {
        "action": "Cypher QA",
        "action_input": "who directed the matrix?"
    }
    ```

    > Entering new GraphCypherQAChain chain...
    Generated Cypher:
    cypher
    MATCH (m:Movie)<-[:DIRECTED]-(d:Director)
    WHERE m.title = "Matrix, The"
    RETURN d.name AS director

    Full Context:
    [{'director': 'Lana Wachowski'}, {'director': ' Lilly Wachowski'}]

    > Finished chain.

    Observation: {'query': 'who directed the matrix?', 'result': 'The Matrix was directed by Lana Wachowski and Lilly Wachowski.'}
    Thought:```json
    {
        "action": "Final Answer",
        "action_input": "The Matrix was directed by Lana Wachowski and Lilly Wachowski."
    }
    ```

    > Finished chain.


    > Entering new AgentExecutor chain...
    ```json
    {
        "action": "Final Answer",
        "action_input": "The Matrix was directed by Lana Wachowski and Lilly Wachowski."
    }
    ```

    > Finished chain.

====

However, the Cypher generated may still generate errors or the wrong results.
You can further improve the responses by using few-shot prompting, which you will learn about in the next lesson.

Once you have completed the steps, click the button below to mark the lesson as completed.

read::It works![]


[.summary]
== Summary

In this lesson, you used fine-tuning to problems with Cypher statement generation.

In the next lesson, you will learn how few-shot prompting can help improve the quality of the Cypher statements generated by the LLM.
