= Creating Nodes
:order: 1

In this lesson you will learn how to write Cypher code to create nodes in the graph.

Using the Movies data model, you will create and execute Cypher code to create Actors and Movies in our graph.

We use the `MERGE` keyword to create a _pattern_ in the database.

After the `MERGE` keyword, we specify the pattern that we want to create.
Usually this will be a single node or a relationship between two nodes.

Suppose we want to create a node to represent _Michael Cain_.
Run this Cypher code to create the node.

[source,cypher, role = noplay]
----
MERGE (p:Person {name: 'Michael Cain'})
----

It creates a single node in the graph.
Note that when you use `MERGE` to create a node, you must specify at least one property that will be the unique primary key for the node.

Verify that the node was created.

[source,cypher, role = noplay]
----
MATCH (p:Person {name: 'Michael Cain'})
RETURN p
----

// browser::MATCH (n) RETURN count(n)[]

== Executing multiple Cypher clauses

We can also chain multiple `MERGE` clauses together within a single Cypher code block.

[source,cypher, role = noplay]
----
MERGE (p:Person {name: 'Katie Holmes'})
MERGE (m:Movie {title: 'The Dark Knight'})
RETURN p, m
----

This code creates two nodes, each with a primary key property.
Because we have specified the variables `p` and `m`, we can use them in the code to return the created nodes.

== Using `CREATE` instead of `MERGE` to create nodes

Cypher has a `CREATE` clause you can use for creating nodes.
The benefit of using `CREATE` is that it does not look up the primary key before adding the node.
You can use `CREATE` if you are sure your data is clean and you want greater speed during import.
We use `MERGE` in this training because it eliminates duplication of nodes.

== Check your understanding

include::questions/1-merge-keyword.adoc[]

include::questions/2-property-label-for-node.adoc[]

[.summary]
== Summary

In this lesson, you learned how to create nodes in the graph.
In the next challenge, you will demonstrate your skill of creating a node.


