= Multiple passes
:order: 2
:type: lesson

Making multiple passes over a single import file to create the data structure.

Note - eager step and the implications of.

Understand the benefits and approach of making multiple passes to import the data.




In the examples you have been exploring, a single file represents a single entity in the graph. For example, `persons.csv` contained `Person` nodes and `movies.csv` contained `Movie` nodes. In this lesson, you will explore a more complex example that requires multiple passes over a single file to create the data structure.






==== Multi-pass import processing

We recommend several passes to process this CSV file:

. Create the Movie nodes and the Genre nodes.
. Create the Person nodes.
. Add the Actor labels and the ACTED_IN relationships.
. Add the Director labels and the DIRECTED relationships.


The advantage of performing the import in multiple passes is that you can check the graph after each import to see if it is getting closer to the data model.
If the CSV file were extremely large, you might want to consider a single pass.



https://stackoverflow.com/questions/59334058/eager-operator-warning-for-importing-csv-file-into-neo4j




[.quiz]
== Check Your Understanding

include::questions/question.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you