= Setting up the Project
:type: text
:order: 1
:go-version: 1.17.7

We have put together a project with all of the boilerplate in place.
As you move through this course, you will learn some theory and then how to apply it to the example project.

In order to run the project, you must make sure that Go is installed.


== Setup Go

We are assuming that in taking this course, you already have at least a basic understanding of Go.

If you haven't already installed Go, you can follow the link:https://go.dev/doc/install[Download and install] instructions on link:https://go.dev[go.dev^].
The project has been written to work with Go version **{go-version}**.

You can verify that the installation is successful by running the following command in the command line:

.Verify Go Version
[source,sh]
go --version


== Clone the Repository

You can obtain a copy of the project source code by cloning link:https://github.com/{repository}[the {repository} repository^] from Github.  Or, if you prefer, you can also link:https://github.com/{repository}/archive/refs/heads/main.zip[download a zip file with the source^].


[.tab]
.HTTPS
====
To clone the repository without logging in via HTTPS, you can run the following command to clone the repository:

.Clone Repository Using HTTPS
[source,shell,subs="attributes+"]
git clone https://github.com/{repository}.git

====

[.tab]
.SSH
====

If you have a GitHub account configured with SSH access, you can run the following command to clone the repository:

.Clone Repository using SSH
[source,shell,subs="attributes+"]
git clone git@github.com:{repository}.git

====

[.tab]
.GitHub CLI
====

If you have the link:https://cli.github.com/[GitHub CLI^] installed, you can run the following command to clone the repository:

.Clone Repository using the GitHub CLI
[source,sh,subs="attributes+"]
gh repo clone {repository}

====

[.tab]
.Download Zip File
====

Click the following link to download the source as a .zip file.

https://github.com/{repository}/archive/refs/heads/main.zip.

====



== Setting Environment Variables

This project will read environment variables from the `config.json` file located in the project root.

In the next lesson you will add your Neo4j Sandbox credentials to this file.



== Start the Project

To start the project, run the following command:



.Start the project
[source,sh]
----
go run ./cmd/neoflix
----


You should see an output similar to the following confirming that the server has successfully started:

.Console Output
[source,sh,role=nocopy]
----
Server listening on http://localhost:3000
----

The REST API will listen for requests on http://localhost:3000.


== A Brief Tour of the Project

If you open up the listening address in your browser, you will see a Single Page Application (SPA) that communicates with the API served at http://localhost:3000/api.
Currently, the responses are hardcoded, but as you progress through the course, you will learn how to query Neo4j to find this information.

Here are some of the important directories in the project:

* `example/` - Example code for working with the driver.
* `pkg/` - The application code:
** `ioutils/` - Utility functions for handling errors and processing JSON
** `routes/` - Route handlers that are registered on the server.  You shouldn't need to edit these files.
** `services/` - Service interfaces which will be modified to communicate with Neo4j
* `public/` - Minified build files for the SPA.  *Do not edit these files*.


== Done!

Once you have the project up and running, click the button below to complete this lesson.

read::The project is running![]


[.summary]
== Next Steps

Now that we have the project up and running, let's take a look at the Neo4j Sandbox instance that has been created as part of your enrollment in this course.
