= Create an Agent
:order: 10
:type: challenge
:optional: true

During this workshop, you have learned about the fundamentals of LLMs, how to interact with them using langchain, and how Neo4j can support the LLM in answering questions.

You can apply this new knowledge and skills to a new problem.

Create a conversational agent using LangChain that can answer questions about a topic you are interested in.

The agent should:

* Use a prompt that sets the scene for the LLM
* Be given additional context that is relevant to the scenario
* Have conversational memory and be able to answer a string of questions
* Be given a few-shot example to support it in answering a specific type of question

I recommend that you approach this challenge in the following order:

. Choose a topic that you are interested in
. Create a prompt and create a chain that uses the prompt
. Create an agent and add conversational memory
. Add additional context to the agent
. Add a few-shot example to the agent

== Continue

When you are ready, you can move on to the next task.

read::Move on[]

[.summary]
== Lesson Summary

You created a conversational agent using LangChain.

In the next lesson, you will learn about ..