= Using Neo4j with Java
:categories: developer:2, Java, software-development:15, intermediate:15,  development:5
:status: active
:caption: Learn how to interact with Neo4j from Java using the Neo4j Java Driver
:next: app-Java
:key-points: Driver life cycle, installing and instantiation, read and write transactions, best practices
// tag::config[]
:slides: true

// end::config[]

== Course Description

In this course, you will learn how to integrate Neo4j into your Java projects.

By the end of this course, you will have gained a solid understanding of how to use Neo4j in a Java application to build a practical and robust API.
You will be able to use your newfound knowledge to create your own Neo4j-backed applications.


=== Prerequisites

By taking this course, we assume that you have a working knowledge of Java and how to build applications.
We also assume that you have at least a basic knowledge of Neo4j.

If you haven't already done so, we recommend that you also take the link:/courses/neo4j-fundamentals/[Neo4j Fundamentals] course in order to gain a basic understanding of Neo4j and the link:/courses/cypher-fundamentals/[Cypher Fundamentals] to understand how to query Neo4j using Cypher.

=== Duration

1 hour

=== What you will learn

* The lifecycle of the Neo4j Driver and how it relates to your application
* How to instantiate the Neo4j Java Driver to your Java project
* How read and write transactions work with Neo4j
* Best practices on how to use Neo4j within your Java project.

[.includes]
== This course includes

* [lessons]#7 lessons#
* [challenges]#8 challenges#
// * [quizes]#20 simple quizzes to support your learning#