= The Complete Graph
:type: lesson
:order: 5

[.slide.discrete.col-2]
== Introduction

[.col]
====
Here is an example complete graph data model for the Northwind dataset.

How does it compare to the graph data model you created in the previous lesson?
====

[.col]
====
[source, mermaid]
.Northwind Graph Model
----
include::diagrams/northwind-graph-model.mermaid[]
----
====

[.slide.discrete]
== It depends!

[NOTE]
.It depends!
====
There is no right or wrong way to complete the challenge.

The model you created is just as valid. A model is partially driven by the questions you want to ask of the data and the insights you want to gain. Your experience is different to others and your model may be different. 

Graph data models in Neo4j can be easily evolve as your use case changes.
====

[.slide]
== Download and import the model

If you want to... 

You can download the complete graph data model, and import it into your instance.

[.transcript-only]
====
:model-filename: northwind-complete.zip
:model-name: Northwind Complete

include::../../shared/download-model.adoc[]
====

[.next]
== Next

read::Continue[]


[.summary]
== Lesson Summary

In this lesson, you learned review an example of a complete Northwind graph data model.

In the next module, you will learn how to work with your graph database using the Aura Explore, Dashboard, and Agent tools.
