= The Neo4j Type System
:type: quiz
:repository-raw: /tmp/app-java

At this point, we look at the Cypher type system.
As Neo4j is written in Java (the _j_ in Neo4**j** stands for Java after all), there are some discrepancies between the types stored in the Neo4j database and native Java types.

Some values like strings, numbers, booleans, dates, and nulls have a direct mapping to Java types but more complex types like nodes, relationship, points, durations need special handling.

//Adam: are the Cypher types here supposed to be the types in the db (according to apoc.meta.nodeTypeProperty??
[%collapsible]
.Java Types to Neo4j/Cypher Types
====
[cols="1,1,1"]
|===
| Java Type | Neo4j Cypher Type | Notes

| `null`,
| `null`
|

| `List`
| `List`,`Array`
| Neo4j can only store a flat array containing strings, booleans or numbers.

| `Map`
| `Map`
|

| `Boolean`
| `Boolean`
|

| `Long`
| `Integer`
|

| `Double`
| `Float`
|

| `String`
| `String`
|

| `byte[]`
| `byte[]`
|

| `LocalDate`
| `LocalDate`
| See <<Temporal Types>>

| `Time`
| `Time`
| See <<Temporal Types>>

| `LocalTime`
| `LocalTime`
| See <<Temporal Types>>

| `DateTime`
| `DateTime`
| See <<Temporal Types>>

| `LocalDateTime`
| `LocalDateTime`
| See <<Temporal Types>>

| `IsoDuration`
| `Duration`
|

| `Point`
| `Point`
|

| `Node`
| `Node`
| See <<Nodes & Relationships>>

| `Relationship`
| `Relationship`
| See <<Nodes & Relationships>>

| `Path`
| `Path`
| See <<Nodes & Relationships>>

|===
====

The `Value` type that is provided by `Record` and also from nested structures, can use `asXxx()` methods to cast underlying values to expected types.
See the https://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/Value.html[API docs for `Value`^].

[source,java,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/src/main/java/example/Results.java[tag=values]
----

Let's take a look at some of these types in more detail.

== Numbers

For numeric values the main confusion comes from the naming, while Neo4j itself can store all kinds of Java primitive values for a unified surface, Cypher only exposes one floating point type called `Float` (equivalent to 64-bit double) and one integer type  called `Integer` (equivalent to 64-bit long).

Cypher itself has functions like `toFloat()` and `toInteger()` respectively and driver parameters of other types are automatically coerced.

The driver's `Value` type can return most Java numeric types via `asXxx()` methods.
Only `BigDecimal/BigInteger` for arbitrary precision math are not supported.

== Temporal Types

The Temporal types used in the Cypher type system mirror the `java.time.*` types, so there are few surprises.
The only difference is `IsoDuration` for which the driver provides a custom type.

.Temporal Types
[cols="1,3,1,1"]
|===
| Type | Description | Example | Access Function

| `Date`
| Represents an instant capturing the date, but not the time, nor the timezone.
| `2020-01-02`
| `asDate`

| `DateTime`
| Represents an instant capturing the date, the time and the timezone identifier.
| `2020-01-02T01:02:03+04:00`
| `asDateTime`


| `LocalDateTime`
| Represents an instant capturing the date and the time, but not the timezone.
| `2020-01-02T01:02:03+04:00`
| `asLocalDateTime`

| `LocalTime`
| Represents an instant capturing the time of day, but not the date, nor the timezone.
| `12:34:56`
| `asLocalTime`

| `OffsetTime`
| Represents an instant capturing the time of day, and the timezone offset in seconds, but not the date.
| `12:34:56+04:00`
| `asOffsetTime`

| `IsoDuration`
| Represents a duration between two dates or timestamps (different resolutions). Has individual accessors for the parts.
| `P1M12D`
| `asIsoDuration`

|===

.Working with Temporal types
[source,java,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/src/main/java/example/Results.java[tag=temporal]
----


== Nodes & Relationships

Nodes and Relationships are both returned as similar types with a common superclass `Entity`.

As an example, let's take the following code snippet:

.Return Nodes and Relationships
[source,java,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/src/main/java/example/Results.java[tag=run]
----

=== Nodes

We can retrieve the `person` value using the `.get()` method on the row and then turn it into a `Node` via `asNode()`.

[source,java,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/src/main/java/example/Results.java[tag=get]
----

The value assigned to the `person` variable will be the instance of a `Node`.
`Node` is a type provided by the Neo4j Java Driver to represent the information held in Neo4j for a node.

An instance of a `Node` has three parts:

.Working with Node Objects
[source,java,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/src/main/java/example/Results.java[tag=node]
----

1. `id` - representing the internal ID for the node.
2. `labels` - an Iterable of String values, eg. `['Person', 'Actor']`
3. `properties` - A Java Map containing all the properties for the node. +
    eg. `{"name": "Tom Hanks", "tmdbId": "31" }`

Properties can also be retrieved from `Entity` instances with the `get(name)` method which then returns a `Value` that has to be converted further.

[TIP]
.Internal IDs
Internal IDs should be treated as opaque values and just sent back to the database as you get them.
These ids can be re-used, a best practice is to always look up a node by its business key and label rather than relying on an internal ID.

=== Relationships

`Relationship` objects are also `Entity` instances, they also include an `id`, a type and properties.


.Working with Relationships
[source,java,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/src/main/java/example/Results.java[tag=rel]
----


1. `identity` - the internal ID for the relationship.
2. `type` - the type of the relationship, eg - `ACTED_IN`
3. `properties` - A Java Map containing all the properties for the relationship. +
    eg. `{"role": "Woody" }`
4. `startNodeId` - representing the internal ID for the node at the start of the relationship
5. `endNodeId` - representing the internal ID for the node at the end of the relationship


=== Paths

If you return a path of nodes and relationships, they will be returned as an instance of a `Path`.

.Working with Path Objects
[source,java,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/src/main/java/example/Results.java[tag=path]
----

1. `start` - the node starting the path
2.  `end` - the node ending the path
3. `length` - A count of the number of _segments_ within the path
4. `segments` - A path is an Iterable of `Path.Segment`
5. `nodes` - An Iterable of Nodes of the Path
6. `relationships` - An Iterable of Relationships of the Path

==== Path Segments

A path is split into segments representing each relationship in the path.
For example, say we have a path of `+(p:Person)-[:ACTED_IN]->(m:Movie)-[:IN_GENRE]->(g:Genre)+`, there would be two segments.

1. `+(p:Person)-[:ACTED_IN]->(m:Movie)+`
2. `+(m:Movie)-[:IN_GENRE]->(g:Genre)+`

.Iterating over Segments
[source,java,role=ncopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/src/main/java/example/Results.java[tag=segments]
----

The `PathSegment` object has three properties:

* `relationship` - A `Relationship` object representing that part of the path.
* `start` - start node for this path segment `*`
* `end` -  end node for this path segment `*`

[TIP]
.`*` Start and End nodes within the Path Segment object
The start and end nodes on the `PathSegment` may differ from the start and end nodes of the relationship itself if the relationship was traversed in reverse direction.


== Converting these values en masse

There may be times when you need to convert many Neo4j types back into native Java types.
For example, when retrieving a set of properties.

For this the `Value` and `Record` type has three functions

* `asObject()` recursively converts a `Value` into the appropriate Java objects
* `asMap()` converts a Value into a Java Map, it can take a callback function to customize conversion of individual keys and values
* `list()` converts a Value into a Java List, it can take a callback function to customize conversion of individual values

The function are recursive, and will handle nested objects and arrays.

== Additional helper functions

`Value` has additional helper functions

* `isTrue` and `isFalse` for boolean values
* `isNull` for null checks
* `isEmpty` for lists and maps


== Check Your Understanding

include::questions/1-node-property.adoc[leveloffset=+1]

include::questions/2-temporal.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

In this lesson you have learned how to handle some of the more complex objects returned by a Cypher query.

As we progress through this module, you will use the knowledge gained so far to read data from, and write data back to the database.
In the next Challenge, you will modify code to read from the database.