= Adding Relationships
:type: challenge
:order: 4
:sandbox: true

Your challenge is to update the GraphQL type definitions from the previous lesson to include the `RATED` relationship between the `User` and `Movie` types.

The `RATED` relationship includes a `rating` property, of type `float`, that holds the user's rating for the movie.

Run this query in the Neo4j Sandbox to explore the `RATED` relationship between the `User` and `Movie` nodes:

[source,cypher]
----
MATCH (u:User)-[r:RATED]->(m:Movie{title: "Matrix, The"}) RETURN u,r,m
----

. Update the type definitions to create a new `Rated` type which specifies `rating` property with an appropriate type.
+
[source,GraphQL]
----
type Rated @relationshipProperties {
  ...
}
----
. Add the `RATED` relationship to the `User` type definition
+
[source,GraphQL]
----
type User @node {
  userId: ID!
  name: String!
  ...
}
----
. Construct a GraphQL query that uses the `RATED` relationship to return all the ratings for the user "Gloria Nelson".

[%collapsible]
.Click here to reveal the new type definitions
====
[source,GraphQL]
----
type Rated @relationshipProperties {
  rating: Float
}

type User @node {
  userId: ID!
  name: String!
  rated: [Movie!]! @relationship(type: "RATED", properties: "Rated", direction: OUT)
}
----
====

[%collapsible]
.Click here to reveal the GraphQL query
====
[source,GraphQL]
----
query MyQuery {
  users(where: {name_EQ: "Gloria Nelson"}) {
    name
    ratedConnection {
      edges {
        properties { 
          rating 
        }
        node {
          title
        }
      }
    }
  }
}
----
====

read::I'm ready![]

[.summary]
== Summary

In this challenge, you created a new relationship between the `User` and `Movie` types and specified a relationship property.

In the next module, you will learn how to create, update, and delete data using GraphQL mutations.