[.question]
= 1. `MERGE` processing

Suppose we have no _Person_ or _Movie_ nodes in our graph. What does this Cypher code do?

[source,cypher,role=nocopy noplay]
----
MERGE (p:Person {name: 'Lucille Ball'})-[:ACTED_IN]->(m:Movie {title: 'Forever, Darling'})
----


* [ ] It creates one relationship and no nodes.
* [ ] It creates two nodes and no relationship.
* [x] It creates two nodes and one relationship.
* [ ] It does not modify the graph.

[TIP,role=hint]
.Hint
====
This code will try to find the _Person_ node for Lucile Ball.
It will also try to find the _Movie_ node for Forever Darling.
The graph has neither of these nodes in it.
It will continue by completing the pattern.
====

[TIP,role=solution]
.Solution
====
This code will try to find the _Person_ node for Lucile Ball.
Since this graph has no _Person_ node for Lucile Ball, it will create it.
It will also try to find the _Movie_ node for Forever Darling.
It will not find it and create the Movie node.
It will then create the relationship between the two newly-created nodes.
====