site:
  title: Self-Grounding Agents with MAF and Neo4j
  url: https://neo4j-partners.github.io/maf-context-providers-lab
  start_page: maf-context-providers-lab::index.adoc

content:
  sources:
  - url: ..
    branches: HEAD
    start_path: site

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    source-highlighter: highlight.js

output:
  dir: ./build/site
  clean: true
