= Adding the Driver
:type: challenge
:branch: 01-connect-to-neo4j
:test-filename: 01_connect_to_neo4j__test

This is your first challenge of this course.
Your challenge here is to modify the code to create a new instance of the Driver that can be used across the application.

As we discussed in the link:../1-about/[About the Driver lesson], it is best practice to create a single instance of the driver in our application per Neo4j cluster or DBMS.

Inside `api/neo4j.py`, you will see an `init_driver()` function.

.api/neo4j.py
[source,python,role=nocopy]
----
include::{repository-raw}/main/api/neo4j.py[tag=driver]

include::{repository-raw}/main/api/neo4j.py[tag=initDriver]
----

This function should use the `uri`, `username` and `password` parameters supplied to create an instance of the Neo4j Python Driver and assign it to the `driver` variable.
The driver instance should then be assigned to the `current_app` variable to ensure that it is available throughout the application.

Below, the `get_driver()` function will provide access to the `driver` variable set in the `init_driver()` above.

.api/neo4j.py
[source,python,role=nocopy]
----
include::{repository-raw}/main/api/neo4j.py[tag=getDriver]
----


== Challenge: Implement the init_driver function.

Your first challenge is to modify the `init_driver()` function in `api/neo4j.py` to create an instance of the driver and assign it to the `driver` variable declared above.
To do this, we will need to:

1. Install the `neo4j` dependency using pip.
2. Import the `GraphDatabase` object from `neo4j` into `neo4j.py`.
3. Create the driver instance with the  `uri`, `username` and `password` parameters passed to the function and use the `verifyConnectivity` function to assert that the credentials are correct.


=== 1. Install the `neo4j` Dependency

First, you will need to install the `neo4j` dependency.
Run the following command in your terminal session:


.Install neo4j
[source,sh]
----
pip install neo4j
----


=== 2. Importing the Dependency

To include the Driver dependency in our module, you will add an `import` command to the top of the file.
Copy and paste the following code at the top of `api/neo4j.py`.

[source,python,subs="attributes+"]
----
include::{repository-raw}/main/example/index.py[tag=import]
----


=== 3. Creating the Driver Instance

Create the driver instance by calling the `GraphDatabase.driver()` function.
The first argument will be the `uri` passed as the first parameter to the function.
The function will also require a named `auth` argument with the tuple: `(username, password)`

Replace the `init_driver` placeholder function with the following code:

// TODO: vvv
.api/neo4j.py
[source,python]
----
include::{repository-raw}/{branch}/api/neo4j.py[tag=driver]

include::{repository-raw}/{branch}/api/neo4j.py[tag=initDriver]
----

The function calls the `verify_connectivity()` function on the driver instance to verify that the connection details are correct before returning the newly created driver instance.

If the connection cannot be made for any reason, an Exception will be thrown.
If this occurs, your application will be unable to communicate with Neo4j.
Manual investigation will be required to diagnose the issue.

If the connection has been successfully verified, the function will return an instance of the driver.


// == Testing Connectivity
include::../../../../includes/test.adoc[]

// To test that the driver has been setup correctly, run the following command in a new terminal session:

// [source,sh]
// npm run test 01

// The test file is located at `test/challenges/01-connecting-to-neo4j.spec.js`.

== Check Your Understanding

// TODO: Verify questio
include::./questions/1-test-number.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

You have implemented the code to create a new driver instance with environment variables read from the `.env` file which verifies that the driver can connect to the DBMS before the server starts.

In the next module we will look at how to use the driver to query the DBMS.
