= Interface-based projections
:order: 2
:type: lesson
:optional: true

Interface-based projections are a great place to start. They are simple to create and commonly used when you want to trim down an entity for user views or retrieval.

Let's take our `Movie` entity as an example. There are sixteen fields on the entity, which is a lot to work with!

[source,java]
----
include::code/Movie.java[]
----

When we were saving new movies back in Module 5, we only sent a few values, making our return results show a lot of `null` values. What if more of our data contained empty values or we wanted to provide a page for users to scroll through all movies, but didn't want to display every field? 

We could write a projection to only include a few key fields. Let's create a projection that only contains the `title`, `released`, and `poster` properties for each movie.

== MovieProjection interface

To create a projection, we need to create an interface that contains the properties we want to include. We will call this interface `MovieProjection`.

[source,java]
----
include::code/MovieProjection.java[]
----

Now let's update our `MovieRepository` and `MovieController` by adding a new method to return a list of `MovieProjection` instead of `Movie`.

[source,java]
----
include::code/MovieRepository.java[]
include::code/MovieController.java[]
----

[TIP]
.Returning a projection from a repository method
====
As mentioned in the https://docs.spring.io/spring-data/neo4j/reference/projections/sdn-projections.html#projections.sdn.full-example[documentation^], the return type of the method (`MovieProjection`) is different from the repository's domain type (`Movie`), and therefore must use properties defined in the domain type. The suffix `By` is needed to make SDN not look for a property called `MovieProjections` in the `Movie` class.
====

Now, when we test the application and call the `/movies/movielist` endpoint, we will only get the three properties we specified in our projection.

[source,shell]
----
curl localhost:8080/movies/movielist
----