:id: _challenge

[.verify]
= Validate Results

Once you have run the MERGE statement twice, click the **Check Database** button and we will check the database for you.


verify::[]

[TIP,role=hint]
.Hint
====
You must use `ON CREATE SET` to set createdAt.
You must use `ON MATCH SET` to set matchedAt.
In addition, you must use `SET` to set updatedAt.
====


[TIP,role=solution]
.Solution
====
The following query uses a `MERGE` clause to find or create a `:Movie` node with the title _Rocketman_.

When initially created, the `createdAt` property will be set but the `matchedAt` property will be null.
If the node already exists, the `createdAt` property will not be set, but a `matchedAt` property will be set.

For both conditions above, the `updatedAt` property will be set to the current date and time.


[source,cypher]
----
include::../solution.cypher[]
----

If you run this query twice, you will see that the `matchedAt` property isn't set the first time as the movie is created, but will be set to the current date and time on the second run.
====