= Relationship Mutations With Nested Mutations
:order: 2
:type: lesson

In the previous lesson, you learned how to create, update, and delete single nodes.

In this lesson, you will connect nodes using relationships.

== Connecting Nodes

Let's return to the example of adding the "Cli-Fi" genre node. This query will use the `movies` relationship in `Genre` and connect any "Jurassic" movie.

[source,GraphQL]
----
mutation MyMutation {
  createGenres(
    input: {
      name: "Cli-Fi"
      movies: { connect: { where: { node: { title_CONTAINS: "Jurassic" } } } }
    }
  ) {
    genres {
      name
      movies {
        title
      }
    }
  }
}
----

Run the query and observe the following in the response:

1. The new genre "Cli-Fi" is created
2. Relationships are created between the new genre and the existing "Jurassic" movies

[source,json]
----
{
  "data": {
    "createGenres": {
      "genres": [
        {
          "name": "Cli-Fi",
          "movies": [
            { "title": "Lost World: Jurassic Park, The" },
            { "title": "Jurassic Park III" },
            { "title": "Jurassic Park" },
            { "title": "Jurassic World" }
          ]
        }
      ]
    }
  }
}
----

There are three key points to identify in this query:

. The `input` object takes the field values for the created `Genre` node
+
[source,GraphQL]
----
    input: {
      name: "Cli-Fi" <1>
    }
----
. The `movies` field is populated using the `connect` argument and the "Jurassic" nodes return by a `where` clause.
+
[source,GraphQL]
----
    input: {
      movies: { connect: { where: { node: { title_CONTAINS: "Jurassic" } } } } <2>
    }
----
. The selection set includes the `movies` relationship field and the `title` field of the connected `Movie` nodes.
+
[source,GraphQL]
----
    genres {
      name
      movies {
        title
      }
    }
----

[.quiz]
== Check Your Understanding

include::questions/question-1.adoc[leveloffset=+1]

[.summary]
== Summary

This lesson covered nested mutation operations with the Neo4j GraphQL Library and the Neo4j GraphQL Toolbox. In the next lesson you will see how to add custom logic to our GraphQL API using Cypher and how to use GraphQL schema directives to configure the GraphQL API generated by the Neo4j GraphQL Library.