= Setting up the Project
:type: text
:order: 1
:python-version: v3.9.9

We have put together a project with all of the boilerplate in place.
As you move through this course, you will learn some theory and then how to apply it to the example project.

In order to run the project, you must make sure that Python is installed.


== Setup Python

We are assuming that in taking this course, you already have at least a basic understanding of Python.

If you haven't already installed Python, you must link:https://wiki.python.org/moin/BeginnersGuide[install Python3 using the instructions on python.org^].
The project has been written to work wth Python version **{python-version}**.

You can verify that the installation is successful by running the following command in the command line:

.Verify Python Version
[source,sh]
python --version

The Python installation comes with **pip**, the link:https://packaging.python.org/en/latest/guides/tool-recommendations/[package installer for Python^].
You can use pip to install packages from the Python Package Index and other indexes.


[TIP]
.Python Version 3
====
The code blocks in this repository use the `python` command which, depending on your configuration, may require you to set up or replace an alias from `python` to the `python3` command.

If you are running multiple version of python you can also replace `python` and `pip` with `python3` and `pip3`.
====


== Clone the Repository

You can obtain a copy of the project source code by cloning link:https://github.com/{repository}[the {repository} repository^] from Github.  Or, if you prefer, you can also link:https://github.com/{repository}/archive/refs/heads/main.zip[download a zip file with the source^].


[.tab]
.HTTPS
====
To clone the repository without logging in via HTTPS, you can run the following command to clone the repository:

.Clone Repository Using HTTPS
[source,shell,subs="attributes+"]
git clone https://github.com/{repository}.git

====

[.tab]
.SSH
====

If you have a GitHub account configured with SSH access, you can run the following command to clone the repository:

.Clone Repository using SSH
[source,shell,subs="attributes+"]
git clone git@github.com:{repository}.git

====

[.tab]
.GitHub CLI
====

If you have the link:https://cli.github.com/[GitHub CLI^] installed, you can run the following command to clone the repository:

.Clone Repository using the GitHub CLI
[source,sh,subs="attributes+"]
gh repo clone {repository}

====

[.tab]
.Download Zip File
====

Click the following link to download the source as a .zip file.

https://github.com/{repository}/archive/refs/heads/main.zip.

====


== Set up a new Environment

To create a virtual environment named sandbox, you can run the following:

[source,sh]
python -m venv sandbox


To activate the virtual enviroment named sandbox, you can run the following:

[source,sh]
source sandbox/bin/activate



== Install Dependencies

Once you have cloned the repository, navigate to the folder in your terminal and run the following command to install the dependencies.


.Install Dependencies using pip
[source,sh]
pip install -r requirements.txt


You can view a full list of dependencies by opening link:{repository-raw}/main/requirements.txt[`requirements.txt`^].


== Setting Environment Variables

This project will read environment variables from the `.env` file located in the project root.

The project contains an example file at `.env.example`.  You can run the following command in your terminal window to copy the example file to `.env`.

[source,sh]
cp .env. example .env


== Start the Project

To start the project, run the following command:


[.tab.macos.linux]
.MacOS
====
.Start the project
[source,sh]
----
export FLASK_APP=api
export FLASK_ENV=development
flask run
----
====

[.tab.windows]
.Windows
====
.Start the project
[source,sh]
----
set FLASK_APP=api
set FLASK_ENV=development
flask run
----
====





You should see an output similar to the following confirming that the server has successfully started:

.Console Output
[source,role=nocopy]
----
* Serving Flask app 'api' (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 566-751-036
----

The REST API will listen for requests on http://localhost:5000.


== A Brief Tour of the Project

If you open up the listening address in your browser, you will see a Single Page Application (SPA) that communicates with the API served at http://localhost:5000/api.
Currently, the responses are hardcoded, but as you progress through the course, you will learn how to query Neo4j to find this information.

Here are some of the important directories in the project:

* `example/` - Example code for working with the driver.
* `api/` - The application code:
** `dao/` - Data Access Objects which will be modified to communicate with Neo4j
** `middleware/` - Some custom middleware functions that are used by Flask throughout the request lifecycle
** `routes/` - Route handlers that are registered on the server.  You shouldn't need to edit these files.
* `public/` - Minified build files for the SPA.  *Do not edit these files*.


== Done!

Once you have the project up and running, click the button below to complete this lesson.

read::The project is running![]


[.summary]
== Next Steps

Now that we have the project up and running, let's take a look at the Neo4j Sandbox instance that has been created as part of your enrollment in this course.
