= Setting up the Project
:type: text
:order: 1
:python-version: v3.10

We have put together a project with all of the boilerplate in place.
As you move through this course, you will learn some theory and then how to apply it to the example project.

In order to run the project, you must make sure that Python is installed.


== Setup Python

We are assuming that in taking this course, you already have at least a basic understanding of Python.

If you haven't already installed Python, you must link:https://wiki.python.org/moin/BeginnersGuide[install Python3 using the instructions on python.org^].
The project has been written to work wth Python version **{python-version}**.

You can verify that the installation is successful by running the following command in the command line:

.Verify Python Version
[source,sh]
python --version

The Python installation comes with **pip**, the link:https://packaging.python.org/en/latest/guides/tool-recommendations/[package installer for Python^].
You can use pip to install packages from the Python Package Index and other indexes.


[TIP]
.Python Version 3
====
The code blocks in this repository use the `python` command which, depending on your configuration, may require you to set up or replace an alias from `python` to the `python3` command.

If you are running multiple version of python you can also replace `python` and `pip` with `python3` and `pip3`.
====


// == Clone the Repository

include::{shared}/lesson/clone-repository.adoc[]


== Set up a new Environment

To create a virtual environment named sandbox, you can run the following:

[source,sh]
python -m venv neoflix


To activate the virtual enviroment named sandbox, you can run the following:

[source,sh]
source neoflix/bin/activate



== Install Dependencies

Once you have cloned the repository, navigate to the folder in your terminal and run the following command to install the dependencies.


.Install Dependencies using pip
[source,sh]
pip install -r requirements.txt


You can view a full list of dependencies by opening link:{repository-raw}/main/requirements.txt[`requirements.txt`^].


== Setting Environment Variables

This project will read environment variables from the `.env` file located in the project root.

The project contains an example file at `.env.example`.  You can run the following command in your terminal window to copy the example file to `.env`.

[source,sh]
cp .env.example .env

Your .env file should have the following settings:

.Example .env File
[source,env]
----
FLASK_APP=api                       # <1>
FLASK_DEBUG=true                    # <2>
FLASK_RUN_PORT=3000                 # <3>
JWT_SECRET=secret                   # <4>
SALT_ROUNDS=10                      # <5>

NEO4J_URI=neo4j://localhost:7687    # <6>
NEO4J_USERNAME=neo4j                # <7>
NEO4J_PASSWORD=password             # <8>
----

1. `FLASK_APP` tells Flask to use the application in the `api/` folder
2. Run Flask in Development Mode
3. Run the server on port `3000`
4. A secret key for signing JWT tokens - This can be a random string of letters and numbers
5. The cost parameter used when hashing passwords
6. The URI for your Neo4j Sandbox instance, we will set this in the next lesson
7. The username for your Neo4j Sandbox instance
8. The password for your Neo4j Sandbox instance



== Start the Project

To start the project, run the following command:


.Start the project
[source,sh]
----
FLASK_APP=api flask run
----


You should see an output similar to the following confirming that the server has successfully started:

.Console Output
[source,role=nocopy]
----
 * Serving Flask app 'api'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:3000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 629-828-990
----

The REST API will listen for requests on http://localhost:3000.


== A Brief Tour of the Project

If you open up the listening address in your browser, you will see a Single Page Application (SPA) that communicates with the API served at http://localhost:3000/api.
Currently, the responses are hardcoded, but as you progress through the course, you will learn how to query Neo4j to find this information.

Here are some of the important directories in the project:

* `example/` - Example code for working with the driver.
* `api/` - The application code:
** `dao/` - Data Access Objects which will be modified to communicate with Neo4j
** `middleware/` - Some custom middleware functions that are used by Flask throughout the request lifecycle
** `routes/` - Route handlers that are registered on the server.  You shouldn't need to edit these files.
* `public/` - Minified build files for the SPA.  *Do not edit these files*.


== Done!

Once you have the project up and running, click the button below to complete this lesson.

read::The project is running![]


[.summary]
== Next Steps

Now that we have the project up and running, let's take a look at the Neo4j Sandbox instance that has been created as part of your enrollment in this course.
