= Instantiating the Driver
:order: 2


== Installing the Driver

The Neo4j JavaScript Driver is available through your preferred package manager.  Simply run the install command below to add the dependency to your `package.json` file.

[.tabs]
[.tab]
====
.NPM
[source,shell]
npm install --save neo4j-driver
====

[.tab]
====
.Yarn
[source,shell]
yarn add --save neo4j-driver
====

== Including the Driver

[.tabs]
====
[.npm]
======
[source]
.NPM
[source,shell]
npm install --save neo4j-driver
======
[.yarn]
======
.Yarn
[source,shell]
yarn add --save neo4j-driver
======
====


.Creating a Driver Instance
[source,js]
----
import neo4j from 'neo4j'

const driver = neo4j.driver('neo4j://localhost:7687', neo4j.auth.basic('neo4j', 'letmein!'))
----


== Instantiating the Driver

Each driver object connects to a single instance of Neo4j using a server address argument, and in most cases an authentication token.

You should create a single instance of the driver per application for each Neo4j instance that you wish to connect to.


.Creating a Driver Instance
[source,js]
----
import neo4j from 'neo4j'

const driver = neo4j.driver('neo4j://localhost:7687', neo4j.auth.basic('neo4j', 'letmein!'))
----

The above example connects to a Neo4j instance running at `localhost` on port `7687`.
The second argument in the function call is to create a _basic_ authentication token (username and password) using the username `neo4j` and the password `letmein!`.


== Building your Connection String

A connection string consists of four elements.

1. The **scheme** used to connect to the Neo4j instance - for example `neo4j` (required)
2. The server address for the Neo4j Service - for example `localhost` (required)
3. The **port number** that the Neo4j service is running on (required if not the default value of `7687`)
4. Additional connection configuration (for example the routing context)

== Choosing your Scheme


  * `neo4j` - Creates an unencrypted connection to Neo4j.  If you are connecting to a local Neo4j instance or have not explicitly turned on encryption then this is most likely the option you are looking for
  * `neo4j+s` - Creates an encrypted connection to Neo4j
