= Creating a Driver instance
:order: 2


== Installing the Driver

Firstly, you will need to install the link:https://neo4j.com/developer/javascript[Neo4j JavaScript Driver^].  The Neo4j JavaScript Driver is one of five officially supported drivers, the others are Java, .NET, Python and Go.

The Neo4j JavaScript Driver is available through the npm registry and can be installed with either `npm` or `yarn`.


[.tab]
.NPM
====
To install using link:https://www.npmjs.com/[NPM^], run the following command.

.NPM
[source,shell]
npm install --save neo4j-driver

The `--save` option will save a reference to the `neo4j-driver` package in your `package.json` file.

====

[.tab]
.Yarn
====

To install using link:https://yarnpkg.com/[Yarn^], run the following command.

.Yarn
[source,shell]
yarn add --save neo4j-driver

The `--save` option will save a reference to the `neo4j-driver` package in your `package.json` file.
====

== Creating a Driver Instance

Each driver instance will connect to one server, or cluster of servers depending on the value provided in the connection string.

The `neo4j-driver` package exports a default `neo4j` object.  This object provides a `driver` method for creating a new driver instance.  The `driver` method takes two arguments:

1. **A connection string** for the Neo4j instance or cluster - for example `neo4j://localhost:7687` or `neo4j+s://_dbhash_.databases.neo4j.io:7687`
2. **An authentication token** - Neo4j supports basic username and password authentication, kerberos tokens or custom authentication.  These can be created through the `neo4j.auth` variable.


Here is an example for how to create a driver instance:

.Creating a Driver Instance
[source,js]
----
import neo4j from 'neo4j'

const driver = neo4j.driver('neo4j://localhost:7687', neo4j.auth.basic('neo4j', 'letmein!'))
----

The above example creates an _unencrypted_ connection to the Neo4j server at `localhost` on the default port number of `7687`.
The driver then attemps to authenticate against the server using a basic authentication with the username `neo4j` and password `letmein!`.


=== Verifying Connectivity

You can verify that the connection details used during driver instantiation are correct by calling the `verifyConnectivity` function.
This function returns a Promise which resolves, or rejects with a `Neo.ClientError.Security.Unauthorized` error if a connection could not be made.

.Verify Connectivity
[source,js]
await driver.verifyConnectivity()
