= Full-text Indexes in Neo4j
:type: quiz
:sandbox: true

//[.video]
//video::Po4k7vXGBIE[youtube,width=560,height=315]

//https://youtu.be/Po4k7vXGBIE

[.transcript]

=== Full-text indexes

Full-text indexes are useful in applications that must parse property values for evaluating whether the property satisfies the criteria.
Full-text indexes rely on Apache Lucene for their implementation which makes their parsing capabilities very powerful.

For example, you may want to find all Movies that have certain phrases in their plots.
Performing this type of retrieval using b-tree or TEXT indexes could be very  expensive, especially if the `WHERE` clause must logically specify criteria of two or more parts of a string.
Using a b-tree or TEXT index, the index is only used for the first criteria specified in the `WHERE` clause.
If you use a full-text index, you can use a regular expression to express how the values will be matched.
In addition, a full-text index can be defined for multiple labels and/or properties or for multiple relationship types and/or properties.

Unlike b-tree and TEXT indexes, you must call a procedure to use a full-text index at runtime.
That is, the query planner will not automatically use a full-text index unless you specify it in your Cypher code.

== Check your understanding

include::questions/1-select-answer.adoc[leveloffset=+1]
include::questions/2-select-answer.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you learned what a full-text index is in Neo4j.
In the next lesson, you will learn how to create a full-text index.
