[.question.freetext]
= Largest Number of Actors

Write and execute a query to return the list of actors for a movie with a given title.
Order  and limit the results so that the movie  title with the largest number of actors is returned.

**Hin**t: There are multiple movies with the same title so you are aggregating by the movie title and not the movieID.

What movie title had the largest number of actors? (Enter a case-sensitive string for the movie title.)

input::answer[]

* [x] Hamlet

[TIP,role=hint]
.Hint
====
Your `MATCH` clause will simply retrieve all actors who acted in a movie.

You will return the movie title, the list of actors for that movie title, the size of the list.
Order the results by the size in descending order with a limit of 1

Use `collect()` to create the list of actors for all movies with a given title.

You should see that there are multiple movies with the same title so the aggregation will be for all movies with that title.

What movie title had the largest number of actors? (The answer is case-sensitive)

Once you have entered the answer, click the **Try Again** button below to continue.
====

[TIP,role=solution]
.Solution
====

You can run the following query to find the answer:

[source,cypher]
----
include::../solution.cypher[]
----

What movie title had the largest number of actors? (The answer is case-sensitive)

Once you have entered the answer, click the **Try Again** button below to continue.
====
