[.question.freetext]
= Largest Cast

Write and execute a query to return the list of actors for each movie.
Order  and limit the results so that the movie with the largest cast is returned.

What movie had the largest list of actors? (Enter a case-sensitive string for the movie title.)

input::answer[]

* [x] Hamlet

[TIP,role=hint]
.Hint
====
Your `MATCH` clause will simply retrieve all actors who acted in a movie

You will return the movie title, the list of actors for the movie, the size of the list.
Order the results by the size in descending order with a limit of 1

Use `collect()` to create the list of actors.

What movie had the largest list of actors? (The answer is case-sensitive)

Once you have entered the answer, click the **Try Again** button below to continue.
====

[TIP,role=solution]
.Solution
====

This is the query to answer the question:

[source,cypher]
----
include::../solution.cypher[]
----

What movie had the largest list of actors? (The answer is case-sensitive)

Once you have entered the answer, click the **Try Again** button below to continue.
====

