[.question]
= 3. Memory Configuration

If you want to increase memory allocation to handle the creation of larger graph projections in GDS, which configuration(s) would you increase?

* [ ] The graph projection is stored off-heap in transaction state, so you would increase `dbms.tx_state.off_heap.max_cacheable_block_size`
* [ ] The graph projection is stored off-heap in the database cache, so you would increase `dbms.memory.pagecache.size`
* [ ] The graph projection is stored on-heap, so you would increase `dbms.memory.heap.size`
* [x] The graph projection is stored on-heap, so you would increase `dbms.memory.heap.initial_size` and/or `dbms.memory.heap.max_size`

[TIP,role=hint]
.Hint
====
The graph projection is stored on-heap, the initial and maximum size of which can be configured to handle larger graph projections.
====

[TIP,role=solution]
.Solution
====
The graph projection is stored on-heap, so you would increase `dbms.memory.heap.initial_size` and/or `dbms.memory.heap.max_size`.

You can link:https://neo4j.com/docs/graph-data-science/current/common-usage/memory-estimation/[read more about memory estimation here].
====
