= Connection Strings and Authentication
:type: lesson
:order: 2

In the previous lesson, you saw some example code for creating a new driver instance.
Let's take a closer look at the `driver()` method and how it is used to create a driver instance.

.Creating a Driver Instance
[source,java,indent=0,subs="attributes+"]
----
include::{repository-raw}/main/src/main/java/example/Index.java[tag=pseudo]
----

The `GraphDatabase.driver()` function accepts the following arguments:

1. A connection string
2. An authentication token
3. Optionally, an object containing additional driver configuration

Let's take a look at these arguments in more detail.


// == 1. Connection String
include::{shared}/courses/apps/connection-strings.adoc[tags="connectionstring"]


== `2` An Authentication Token

In most cases, you will connect to the DBMS using basic authentication consisting of a username and password.
You can create a basic authentication token by calling the `basic()` method on the `AuthTokens` object.

.Creating a Basic Authentication Token
[source,java,role=nocopy,subs="attributes+",indent=0]
----
include::{repository-raw}/main/src/main/java/example/Index.java[tag=auth]
----

// Neo4j also supports kerberos authentication tokens and can be extended to support custom authentication.
// These authentication methods require additional configuration and are outside of the scope of this course.

For more information on additional authentication methods, see the link:https://neo4j.com/docs/operations-manual/current/authentication-authorization/[Authentication and authorization^] section of the link:https://neo4j.com/docs/operations-manual/current/[Neo4j Operations Manual^].


== `3` Additional Driver Configuration (Optional)

The `driver()` method also accepts a third additional configuration object.
This object allows you to provide advanced configuration options, for example setting the connection pool size or changing timeout limits.

.Example Additional Configuration
[source,java,role=nocopy,indent=0]
----
include::{repository-raw}/main/src/main/java/example/Index.java[tag=configuration]
----

For more information or a full list of configuration options, please link:https://neo4j.com/docs/java-manual/current/client-applications/#java-driver-configuration[visit the Neo4j Java Driver manual^].


// == What happens next?
include::{shared}/courses/apps/connection-strings.adoc[tag="next"]


== Check Your Understanding

// To do: need to add some hints for these

include::./questions/1-valid-schemes.adoc[leveloffset=+2]

include::./questions/2-aura-scheme.adoc[leveloffset=+2]


// == Summary
include::{shared}/courses/apps/connection-strings.adoc[tag="summary"]