[.question]
= 1. ?

// TBD
Suppose your graph data model includes _Customer_ nodes and _Order_ nodes where there is a _SUBMITTED_ relationship between a _Customer_ node and an _Order_ node.
The _SUBMITTED_ relationship has the _date_, _vendorNum_, and _total_ properties.
The customer can only submit one order per day for a given vendor (identified by vendorNum).

What type of constraint would be best for this use case and important query in our application?

[source,cypher,rel="norun nocopy"]
----
// What orders where submitted to vendor $vnum today?
MATCH (c:Customer)-[r:SUBMITTED]->(o:Order)
WHERE r.date = date() AND r.vendorNum = $vnum
RETURN c.name, r.total, r.vendorNum, o.orderNum
----

* [ ] existence on the relationship property date
* [ ] uniqueness on the relationship property date
* [x] Node key on date and vendorNum
* [ ] Node key on name and orderNum

[TIP,role=hint]
.Hint
====
A node key constraint provides existence and uniqueness for multiple property values.

A node key is an index for fast lookups.
====

[TIP,role=solution]
.Solution
====
A node key provides a uniqueness lookup for the date and vendorNum values in the query.
====