= Creating Movie nodes
:order: 1
:type: lesson

We have seen how to read nodes and relationships from the database. Now let's look at how to write them to the database. We will start by using the `save()` method to create a new node in Neo4j.

== Save() method

If you remember from an earlier lesson, Spring Data has some derived methods that are provided out-of-the-box. One of those is the `save()` method for saving data to a database. We can use this method to create new nodes in Neo4j.

We have most of the pieces already in place, so we will just need to add the method in the `MovieController` class. Open the `MovieController.java` file in the `src/main/java/com/example/appspringdata` directory and add the following code:

[source,java]
----
@RestController
@RequestMapping("/movies")
public class MovieController {
    //previous code and methods

    @PostMapping("/save")
    Movie save(@RequestBody Movie movie) {
        return movieRepo.save(movie);
    }
}
----

This method is annotated with `@PostMapping` and will handle requests to the `/movies/save` endpoint. It calls the `save()` method on the repository and returns the results.

All that is left is to test it out.

== Testing the save() method

We will need to pass values for the new movie object we want to create. While the `Movie` domain class contains several fields, most are not required, so we can pick and choose what to send. For this example, we will send the `movieId` and `title` fields, which we have outlined in the `movie.json` file in the `src/main/resources` directory.

[source,json]
----
include::{repository-raw}/src/main/resources/movie.json[]
----

We can test the `save()` method on the command line. Open a terminal window and run something like the following command:

[source,shell]
----
curl localhost:8080/movies/save \
  -H 'Content-Type: application/json; charset=utf-8' \
  -d @src/main/resources/movie.json
----

You should see something like the following output:

[source,shell]
----
{"movieId":"9876","title":"MyMovie","plot":null,"poster":null,"url":null,"imdbId":null,"tmdbId":null,"released":null,"year":null,"runtime":null,"budget":null,"revenue":null,"imdbVotes":null,"imdbRating":null,"languages":null,"countries":null,"actors":null}
----

You can also navigate to Neo4j Browser at `{sandbox_host}.neo4jsandbox.com/browser/` and run the following query to see the new node:

[source,cypher]
----
MATCH (m:Movie {movieId: "9876"})
RETURN *
----

You can feel free to play around with including different fields and values in the `movie.json` file.

[.summary]
== Summary

In this lesson, you learned how to create a `Movie` node in Neo4j using the `save()` method.

In the next lesson, you will build upon that skill to create a pattern (node with relationships).