= Initializing Data
:type: quiz
:sandbox: true

//[.video]
//video::ImKvXY72SA0[youtube,width=560,height=315]

[.transcript]
== Initializing data for a query

If you have a basic `MATCH` clause such as:

[source,cypher]
----
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
WHERE p.name = 'Tom Hanks'
RETURN m.title AS Movies
----

You can initialize the data to be used in the query with a `WITH` clause:

[source,cypher]
----
WITH 'Tom Hanks' AS actorName
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
WHERE p.name = actorName
RETURN m.title AS Movies
----

Before the `MATCH` clause, we define a variable, actorName to have a value of Tom Hanks.
The variable, actorName is in the scope of the query so it can be used like a parameter.
The query itself can be reused with a different value for actorName.

[NOTE]
You will learn about using parameters in Cypher later in this course.

=== Using `WITH` to scope variables


== Check your understanding

include::questions/1-complete-query.adoc[leveloffset=+1]
include::questions/2-select-answer.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, how to graph traversal works and that how it can impact query performance.
In the next challenge, you will answer some questions about a graph traversal.
