= Listing Ratings
:type: challenge
:optional: true
:test-filename: _13_ListingRatingsTest
:branch: 13-listing-ratings

The last remaining element on the Movie page is the list of ratings on the right-hand side of the page.
Although the count in the header is now accurate, the ratings list being by the API needs to be implemented.

The list of ratings is populated by the `forMovie()` method in the link:{repository-blob}/main/src/main/java/neoflix/services/RatingService.java[`RatingService`^], which currently returns a hardcoded list of ratings from the fixture `ratings.json`.

.neoflix/services/RatingService.java
[source,java,indent=0]
----
include::{repository-raw}/main/src/main/java/neoflix/services/RatingService.java[tag=forMovie]
----

In this challenge, you will run the following Cypher statement in a **read transaction**:

.Get Ratings
[source,cypher]
----
include::{cypher-repository-raw}/main/cypher/3-backlog/5-listing-ratings/listing-ratings.cypher[]
----


== Your Task

* Modify the `forMovie()` method to retrieve the ratings from Neo4j.
* Remember to auto-close the session and use the `toMap()` function to convert the result record into native Java types.


[%collapsible]
.Click to reveal the completed `forMovie()` method
====

.neoflix/services/RatingService.java
[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/main/java/neoflix/services/RatingService.java[tag=forMovie]
----

====


// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-first-rating.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you modified the `forMovie()` method on the `RatingService` to return a paginated list of reviews for a movie from the Neo4j database.

In the next Challenge, you will update the `PersonService` to return list of actors and directors from Neo4j.
