= Graph Management
:type: quiz

// [.video]
// video::xxxx[youtube,width=560,height=315]


[.transcript]
== Introduction

In this module we will discuss Machine Learning in GDS.  How it is designed and the tools and methodologies available for use.  To start things we will go over some of the basics around motivation and design patterns in this lesson.

== Why GDS Has Machine Learning Capabilities?

To start, it may be helpful to discuss why GDS has machine learning capabilities in the first place.  It always has, and remains to be true, that you can generate graph features in Neo4j and export then into another environment to do machine learning, such as Python, Spark, VertexAI, Sagemaker, etc. These external platform will, by design, have a lot of flexibility to custom and tune machine learning models.  However, there are still multiple reasons why you may want to use graph based machine learning tools in GDS:


. *Managing Complex Model Design:*  Graphs by nature of being highly connecting introduce potential complications into machine learning workflows that can be tough to catch and work through for those less familiar with graph. Gone un accounted for, these complications can compromise the validaty and performance of the machine workflow. GDS pipelines include methodology to avoid data leakage in feature engineering and data splitting stages that would ordinarily be complex to develop and maintain in a general purpose, non-graph speepcific, ML pipeline
    .. *Data Splitting Design:* Due to the high-interconnectivity of graph structures it isn’t always intuitive to know how to split your data correctly. GDS pipelines handles data splitting for you automatically
    .. *Data leakage:* Related to the issue of data splitting, data leakage is the unintentional use of information during model training that would not ordinally be available at prediction time - it causes model performance to be overestimated.  Due to the high inter-connectivity of graph data structures, it is easy to accidentally include information in the feature engineering process that would not ordinarily be available for the model, particularly for link prediction problems. This leads to data leakage and, at times, extreme overestimation of performance. GDS pipelines include methodology to avoid data leakage in feature engineering and data splitting stages that would ordinarily be complex to develop and maintain in in a general purpose, non-graph speepcific, ML pipeline
    .. *Handling Class Imbalance:* While it is not true for all graph ML problems, a large number tend to have high class imbalance.  Fraud and anomaly detection are common examples at the entity/node prediction level. Moreover, and perhaps even trickier, Entity resolution and knowledge graph completion, where the goal is to predict links between pairs of nodes tend to have very extreme class imbalance just do to the combinatorial nature of the problem.  THis type of severe class imbalance calls for thoughtful data sampling and model evaluation techniques which GDS pipelines provide for you automatically.
    .. *Performance:* Related to the issue of severe class imbalance, particularly for link prediction problems, the size of the complete negative sample space can be exceeding large.  THus an intelligence approach must be taken to subsampling the negative sample space for training, evaluation, and prediction phases.  GDS includes native tooling for this.
. *Managed Graph Native Pipeline:* A big advantage to tGDS native ML is the managed Pipeline and model+pipeline catelog.  This includes tooling for saving, tracking, publishing and sharting ML models across teams.  TIn the pipeline, feature engineering, data splitting and training steps are coupled together,  Once a model is trained in a pipeline, it can be used to make predictions directly into the database
Strong Coupling to Database: Having the model saved with database makes it easy to incorporate ML predictions and inferences directly into a hardened production database.
Development: Even for seasoned practitioners at enterprises with a mature MLOps pipeline, the native ML pirpelines remove alot of initial friction often associated with graph machine learning, allowing you to  experimenting testing model approaches and get off the ground quickly.


== Check your understanding

[.summary]
== Summary

In this lesson you learned about the graph catalog and basic mechanisms for managing graph projections. In the upcoming lessons we will go into more depth with different projection types and how and when to use them.