[.question.freetext]
= Average Reviews per User

Write a query to returns the average number of reviews of movies per user.

What is average number of reviews for all users? (enter an integer number)

Once you executed, enter the value below and click **Check Answer**.

input::answer[]

* [x] 149

[TIP,role=hint]
.Hint
====

Your query should start with:

----
MATCH (u:User)-[r:RATED]-(m:Movie)
WITH u, count(r) AS NumReviews
WITH collect(NumReviews) AS ReviewCounts
----

Then add code to `UNWIND` the list and return the average.

Use toInteger() to return the average as an integer.

What is average number of reviews for all users? (enter an integer number)

Once you have entered the answer, click the **Try Again** button below to continue.

====

[TIP,role=solution]
.Solution
====

This is the query to answer the question:

[source,cypher]
----
include::../solution.cypher[]
----

What is average number of reviews for all users? (enter an integer number)

Once you have entered the answer, click the **Try Again** button below to continue.
====


