[.question]
= Graph Model Design

In the Northwind graph model, how is the employee management hierarchy represented?

- [ ] A `Manager` label on some Employee nodes
- [ ] A separate `Manager` node type
- [x] A `REPORTS_TO` relationship from Employee to Employee
- [ ] A `managerId` property on Employee nodes


[TIP,role=hint]
.Hint
====
The employees table has a reports_to column that references another row in the same table; in the graph this is modeled as a REPORTS_TO relationship from Employee to Employee.
====

[TIP,role=solution]
.Solution
====
The employee management hierarchy is represented as a **self-referencing `REPORTS_TO` relationship** from Employee to Employee.

This pattern:
- `(Employee)-[:REPORTS_TO]->(Employee)`

Allows you to traverse the entire management chain with queries like:

[source,cypher]
----
MATCH path = (e:Employee)-[:REPORTS_TO*]->(manager:Employee)
WHERE e.firstName = 'Nancy'
RETURN path
----

This eliminates the need to store a `managerId` property and perform table joins.
====
