= Neo4j Management, Optimization, and Refactoring Workshop : Facilitators Guide

link:https://graphacademy.neo4j.com/courses/workshop-optimization[graphacademy.neo4j.com/courses/workshop-optimization]

== Introduction

The Neo4j Management, Optimization, and Refactoring Workshop is structured to provide learners with opportunities to experiment with more complex Cypher and investigate how you can improve your Cypher queries and graph structure.

The workshop starts by creating an Aura instance (or setting up the provisioned sandbox as a managed instance), exploring the management features of Aura, and using Import to create the Northwind data model.

Participants will learn about the Cypher runtime and how queries are executed before moving onto using PROFILE to review execution plans of some typical causes behind poorly performing queries.

The workshop concludes with exploring refactoring and typical approaches for refactoring a graph database.

The majority of learning benefit comes from the challenges and exploration of examples and learners should be given plenty of time to explore and create their own solutions.

== Prerequisites

Learners should have a good understanding of Neo4j, writing Cypher queries, and graph data modelling.

== Learning objectives

* Neo4j Aura database management.
* Monitoring database instances.
* Performance metrics.
* Cypher query profiling and optimization.
* Graph refactoring strategies.

== Preparation

What you should know:

* link:https://graphacademy.neo4j.com/courses/genai-fundamentals/[Neo4j Fundamentals]
* link:https://graphacademy.neo4j.com/courses/cypher-fundamentals/[Cypher Fundamentals]
* link:https://graphacademy.neo4j.com/courses/cypher-intermediate-queries[Intermediate Cypher Queries]
* link:https://graphacademy.neo4j.com/courses/cypher-aggregation[Cypher Aggregation]
* link:https://graphacademy.neo4j.com/courses/cypher-indexes-constraints[Cypher Indexes and Constraints]
* link:https://graphacademy.neo4j.com/courses/aura-fundamentals[Aura Fundamentals]
* link:https://graphacademy.neo4j.com/courses/aura-administration[Aura in Production]

What you will need:

* A link:https://graphacademy.neo4j.com[GraphAcademy] account
* An link:https://console.neo4j.io[Aura] account
* A blank Aura instance
* Recommended: Create a new Aura project for the workshop to keep it separate from any other work you may have in Aura

What you will need to do:

. Complete the workshop before delivering it
. Review the outline plan (below) for additional context / approach
. Create a personalized copy of the link:https://docs.google.com/presentation/d/13yEKVBIlK3q-Ka2NoDlRvpTD3CUXkZLTVD0ckMo3jJk/edit?slide=id.g3b9011bb0be_0_0#slide=id.g3b9011bb0be_0_0[introduction slides]
. Delete your previous enrollment to the workshop (so you see the same view as the participants)
. Tidy up your Aura project (delete any unnecessary instances, graph models, dashboards, agents, etc) so you can use it for the workshop and demonstrate the features without confusion
. Be ready to create an Aura instance (either a free or a professional)
. Run the workshop!

== Outline plan

(All timings are estimates and adaptable)

=== Introduction

(10 mins)

*Introduce yourself, the session, and have participants login*

Use the introduction slides to introduce yourself and the agenda

Introduce GraphAcademy and ask learners to create an account and goto the workshop URL in the notes document.

Starter activity

* Has anyone created a Neo4j instance in Aura before? What did you do with it?
* What do people think the key challenges are to writing performant queries for graphs?

Show learners the GraphAcademy course summary, summarise the learning objectives and enrol in the course.

=== Setup Neo4j Aura

(20 - 30 mins)

*Create a Neo4j Aura instance and import the Northwind dataset*

Demonstrate how to sign in and create an instance in Aura. If this is the first time someone has signed into Aura, they will likely be met with the onboarding process, which they should complete to be able to continue. The onboarding process may ask them to create an instance.

Participants can complete the workshop using a free instance or a professional instance (including a free trial). Where possible learners should be encouraged to use a professional instance as they will be able to view the professional features such as logs which are covered in the course content.

If a participant cannot create an instance (e.g. they already have a free instance they dont want to lose / are not eligible for a free trial), there are instructions to add the sandbox created by GraphAcademy as a “self managed” instance. This will allow them to continue with the course.

The Aura instance may take a few minutes to start up, you can continue with the Aura overview lesson content while this is happening.

Finally, learners will download the Northwind graph data model and use Import to load the data into their instance.

=== Aura Administration

(30 - 45 mins)

*Review the Aura administration tools and services*

Describe the structure of the Aura console (Organizations, Projects, Instances) and the available tools.

Allow participants time to investigate the console themselves, particularly taking and exporting snapshots and reviewing query logs.

Take time to describe the complex subjects such as Memory Usage and Data Store Size.

Ask participants to talk about their experience in administering databases and show how you would achieve the same using the Aura console.

=== Query Performance

(45 - 60 mins)

*Learn how to create performant Cypher queries*

Learners will explore the Cypher query lifecyle and how they can use EXPLAIN and PROFILE to understand and analyze a query.

Spend time expanding on the examples in the Good Practice - Query Optimization Checklist - an introduction to these issues will help the learners connect with the following lessons where they will explore specific scenarios.

Learners will explore how they can improve the performance of queries. Its important they have time to complete the challenges. The main aim of this section is to allow them to become familiar with interpreting the results from PROFILE and taking action. The examples are only a sample of issues they may face so allow them to build confidence so when they come across issues for real they have the tools to investigate.

The last lesson is an open challenge where they are given a query to investigate and find a solution for.

Solutions are provided for all the challenges, learners should only look at the solution after they have at least attempted the challenge.

=== Graph Refactoring

(45 - 60 mins)

*Refactor the graph data model*

Describe the need to graph refactoring and how it should be approached.

Learners will review common approaches to graph refactoring and complete challenges to refactor the Northwind data set. They should be given time and encouraged to complete the activities. 

The course concludes with an activity to identify an opportunity to area in the graph to refactor and write the Cypher to change the data model.

Ask participants at the end of the course to share the refactoring opportunity they identified and how they approached it.

=== Close

Return to the introduction slides, remind learners they will have access to the workshop content indefinitely.

Run a Q&A session.

Suggest GraphAcademy courses for learners to continue their learning.
