# LangChain Agent
:order: 2
:type: challenge
:branch: new-workshop

You will be updating a LangChain agent, adding a set of tools, to interact with Neo4j.

## Agent

Open `workshop-genai/agent.py`.

[source, python]
.agent.py
----
include::{repository-raw}/{branch}/workshop-genai/agent.py[]
----

Review the code and try to answer the following questions:

. What is the agent's function?
. What do you think the response to the `query` will be?
. How could you extend the agent?

Run the agent to see what it does.

## Review

This program is a LangChain agent that uses a Neo4j database.
The agent has access to a single tool which retrieves the database schema.
The agent uses this tool to answer questions about the database structure.

The code:

. Creates an `OpenAI` LLM `model`.
+ 
[source, python]
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent.py[tag=model]
----
. Connects to your Neo4j database.
+
[source, python]
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent.py[tag=driver]
----
. Defines a `Get-graph-database-schema` tool.
+
[source, python]
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent.py[tag=tools]
----
+
The tool uses the Neo4j driver to get the database schema and return it as a string.
+
[NOTE]
.Determine what tool to use
====
The agent will use the tool's name (`Get-graph-database-schema`), and docstring (`Get the schema of the graph database.`) to determine whether it should execute the tool to resolve a user's query.
====
. Creates a react (Reasoning and Acting) agent using the `model` and `tools`.
+
[source, python]
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent.py[tag=agent]
----
. Runs the agent, passing the `query` and streams the response.
+
[source, python]
----
include::{repository-raw}/{branch}/workshop-genai/solutions/agent.py[tag=run]
----
+
When you run the agent, you will see:

** The messages between `Human`, `AI`, and `Tool`
** The context of the database schema
** The agent's final response

## Experiment

Experiment with agent, modify the `query` to ask different questions, for example:

* `"What questions can I answer using this graph database?"`
* `"How are concepts related to other entities?"`
* `"How does the graph model relate technologies to benefits?"`

read::Continue[]

[.summary]
== Lesson Summary

In this lesson, you reviewed an agent which can answer questions about a Neo4j database schema.

In the next lesson, you will add a vector + cypher tool to the agent to enable semantic search capabilities.
