= The Neoflix Project
:overline: Introducing our Client
:byline: Our courses all work towards the goal of building a website for a fictional client called Neoflix.

The majority of our courses are centred around a fictional company called **Neoflix**, a ficticious movie streaming website.
If you complete all of the courses on GraphAcademy, we aim for you to have a fully functional website providing movie recommendations based on the link:https://github.com/neo4j-graph-examples/recommendations[Recommendations Graph Example dataset^].

When you enroll to a course, a new instance of the Recommendations dataset will be created in link:https://sandbox.neo4j.com[Neo4j Sandbox], which you will then work with throughout.


== Data Engineers

As a link:/categories/cypher/[Data Engineer], you will be tasked with writing the Cypher code required to serve real-time recommendations to users of Neoflix.
The courses in the link:/categories/cypher/[Cypher category] provide all of the knowledge needed to write and optimise advanced cypher queries.


== Backend Developers

Taking on the role of Developer, you will take the queries written in the link:/categories/cypher/[Cypher category] and use them to link:/categories/developr/[build an API] in the language of your choice.

The API will connect to the sandbox, and serve as a basis for a Single Page Application (SPA) built with React.
As you build the API, it will unlock more features in app and provide you with codes to copy in order to complete each lesson.

At the end of the course, you will have a fully working recommendation engine!

== Data Scientists

link:/categories/data-scientist/[Data Scientists] will use the link:https://neo4j.com/product/graph-data-science-library/[Graph Data Science (GDS)^] library to analyse the graph and use the data generated by GDS to improve the recommendations.

