= Authenticating a User
:type: challenge
:branch: 05-authentication
:test-filename: 05_authentication__test
:lab-filename: api/dao/auth.py
:lab: {repository-blob}/main/src/{lab-filename}
:optional: true

At stage of the project,  a user can register, but they are still unable to sign in.
As with the previous Challenge, the `authenticate()` method is currently hard coded to accept only the email `graphacademy@neo4j.com` and password `letmein`.

In this challenge you will rewrite the `authenticate()` function of the link:{repository-blob}/main/api/dao/auth.py[`AuthDAO`^] to find the User node with the corresponding email and compare the password before issuing a JWT token.

But first, let's take a look at how Authentication works in the application.
If you prefer, you can skip straight to <<Implementing Authentication>>.

== How Authentication Works

When a user attempts to access an API endpoint that requires authentication, the server checks for a JWT token.

When a user registers or signs in, a JWT token is generated and appended to the User record.
This token is then stored by the UI and appended to `Bearer` to create an `authorization` header.

The token generation happens in the link:{repository-blob}/main/api/dao/auth.py[`AuthDAO`^] using the `_generate_token()` method.

When The API receives a request which includes the `authorization` header, the link:https://pythonhosted.org/Flask-JWT/[Flask-JWT] library attempts to decode the value and makes the payload available by importing `current_user` from `flask_jwt`.


=== Login Route

When a user submits the login form on the website, a request is sent to `http://localhost:3000/api/login` with a username and password.


== Implementing Authentication

To implement database authentication, you will modify the `authenticate` method in the `AuthDAO`.

.api/dao/auth.py
[source,python,indent=0]
----
include::{repository-raw}/main/api/dao/auth.py[tag=authenticate]
----

Your challenge is to update the `authenticate()` method to perform the following actions:

1. <<Create a transaction function to find the User>>
2. <<Execute the function within a Read Transaction>>
3. <<Verify the User exists>>
4. <<Compare Passwords>>
5. <<Return User Details>>

lab::Open `{lab-filename}`[]

=== Create a transaction function to find the User

The Transaction function should be a simple query that uses Cypher to look up a `:User` node by the `email` parameter provided and return a single result.


.Get User by Email
[source,python,indent=0]
----
include::{repository-raw}/{branch}/api/dao/auth.py[tag=get_user]
----


=== Execute the function within a Read Transaction

After opening up a new session, call the `execute_read` method to execute the `get_user` function above.

.Call the Transaction Function
[source,python,indent=0]
----
include::{repository-raw}/{branch}/api/dao/auth.py[tag=call_get_user]
----

=== Verify the User exists

If the user does not exist, then `get_user` will return `None`.
In this case, return `False`.

[source,python,indent=0]
----
include::{repository-raw}/{branch}/api/dao/auth.py[tag=user_not_found]
----

=== Compare Passwords

The `authenticate()` method uses the `hashpw` function imported from `bcrypt` to encrypt the password.
The library also provides a `checkpw` function for comparing a plain text value against the previously encrypted value.

If the check fails, return `False`.

[source,python,indent=0]
----
include::{repository-raw}/{branch}/api/dao/auth.py[tag=compare_passwords]
----

=== Return User Details

Finally, if the user exists and the password comparison returns true, generate a JWT token and return it along with information about the User.


[source,python,indent=0]
----
include::{repository-raw}/{branch}/api/dao/auth.py[tag=auth_jwt]
----


Once you have applied these changes to the `authenticate()` method, scroll to <<Testing>> to verify that the method works as expected.


== Working Solution

[%collapsible]
.Click here to reveal the completed `authenticate()` method:
====

.api/dao/auth.py
[source,python,indent=0]
----
include::{repository-raw}/{branch}/api/dao/auth.py[tag="authenticate"]
----

====

include::../../../../includes/test.adoc[]


include::./questions/verify.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

In this Challenge, you have updated the `AuthDAO` to authenticate a User using the data held in the Sandbox database.

In the next Challenge, you will save user ratings to the database.
