apiVersion: batch/v1
kind: CronJob
metadata:
  name: fail-stale-certifications
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fail-stale-certifications
            image: 715633473519.dkr.ecr.us-east-1.amazonaws.com/graphacademy
            imagePullPolicy: IfNotPresent
            command:
            - npm
            - run
            - cmd:failed-certifications
            env:

            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: BASE_URL
            - name: NEO4J_HOST
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: NEO4J_HOST
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: NEO4J_PASSWORD
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: NEO4J_USERNAME
