= Working with Lists
:type: quiz
:sandbox: true

//[.video]
//video::ImKvXY72SA0[youtube,width=560,height=315]

[.transcript]
== Aggregation in Cypher

In this lesson you will learn how aggregation works in a Cypher query and how to work with properties that contain multiple values.

When you aggregate in a Cypher query, this means that the query must process all patterns in the `MATCH` clause to complete the aggregation to either return results or perform the next part of the query.

Here is an example:

[source,cypher]
----
MATCH (a:Person)-[:ACTED_IN]->(m:Movie)<-[:DIRECTED]-(d:Person)
RETURN a.name, d.name, count(m) ORDER BY count(m) DESC
----

The query engine processed all nodes and relationships in the pattern so that it could perform a count of all movies for a particular actor/director pair in the graph.
Then, it returned the results grouped by the name of the director and actor pair.

That is, Clint Eastwood acted in and directed 20 movies, Woody Allen acted in an directed 19 movies, and Adam Sandler acted in the same 8 movies that Dennis Dugan directed.
Aggregation in Cypher is different from aggregation in SQL.
In Cypher, you need not specify a grouping key.
As soon as an aggregation function is used (count()), all non-aggregated result columns become grouping keys.

The grouping is implicitly done, based upon the fields in the `RETURN` clause.

== Lists in the graph

You have already seen data in the graph that is stored as lists:

[source,cypher]
----
MATCH (m:Movie)
RETURN m.languages AS Languages, m.countries AS Countries LIMIT 10
----

Notice that these lists are shown in square brackets and each element of the list is separated by a comma.
These lists contains a set of strings.

=== Using collect to create a list

Cypher has a built-in function, `collect()` that enables you to aggregate a value into a list.
The value can be a property value, a node, a relationship, or a path.

[source,cypher]
----
MATCH (a:Person)-[:ACTED_IN]->(m:Movie)<-[:DIRECTED]-(d:Person)
RETURN a.name, d.name, count(m), collect(m.title) as Movies  ORDER BY count(m) DESC
----

The query returns a list of movie titles associated with each actor/director name pair.


== Check your understanding

include::questions/1-complete-query.adoc[leveloffset=+1]
include::questions/2-select-answer.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, reviewed and learned about basic query filtering using the `WHERE` clause.
In the next challenge, you will write queries to filter data.
