= What is an Agent?
:type: lesson
:order: 1

[.slide.discrete.col-2]
== Overview

[.col]
====
_An agent is an autonomous AI system that can perform tasks, make decisions, and operate independently._

An agent will:

. Process a users input
. Plan and reason about the task
. Select and execute tools
. Observe the results
. Decide if the goal is met
. Repeat if necessary
. Output the result
====

[.col]
image::images/agent-process.svg["A diagram showing the agent process and cyclic decision making"]

[.slide.col-2]
== Benefits 

[.col]
====
Agents are: 

* Flexible
* Adaptive
* Great at general tasks
====

[.col]
====
However, they need good context, because Agents:

* Struggle with ambiguous or poorly defined goals
* Depend heavily on the quality of input data
* Can fail in specialized or domain-specific tasks
====

read::Continue[]

[.summary]
== Summary

In this lesson, you learned about what an agent is, how it works, and its benefits and limitations.

In the next lesson, you will review the code for, and run an agent using Neo4j, Python, and LangChain.
