= Setup
:type: lesson
:disable-cache: true
:slides: true
:order: 1
:minutes: 10
:branch: main

To experiment with Neo4j and Java during this course you will need to setup a development environment.

include::../../../../../../shared/courses/codespace/get-started.adoc[]

The repository contains an example Maven project with the required dependencies and a `pom.xml` file.

[%collapsible]
.Develop on your local machine
====
You will need link:https://www.java.com[Java] 17 or higher installed.
You can check your version by running `java -version`.
To download Java, you can choose from many link:https://neo4j.com/docs/operations-manual/current/installation/requirements/#deployment-requirements-software[supported vendor options^]. For example, link:https://www.azul.com/downloads/?package=jdk#zulu[Azul's JDK^] or hlink:ttps://openjdk.org/install/[OpenJDK^].

Clone the link:{repository-link}[github.com/neo4j-graphacademy/drivers-java] repository:

[source,bash]
----
git clone https://github.com/neo4j-graphacademy/drivers-java
----

[TIP]
.Fork the repository
You can link:https://github.com/neo4j-graphacademy/drivers-java/fork[fork the repository] and have a copy for future reference.

Install the project and dependencies using Maven:

[source,bash]
----
cd drivers-java
./mvnw clean install -U -DskipTests
----

You do not need to create a Neo4j database as you will use the provided sandbox instance.
====

== Driver installation

The Neo4j driver is included in the `pom.xml` file, so you do not need to install it separately.

[source, xml]
----
include::{repository-raw}/{branch}/pom.xml[tag=neo4j-driver]
----

[%collapsible]
.Click to view the complete pom.xml file
====
[source, xml]
----
include::{repository-raw}/{branch}/pom.xml[tag=**]
----
====

== Setup the environment

Create a new `/src/main/resources/application.properties` file and copy the contents of the `example.properties` file into it.

Fill in the required values:

[source]
.Create a resources/application.properties file
----
include::{repository-raw}/{branch}/src/main/resources/example.properties[]
----

Update the Neo4j sandbox connection details:

NEO4J_URI:: [copy]#neo4j://{sandbox-ip}:{sandbox-boltPort}#
NEO4J_USERNAME:: [copy]#{sandbox-username}#
NEO4J_PASSWORD:: [copy]#{sandbox-password}#

== Test your setup

You can test your setup by running the test - `src/test/java/com/neo4j/app/AppTest.java`.

The test will attempt to load the values in the `application.properties` file and connect to the Neo4j sandbox.

[source,bash]
----
./mvnw test
----

You will see `Tests run: 2, Failures: 0, Errors: 0, Skipped: 0` and a `BUILD SUCCESS` message if you have set up your environment correctly. 

If any tests fail, check the contents of the `.application.properties` file.

== Continue

When you are ready, you can move on to the next task.

read::Success - let's get started![]

[.summary]
== Summary

You have setup your environment and are ready to start this module.
