= Connection Strings and Authentication
:type: quiz

In the previous lesson, you saw some example code for creating a new driver instance.
Let's take a closer look at the `driver()` function and how it is used to create a driver instance.

.Creating a Driver Instance
[source,python,indent=0,subs="attributes+"]
----
include::{repository-raw}/main/example/index.py[tag=pseudo]
----

The `neo4j.driver()` function accepts the following arguments:

1. A connection string
2. An authentication method to use when connecting - in this case, username/password authentication
3. Optionally, you can provide additional configuration as named parameters

Let's take a look at these points in more detail.


// == 1. Connection String
include::{shared}/courses/apps/connection-strings.adoc[tags="connectionstring"]


== `2` An Authentication Token

In most cases, you will connect to the DBMS using basic authentication consisting of a username and password.
You can pass the username and password as a tuple to the `auth` parameter.

.Username/Password Authentication
[source,python,role=nocopy,subs="attributes+"]
----
include::{repository-raw}/main/example/index.py[tag=auth]
----

// For more information on additional authentication methods...
include::{shared}/courses/apps/connection-strings.adoc[tags="tokenafter"]


== `3` Additional Driver Configuration (Optional)

The `driver()` function also accepts additional configuration parameters.



This object allows you to provide advanced configuration options, for example setting the connection pool size or changing timeout limits.

.Example Additional Configuration
[source,python,role=nocopy]
----
GraphDatabase.driver(uri, auth=auth,
    max_connection_lifetime=30 * 60,
    max_connection_pool_size=50,
    connection_acquisition_timeout=2 * 60)
----

For more information or a full list of configuration options, please link:https://neo4j.com/docs/python-manual/current/get-started/[visit the Neo4j Python Driver manual^].


// == What happens next?
include::{shared}/courses/apps/connection-strings.adoc[tag="next"]


== Check Your Understanding

// To do: need to add some hints for these

include::./questions/1-valid-schemes.adoc[leveloffset=+1]

include::./questions/2-aura-scheme.adoc[leveloffset=+1]

// == Summary
include::{shared}/courses/apps/connection-strings.adoc[tag="summary"]