= Introduction to GraphRAG Workshop
:caption: A one hour hands-on introduction to GraphRAG.
:status: disabled
:duration: 1 hour
:usecase: blank-sandbox
:repository: neo4j-graphacademy/workshop-graphrag-introduction
:categories: workshops, genai
:key-points: GraphRAG, Knowledge Graphs, Retrieval-Augmented Generation, Vector Search, Text to Cypher
:slides: true

In this 60 minute workshop, you will learn about GraphRAG, a technique that combines graph databases with generative AI to improve the quality of LLM-generated content.

We will explore the terms Retrieval-Augmented Generation (RAG) and Context Engineering, and how GraphRAG can be used in both scenarios.

The workshop is aimed at Generative AI practitioners who are familiar with vector-based Retrieval-Augmented Generation (RAG) and would like to understand how the approach of GraphRAG can improve the quality of LLM-generated content.



== What you will learn

* What GraphRAG is and how it can improve the quality of LLM-generated content
* The common graph shapes used in GraphRAG
* How to extract structure from unstructured data and store it in a Knowledge Graph
* How to use relationships to provide additional context to vector-based semantic search
* How to convert natural language queries into Cypher queries


== Prerequisites

Before taking this workshop, you should have:

* An understanding of Generative AI and Large Language Models (LLMs)


== Duration

1 hour
