= Creating a RANGE Index on a Relationship Property
:type: challenge
:sandbox: true

== Performance improvement needed

In our Movie data model, we have identified another query as important and one that we need to make as fast as possible for our users.
Here is an example where we are testing the rating property value for the RATED relationships in the graph.

[source,cypher]
----
PROFILE MATCH (u:User)-[r:RATED]->(m:Movie)
WHERE r.rating >= 4
RETURN u.name, r.rating, m.title
----

**Step 1:**

Profile this query and note if an index is used. Also note the number of total db hits and elapsed time.
It does not use an index.

**Step 2:**

Create a RANGE index for the rating property of the RATED relationship type.

* *`index_name`*: [copy]#RATING_rating#
* *`relationship_type`*: [copy]#RATED#
* *`property_key`*: [copy]#rating#

**Step 3:**

Repeat the query twice with a profile.

[NOTE]
.Why repeat when profiling?
--
You repeat the query because the first execution of the query includes time to parse the query, create the execution plan, and add it to the query cache.
The first and second executions will have the same number of total db hits, but the difference will be the elapsed ms times.
The second execution of the query is purely execution time of the query.
--

Was your newly-created RANGE index used?

// reco db change impact
// change to: Is the elapsed time reduced?
Are the number of total db hits  or elapsed time reduced?

include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Summary

In this Challenge, you demonstrated that you can create a single property RANGE index on a relationship type in the graph to improve the performance of a query.
In the next lesson, you will learn how to create Composite indexes.