= Person Profile
:type: challenge
:test-filename: 15_person_profile__test
:test-output: true
:branch: 15-person-profile
:optional: true

// Optional Lesson
include::../../../../../../shared/lesson/optional.adoc[]

If you click on a Person card anywhere on the website, you will be taken to a Person profile.
This API call is the same regardless of whether the person is an actor, director, or both.

We have already implemented the methods that populate the methods in the `MovieService` to get a list of movies that the person has either acted in or directed.

But if you take a look at the link:{repository-blob}main/api/services/people.go[`PeopleService`^], you will see two methods that need to be implemented to complete this page:

* <<find_by_id>> - should find a person by their ID.
* <<get_similar_people>> - should return a list of similar people who are commonly connected to the same movies.


[#find_by_id]
== find_by_id()

The `find_by_id()`  method is currently hardcoded to return information about _Al Pacino_.

.api/services/people.go
[source,go,indent=0]
----
include::{repository-raw}/main/api/services/people.go[tag="findById"]
----

You will update this method to run the following cypher statement in a **read transaction**.

//Adam: it just occurred to me that the user may need some hints or instructions for setting parameters if they run these Cypher queries in Neo4j Browser.

.Get Person information
[source,cypher,indent=0]
----
include::{cypher-repository-raw}/main/cypher/3-backlog/7-person-view/person-profile.cypher[]
----

The query will return the properties for the person with the corresponding `tmdbId`, along with a count of the number of movies that the person has acted in and directed.

=== Your Task

* Modify the `find_by_id()` method to query Neo4j and return details for the requested person.
* The returned object should include counts of the number of movies that the person has acted in or directed.
* If no records are returned, the method will raise a `NotFoundException`.


[%collapsible]
.Click here to reveal the final `find_by_id()` method.
====

[source,go,indent=0]
----
include::{repository-raw}/{branch}/api/services/people.go[tag="findById"]
----

====


[#get_similar_people]
== get_similar_people()

The `get_similar_people()` method should return a paginated list of similar people based on their second degree connections - either people who have acted in or have directed the person.

.api/services/people.go
[source,go,indent=0]
----
include::{repository-raw}/main/api/services/people.go[tag="getSimilarPeople"]
----

There could be a more clever algorithm for finding similar people by weighting the type of relationship differently, but for now, the following query will find a list of similar people based on the number of relationships in common.

.Get Similar People
[source,cypher,indent=0]
----
include::{cypher-repository-raw}/main/cypher/3-backlog/7-person-view/similar-people.cypher[]
----

[IMPORTANT]
.Parameters in Neo4j Browser
====
To run this query in Neo4j Sandbox, you will have to define a parameter in your Neo4j Browser session.
To do so, you can use the `:param` command.

For example, to view **Kevin Bacon**, you can set the `id` parameter to "4724":

[source,cypher]
----
:param id: "4724"
----

====

=== Your Task

* Modify the `get_similar_people()` method to query Neo4j and return a list of similar people.
* The returned objects should include a list of actors and an `inCommon` property to show how the two people are related.


[%collapsible]
.Click here to reveal the final `get_similar_people()` method.
====

[source,go,indent=0]
----
include::{repository-raw}/{branch}/api/services/people.go[tag="getSimilarPeople"]
----

====


// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-similar-people.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you have implemented the final methods in the `PeopleService`.
