= Adding specific node labels
:order: 2

[.slide]
== Introduction

In this lesson, you will learn how to refactor your graph by adding specific node labels to improve query performance and semantic clarity.

Labels allow you to categorize nodes and relationships in your graph, making it easier to query and understand the structure of your data. 

By adding specific labels to nodes, you can optimize query performance by reducing the search space and improving index utilization.

[.slide]
== Managers

Currently, all employees are represented with the `Employee` label. A manager can only be identified by the existence of a `REPORTS_TO` relationship.

[source, mermaid]
.Employee REPORTS_TO Employee
----
include::diagrams/employee.mermaid[]
----

[.slide]
=== Finding Managers

This query traverses all the `Employee` nodes and the `REPORTS_TO` relationships to find the managers. 

// identify the manager of each employee
[source, cypher, role=noplay]
.Find the managers
----
MATCH (e:Employee)-[:REPORTS_TO]->(manager:Employee)
RETURN manager.firstName
----

By adding a `Manager` label to the manager nodes, you can optimize this query.

[.slide]
=== Adding a Manager label

Set a `Manager` label to the Employee nodes that have an incoming REPORTS_TO relationship:

[source, cypher, role=noplay]
.Set Manager label
----
MATCH (e:Employee)-[:REPORTS_TO]->(manager:Employee)
SET manager:Manager
RETURN manager
----

[.slide]
=== Query the Manager label

You can now find all managers by querying for nodes with the `Manager` label:

[source, cypher, role=noplay]
.Find all managers
----
MATCH (manager:Manager)
RETURN manager.firstName
----

Compare the `PROFILE` of the original query and the refactored query to see the performance difference.

[.transcript-only]
====
[TIP]
.Removing labels
=====
You can remove a label from a node using the `REMOVE` clause. For example, to remove the `Manager` label from all nodes:

[source, cypher, role=noplay]
.Remove Manager label
----
MATCH (e:Employee)-[:REPORTS_TO]->(manager:Employee)
REMOVE manager:Manager
RETURN manager
----
=====
====

[.slide.col-2]
== Adding a ProductDiscontinued label

[.col]
====
Your challenge is to create an `ProductActive` label.

Not all products are still available for sale. The `discontinued` property on the `Product` nodes indicates whether a product has been discontinued or not.

[source, cypher, role=noplay]
.Find all discontinued products
----
MATCH (p:Product)
WHERE p.discontinued = true
RETURN p.productName
----
====

[.col]
====
To complete the challenge you will need to:

. Create a Cypher query to identify the active products.
. Update the query to `SET` a new `ProductActive` label on the active products.
. Write a new query to find all active products using the new `ProductActive` label.
====

[.transcript-only]
====
[%collapsible]
.Click to reveal the solution
=====
. You can identify the active products by checking for `discontinued = FALSE`:
+
[source, cypher, role=noplay]
.Find active products
----
MATCH (p:Product)
WHERE p.discontinued = false
RETURN p.productName
----

. You can set the `ProductActive` label on the active products:
+
[source, cypher, role=noplay]
.Set the label
----
MATCH (p:Product)
WHERE p.discontinued = false
SET p:ProductActive
RETURN p.productName
----

. Query for active products using the new label:
+
[source, cypher, role=noplay]
.Find `ProductActive` nodes
----
MATCH (p:ProductActive)
RETURN p.productName
----
=====


[TIP]
.Finding discontinued products
=====
To find all discontinued products, you can query for `Product` nodes and do *not* have the `ProductActive` label:

[source, cypher, role=noplay]
.Find discontinued products
----
MATCH (p:Product&!ProductActive)
RETURN p.productName
----
=====
====
read::Complete[]

[.summary]
== Lesson Summary

In this lesson, you learned about adding specific node labels to improve query performance and make your graph model more semantically clear.

In the next lesson, you will learn about adding indirect relationships between nodes.
