= Structured and Unstructured Data

What you have to think about when importing unstructured data

The strategies for importing unstructured data.


Understand the challenges of dealing with unstructured data 

Explore methods for dealing with unstructured data


As you have learned in previous lessons, a key challenge in data science is making sense of unstructured data. 
In this lesson, you will explore a strategy for storing unstructured data in a graph. 

Vector indexes and embeddings go some way to allow you to search and query unstructured data, but they are not a complete solution.
You can use the metadata surrounding the unstructured data to help make sense of it.

Imagine the following use case. You want to analyze customer emails to:

- when they sent the email
- understand the customer sentiment (are they happy or unhappy?)
- identify any products or services

You could represent this data in a graph of `Email`, `Customer`, and `Product` nodes. 

image::images/email-graph.svg[A graph of email, customer, and product nodes. Connected by `SENT` and `REFERS_TO` relationships.]

An import for this process would have to:

. Extract the email metadata (date, sender, recipient, subject)
. Embed the email text
. Extract the customer sentiment using a vector index
. Search for references to products or services in the email text

By importing the unstructured data into a graph, you can use the known relationships between the data to help make sense of it.

For example, you could use the graph to answer questions like:
- What products are customers talking about positively in their emails?
- Are there times in the year when customers are more likely to complain?
- What are customers saying about a particular product?

== Course data

During this module, you will use Python and Langchain to import the text of this course into Neo4j.
The data is unstructured, but you can make sense of it by using the metadata (the course structure), embeddings, and vector indexes

GraphAcademy represents courses as a graph of `Course`, `Module`, and `Lesson` nodes. A course has modules, and a module has lessons.

A simplistic view of the graph would look like this:

image::images/graphacademy-lessons.svg[A graph of course, module, and lesson nodes. Connected by `HAS_MODULE` and `HAS_LESSON` relationships.]

The link:https://github.com/neo4j-graphacademy/courses[GraphAcademy course content^] is in a public GitHub repository. We write courses in plain text link:https://asciidoc.org/[AsciiDoc^] that is parsed and displayed on the GraphAcademy website.

The course content is unstructured, but you can use the metadata (the course structure) to make sense of it.

You can view this lesson content at link:

== Check Your Understanding

include::questions/1-question.adoc[leveloffset=+1]

[.summary],
== Lesson Summary

In this lesson, you learned about ..

In the next lesson, you will learn about ..