= Community support

Questions that are posted for GraphAcademy are found here:

https://community.neo4j.com/c/general/graph-academy/116

Make sure that your notification level (Bell icon on the right) is set to Watching.

If your account is set up property in Community, you should receive an email whenever a question is posted or answered in this area.

You should visit this page regularly to ensure that no questions are unanswered.

If there is a particular question that cannot be answered, please use slack to get an answer.

In addition, if you see a Community post that is sent to devrel that you think you can answer, please chime in!

== Most common questions

* Cannot execute code against the sandbox.
** Does the course have a connection to the sandbox?
*** They should log in to sandbox.neo4j.com in a different tab and sign in with the same credentials they use to sign in to GraphAcademy.
**** Do they see the $neo4j prompt in the sandbox window for the course? Sometimes it takes a minute or so for the $neo4j prompt to appear.

* If the Challenge does not validate:
** Did they possibly modify the graph in sandbox.neo4j.com, but possibly the wrong database?
** Are they using the same sandbox instance for 2 courses? This happens when the user is currently going through 2 courses at the same time.

== Sandboxes per course

Cypher Fundamentals: movies
Modeling Fundamentals, Importing CSV Data into Neo4j: blank
Cypher Intermediate Queries, Indexes and Constraints, app-* courses: recommendations