= Email support

Tag team with Adam to make sure all questions that come in to graphacademy@neo4j.com.
Reply to all to make sure Adam sees what has been answered.

The most common questions:

* Certification says pending
** Ask them to unenroll in the certification and re-enroll.
* Could not order t-shirt
** Ask for more details. Check printful to see if the order is in the system: https://www.printful.com/dashboard/default/orders
* Did not receive t-shirt
** Refer to Alexander Erdl
* Typo/unclear in course
** Fix the course content if it is wrong or unclear
* Cannot see badges in GraphAcademy
** User may have signed in with more than one type of credentials
** Ask user for old/new credentials and use a variation of the Cypher to combine accounts (transfer-user.adoc).
* Need to change email
** Ask user to create a new GraphAcademy account with the new email and send the old/new credentials.
** Ask user for old/new credentials and use a variation of the Cypher to combine accounts (transfer-user.adoc).