= GraphAcademy FAQs

== 'Configuring Sandbox, please wait'

This error occurs in the embedded sandbox in the right pane for a course for a couple of reasons:

. User is not connected to the sandbox for the course.
. VPN connection is blocking access.

=== Solution

In most cases it is a sandbox connection issue. In the same browser window where you are signed in to GraphAcademy, open a new tab and sign in to sandbox.neo4j.com using the same credentials you use for signing into GraphAcademy.
Then, if you simply refresh the GraphAcademy course page, the issue should resolve.

If you are connected to a VPN, you may have to disconnect to access the embedded browser from the course.

== Queries do not run

This behavior is typically due to the course page losing its connection to the sandbox.

=== Solution

Refresh the course page. This should reset the connection.

== Cannot see certification in GraphAcademy

User has taken and passed the Neo4j Certified Professional exam.
When user is signed in to GraphAcademy, they cannot see their badge/certificate.

=== Solution

After passing the certification, it may take up to an hour to propagate to GraphAcademy.
If the badge/certificate is not showing up after an hour, there is a possibility that the user has signed in to GraphAcademy in more than one way?
For example using a different email address, or using google auth vs. email.
If there is more than one GraphAcademy account, for example the following query returns multiple rows:

[source,cypher]
----
match (u:User)-[:HAS_ENROLMENT]-(x:CompletedEnrolment)--(c:Certification)
where u.givenName contains  'USER givenName'
return u.email, u.givenName, u.sub, 'https://graphacademy.neo4j.com/u/' + u.id
----

Ask the user what credentials they want to use going forward and merge the user's enrollment into the "new" user using transfer-user.adoc.
