
graph LR
    subgraph "Table"
        CT["<b>Customer</b><br/>customer_id (PK)<br/>name<br/>email<br/>address"]
    end
    
    subgraph "Node"
        CN(("<b>Customer</b>"))
        PROPS["customerId<br/>name<br/>email<br/>address"] 
    end
    
    CT --> CN
