graph TD
    Customer -->|PLACED| Order
    Order -->|CONTAINS| Product
    Customer -->|REVIEWED| Product

    Customer(("<b>Customer</b>"))
    Order(("<b>Order</b>"))
    Product(("<b>Product</b>"))