graph TD
    Noun -->|Verb| Noun_
    Customer -->|PLACED| Order
    Person -->|DIRECTED| Movie
    
    Noun(("<b>Noun</b>"))
    Noun_(("<b>Noun</b>"))
    Order(("<b>Order</b>"))
    Customer(("<b>Customer</b>"))
    Person(("<b>Person</b>"))
    Movie(("<b>Movie</b>"))
