graph LR
    subgraph "Table"
        OPT["<b>OrderProduct Table</b><br/>order_id (FK)<br/>product_id (FK)<br/>quantity<br/>unit_price"]
    end
    
    subgraph "Graph"
        O((Order))
        P((Product))
        REL[CONTAINS<br/>quantity: 2<br/>unitPrice: 15.99]
        O --> REL --> P
    end
    
    OPT --> REL