graph LR
    subgraph "Relational Tables"
        CT["Customer"]
        OT["Order"]
        PT["Product"]
        OPT["OrderProduct<br/>(Many-to-Many)"]
    end
    
    subgraph "Graph Model"
        CN(("Customer"))
        ON(("Order"))
        PN(("Product"))
        REL["(Order)-[<b>CONTAINS</b>]->(Product)"]
    end
    
    CT --> CN
    OT --> ON
    PT --> PN
    OPT --> REL
