= Using List Comprehension to Aggregate
:type: video
:order: 11
:sandbox: true

[.video]
video::ZcP27xl9Kc4[youtube,width=560,height=315]

//https://youtu.be/ZcP27xl9Kc4

[.transcript]

== Using list comprehension to aggregate data

List comprehension enables you to extract values from an existing list.
You can create a list by evaluating an expression that tests for list inclusion.
In addition, you can modify the values returned in the list.

Here is an example where we simply return a subset of the list where the values in the countries list property are either USA or Germany or both:

[source,cypher]
----
MATCH (m:Movie)
RETURN m.title AS MovieTitle,
[x IN m.countries WHERE x CONTAINS 'USA' OR x CONTAINS 'Germany' | x]
AS Country LIMIT 500
----

// reco db change impact
// need to delete this line
Notice that for this evaluation, we use CONTAINS. This is because some of the data in the lists have leading blanks and we want to make sure we account for all values in the list.

Here is another example where we modify the values that are returned in the list:

[source,cypher]
----
MATCH (m:Movie)-[:ACTED_IN]-(a:Actor)
WHERE a.name = 'Tom Hanks'
WITH m ORDER by m.released DESC
WITH collect(m) AS Movies
WITH [x IN Movies | x.title + ": " + toString(date().year - date(x.released).year + 1)] AS Summary
RETURN Summary
----

In this code we are transforming the list to contain the title of the movie and the number of years since it was released in descending order.



[.quiz]
== Check your understanding

include::questions/1-list-comprehension.adoc[leveloffset=+2]
include::questions/2-list-comprehension.adoc[leveloffset=+2]

[.summary]
== Summary

In this lesson, you reviewed and learned more about list comprehension to aggregate data in your Cypher queries.
In the next Challenge, you will create a query  using list comprehension.
