[.question.freetext]
= Who directed Toy Story?

Take the Director value output from the statement above and paste it into the box below.

input::answer[]

* [x] John Lasseter

[TIP,role=hint]
.Hint
====
You need to call the `neo4j.NewDriverWithContext()` object to create a Driver instance using the `Uri`, `Username` and `Password` variables provided by the `GetNeo4jCredentials()` function, then open a new session, execute the Cypher statement and log the `Director` value of the first record.

Once you have a result object, use the `neo4j.SingleTWithContext()` function to extract the `Director` value from the first record.

Your `fmt.Println()` call should look similar to the code block below:

[source,ts]
----
fmt.Println(director)
----

Copy the answer without any quotes or whitespace.
====


[TIP,role=solution]
.Solution
====
**John Lasseter** directed Toy Story.

You can compare your code with the solution here.

[source,go]
----
include::{repository-raw}/main/{lab-solution}[]
----

link:{repository-blob}/main/{lab-solution}[Click here to view the solution^].
====
