= Movie Details
:type: challenge
:test-number: 12
:branch: 12-movie-details

If you click on any movie, you'll see that the API currently only returns information about the film Goodfellas.

The page itself is populated by three API calls:

1. The details about the movie are loaded via the `api/movies/{id}` endpoint.  This endpoint populates the information in the header along with the list of directors and actors.
2. The similar movies list is loaded by a call to the `api/movies/{id}/similar` endpoint.
3. The ratings on the right hand side of the page are loaded by a call to the `api/movies/{id}/ratings` endpoint.


== Movie Details

The movie details are retrieved by the `findById` method on the `MovieService` in `src/services/movie.service.js`.

.src/services/movie.service.js
[source,js,indent=0]
----
include::{repository-raw}/main/src/services/movie.service.js[tag=findById]
----

Most of the important information is held as properties on the Movie node, but the payload should also return some additional information.
We can use the `size` function to get a count of ratings for the movie and use a link:https://neo4j.com/docs/cypher-manual/current/syntax/lists/#cypher-pattern-comprehension[Pattern Comprehension] to get a list of actors and directors.

As with the other movie methods in the `MovieService`, we should also provide a `favorite` value to represent whether the user has added this movie to their My Favorites list or not.

Here is the Cypher query:

.Movie Details
[source,cypher]
----
include::{repository-raw}/main/cypher/3-backlog/4-movie-view/movie-details.cypher[]
----

We should also throw a `NotFound` error if the query returns no records.

Update the `findById` method to retrieve the movie details from the database.

[%collapsible]
.Click to reveal the completed `findById` method
====

.src/services/movie.service.js
[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/movie.service.js[tag=findById]
----

====


== Similar Movies

Similar movies are retrieved using the `getSimilarMovies` method.


To provide a simple set of similar movies, we can use the number of neighbours in common and their IMDB rating to generate a similarity score.

.Find Similar Movies
[source,cypher]
----
include::{repository-raw}/main/cypher/3-backlog/4-movie-view/similar-movies.cypher[]
----

Update the `getSimilarMovies` method to return similar movies from the database.


[%collapsible]
.Click here to reveal the completed `getSimilarMovies` method
====

.src/services/movie.service.js
[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/movie.service.js[tag=getSimilarMovies]
----

====


// Testing
include::../../../../includes/test.adoc[]

== Verifying the Test

include::./questions/1-most-similar-movie.adoc[]


[.summary]
== Lesson Summary

In this lesson, we modified the `findById` method to return movie details from the Neo4j database.

In the next lesson, we will finish off the Movie page by populating the list of reviews from Neo4j.
