[.question]
= 1. Outcomes of testing

During your testing of the use cases, what might you need to do?

* [x] Add more data to the graph to test scalability.
* [x] Test and modify any Cypher code used to test the use cases.
* [x] Refactor the data model if a use case cannot be answered.
* [ ] Eliminate use cases from the application.

[TIP,role=hint]
.Hint
====
Remember that graph data modeling is an iterative process that involves domain experts and Cypher developers.

Three of the four options above should be done to test your data model as part of an interative refactoring process.
====

[TIP,role=solution]
.Solution
====
The first three answers in the list above are correct.

You may want to **add more data** to your graph to test that query results returned in a prompt manner. +
If resuls are not returned fast enough, you may want to **test and modify any Cypher** to improve performance. +
If results can not be obtained in a timely fashion, or your entire use case is not yet supported, you will need to **refactor your data** model.

Graphs are flexible enough to answer almost any question, so there is **no need to eliminate use cases** from the application.
====
