[.question]
= Understanding GDS Syntax

You want to run PageRank on a projection called `'social-network'` and save the results as a property called `'influence'` in your main database.

Which command is correct?

* [ ] `CALL gds.pageRank.stream('social-network', {writeProperty: 'influence'})`
* [x] `CALL gds.pageRank.write('social-network', {writeProperty: 'influence'})`
* [ ] `CALL gds.write.pageRank('social-network', {property: 'influence'})`
* [ ] `CALL gds.pageRank('social-network', {mode: 'write', property: 'influence'})`

[TIP,role=hint]
.Hint
====
Think about the syntax pattern: `CALL gds.<algorithm>.<mode>`. Which mode persists results to the database?
====

[TIP,role=solution]
.Solution
====
**`CALL gds.pageRank.write('social-network', {writeProperty: 'influence'})`** is correct.

The GDS syntax pattern is `CALL gds.<algorithm>.<mode>`. To save results to the database, use `write` mode. The `writeProperty` parameter specifies what to name the property.

`stream` mode returns results without writing them. The other options don't follow the correct GDS syntax pattern.
====

