= Indexes in Neo4j
:type: quiz
:sandbox: true

//[.video]
//video::Po4k7vXGBIE[youtube,width=560,height=315]

//https://youtu.be/Po4k7vXGBIE

[.transcript]

== Indexes in Neo4j

An index in Neo4j is a data structure that allows the graph engine to retrieve data quickly.
All indexes in Neo4j require more storage in the graph, so you must ensure that you do not index everything!

You learned in the previous module that a best practice is to create uniqueness constraints before you load your data.
After the data is loaded, you create additional indexes to make your queries perform faster.
Using indexes makes writing data slower, but retrieving it faster.

Uniqueness constraints are implemented as indexes, but there are more types of indexes that you can create and use:

* b-tree
* Composite
* TEXT

[NOTE]
--
Full-text indexes are used differently from other indexes and will be covered in the next module.
--

=== Using `PROFILE` to analyze queries that use indexes

Previously in this course, you learned about the importance of creating the required indexes for the use cases of your application.
At runtime, only one index is used by default.
This means that not only must you plan what indexes are appropriate for your use cases, but also that the amount of data in the graph will impact what indexes are used at runtime.

In this module you will `PROFILE` queries to:

* Identify which index is used for a query.
* Determine if adding an index improves query performance.

=== b-tree indexes

A b-tree is a common implementation of an index that enables you to sort values.
You can define a b-tree index on a property of a node label or relationship type.
The data stored in the index can be numeric or string types.

A b-tree index can speed up the following  in your Cypher code:

* Equality checks `=`
* String  or numeric range comparisons `>`,`+>=+`,`<`, `+<=+`
//* List membership `IN`
* String comparisons `STARTS WITH`, `ENDS WITH`, `CONTAINS`
* Existence checks `IS NOT NULL`

This query could benefit from a b-tree index in the graph for the born property associated with the Person label:

[source,cypher]
----
MATCH (p:Person)
WHERE p.born IS NOT NULL
RETURN p
----

=== Composite indexes

A composite index combines values from multiple properties for a node label or for relationship type.
You create composite indexes when multiple properties are always tested together in a query.
The values stored for a composite index can be all strings, all numerics, or a combination.

During query planning, at most one index is used, so it is beneficial in some cases to create a composite index when multiple properties need to be retrieved quickly.

For example, you might want to index on the Movie.year and the Movie.title properties.
If you created a composite index on these two properties, then this query would perform better:

[source,cypher]
----
MATCH (m:Movie) WHERE m.year > 1999
AND m.title CONTAINS "Toy"
RETURN m.title, m.year, m.imdbRating
----

=== TEXT indexes

A TEXT index supports node or relationship property types that must be strings.
It is optimized for queries that may specify `CONTAINS or `ENDS WITH` in their predicates, but is also used for any type of test of a string property.


////
On thing that is different about b-tree indexes vs. TEXT indexes is that a predicate such as the following cannot use a TEXT index:

[source,cypher]
----
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)<-[:DIRECTED]-(p2:Person)
WHERE p.name = p2.name
RETURN p
----
////

=== About LOOKUP indexes

There are two types of  LOOKUP indexes in a Neo4j database (release 4.3 and later).
These indexes are created automatically for you and are used to look up a node label or relationship type value.

Without these indexes queries would need to scan the entire set of nodes or relationships for some queries which is very inefficient.

[WARN]
You should not create or remove these types of indexes in the database as they are automatically created for you.


[NOTE]
.Indexes Coming Soon
--
This course does not cover RANGE  or POINT indexes that will be added in a future release of Neo4j.
--

== Check your understanding

include::questions/1-select-answer.adoc[leveloffset=+1]
include::questions/2-select-answer.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you learned  about the types of indexes that Neo4j supports.
In the next lesson, you will learn how to create an index on a node property.
