= Agent Architecture
:type: lesson
:optional: true

Before jumping into building the agent, let's recap how the agent will work.

== Tools

As you learned in link:/courses/llm-fundamentals/[Neo4j & LLM Fundamentals], an Agent is a class that provides an LLM with access to a set of tools.  These tools may access additional data sources, APIs, or functionality. The model is used to determine which of the tools to use to complete a task.

In this case, we have two tools that are suitable for distinct tasks.

1. The link:../../4-vector-retrieval/[Vector Retrieval Chain from Module 4^] searches embeddings of movie plots to find movies based on a text input.  For example, _"recommend me a movie about a love story that ends in tragedy"_.
2. For more complex queries, the link:../../4-vector-retrieval/[Cypher Retrieval Chain from Module 5^] will use the schema to generate a Cypher statement that answers a question.  For example, _"Who directed Toy Story?"_ or _"What was the average user rating of La La Land?"_

The LLM will use descriptions of these tools to decide which tool is most appropriate to perform the task at hand.

Each of these chains has been designed to expect an object containing an `input` and `rephrasedQuestion` and return a string.


== Memory

Our Agent will also be capable of simulating a real conversation by recalling the conversation history and rephrasing the current user input.

This step will need to be performed before the agent selects which tool to use.


== Process

Therefore, the agent chain should adhere to the following steps:

1. User input is received by a `Runnable` sequence
2. The sequence should pull the recent conversation history from the database
3. The history should be used to rephrase the input into a standalone question
4. The standalone question should then be passed to the agent executor, which will select a tool, invoke it and return a string response.


== Ready?

Now we have covered the architecture, it's time to build.

Once you're ready, click the button below to mark the lesson as read and to continue to the challenge.

read::I'm ready![]


[.summary]
== Summary

In this lesson, we discussed the architecture of the agent and outlined how the agent will work.

In the next lesson, you will build it!
