= Browsing Genres
:type: challenge
:branch: 09-genre-list
:test-filename: 09_genre_list__test
:test-output: true
:optional: true

// Optional Lesson
include::../../../../../../shared/lesson/optional.adoc[]

If you click on the **Genres** link in the main navigation, you will be taken to a link:http://localhost:5000/genres[list of Genres^].
This list is populated by the API route at http://localhost:5000/api/genres, with the list being produced by the `all()` method within the link:{repository-blob}main/api/dao/genres.py[`GenreDAO`^].

.api/dao/genres.py
[source,python,indent=0]
----
include::{repository-raw}/main/api/dao/genres.py[tag=all]
----

In this challenge, you will modify the method to run the following Cypher statement in a **read transaction**:


.Listing Genres
[source,cypher]
----
include::{cypher-repository-raw}/main/cypher/3-backlog/1-browse-genres/genre-details.cypher[]
----


== Your Task

* Modify the `all()` method on the `GenreDAO` to query Neo4j and return a list of properties ordered by genre name.
* Each genre should have a name, the number of movies listed in that genre (`movies`), and a poster image (from the most popular movie in that genre).


== Working Solution

[%collapsible]
.Click here to view the completed `all()` method.
====

.api/dao/genres.py
[source,python,indent=0]
----
include::{repository-raw}/{branch}/api/dao/genres.py[tag=all]
----

====

// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-movie-count.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you updated the `GenreDAO` to retrieve a list of genres from the database.

In the next Challenge, you will update the `GenreDAO` to query Neo4j to find the details of an individual genre.
