[.question]
= Course Completion

Which of the following are benefits of migrating relational data to a graph database? (Select all that apply)

- [x] Relationships become explicit and first-class citizens
- [x] Complex JOIN queries are replaced by simple traversals
- [x] The data model can evolve more flexibly
- [ ] All data must be normalized to third normal form


[TIP,role=hint]
.Hint
====
Think about the differences between relational and graph databases that you learned throughout this course.
====

[TIP,role=solution]
.Solution
====
The benefits of migrating to a graph database include:

* **Relationships become explicit** - Unlike foreign keys, graph relationships are stored directly and can have properties
* **Simple traversals replace JOINs** - Following relationships is a constant-time operation
* **Flexible schema** - Graph databases allow the model to evolve without rigid schema changes

Graph databases do not require normalization - in fact, some denormalization can improve query performance.
====

