= Modifying Returned Data
:sandbox: true

//[.video]
//video::ImKvXY72SA0[youtube,width=560,height=315]

//[.transcript]
== Modifying data returned

You can always modify the data that is returned by performing string or numeric operations on the data.

For example:

[source,cypher]
----
MATCH (m:Movie)<-[:ACTED_IN]-(p:Person)
WHERE m.title CONTAINS 'Toy Story' AND p.died IS NULL
RETURN m.title AS Movie, p.name AS Actor, p.born AS DOB, date().year - p.born.year AS `Age This Year`
----

This query returns the actors in each Toy Story movie and their age if they are still living according to our graph.
We add data to each line by calculating the actor's age.

Here is an example where we concatenate string data returned:

[source,cypher]
----
MATCH (m:Movie)<-[:ACTED_IN]-(p:Person)
WHERE m.title CONTAINS 'Toy Story' AND p.died IS NULL
RETURN 'Movie: ' + m.title AS Movie, p.name AS Actor, p.born AS DOB, date().year - p.born.year AS `Age This Year`
----

== Conditionally modifying data returned

Cypher has a `CASE` clause that you can specify to conditionally modify data returned.

Here is an example:

[source,cypher]
----
MATCH (m:Movie)
RETURN m.title AS Movie,
CASE
WHEN ("USA" IN m.countries  OR " USA" in m.countries) AND ("Canada" in m.countries OR " Canada" in m.countries)  THEN "North American"
WHEN "USA" IN m.countries  OR " USA" in m.countries AND NOT ("Canada" in m.countries OR " Canada" in m.countries)  THEN "American"
WHEN "Canada" in m.countries OR " Canada" in m.countries AND NOT ("USA" IN m.countries  OR " USA" in m.countries) THEN "Canadian"
ELSE "Foreign"
END AS Type , m.countries LIMIT 500
----

In this query we transform the data returned such that:

* Movies released in the USA, but not in Canada return Type of American.
* Movies released in the USA and Canada return Type of North American.
* Movies released in Canada, but not in USA return Type of Canadian.
* Otherwise, the Type is returned as Foreign.

== Check your understanding

include::questions/1-complete-query.adoc[leveloffset=+1]
include::questions/2-select-answer.adoc[leveloffset=+1]

[.summary]
== Summary

In this lesson, you learned how you can add to or modify results returned.
In the next challenge, you will write queries to modify results returned.
