= Create a Graph
:type: challenge
:optional: true
:sandbox: true
:order: 7
:image-path: {cdn-url}/courses/neo4j-fundamentals/1-graph-thinking/3-graphs-are-everywhere/images
:slides: true

[.slide.col-2]
== Knowledge Graph
[.col]
====
Knowledge graphs provide a structured way to represent entities, their attributes, and their relationships, allowing for a comprehensive and interconnected understanding of the information.

Knowledge graphs can break down sources of information and integrate them, allowing you to see the relationships between the data.

You may not be familiar with the term knowledge graph, but you have probably used one. Search engines typically use knowledge graphs to provide information about people, places, and things.
====

[.col]
====
The following knowledge graph could represent Neo4j:

image::{image-path}/neo4j-google-knowledge-graph.svg[An example of a knowledge graph of Neo4j showing the relationships between people, places, and things, width=80%]
====

[.slide]
== Create your knowledge graph

Use `MERGE` to create a knowledge graph about you.

Create a node for yourself and relationships to other nodes related to your such as people, places, and things.

[source, cypher]
----
MERGE (p:Person {name: "Your Name"})
MERGE (neo4j:Technology {name: "Neo4j"})
MERGE (p)-[:LEARNED_ABOUT]->(neo4j)
----

[.next.discrete]
== Next

read::Continue[]

[.summary]
== Summary

In this optional challenge, you created your own knowledge graph.

