= Gen-AI - Hands-on Workshop
:status: active
:duration: 2 hours
:caption: GenAI Beyond Chat with RAG, Knowledge Graphs and Python
:usecase: blank-sandbox
:key-points: A comma, separated, list of learnings
:repository: neo4j-graphacademy/genai-workshop

== Course Description

In this GenAI and Neo4j workshop, you will learn how Neo4j can support your GenAI projects. 

You will: 

* Use Vector indexes and embeddings in Neo4j to perform similarity and keyword search
* Use Python and Langchain to integrate with Neo4j and OpenAI
* Learn about Large Language Models (LLMs), hallucination and integrating knowledge graphs
* Explore Retrieval Augmented Generation (RAG) and its role in grounding LLM-generated content

After completing this workshop, you will be able to explain the terms LLM, RAG, grounding, and knowledge graphs. You will also have the knowledge and skills to create simple LLM-based applications using Neo4j and Python.

=== Prerequisites

Before taking this course, you should have:

* A basic understanding of Graph Databases and Neo4j
* Knowledge of Python and capable of reading simple programs

While not essential, we completing the GraphAcademy link:/courses/neo4j-fundamentals/[Neo4j Fundamentals^] course.

=== Duration

{duration}

== What you need

To complete the practical tasks within this workshop, you will need: 

* Access to gitpod.io (you will need a github, gitpod, or bitbucket account) or a local Python environment
* An OpenAI billing account and API key
