= Gen-AI - Hands-on Workshops
:categories: beginners:5
:status: unlisted
:duration: 2 hours
:caption: GenAI Beyond Chat with RAG, Knowledge Graphs and Python
:usecase: blank-sandbox
:video: https://www.youtube.com/embed/vVCHJFa01gA
:key-points: ${11:A comma, separated, list of learnings

== Course Description

In this Introduction to Neo4j & LLMs you will learn how to integrate Generative AI models using Python and Langchain. 

You will: 

* Use Vector indexes and embeddings in Neo4j to perform similarity and keyword search
* Use Python and Langchain to integrate with Neo4j and OpenAI
* Learn about Large Language Models (LLMs), hallucination and integrating knowledge graphs
* Explore Retrieval Augmented Generation (RAG) and its role in grounding LLM-generated content

After completing this workshop you will be able to explain the terms LLM, RAG, grounding, and knowledge graphs. You will also have the knowledge and skills to create simple LLM-based applications using Neo4j and Python.


=== Prerequisites

Before taking this course, you should have:

* A basic understanding of Graph Databases and Neo4j
* Knowledge of Python and capable of reading simple programs

While not essential, we completing the GraphAcademy link:/courses/neo4j-fundamentals/[Neo4j Fundamentals^] course.

To complete the practical tasks within this course, you will need: 

* Python installed or access to gitpod.io
* A Neo4j database, we recommended signing up for a free Aura database
* An OpenAI billing account and API key


=== Duration

{duration}


=== What you will learn

TODO - complete