= Creating Movie Actors
:type: lesson

We have seen how to add a `Movie` node to our database. But what if we also wanted to add the actors who acted in the movie? We can do this by passing a little more data to our `save()` method.

== Testing the save() method with relationships

Now that we can save a single node to the database, let's look at how to save relationships with it. We can add this information to a JSON file and pass it to the `save()` method without any additional code changes.

Because the `actors` field is already part of the `Movie` domain class, the extra data will automatically get mapped. The `actors` field is a `List<Person>`, so the JSON file needs to contain an array of `Person` objects. The `save()` method will then map those to the `actors` field.

Let's try it!

[source,json]
----
include::{repository-raw}/src/main/resources/movieRels.json[]
----

Now let's run this command at the command line:

[source,shell]
----
curl localhost:8080/movies/save \
  -H 'Content-Type: application/json; charset=utf-8' \
  -d @src/main/resources/movieRels.json
----

Output from the command should look something like this:

[source,shell]
----
{"movieId":"9876","title":"MyMovie","plot":null,"poster":null,"url":null,"imdbId":null,"tmdbId":null,"released":null,"year":null,"runtime":null,"budget":null,"revenue":null,"imdbVotes":null,"imdbRating":null,"languages":null,"countries":null,"actors":[{"id":null,"role":"self","person":{"imdbId":"12","tmdbId":null,"name":"Jennifer Reif","bio":null,"poster":null,"url":null,"bornIn":null,"born":null,"died":null}}]}
----

And check the results in Neo4j Browser:

[source,cypher]
----
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie {movieId: "9876"})
RETURN *
----

Just as before, feel free to play around with the data in the JSON file and save different variations of the movie and actors.

[.summary]
== Lesson Summary

In this lesson, you learned how to save nodes with their relationships to the database.

Next, you will learn how to write custom queries and methods to read and write data to Neo4j from your application.