= Welcome
:type: lesson
:order: 0
:branch: main

[.slide.discrete]
== Welcome to Introduction to GraphRAG

Welcome to the hands-on **Introduction to GraphRAG** Workshop, where you will learn:

* How to use GraphRAG to improve the quality of LLM-generated content
* How to build a knowledge graph from unstructured data
* How to combine vector search with knowledge graphs to improve the quality of LLM-generated content
* How to use retrievers to read data from the knowledge graph
* How to convert natural language questions into database queries using an LLM
// * How to use LangGraph's prebuilt ReAct agent to connect to Neo4j
// * How to provide the agent with access to the knowledge graph using the `langchain-neo4j` library



// [.slide]
// == Hands-on Workshop

// This is a hands-on workshop with interactive exercises in Jupyter Notebooks.
// To follow along, open up the link:{repository-link}[{repository}^] in Github Codespaces.

// **Before you start the hands-on exercises**, you need to set up your development environment to run the code examples.

[.slide]
include::../../../../../../shared/courses/codespace/get-started.adoc[]

// The codespace is pre-configured with the necessary dependencies.

[.slide]
== Develop on your local machine

To follow along locally, you will need:

* link:https://python.org[Python].
* link:https://code.visualstudio.com/[Visual Studio Code^].
* link:https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter[Jupyter extension for Visual Studio Code^].
* The ability to install packages using `pip`.

You may want to set up a virtual environment using link:https://docs.python.org/3/library/venv.html[`venv`^] or link:https://virtualenv.pypa.io/en/latest/[`virtualenv`^] to keep your dependencies separate from other projects.


[.slide.discrete]
== Clone the repository

Clone the link:{repository-link}[github.com/neo4j-graphacademy/workshop-genai] repository:

[source,bash]
----
git clone https://github.com/neo4j-graphacademy/workshop-genai
----

Install the required packages using `pip` and download the required data:

[source,bash]
----
cd workshop-genai
pip install -r requirements.txt
----

You do not need to create a Neo4j database as you will use the provided instance.

The instance uses Neo4j's GenAI functions, you can find out more about how to configure them in the link:https://neo4j.com/docs/cypher-manual/current/genai-integrations/[Neo4j GenAI integration documentation^].

[.slide]
== Configure the environment

Today we will need an API key to use OpenAI's LLMs and embedding models.
You can use the `OPENAI_API_KEY` provided, or use your own API key generated from link:https://platform.openai.com[platform.openai.com^].

We have created a Neo4j instance for you to use during this workshop.

Create a file called `.env` and copy the following code into it.

[source,env]
.env
----
OPENAI_API_KEY=sk-...
NEO4J_URI=bolt://{instance-ip}:{instance-boltPort}
NEO4J_USERNAME={instance-username}
NEO4J_PASSWORD={instance-password}
----


[.slide]
== Test your setup

You can test your setup by running `workshop-genai/test_environment.py` - this will attempt to connect to the Neo4j sandbox and the OpenAI API.

You will see an `OK` message if you have set up your environment correctly. If any tests fail, check the contents of the `.env` file.


[.slide]
== Keep your codespace running

To avoid creating a new environment for each challenge, you can keep your environment running for the duration of the workshop.

The environment will automatically pause after a period of inactivity.



[.slide]
== Are you ready?

When you are ready, you can move on to the next lesson.

read::Success - let's get started![]

[.summary]
== Lesson Summary

You have setup your development environment and are ready for hands-on practice.

In the next lesson, you will learn the fundamentals of GraphRAG.
