CREATE CONSTRAINT Person_tmdbId_uniqueness IF NOT EXISTS FOR (x:Person) REQUIRE x.tmdbId IS UNIQUE;
CREATE CONSTRAINT User_userId_uniqueness IF NOT EXISTS FOR (x:User) REQUIRE x.userId IS UNIQUE;
CREATE CONSTRAINT Genre_name_uniqueness IF NOT EXISTS FOR (x:Genre) REQUIRE x.name IS UNIQUE