= Authenticating a User
:type: challenge
:branch: 05-authentication
:test-filename: 05_authentication_test
:test-function: TestAuthentication

At stage of the project,  a user can register, but they are still unable to sign in.
As with the previous Challenge, the `FindOneByEmailAndPassword()` method is currently hard coded to accept only the email `graphacademy@neo4j.com` and password `letmein`.

In this challenge you will rewrite the `FindOneByEmailAndPassword()` function of the link:{repository-blob}main/pkg/services/auth.go[`AuthService`^] to find the User node with the corresponding email and compare the password before issuing a JWT token.

But first, let's take a look at how Authentication works in the application.
If you prefer, you can skip straight to <<Implementing Authentication>>.

== How Authentication Works

When a user attempts to access an API endpoint that requires authentication, the server checks for a JWT token.

When a user registers or signs in, a JWT token is generated and appended to the User record.
This token is then stored by the UI and appended to `Bearer` to create an `authorization` header.

The token generation happens in the link:{repository-blob}main/pkg/services/auth.go[`AuthService`^] by calling the `Sign()` method in the {repository-blob}main/pkg/services/jwtutils/jwt.go[`jwtutils`^] package.

When The API receives a request which includes the `authorization` header, this token is decoded to verify the identify of the user.


=== Login Route

When a user submits the login form on the website, a request is sent to `http://localhost:3000/api/login` with a username and password.


== Implementing Authentication

To implement database authentication, you will modify the `FindOneByEmailAndPassword()` method in the `AuthService`.

.pkg/services/auth.go
[source,go,indent=0]
----
include::{repository-raw}/main/pkg/services/auth.go[tag=authenticate]
----

Your challenge is to update the `FindOneByEmailAndPassword()` method to perform the following actions:

1. <<Open a new Session>>
2. <<Find the User node within a Read Transaction>>
3. <<Verify the User exists>>
4. <<Compare Passwords>>
5. <<Return User Details>>


=== Open a new Session

Use the `as` variable to access the Driver, and call the `NewSession()` method to open a new session.

.pkg/services/auth.go
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/auth.go[tag="session"]
----


=== Find the User node within a Read Transaction

Within the session, execute a Read Transaction to execute the following Cypher query:

.Find User by Email
[source,cypher]
----
MATCH (u:User {email: $email}) RETURN u
----

You execute a new read transaction by calling the `ReadTransaction()` method on the `session` variable, providing a function represent the unit of work.

.pkg/services/auth.go
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/auth.go[tag="query"]
----


=== Verify the User exists

As this query should only return a single result, so you can call the `Single()` method on the result to get the first and only record.

.pkg/services/auth.go
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/auth.go[tag="exists"]
----

The `Single()` method expects one result, and will return an error if zero or more than one records are returned.
In the example above, both of these cases are handled by returning an error informing the user that the account cannot be found.

If a single result is successfully returned, then the next step is to verify the password.


=== Compare Passwords

An encrypted version of the password is stored in the `password` property.
A helper function called `verifyPassword` is included in `auth.go` which uses bcrypt to compare the supplied password with user's password property.

.pkg/services/auth.go
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/auth.go[tag="password"]
----


=== Return User Details

Finally, if the user exists and the password comparison returns true, generate a JWT token and return it along with information about the User.


.pkg/services/auth.go
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/auth.go[tag="authreturn"]
----


Once you have applied these changes to the `FindOneByEmailAndPassword()` method, scroll to <<Testing>> to verify that the method works as expected.


== Working Solution

[%collapsible]
.Click here to reveal the completed `FindOneByEmailAndPassword()` method:
====

.pkg/services/auth.go
[source,go,indent=0]
----
include::{repository-raw}/{branch}/pkg/services/auth.go[tag="authenticate"]
----

====

include::../../../../includes/test.adoc[]


include::./questions/verify.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

In this Challenge, you have updated the `AuthService` to authenticate a User using the data held in the Sandbox database.

In the next Challenge, you will save user ratings to the database.
