= Registering a User
:type: challenge
:branch: 03-registering-a-user
:test-number: 03

Now that you have read data from the database, you are now ready to write data to the database.

In this challenge, you will rewrite the `register()` method in the link:{repository-blob}main/src/routes/auth.services.js[`AuthService`^] to do the following:

1. <<Open a new Session>>
2. <<Execute a Cypher query within a new Write Transaction>>
3. <<Extract the User from the Result>>
4. <<Close the Session>>
5. <<Return the Results>>


== Registering Users

A key piece of functionality that the application should provide is for new users to be able to register themselves with the site.
This functionality is already built into the front end, but at the moment the credentials are hard coded in the API.
This might be fine for demo purposes, but limiting the number of users to one is bad for Neoflix's bottom line.

The dummy register logic is already written into the `register()` method of the `AuthService` at `src/services/auth.service.js`.  As we can see from the snippet below, at the moment it will only accept an email address of `graphacademy@neo4j.com`.


[source,java,indent=0]
.src/services/auth.service.js
----
include::{repository-raw}/main/src/services/auth.service.java[tag="register"]
----

From the last line, you can see that an additional `token` property is added to the return.
This represents the JWT token required to authenticate the user on any future requests.
This token is generated further down within this class.

You will replace these `TODO` comments with working code to complete the challenge.


== Implementing Write Transactions

You will follow similar steps to the previous challenge, with the one change that the Cypher query will be executed within a Write Transaction.

To do so, you will need to call the `writeTransaction()` method on the `session` object with a function to represent unit of work.

Here are the steps to complete the challenge.

=== Open a new Session

First, open a new session:

[source,java,indent=0]
----
include::{repository-raw}/main/example/index.java[tag=session]
----

=== Execute a Cypher query within a new Write Transaction

Next, within that session, run the `writeTransaction()` method with two arguments:

1. The Cypher query as a parameterized string
2. An object containing the values for the parameters prefixed in the query with a dollar sign (`$`).  You will need to pass three parameters to the query:
  a. `email` as provided as the first parameter
  b. `encrypted` an encrypted version of the password provided in the second parameter
  c. `name` as provided in the third parameter

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/services/auth.service.java[tag="create"]
----


=== Extract the User from the Result

The Cypher query above returns the newly-created `:User` node as `u`.
As this query creates a single node, it will only ever return one result, so the `u` value may be taken from the first row.


[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/services/auth.service.java[tag="extract"]
----

The final line uses the link:https://developer.mozilla.org/en-US/docs/Web/Java/Reference/Operators/Destructuring_assignment[Destructuring assignment^] and link:https://developer.mozilla.org/en-US/docs/Web/Java/Reference/Operators/Spread_syntax[Spread syntax (`...`)^] to extract a set of _safe_ properties that can be used in the JWT token.


=== Close the Session

Before the user information is returned, make sure that the session is closed.

[source,java,indent=0]
----
include::{repository-raw}/main/example/index.java[tag="session.close"]
----


=== Return the Results

The return statement has already been written, so this can be left as it is.

[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/services/auth.service.java[tag="return"]
----


== Working Solution

.Click here to reveal the fully-implemented `register()` method.
[%collapsible]
====
[source,java,indent=0]
----
include::{repository-raw}/{branch}/src/services/auth.service.java[tag="register"]
----
====

include::../../../../includes/test.adoc[]


include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you wrote the code to create a new User node to Neo4j.

We still have `TODO` comments in the query for handling unique constraint violations in the database, so let's learn about that in the next lesson.
