= Course Summary
:driver: Neo4j JavaScript Driver
:dependency: neo4j-driver
:method: driver()

In this lesson you learned how to use TypeScript types to allow the TypeScript interpreter to identify errors during development including:

* How to install the Neo4j JavaScript Driver.
* How to connect to a Neo4j instance using the Driver.
* Best Practices for using the Driver to execute Cypher statements within Read and Write transactions.
* The Neo4j Type System and how Integers differ in Neo4j & JavaScript .
* How to use TypeScript types to enable type-checking and auto-completion.


== Continue Learning

Now that you have completed the course, we have terminated your Sandbox instance.
If you would like to continue learning, you can either link:https://samdbox.neo4j.com/?usecase=recommendations[create a new Neo4j Sandbox instance^] or link:https://github.com/neo4j-graph-examples/recommendations/data[download the Recommendations dataset^] and follow the instructions in the link:../0-setup/2-sandbox/[Your Neo4j Sandbox^] to update the credentials used by the driver.

You can find instructions on how to
link:https://neo4j.com/docs/operations-manual/current/backup-restore/restore-dump/[import a Neo4j dump using the `neo4j-admin load` command^] in the link:https://neo4j.com/docs/operations-manual/current/[Neo4j Operations Manual^].


include::../../resources.adoc[]
