[.question.select-in-source]
= 1. Creating a b-tree index

Suppose we have a graph that contains Company nodes. One of the properties of a Company node is name.
We want to be able to optimize queries that test the names of companies.
What is the correct statement to create this b-tree index?

Once you have selected your option, click the **Check Results** query button to continue.

[source,cypher,role=nocopy noplay]
----
/*select:CREATE INDEX Company_name IF NOT EXISTS FOR (x:Company) ON (x.name)*/
----


* [ ] `CREATE b-tree Company_name IF NOT EXISTS ON (Company.name)`
* [ ] `CREATE b-tree Company_name IF NOT EXISTS FOR (x:Company) ON (x.name)`
* [x] `CREATE INDEX Company_name IF NOT EXISTS FOR (x:Company) ON (x.name)`
* [ ] `CREATE INDEX Company_name IF NOT EXISTS ON (Company.name)`

[TIP,role=hint]
.Hint
====
You are creating an index. The index type by default is b-tree.
====

[TIP,role=solution]
.Solution
====

The correct code for creating the b-tree index is:

`CREATE INDEX Company_name IF NOT EXISTS FOR (x:Company) ON (x.name)`
====
