= Writing Data to Neo4j
:type: challenge
:challenge: src/challenges/write/challenge.ts
:lab: {repository-blob}/main/src/challenges/write/challenge.ts

Your challenge is to modify another pre-written file to add yourself as an actor in The Matrix.

link:./lab[Open Challenge in an Online IDE →^, role=btn]

== Steps

1. Update the `params` object to use your name.
This step isn't strictly required, just a bit of fun.


2. The Cypher statement is already written for you.
Call the `session.executeRead()` method, passing a callback function to represent the unit of work.


3. In that function you must call the `run()` method on the first parameter passed to the query, using the `cypher` and `params` variables.

4. `await` the results and use `console.log` to check that the code has executed correctly.

5. To add the new node and relationship to the database, click the Debug icon to the left of the window and run **Create Driver** job, or use the integrated terminal window to run the following command: +
+
.Run The Challenge
[source,sh,subs=attributes+]
----
ts-node {challenge}
----

6. Once the code has run, click **Verify** and we will check that the node has been added to the database.

include::questions/verify.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

In this challenge, you used your knowledge to create a driver instance and run a Cypher statement.

Next, we will look at the Neo4j Type System and some of the considerations that you need to make when working with values coming from Neo4j in your TypeScript application.
