= Listing People
:type: challenge
:test-number: 14
:branch: 14-person-list

If you open click on the **People** link in the main navigation, you will see link:http://localhost:3000/people/[a paginated list of actors and directors^].

== People Search

A list of people can be retrieved by calling the link:http://localhost:3000/people/[http://localhost:3000/people/^] endpoint.
The list is populated by the `all()` method in the link:{repository-blob}main/src/services/people.service.js[`PeopleService`^].

.src/services/people.service.js
[source,js,indent=0]
----
include::{repository-raw}/main/src/services/people.service.js[tag=all]
----

This list varies slightly from the Movie lists because this features a **Search by Name** input.
When this value is set, an additional `q` parameter will need to be passed to the `tx.run`, and if defined, the query should add an additional `CONTAINS` predicate.

.Find People with CONTAINS predicate
[source,cypher]
----
include::{repository-raw}/main/cypher/3-backlog/6-person-list/find-people.cypher[]
----


[TIP]
.Using Text Indexes
The `STARTS WITH`, `ENDS WITH` and `CONTAINS` predicates are **case-sensitive**.
If you are looking for a case-insensitive search, you should consider setting up a link:https://neo4j.com/docs/cypher-manual/current/indexes-for-full-text-search/[Full-text Index^].


== Your Task

* Modify the `all()` method to query Neo4j and return a list of People
* If the `q` parameter is defined, add a `WHERE` clause to check that the `name` property contains the value provided.
 ** **Hint:** you can use a link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator[conditional operator^] within the string literal to add this WHERE clause
* Remember to close the session and use the `toNativeTypes` function within a `map` function on `res.records` to convert the values to native JavaScript types.


[%collapsible]
.Click to reveal the completed `all()` method
====

.src/services/people.service.js
[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/people.service.js[tag=all]
----

====

// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-alphabetical-order.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this lesson, you implemented the `all`  method in the `PeopleService` to return a paginated list of people from the Neo4j database and implemented a conditional WHERE clause on the `:Person` `name` property.

In the next lesson, you will retrieve an individual's details from the database.
