== Clone the Repository

You can obtain a copy of the project source code by cloning link:https://github.com/{repository}[the {repository} repository^] from Github.  Or, if you prefer, you can also link:https://github.com/{repository}/archive/refs/heads/main.zip[download a zip file with the source^].


[.tab]
.HTTPS
====
To clone the repository without logging in via HTTPS, you can run the following command to clone the repository:

.Clone Repository Using HTTPS
[source,shell,subs="attributes+"]
git clone https://github.com/{repository}.git

====

[.tab]
.SSH
====

If you have a GitHub account configured with SSH access, you can run the following command to clone the repository:

.Clone Repository using SSH
[source,shell,subs="attributes+"]
git clone git@github.com:{repository}.git

====

[.tab]
.GitHub CLI
====

If you have the link:https://cli.github.com/[GitHub CLI^] installed, you can run the following command to clone the repository:

.Clone Repository using the GitHub CLI
[source,sh,subs="attributes+"]
gh repo clone {repository}

====

[.tab]
.Download Zip File
====

Click the following link to download the source as a .zip file.

https://github.com/{repository}/archive/refs/heads/main.zip.

====

// [.tab]
// .CodeSandbox
// ====

// You can clone this repository to link:https://codesandbox.io[CodeSandbox^] and follow this course in your browser by opening the following URL:

// link:https://codesandbox.io/s/github/neo4j-graphacademy/app-nodejs/tree/with-env[https://codesandbox.io/s/github/neo4j-graphacademy/app-nodejs/tree/with-env^]

// CodeSandbox will automatically install the dependencies for you, so you can skip to <<Setting Environment Variables>>.

// ====


