= Further Steps
:type: conversation
:order: 4

In the previous lessons, you learned how to manage your Aura instances and users.

In this section, you will learn about additional resources and next steps to continue your journey with Neo4j Aura.

Feel free to ask any questions in the chat!


== Continuing your learning journey

To continue your learning journey, you can explore the following resources:

* Documentation:
** link:https://neo4j.com/docs/aura/security/mfa/[Secure your account by enabling MFA^]
** link:https://neo4j.com/docs/aura/security/encryption/[Learn about Encryption in Aura^]
** link:https://neo4j.com/docs/aura/tutorials/migration/[Migrate on-premises Neo4j Databases to Aura^]
* link:https://community.neo4j.com/[Visit the Neo4j Community Forum^]
* link:https://graphacademy.neo4j.com/[Explore GraphAcademy^]:
** link:https://graphacademy.neo4j.com/courses/modeling-fundamentals[Learn to design and build graph data models^]
** link:https://graphacademy.neo4j.com/courses/cypher-fundamentals[Learn Cypher, the query language for Neo4j^]
** link:https://graphacademy.neo4j.com/courses/[Explore more advanced topics^]




[.TIP]
After launching one of the available sample projects, you can use them to practice the GraphAcademy skills you obtained.

read::Click to complete[]

[.summary]
== Summary

In this lesson, you learned about additional resources to continue your learning journey with Neo4j Aura.

You can explore the Neo4j documentation, community forum, and GraphAcademy for more information and learning materials.
