= Browsing Genres
:type: challenge
:branch: 09-genre-list
:test-number: 09
:optional: true

// Optional Lesson
include::../../../../../../shared/lesson/optional.adoc[]

If you click on the **Genres** link in the main navigation, you will be taken to a link:http://localhost:3000/genres[list of Genres^].
This list is populated by the API route at http://localhost:3000/api/genres, with the list being produced by the `all()` method within the link:{repository-blob}/main/src/services/genre.service.js[`GenreService`^].

.src/services/genre.service.js
[source,js,indent=0]
----
include::{repository-raw}/main/src/services/genre.service.js[tag=all]
----

In this challenge, you will modify the method to run the following Cypher statement in a **read transaction**:


.Listing Genres
[source,cypher]
----
include::{cypher-repository-raw}/main/cypher/3-backlog/1-browse-genres/genre-details.cypher[]
----


== Your Task

* Modify the `all()` method on the `GenreService` to query Neo4j and return a list of properties ordered by genre name.
* Each genre should have a name, the number of movies listed in that genre (`movies`), and a poster image (from the most popular movie in that genre).
* Remember to close the session and use the `toNativeTypes()` function within a `map()` function on `res.records` to convert the values to native JavaScript types.


== Working Solution

[%collapsible]
.Click here to view the completed `all()` method.
====

.src/services/genre/genre.service.js
[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/genre.service.js[tag=all]
----

====

// Testing
include::../../../../includes/test.adoc[]


// == Verifying the Test

include::./questions/1-movie-count.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you updated the `GenreService` to retrieve a list of genres from the database.

In the next Challenge, you will update the `GenreService` to query Neo4j to find the details of an individual genre.
