= Movie Lists and Pagination
:type: challenge
:test-filename: 11_movie_lists__test
:test-output: true
:branch: 11-movie-lists
:optional: true

// Optional Lesson
include::../../../../../../shared/lesson/optional.adoc[]

In this challenge, you will implement the remaining methods in the link:{repository-blob}main/api/dao/movies.py[`MovieDAO`^] for retrieving a list of movies:

* <<get_by_genre>> - should return a paginated list of movies that are listed in a particular Genre
* <<get_for_actor>> - should return a paginated list of movies that a particular Person has acted in
* <<get_for_director>> - should return a paginated list of movies that a particular Person has directed

These methods are very similar to the `all()` method which returns a full list, but with a different pattern in the `MATCH` clause.

// .api/dao/movies.py
// [source,python,indent=0]
// ----
// include::{repository-raw}/10-genre-details/api/dao/movies.py[tag=all]
// ----

For each subtask, we will provide you with the pattern required to run in the Cypher query, plus any additional parameters that are required for the query to run.

All you need to do is take the code from the `all()` method of the `MovieDAO` and modify the pattern in the first line of the Cypher query in the first argument of the `tx.run()` call, then if necessary add the additional parameters to the second argument.

If you get stuck at any point, you can click to reveal the completed solution or skip to the bottom for instructions on how to checkout the branch with the working solution.

[#get_by_genre]
== get_by_genre()

The `get_by_genre()` method returns a paginated list of movies that are listed within a certain genre.

.api/dao/movies.py
[source,python,indent=0]
----
include::{repository-raw}/main/api/dao/movies.py[tag=getByGenre]
----

Update the `get_by_genre()` method to use the following Cypher Pattern:

[source,cypher,role=norun]
MATCH (m:Movie)-[:IN_GENRE]->(:Genre {name: $name})

The `tx.run()` call will need to include the `name` property, which represents the name of the genre.


[%collapsible]
.Click to reveal the completed `get_by_genre()` method
====

Find the `get_by_genre()` method in `api/dao/movies.py` and modify the function to find a list of movies by genre.

.api/dao/movies.py
[source,python,indent=0]
----
include::{repository-raw}/{branch}/api/dao/movies.py[tag=getByGenre]
----

====


[#get_for_actor]
== get_for_actor()

The `get_for_actor()` method returns a paginated list of movies that a person has acted in.

.api/dao/movies.py
[source,python,indent=0]
----
include::{repository-raw}/main/api/dao/movies.py[tag=getForActor]
----

Find the `get_for_actor()` method in `api/dao/movies.py` and modify the function to find a list of movies by actor.

The pattern required in the `MATCH` clause will be:

[source,cypher,role=norun]
MATCH (:Person {tmdbId: $id})-[:ACTED_IN]->(m:Movie)

You will have to include the additional parameter `id` - The `tmdbId` property relating to the actor.

[%collapsible]
.Click to reveal the completed `getForActor()` method
====

.api/dao/movies.py
[source,python,indent=0]
----
include::{repository-raw}/{branch}/api/dao/movies.py[tag=getForActor]
----

====

[#get_for_director]
== get_for_director()

The `get_for_director()` method returns a paginated list of movies that a person has directed.

.api/dao/movies.py
[source,python,indent=0]
----
include::{repository-raw}/main/api/dao/movies.py[tag=getForDirector]
----

Find the `getForDirector()` method in `api/dao/movies.py` and modify the function to find a list of movies by director.

The pattern required in the `MATCH` clause will be:

[source,cypher,role=norun]
MATCH (:Person {tmdbId: $id})-[:DIRECTED]->(m:Movie)

You will have to include the additional parameter `id` - The `tmdbId` property relating to the director.


[%collapsible]
.Click to reveal the completed `get_for_director()` method
====

.api/dao/movies.py
[source,python,indent=0]
----
include::{repository-raw}/{branch}/api/dao/movies.py[tag=getForDirector]
----

====

// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-coppola-films.adoc[leveloffset=+1]


[.summary]
== Lesson Summary

In this Challenge, you modified the functions in the `MovieDAO` to return lists of movies.

In the next Challenge, you will implement the `find_by_id()` method.
