graph TD
    Territory -->|IN_REGION| Region
    Employee -->|IN_TERRITORY| Territory
    Employee -->|<i>PART_OF_REGION</i>| Region
    
    Territory(("<b>Territory</b>"))
    
    Region(("<b>Region</b>"))
    
    Employee(("<b>Employee</b>"))

    %% Style the new relationship
    linkStyle 2 stroke-dasharray: 5 5
