graph TD
    Customer -->|PURCHASED| Order
    Employee -->|SOLD| Order
    Employee -->|<i>SOLD_TO</i>| Customer
    
    Order(("<b>Order</b>"))
    
    Customer(("<b>Customer</b>"))
    
    Employee(("<b>Employee</b>"))
    
    %% Style the new relationship
    linkStyle 2 stroke-dasharray: 5 5

    