graph TD
    Node1 -->|RELATIONSHIP| Node2
    Node2 -->|RELATIONSHIP| Node3
    Node1 -->|<i>INDIRECT_RELATIONSHIP</i>| Node3
    
    Node1(("<b>Node</b>"))
    
    Node2(("<b>Node</b>"))
    
    Node3(("<b>Node</b>"))

    %% Style the new relationship
    linkStyle 2 stroke-dasharray: 5 5
