= Challenge: Updating Properties
:order: 6
:usecase: movies
:sandbox: true
:verify: MATCH (m:Movie {title: 'Get Out'}) WHERE  m.tagline = 'Gripping, scary, witty and timely!' AND m.released = 2017 RETURN true AS outcome
:cypher: MATCH (m:Movie {title: 'Get Out'}) \
RETURN m.title, m.tagline, m.released

<<<<<<< HEAD
We discovered that we created the _Movie_ node for the movie [copy]#Get Out#, but we forgot to add the tagline which is [copy]#Gripping, scary, witty and timely!# and the released year of 2017.

Write the Cypher code to find this _Movie_ node and add the _tagline_ and _released_ properties for the node.

=======
In the link:../4-create-relationship-challenge/[Creating a Relationship] challenge, we created a new `Movie` node for the movie *Get Out*.  However, we forgot to add a a tagline or release year.

Use the Sandbox window to the right to add two new properties to the node:

* *`tagline`*: [copy]#Gripping, scary, witty and timely!#
* *`released`*: [copy]#2017#


>>>>>>> b12cdad1ee25472de1f709ea0c85bde05ecd17da
include::questions/verify.adoc[]


[.summary]
== Summary

In this challenge, you demonstrated that you can add properties to a node.
In the next lesson, you will learn how to add or update properties when a node is created or retrieved.