[.question]
= 2. GDS Licensing

Which of the below statements are true in respect to the GDS Community and Enterprise licenses (select all that apply):

* [x] Community and Enterprise both have access to all the GDS algorithms and machine learning methods
* [ ] Community and Enterprise both have fine-grained security
* [ ] Community and Enterprise both have unlimited concurrency
* [x] Enterprise-only features for increased performance include unlimited concurrency and a low-memory analytics graph format

[TIP,role=hint]
.Hint
====
Both the Community and Enterprise versions of the GDS Library offer comprehensive access to all algorithms and machine learning methods, while the Enterprise version provides additional performance-enhancing features such as unlimited concurrency and a low-memory analytics graph format.

====

[TIP,role=solution]
.Solution
====
The correct answers are:

**Community and Enterprise both have access to all the GDS algorithms and machine learning methods** +
**Enterprise-only features for increased performance include unlimited concurrency and a low-memory analytics graph format**
====
