= Create the Answer Vector Index
:order: 4
:type: challenge
:sandbox: true

Apply what they have learned to create the vector index on the `Answer` nodes


In this challenge, you will apply your knowledge and create the vector index on the `Answer` nodes.

The `Answer` nodes have a `text` and `embeddings` property. The `text` property contains the answer text, and the `embeddings` property is the vector representation of the answer text.

Your task is to create a vector index on the `Answer` nodes using the `embedding` property.

You should note the following:

. The index should be named `answers`.
. The embedding has 1536 dimensions.
. The vector index should use the `cosine` similarity function.

Here is the Cypher you used to create the `questions` index:

[source,cypher, role="noplay"]
----
CREATE VECTOR INDEX questions IF NOT EXISTS
FOR (q:Question)
ON q.embedding
OPTIONS {indexConfig: {
 `vector.dimensions`: 1536,
 `vector.similarity_function`: 'cosine'
}}
----

You can view the current vector indexes by running the following Cypher:

[source,cypher]
----
SHOW INDEXES WHERE type = "VECTOR"
----

include::questions/1-verify.adoc[leveloffset=+1]

[.summary],
== Lesson Summary

In this challenge, you used Cypher to create a vector index.

In the next lesson, you will learn how to query vector indexes.

[.checklist]