= Custom Resolvers
:order: 2


Combining the power of Cypher and GraphQL is extremely powerful, however there are bound to be some cases where we want to add custom logic using code by implementing resolver functions. This might be where we want to fetch data from another database, API, or system. Let's consider a contrived example where we compute an estimated delivery date using a custom resolver function.

First, we add an `estimatedDelivery` field to the `Order` type, including the https://neo4j.com/docs/graphql-manual/current/type-definitions/access-control/#type-definitions-access-control-ignore[`@ignore`^] directive which indicates we plan to resolve this field manually and it will not be included in the generated database queries.


[source,GraphQL]
----
# schema.graphql

extend type Order {
    estimatedDelivery: DateTime @ignore
}
----

Now it's time to implement our `Order.estimatedDelivery` resolver function. Our function simply calculates a random date - but the point is that this can be any custom logic we choose to define.

Add this function to beginning of *index.js*:

[source,JavaScript]
----
// index.js

const resolvers = {
  Order: {
    estimatedDelivery: (obj, args, context, info) => {
      const options = [1, 5, 10, 15, 30, 45];
      const estDate = new Date();
      estDate.setDate(
        estDate.getDate() + options[Math.floor(Math.random() * options.length)]
      );
      return estDate;
    }
  }
};
----

Next, we include the `resolvers` object when instantiating `Neo4jGraphQL`.

Modify these objects in *index.js*:

[source,JavaScript]
----
// index.js

const neoSchema = new Neo4jGraphQL({
  typeDefs,
  resolvers,
  debug: true
});

const server = new ApolloServer({
  context: { driver },
  schema: neoSchema.schema,
  introspection: true,
  playground: true
});
----

And now we can reference the `estimatedDelivery` field in our GraphQL queries. When this field is included in the selection instead of trying to fetch this field from the database, our custom resolver will be executed.

[source,GraphQL]
----
{
  orders {
    shipTo {
      address
    }
    estimatedDelivery
  }
}
----


[source,JSON,role=nocopy]
----
{
  "data": {
    "orders": [
      {
        "shipTo": {
          "address": "111 E 5th Ave, San Mateo, CA 94401"
        },
        "estimatedDelivery": "2021-05-09T23:43:05.970Z"
      },
      {
        "shipTo": {
          "address": "Nordenskiöldsgatan 24, 211 19 Malmö, Sweden"
        },
        "estimatedDelivery": "2021-04-29T23:43:05.970Z"
      }
    ]
  }
}
----