= Creating a b-tree composite index on a node property
:type: challenge
:sandbox: true

== Performance improvement needed

In our Movie data model, we have identified this query as important and one that we need to make as fast as possible for our users.
Here is an example where we have hard-coded the test values.

[source,cypher]
----
MATCH (m:Movie)
WHERE  1990 <= m.year < 2000 AND m.imdbRating >= 8
RETURN m.title, m.year, m.imdbRating
----

**Step 1:**

Profile this query and note if an index is used. Also note the number of db hits.
It uses an the b-tree index for the title property of the Movie nodes which is not helpful.

**Step 2:**

Create a b-tree composite index that will make this query faster.

**Step 3:**

Repeat the query with a profile.
Was your newly-created b-tree index used?
Are the number of db hits reduced?

include::./questions/verify.adoc[leveloffset=+1]


[.summary]
== Summary

In this Challenge, you demonstrated that you can create a b-tree composite index in the graph to improve the performance of a query.
In the next lesson, you will learn how to create a TEXT index.