= Challenge: Create Person classes
:order: 2
:type: challenge
:sandbox: true

Your challenge is to use the skills from last lesson to create the class for the Person domain.

== Person node properties

In the `src/main/java/com/example/appspringdata` directory, create a new class file called `Person.java` and utilize the following list of properties and data types for the Person node in Neo4j to map in your domain class, using the `imdbId` field as the class's identifier. You can also verify the data types yourself by running the query shown in the sandbox tab on the right.

[source,text]
----
{
  born:"DATE", 
  bornIn:"STRING", 
  tmdbId:"STRING", 
  bio:"STRING", 
  died:"DATE", 
  name:"STRING", 
  poster:"STRING", 
  imdbId:"STRING", 
  url:"STRING"
}
----

Reference the Cypher-to-Java https://neo4j.com/docs/java-reference/current/extending-neo4j/values-and-types/[data type mappings^] from the documentation, if needed.

[%collapsible]
.Click to reveal the completed `Person` domain class code
====
[source,java]
----
include::code/Person.java[tag=person]
----
====

[.summary]
== Lesson Summary

In this challenge, you used what you have learned to create the domain class for Person entities.

In the next lesson, you will learn how to create the interface and controller class to access the `Movie` and `Person` domain entities.
