name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development

jobs:
  set_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment based on branch
        id: environment_check
        run: |          
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          
          if [[ "$BRANCH_NAME" = "master" ]]; then
            ENVIRONMENT="production"
          else
            ENVIRONMENT=$BRANCH_NAME
          fi
          
          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT
    outputs:
      environment: ${{ steps.environment_check.outputs.ENVIRONMENT }}

  assets:
      runs-on: ubuntu-latest
      needs: set_environment
      permissions:
        id-token: write
        contents: read
      env:
        AWS_REGION: us-east-1

      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Use Node.js 20
            uses: actions/setup-node@v3
            with:
                node-version: '20'

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: ${{ secrets.DEVELOPMENT_GH_OIDC_ROLE_ARN }}
              aws-region: us-east-1

          - name: Install NPM Dependencies
            run: npm install

          - name: Build CSS
            run: npm run build:css

          - name: Build Front-end JS
            run: npm run build:ui

          - name: Sync Assets
            run: aws s3 sync public/ s3://${{ needs.set_environment.outputs.ENVIRONMENT }}-graphacademy-assets/assets/ --acl public-read
#    invalidate-cache:
#        runs-on: ubuntu-latest
#        needs: assets
#        steps:
#            - name: Invalidate CloudFront Cache
#              uses: chetan/invalidate-cloudfront-action@v2
#              env:
#                  DISTRIBUTION: ${{ secrets.GA_CLOUDFRONT_DISTRIBUTION }}
#                  PATHS: '/assets'
#                  AWS_REGION: ${{ secrets.AWS_REGION }}
#                  role-to-assume: ${{ secrets.DEVELOPMENT_GH_OIDC_ROLE_ARN }}

  deploy:
      runs-on: ubuntu-latest
      needs: [set_environment, assets]
      permissions:
        id-token: write
        contents: read
      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                role-to-assume: ${{ secrets.DEVELOPMENT_GH_OIDC_ROLE_ARN }}
                aws-region: us-east-1

          - name: Login to Amazon ECR Private
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2

          - name: Generate timestamp
            id: timestamp
            run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              tags: ${{env.IMAGE}}
            env:
              IMAGE: "${{ steps.login-ecr.outputs.registry }}/${{ needs.set_environment.outputs.ENVIRONMENT }}-devrel-graphacademy-repository:${{ steps.timestamp.outputs.TIMESTAMP }}"
              aws-region: us-east-1

          - name: Set and output URL with tag
            id: output_url
            run: |
              imageURL="${{ steps.login-ecr.outputs.registry }}/${{ needs.set_environment.outputs.ENVIRONMENT }}-devrel-graphacademy-repository:${{ steps.timestamp.outputs.TIMESTAMP }}"
              echo "IMAGEURL=$imageURL" >> $GITHUB_OUTPUT
            env:
              REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              ENVIRONMENT: ${{ needs.set_environment.outputs.ENVIRONMENT }}
              TIMESTAMP: ${{ steps.timestamp.outputs.TIMESTAMP }}

          - name: Retrieve the latest task definition and update it
            id: register-task-def
            run: |
              IMAGE_URI="${{steps.login-ecr.outputs.registry}}/${{needs.set_environment.outputs.ENVIRONMENT}}-devrel-graphacademy-repository:${{steps.timestamp.outputs.TIMESTAMP}}"
              TASK_NAME="${{ needs.set_environment.outputs.ENVIRONMENT }}-devrel-graphacademy-task"
              TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_NAME)

              # Use the AWS CLI to fetch the secret values from AWS Secrets Manager
              NEO4J_HOST=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/NEO4J_HOST | jq -r .SecretString | jq -r .NEO4J_HOST)
              NEO4J_USERNAME=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/NEO4J_USERNAME | jq -r .SecretString | jq -r .NEO4J_USERNAME)
              NEO4J_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/NEO4J_PASSWORD | jq -r .SecretString | jq -r .NEO4J_PASSWORD)
              BASE_URL=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/BASE_URL | jq -r .SecretString | jq -r .BASE_URL)
              COMMUNITY_GRAPH_HOST=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/COMMUNITY_GRAPH_HOST | jq -r .SecretString | jq -r .COMMUNITY_GRAPH_HOST)
              COMMUNITY_GRAPH_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/COMMUNITY_GRAPH_PASSWORD | jq -r .SecretString | jq -r .COMMUNITY_GRAPH_PASSWORD)
              COMMUNITY_GRAPH_USERNAME=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/COMMUNITY_GRAPH_USERNAME | jq -r .SecretString | jq -r .COMMUNITY_GRAPH_USERNAME)
              AUTH0_CLIENT_ID=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/AUTH0_CLIENT_ID | jq -r .SecretString | jq -r .AUTH0_CLIENT_ID)
              AUTH0_CLIENT_SECRET=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/AUTH0_CLIENT_SECRET | jq -r .SecretString | jq -r .AUTH0_CLIENT_SECRET)
              AUTH0_ISSUER_BASE_URL=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/AUTH0_ISSUER_BASE_URL | jq -r .SecretString | jq -r .AUTH0_ISSUER_BASE_URL)

              NEW_TASK_DEF=$(echo "$TASK_DEF" | jq --arg IMAGE_URI "$IMAGE_URI" \
                                                   --arg NEO4J_HOST "$NEO4J_HOST" \
                                                   --arg NEO4J_USERNAME "$NEO4J_USERNAME" \
                                                   --arg NEO4J_PASSWORD "$NEO4J_PASSWORD" \
                                                   --arg BASE_URL "$BASE_URL" \
                                                   --arg COMMUNITY_GRAPH_HOST "$COMMUNITY_GRAPH_HOST" \
                                                   --arg COMMUNITY_GRAPH_PASSWORD "$COMMUNITY_GRAPH_PASSWORD" \
                                                   --arg AUTH0_CLIENT_ID "$AUTH0_CLIENT_ID" \
                                                   --arg AUTH0_CLIENT_SECRET "$AUTH0_CLIENT_SECRET" \
                                                   --arg AUTH0_ISSUER_BASE_URL "$AUTH0_ISSUER_BASE_URL" \
                                                   --arg COMMUNITY_GRAPH_USERNAME "$COMMUNITY_GRAPH_USERNAME" '
               .taskDefinition |
               del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) |
               .containerDefinitions[0].image = $IMAGE_URI |
               .containerDefinitions[0].environment = [
                    {"name": "NEO4J_HOST", "value": $NEO4J_HOST},
                    {"name": "NEO4J_USERNAME", "value": $NEO4J_USERNAME},
                    {"name": "NEO4J_PASSWORD", "value": $NEO4J_PASSWORD},
                    {"name": "BASE_URL", "value": $BASE_URL},
                    {"name": "COMMUNITY_GRAPH_HOST", "value": $COMMUNITY_GRAPH_HOST},
                    {"name": "COMMUNITY_GRAPH_PASSWORD", "value": $COMMUNITY_GRAPH_PASSWORD},
                    {"name": "COMMUNITY_GRAPH_USERNAME", "value": $COMMUNITY_GRAPH_USERNAME},
                    {"name": "AUTH0_CLIENT_ID", "value": $AUTH0_CLIENT_ID},
                    {"name": "AUTH0_CLIENT_SECRET", "value": $AUTH0_CLIENT_SECRET},
                    {"name": "AUTH0_ISSUER_BASE_URL", "value": $AUTH0_ISSUER_BASE_URL}
                  ]
              ')
              echo "$NEW_TASK_DEF"
              echo "$NEW_TASK_DEF" > new-task-def.json
            env:
              AWS_REGION: us-east-1
          - name: Deploy new task definition to ECS
            uses: aws-actions/amazon-ecs-deploy-task-definition@v1
            with:
              service: ${{ needs.set_environment.outputs.ENVIRONMENT }}-devrel-graphacademy-service
              cluster: ${{ needs.set_environment.outputs.ENVIRONMENT }}-devrel-graphacademy-cluster
              task-definition: new-task-def.json

  update-eventbridge:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEVELOPMENT_GH_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install jq
          sudo pip install yq

      - name: Read YAML configurations, update Eventbridge Schedules and Targets
        run: |
          tasks=$(yq e '.crons' deployment-config/cron-config.yaml)
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ENV_NAME=${{ needs.set_environment.outputs.environment }}

          for task in $(echo "${tasks}" | yq e -j '.[]' -)
          do
            NAME=$(echo $task | jq -r '.name')
            COMMAND=$(echo $task | jq -r '.command')
            CRON=$(echo $task | jq -r '.cron')
            ENV_VARS=$(echo $task | jq -r '.env[]') 
            TASK_NAME="${ENV_NAME}-${NAME}-task-cron"
            RULE_NAME="${ENV_NAME}-${NAME}-rule"

            ENV_VARS_JSON="[]"
            for var_name in ${ENV_VARS}
            do
              var_value=$(aws secretsmanager get-secret-value --secret-id $var_name --region us-east-1 --query SecretString --output text)
              ENV_VARS_JSON=$(echo $ENV_VARS_JSON | jq --arg name "$var_name" --arg value "$var_value" '. += [{"name": $name, "value": $secret}]')
            done

            EVENTBRDIGE_ROLE="arn:aws:iam::${AWS_ACCOUNT_ID}:role/${ENV_NAME}-devrel-graphacademy-ecs-events-role"              

            DEF=$(aws ecs describe-task-definition --task-definition ${{ needs.set_environment.outputs.environment }}-devrel-graphacademy-task)

            NEW_DEF=$(echo $DEF | jq --argjson command "$COMMAND" --argjson environment "$ENV_VARS_JSON" ".taskDefinition | .containerDefinitions[0].image=env.TARGET_IMAGE | .containerDefinitions[0].command=$command | .containerDefinitions[0].environment=$environment | .family=\"${TASK_NAME}\"")              

            echo $NEW_DEF

            response=$(aws ecs register-task-definition --cli-input-json "$NEW_DEF")
            revision=$(echo $response | jq -r '.taskDefinition.revision')
            target_id=$(echo $response | jq -r '.taskDefinition.taskDefinitionArn')
            target_arn=$(echo $response | jq -r '.taskDefinition.taskRoleArn')

            aws events put-rule --name $RULE_NAME --schedule-expression $CRON
            aws events put-targets --rule $RULE_NAME --targets 'Id='"$target_id"',Arn='"$target_arn"',EcsParameters={TaskDefinitionArn="arn:aws:ecs:us-east-1:'"${AWS_ACCOUNT_ID}"':task-definition/'"$TASK_NAME"':'"$revision"', RoleArn="'$EVENTBRDIGE_ROLE'"}'
          done