name: Feedback triage

on:
  schedule:
    - cron: "0 8 * * 1" # Every Monday at 08:00 UTC
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install NPM Dependencies
        run: npm install --include=dev

      - name: Run triage
        env:
          LINEAR_TOKEN: ${{ secrets.LINEAR_TOKEN }}
          NEO4J_HOST: ${{ vars.NEO4J_HOST }}
          NEO4J_USERNAME: ${{ vars.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        run: npm run feedback:triage
