= Using Constraints in Neo4j
:sandbox: false
:order: 2

//[.transcript]
== Module overview

Constraints are a specialized type of index that enable you to control if a property value must exist and/or is unique.

If a constraint is violated when a node or relationship is created or updated, an error is raised.

Uniqueness constraints are important, especially when large amounts of data are imported into the graph.
This enables the graph engine to quickly look up a node and prevent duplication of data.

In this module, you will:

* Learn about the types constraints available in Neo4j and why you would use them.
* Create a uniqueness constraint.
* Create an existence constraint for a node property.
* Create an existence constraint for a relationship property.
* Create a uniqueness and existence constraint for a set of properties (node key).
* Manage constraints in the graph.

== Resources

During this course, you can refer to:

* link:https://neo4j.com/docs/cypher-manual/current/[Neo4j Cypher Manual^].
* link:https://neo4j.com/docs/cypher-refcard/current/[Neo4j Cypher Refcard^].
