= Using Constraints in Neo4j
:sandbox: false
:order: 2

//[.transcript]
== Module overview

Constraints are a specialized type of index that enable you to control:

* Uniqueness of values for:
** A property of node with a given label.
** A set of properties for a node with a given label.
* Whether a property is required for a node or relationship.

If a constraint is violated when a node or relationship is created ot updated, an error is raised.

Uniqueness constraints are important, especially when large amounts of data is imported into the graph.
This enables the graph engine to quickly look up a node and prevent duplication of data.

In this module, you will:

* Learn about the types constraints available in Neo4j and why you would use them.
* Create a uniqueness constraint.
* Create a uniqueness constraint for a set of properties.
* Create an existence constraint for a node property.
* Create an existence constraint for a relationship property.
* Manage constraints in the graph.

== Resources

During this course, you can refer to:

* link:https://neo4j.com/docs/cypher-manual/current/[Neo4j Cypher Manual^].
* link:https://neo4j.com/docs/cypher-refcard/current/[Neo4j Cypher Refcard^].
