= Query Good Practice
:type: lesson
:order: 3


== Introduction

In the following lessons you will learn some of the common best practices for writing efficient Cypher queries including:

* Use of indexes
* Count stores
* Using WITH to break down complex queries
* Reading properties late

// Potential examples we could use:

// * Read early
// * Break down complex queries
// * Using WITH
// * Query parameters
// * Indexing
// * USING INDEX
// * Labels
// * Avoiding Eager
// * Super nodes



// TODO - DOES THIS GO HERE? Is it too early? There are a lot of new concepts, it might be better to have this at the end of the module as a checklist for query optimization?
== Query Optimization Checklist

When analyzing slow queries, check for these common issues:

* **Variable length paths have upper limits**: Use `[\*1..5]` instead of `[*]` to prevent excessive traversals
* **Node labels are specified**: Use `MATCH (u:User)` instead of `MATCH (u)` to avoid scanning all nodes
* **Properties have indexes**: Create indexes on properties used in `WHERE` clauses and lookups
* **Relationship types are specified**: Always provide relationship types to narrow traversals
* **Relationship directions are specified**: Always specify the direction of the relationship when it is known
* **Queries use parameters**: Replace literal values with `$parameter` to enable plan caching
* **Return only needed properties**: Use `RETURN u.name, m.title` instead of `RETURN u, m` to reduce data transfer
* **Result sets are limited**: Add `LIMIT` clauses to prevent returning excessive data


read::Continue[]

[.summary]
== Lesson Summary

In this lesson, you learned ...

In the next lesson, you will ...
