[.question.select-in-source]
= 1. Providing a query hint

Suppose we have a graph that contains Company nodes. One of the properties of a Company node is name and we have a TEXT index on that property.
The graph also has Employee nodes that has a WORKS_AT relationship to Company nodes.
An Employee node has a name property and we have a TEXT index on that property.

Based upon our query testing, we have decided that we want to ensure that the TEXT index for the name property of a company is always used in this query.
How do you specify this query hint?:

Once you have selected your option, click the **Check Results** query button to continue.

[source,cypher,role=nocopy noplay]
----
PROFILE MATCH
(e:Employee)-[:WORKS_AT]->(c:Company)
/*select:USING INDEX c:Company(name)*/
WHERE
e.name CONTAINS 'John'
AND
c.name CONTAINS 'Processing'
RETURN p.name,  m.title

----

* [ ] `USING INDEX c:Company_name_text`
* [ ] `USING INDEX Company_name_text`
* [ ] `USING TEXT INDEX Company.name`
* [x] `USING INDEX c:Company(name)`

[TIP,role=hint]
.Hint
====
You must specify the variable used in the query path.
====

[TIP,role=solution]
.Solution
====

The correct code for providing this query hint is:

`USING INDEX c:Company(name)`
====
