[.question.freetext]
= Update Movie Reviews

Write a query that returns a list pertaining to the movie, Toy Story. The list will contain the rating value for the RATED relationships for the movie with the title, Toy Story.

Once you have created the list, transform the values to integers.

How many list elements are transformed to the value 4?

Once you execute the query, enter the value below and click **Check Answer**.

input::answer[]

* [x] 96

[TIP,role=hint]
.Hint
====

First write a `MATCH` clause to find the users and RATED relationships for the movie Toy Story.

Use a `WITH` clause to create the list containing the rating value of the RATED relationship.

Use a `WITH` clause to transform the elements of the list to Integer values.

Use `UNWIND` to process each element in the list and count the elements that have a value of 4.


How many list elements are transformed to the value 4?

Once you have entered the answer, click the **Try Again** button below to continue.

====

[TIP,role=solution]
.Solution
====

This is the query to answer the question:

[source,cypher]
----
include::../solution.cypher[]
----

How many list elements are transformed to the value 4?

Once you have entered the answer, click the **Try Again** button below to continue.
====


