== Testing

To test that this functionality has been correctly implemented, run the following code in a new terminal session:

.Running the test
[source,sh,subs="attributes+"]
mvn test -Dtest=neoflix.{test-filename}#{test-method}

ifdef::test-filename[]
The test file is located at link:{repository-raw}/main/src/test/java/neoflix/{test-filename}.java[`src/test/java/neoflix/{test-filename}.java`^].
endif::[]

ifdef::branch[]
The test file is located at link:{repository-raw}/main/test/challenges/{branch}.spec.js[`test/challenges/{branch}.spec.js`^].
endif::[]

ifdef::branch[]

// [%collapsible]
// .If you get stuck, you can see a working solution by checking out the {branch} branch.
// ====
// [source,sh,subs="attributes+"]
// ----
// git checkout {branch}
// ----
// ====


[.stuck]
[%collapsible]
.Are you stuck?  Click here for help
====
If you get stuck, you can see a working solution by checking out the `{branch}` branch by running:

.Check out the {branch} branch
[source,sh,subs="attributes"]
----
git checkout {branch}
----

You may have to commit or stash your changes before checking out this branch.  You can also link:#[click here to expand the Support pane, role=classroom-support-toggle].

====


endif::[]
