= Finding Genre Details
:type: challenge
:test-number: 10
:branch: 10-genre-details

When the user clicks a Genre in the list, they are taken to a list of movies for that genre.  A request is sent to the `/api/[name]` API endpoint.

The `find()` method the the `GenreServie` accepts one argument, the name of the Genre and should return the information identical to the entry from the above endpoint.

.src/services/genre.service.js
[source,js,indent=0]
----
include::{repository-raw}/main/src/services/genre.service.js[tag=find]
----


In this challenge, you should run the following cypher statement in a **read transaction**:

.Finding Genre Details
[source,cypher]
----
include::{repository-raw}/main/cypher/3-backlog/2-find-genre-details/genre-details.cypher[]
----

[IMPORTANT]
.What does this query do?
====
This query uses the `MATCH` clause to genre with the name passed through with the function call as a parameter.
The query then finds the highest rated movie with a `poster` property and uses that image as the background to the card in the UI.

The `size()` function uses a precalculated value stored against the `:Genre` node to return the number of incoming `:IN_GENRE` relationships to this node.
====


== Your Task

* Modify the `find()` method on the `GenreService` to call the Neo4j database and return details for a Genre
* The `name` variable should be passed to the `run` call as a parameter
* If no records are found, a `NotFoundError` should be thrown
* Remember to close the session and use the `toNativeTypes` function to convert the genre value to native types


== Working Solution

[%collapsible]
.Click here to view the completed `find()` method.
====

.src/services/genre/service.js
[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/genre.service.js[tag=find]
----
====

// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-genre-movie-count.adoc[]

[.summary]
== Lesson Summary

In this lesson, we modified the `find()` method to retrieve basic genre information from the Neo4j database.

In the next lesson, we will look at the methods in the `MovieService` that we use to populate lists of movies in the UI.
