= Finding Genre Details
:type: challenge
:test-number: 10
:branch: 10-genre-details

When the user clicks a Genre in the list, they are taken to a list of movies for that genre.  This list is populated by an API request to `/api/genres/[name]`, for example http://localhost:3000/api/genres/Comedy.

The `find()` method the the `GenreServie` accepts one argument, the name of the Genre, and should return the information about the genre, along with a count of movies and a poster image.

.src/services/genre.service.js
[source,js,indent=0]
----
include::{repository-raw}/main/src/services/genre.service.js[tag=find]
----


In this challenge, you will need to modify the method to run the following Cypher statement in a **read transaction**:

.Finding Genre Details
[source,cypher]
----
include::{repository-raw}/main/cypher/3-backlog/2-find-genre-details/genre-details.cypher[]
----

[IMPORTANT]
.What does this query do?
====
This query uses the `MATCH` clause to genre with the name passed through with the function call as a parameter.
The query then finds the highest rated movie with a `poster` property and uses that image as the background to the card in the UI.

The `size()` function uses a precalculated value stored against the `:Genre` node to return the number of incoming `:IN_GENRE` relationships to genre node.
====


== Your Task

* Modify the `find()` method on the `GenreService` to call the Neo4j database and return details for a Genre
* The `name` variable should be passed to the `run` call as a parameter
* If no records are found, a `NotFoundError` should be thrown
* Remember to close the session and use the `toNativeTypes` function to convert the genre value to native JavaScript types


== Working Solution

[%collapsible]
.Click here to view the completed `find()` method.
====

.src/services/genre/service.js
[source,js,indent=0]
----
include::{repository-raw}/{branch}/src/services/genre.service.js[tag=find]
----
====

// Testing
include::../../../../includes/test.adoc[]


== Verifying the Test

include::./questions/1-genre-movie-count.adoc[leveloffset=+1]

[.summary]
== Lesson Summary

In this lesson, you modified the `find()` method in the `GenreService` to retrieve genre information from Neo4j.

In the next lesson, you will update multiple methods in the `MovieService` that return a paginated list of Movies.
